### PR TITLE
ARF 83474 pt. 2 Create new PilotRepresentative model

### PR DESCRIPTION
**Pull request by ddzz**
Depends on https://github.com/department-of-veterans-affairs/vets-api/pull/17507

## Summary

- *This work is behind a feature toggle (flipper): YES/NO*
- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution?)*
- *(Which team do you work for, does your team own the maintenance of this component?)*
- *(If introducing a flipper, what is the success criteria being targeted?)*

## Related issue(s)

- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by gabezurita** [comment]
@ddzz, given there is no production data and no users for this yet, let's rename (instead of create/delete) the VerifiedRepresentative model so as not to lose the git history on the file.

**Review by gabezurita — CHANGES_REQUESTED** [review]
@ddzz, given there is no production data and no users for this yet, let's rename (instead of create/delete) the VerifiedRepresentative model so as not to lose the git history on the file.

**Comment by ddzz** [comment]
@gabezurita I'm following the flow defined in Gia's comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83474#issuecomment-2183500146), which says to create a new model rather than renaming.

**Comment by gabezurita** [comment]
> @gabezurita I'm following the flow defined in Gia's comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83474#issuecomment-2183500146), which says to create a new model rather than renaming.

[Gia's comment](https://github.com/department-of-veterans-affairs/vets-api/pull/17488#issuecomment-2229032706) links to one of [my comments](https://github.com/department-of-veterans-affairs/vets-api/pull/16493#issuecomment-2076279725) 😄 The screenshot that's being referenced is below:
image

That talks about migrations. Do we foresee risks in renaming vs deleting/recreating? If CI can go green with the renaming route (let's check that), there are no `VerifiedRepresentative` users in production environments, so I do not see a risk — what risk do you see?

**Comment by gabezurita** [comment]
@ddzz, there are 2 failures on this branch:
```
Failures:

  1) AccreditedRepresentativePortal::RepresentativeUserLoader#perform when user record no longer exists in redis behaves like reloaded user and associated session exists verified_representatives #poa_codes when reloading a user sets the poa_codes based on the ogc_registration_number on the accredited_individual
     Failure/Error: expect(reloaded_user.poa_codes).to be_present
       Expected nil to return a truthy result for present? or presents?.
     Shared Example Group: "reloaded user" called from ./modules/accredited_representative_portal/spec/services/accredited_representative_portal/representative_user_loader_spec.rb:132
     # /usr/local/bundle/cache/ruby/3.3.0/gems/super_diff-0.12.1/lib/super_diff/rspec/monkey_patches.rb:43:in `handle_failure'
     # ./modules/accredited_representative_portal/spec/services/accredited_representative_portal/representative_user_loader_spec.rb:100:in `block (8 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

  2) AccreditedRepresentativePortal::RepresentativeUserLoader#perform when user record no longer exists in redis behaves like reloaded user and associated session exists verified_representatives #ogc_registration_number when a matching verified_representative is found returns the OGC registration number
     Failure/Error: expect(reloaded_user.ogc_registration_number).to eq(verified_representative.ogc_registration_number)
       Expected nil to eq "12300".
     Shared Example Group: "reloaded user" called from ./modules/accredited_representative_portal/spec/services/accredited_representative_portal/representative_user_loader_spec.rb:132
     # /usr/local/bundle/cache/ruby/3.3.0/gems/super_diff-0.12.1/lib/super_diff/rspec/monkey_patches.rb:43:in `handle_failure'
     # ./modules/accredited_representative_portal/spec/services/accredited_representative_portal/representative_user_loader_spec.rb:84:in `block (8 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /usr/local/bundle/cache/ruby/3.3.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

Finished in 5 minutes 52 seconds (files took 57.07 seconds to load)
5929 examples, 2 failures
```

Fixing on this branch:
https://github.com/department-of-veterans-affairs/vets-api/pull/17564

**Comment by gabezurita** [comment]
@ddzz, want to close this PR in favor of https://github.com/department-of-veterans-affairs/vets-api/pull/17564 or cherry-pick the changes onto this one?

**Comment by ddzz** [comment]
@gabezurita Let's use your branch. I see CI failures on yours too, so I can help out there.

**Comment by gabezurita** [comment]
> @gabezurita Let's use your branch. I see CI failures on yours too, so I can help out there.

Sounds good. The only failure was a rubocop one that I just fixed! I think we're good to merge (pending Platform approval).

**Pull request closed without merging**
