### PR TITLE
Multi file datadog service catalog update

### PR DESCRIPTION
**Pull request by lexicalninja**
## Summary

This PR adds functionality that would pull all of the service catalog data out of the single file and into separate files for each service. 

the action currently ignores changes to the single file so that teams can copy their data to a single file and delete their entry in the large file. 

## Related issue(s)
[#69542](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69542)
[#69776](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69776)
PR #14429 

## Testing done
Ran the workflows with a combination of files within the filtered directory to make sure it only triggered on the correct paths. 

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
DataDog Service Catalog Workflows 

## Acceptance criteria

- [x]  Create or update workflow for DataDog so that it can handle multiple files when updating the service catalog after merge
- [x]  do not update deleted files

## Requested Feedback

This currently filters out deleted files in git to avoid errors. 

There is an option where a deleted file can trigger a delete action, but would like input from the CY team on whether that should happen or not, at all, and whether we should make a ticket to add that after this PR.

### CODE REVIEW

**Comment by acrollet** [comment]
> This currently filters out deleted files in git to avoid errors.
> 
> There is an option where a deleted file can trigger a delete action, but would like input from the CY team on whether that should happen or not.

Hmm, I think it should be somewhat hard to delete services, so imo we should either:

- throw an error or otherwise require an approval when a file is deleted, and trigger the delete action, or:
- ignore deleted files and deal with manually deleting services in datadog

@patrickvinograd any thoughts?

**Comment by lexicalninja** [comment]
ran some tests to make sure it was filtering correctly. outputs are here, will be updating to add the actual merge filter and the actual API call now

**Comment by lexicalninja** [comment]
> Reference in

Right now, this change filters out delete actions with the `--diff-filter=d`

I figured that I would get the rest of the things in there and then talk about the delete and decide.

**Review by ericboehs — APPROVED** [review]

**Review by ericboehs — APPROVED** [review]

**Review by patrickvinograd — APPROVED** [review]

**Comment by lexicalninja** [comment]
You are deleting a DataDog Service Definition file in this PR. If this changes is merged to the main branch, that service will be automatically delteed from DataDog via API. Please double check that this service no longer exists and needs to be deleted.

**Comment by lexicalninja** [comment]
You are deleting a DataDog Service Definition file in this PR. If this changes is merged to the main branch, that service will be automatically delteed from DataDog via API. Please double check that this service no longer exists and needs to be deleted.

**Comment by lexicalninja** [comment]
You are deleting a DataDog Service Definition file in this PR. If this changes is merged to the main branch, that service will be automatically delteed from DataDog via API. Please double check that this service no longer exists and needs to be deleted.

**Pull request merged**
