### PR TITLE
Fetch and cache aws creds when needed

### PR DESCRIPTION
**Pull request by austin-martinez**
The key changes on each deploy so cannot be reliably retrieved from an ENV var.
This was originally in an initializer but failed during `rake db:migrate` as the bake instance does not have the appropriate role. This change will only call the instance metadata endpoint when a document upload is first attempted, and will cache the credentials.

### CODE REVIEW

**Comment by aub** [comment]
Another way to do this would be to add roles to the EC2 instances and then we wouldn't have to deal with fetching the credentials at all. But of course you'd need to get some DevOps help setting that up.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

**Comment by knkski** [comment]
@carlmjohnson: Yeah, it will show up in CloudWatch, where we'll get alerts

**Comment by knkski** [comment]
@aub: Roles have been set up on the instance (and the credentials this retrieves are tied to that role), but the library that @austin-martinez is using requires that we pass it valid credentials.

**Comment by austin-martinez** [comment]
@aub pointed me to a few different resources showing how to use aws-sdk to get the credentials from the instance. replaced fog/aws with carrierwave-aws gem and tested on an EC2 instance and all was :+1: so going to merge

**Pull request merged**
