### PR TITLE
84169: Add case_id to IvcChampVAForms table

### PR DESCRIPTION
**Pull request by balexandr**
First of a couple of PRs, this one just adds the column to the DB table.

## Summary

- Generate migration to add `case_id` to IvcChampVaForms table

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84169

## Screenshots
Screenshot 2024-06-05 at 1 09 34 PM

### CODE REVIEW

**Review by michaelclement — DISMISSED** [review]

**Review by ryan-mcneil — CHANGES_REQUESTED** [review]
@balexandr is the `safety_assured` block necessary if we're just adding a column?

**Comment by balexandr** [comment]
> @balexandr is the `safety_assured` block necessary if we're just adding a column?

@ryan-mcneil  I noticed it in a lot of other places, and figured it'd be safer than sorry to use it. I'll remove it

**Review by cloudmagic80 — CHANGES_REQUESTED** [review]
Do we have to call it pega_case_id? Case_id might be a better name since pega_case_id suggests that it is related to a specific case or context (Pega). If this is a generic case ID that can be used across different contexts, you might consider naming it simply case_id for better readability and reusability.
Also, it is generally a good practice to include the corresponding changes in the codebase that utilize the new column within the same commit. This helps maintain the integrity and consistency of the codebase.

**Comment by balexandr** [comment]
> Do we have to call it pega_case_id? Case_id might be a better name since pega_case_id suggests that it is related to a specific case or context (Pega). If this is a generic case ID that can be used across different contexts, you might consider naming it simply case_id for better readability and reusability. Also, it is generally a good practice to include the corresponding changes in the codebase that utilize the new column within the same commit. This helps maintain the integrity and consistency of the codebase.

@cloudmagic80  Typically I would agree but I am prefixing it with pega_ in case we change systems in the future (Which seems likely) and don't want to merge case_ids across systems.

Second, I would normally include all the changes in one PR but when you do a migration through platform you have to push it up in a PR separately than the code otherwise it will get rejected. I've had to break out multiple migrations as well.

**Review by cloudmagic80 — DISMISSED** [review]

**Review by ryan-mcneil — APPROVED** [review]
🚢

**Pull request merged**
