### PR TITLE
Client response refactor Part 1

### PR DESCRIPTION
**Pull request by saneshark**
This just does the following:

1.  rename Common::Client::Errors::ClientResponse to Common::Client::Errors::APIError
2.  moves the class into its own file.

In a future this class might not be necessary at all, but for now, based on previous conversation, this will be a more accurate name.

### CODE REVIEW

**Comment by saneshark** [comment]
This is super minor, first step in additional refactors. This class might go away entirely eventually based on direction the other phases of this refactor will take, but I thought this was a good first step PR. Should have another one shortly.

**Comment by aub** [comment]
Nice, this is definitely a big improvement. I'm wondering if the name of the exception could be even more clear, though. From the name it's still a little unclear to me whether it means an error in _our_ API or an error in one of the backend APIs. Maybe I'm just not thinking about it the right way.

**Comment by saneshark** [comment]
Yea, I was going to do APIServerResponseError but opted for brevity. I'm open to suggestions.

**Comment by aub** [comment]
BackendServiceError?

**Comment by aub** [comment]
Yay!

**Pull request merged**
