### PR TITLE
remove env vars for mhv user_ids

### PR DESCRIPTION
**Pull request by saneshark**

### CODE REVIEW

**Comment by saneshark** [comment]
@ayaleloehr

**Comment by ayaleloehr** [comment]
LGTM. This removes an environment variable that we no longer need and will let us have consistent variables across dev/staging/prod (since we won't have this variable in prod).  

Deferring to @plusjeff or @robbiethegeek on whether this can be merged or not.

**Comment by plusjeff** [comment]
LGTM to me. This is super low risk since it just impacts tests rather than core functionality. OK by me. Any concerns @robbiethegeek ?

**Comment by robbiethegeek** [comment]
Nope 👍  :shipit:

**Comment by saneshark** [comment]
@plusjeff I'm went ahead and upmerged, let me know if it is safe to merge or if it needs to coincide with whenever the next build will take place.

**Comment by plusjeff** [comment]
@saneshark All merged!

**Pull request merged**
