### PR TITLE
BAH Pre-fill Education Form 0994

### PR DESCRIPTION
**Pull request by abhijitvk**
## Description of change

PR that includes the following updates:
- Configure pre-fill for VetTec 0994 Form. Form PDF [22-0994](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability%20Compensation/BAH-526/engineering/VetTec/Form22-0994.pdf)
- Form [22-0994 Schema](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/22-0994-schema.json)
- Unit tests to support the code

## Testing done
- Unit testing
- Local testing

## Testing planned
- Unit testing
- Cross-browser (by QA)
- Manual testing (by QA)

## Acceptance Criteria (Definition of Done)
- Unit tests passed
    - spec/models/form_profile_spec.rb

#### Unique to this PR
 NA

#### Applies to all PRs

- [X] Appropriate logging
- [X] Swagger docs have been updated, if applicable
- [X] Provide link to originating GitHub issue, or connected to it via ZenHub
- [X] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [X] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by abhijitvk** [comment]
Code changes can safely be merged into master after review. This is the back end code and the new edu form 0994 model will come into play for a that form id `22-0994`

**Comment by abhijitvk** [comment]
@department-of-veterans-affairs/code-reviewers-for-external-teams-group  - Requesting a code review on this PR. Thanks

**Comment by rianfowler** [comment]
@kreek Can someone on your team review this? Thanks!

**Comment by abhijitvk** [comment]
@briangryth : PR has been approved. Do you need someone else to review this before I can merge this into master?

**Comment by briangryth** [comment]
@abhijitvk No you are good to go. If @kreek gave the approval, then it is good to go.

**Pull request merged**
