### PR TITLE
Increase file upload size for Form526 bdd

### PR DESCRIPTION
**Pull request by annaswims**
## Description of change
Increase allowed upload size 

Do not merge until after the limit has been increased in VBA and EVSS (anticipated date Sept ~~16~~ 30, we've been emailing)
## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13178

### CODE REVIEW

**Comment by annaswims** [comment]
note to self - reconsider EVSS::DocumentsService::DEFAULT_TIMEOUT

**Comment by annaswims** [comment]
latency metrics http://grafana.vfs.va.gov/d/000000050/backend-service-report?viewPanel=101&orgId=1&from=now-2d&to=now

**Comment by kfrz** [comment]
@annaswims any update - has this limit been upp'd by EVSS?

**Comment by annaswims** [comment]
nope. delayed to  9/30. 🤞 https://dsva.slack.com/archives/G016CG5FT6Z/p1599853479019500

**Comment by annaswims** [comment]
DEFAULT_TIMEOUT = 180 and average latency tops out at around 35s, so we're probably fine with the current timeout but I'll keep an eye on it after launch

**Comment by annaswims** [comment]
confirmed that EVSS update is going out tongiht.

**Review by erluti — APPROVED** [review]
LGTM

**Pull request merged**
