### PR TITLE
[84308] Preventing Sign Up Service Terms of Use calls when user does not have a sec id

### PR DESCRIPTION
**Pull request by bosawt**
## Summary

- This PR prevents Terms of Use Accept/Decline calls from being propagated to the Sign Up Service when a user does not have a sec id. It will instead log that the Sign up Service is not being called and accept the terms for VA.gov, still allowing the user to log in

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84308

## Testing done

- Authenticated with a normal verified user and confirmed SignUpServiceUpdaterJob was attempted
- Authenticated with a verified user with no sec_id and confirmed SignUpServiceUpdaterJob was not attempted, and log that states the job will not be called was logged

## What areas of the site does it impact?
Terms of Use
Authentication

## Acceptance criteria

- [ ]  Authenticate with a verified user that does not have a sec id (which has not previously accepted terms of use)
- [ ]  Accept terms and confirm the following log:  '[TermsOfUse] [Acceptor] Sign Up Service not updated due to user missing sec_id'
- [ ] Confirm no calls to the SignUpServiceUpdaterJob were attempted
- [ ] Authenticate with a verified user that does have a sec id
- [ ] Confirm a calla to the SignUpServiceUpdaterJob was attempted

### CODE REVIEW

**Review by dickdavis — APPROVED** [review]
LGTM

**Review by bramleyjl — APPROVED** [review]
Confirmed no SuS ToU Updater Job call occurred on an mpi_profile with no sec_id, authentication was still successful and an `accepted` ToU agreement record was still made.

`Rails -- [TermsOfUse] [Acceptor] Sign Up Service not updated due to user missing sec_id -- { :icn => "1008596379V859838" }`

**Comment by ph-One** [comment]
@bosawt Does this relate to the several hundred retries in sidekiq that have built up, by chance?

```
TermsOfUse::SignUpServiceUpdaterJob
```

```
Common::Client::Errors::ClientError: [MAP][SignUp][Service] agreements accept failed, client error, status: 500
```

**Comment by bosawt** [comment]
> @bosawt Does this relate to the several hundred retries in sidekiq that have built up, by chance?
> 
> ```
> TermsOfUse::SignUpServiceUpdaterJob
> ```
> 
>  ```
> Common::Client::Errors::ClientError: [MAP][SignUp][Service] agreements accept failed, client error, status: 500
> ```

Yes, we've identified a set of jobs that won't succeed no matter how many times they're retried, and this commit should stop these jobs from being enqueued.

Unfortunately, there are a number of jobs in the retry queue that fail once or twice but pass after that, so we'd prefer if we didn't just clear the retry queue and let them naturally expire (they will expire after 48 hours). If the queue starts to hit size limits before this PR is deployed and jobs naturally expire, of course we could probably come up with a compromise

**Pull request merged**
