### PR TITLE
Temporarily set loa_highest to loa_current

### PR DESCRIPTION
**Pull request by bshyong**
## Description of change
Temporarily sets `loa_highest` to `loa_current` to facilitate SSOe testing with IAM team

## Testing done
Local testing

## Testing planned
Testing in staging 

## Acceptance Criteria (Definition of Done)
Temporarily sets `loa_highest` to `loa_current` to facilitate SSOe testing with IAM team

### CODE REVIEW

**Comment by patrickvinograd** [comment]
This is failing a test case.

**Comment by johnpaulashenfelter** [comment]
@bshyong is this solely for testing (as in will never get merged)? Would love to see a blocked tag on it (and would prefer to see it as a draft PR, but github doesn't give you a way to convert back to that).

**Comment by patrickvinograd** [comment]
The overall SSOe integration feature is exposed in dev only. But it needs to get merged to master to unblock additional testing, and thus is not a draft PR. 

This logic is temporary because we are awaiting some additional attributes to  be mapped into the SAML  payload from the SSOe team, at which point we will adjust the logic to account for the additional incoming data.

**Comment by johnpaulashenfelter** [comment]
@bshyong @patrickvinograd oh! this is for the work in the v1 sessions controller?

**Comment by bshyong** [comment]
@johnpaulashenfelter the V1 sessions controller work relates to Okta which is a separate stream of work. This PR touches code that will only get triggered when testing our specific login flow

**Comment by patrickvinograd** [comment]
@johnpaulashenfelter Yes. The ssoe user attributes class is only used in the v1 session controller code  path.

**Pull request merged**
