### PR TITLE
Add pghero gem

### PR DESCRIPTION
**Pull request by annaswims**
## Description of change
We had an an outage last night due to increased traffic and decreased database capacity. 

This PR is the first in a series to add visibility to issues of database performance and maintenance. 

[PGhero](https://github.com/ankane/pghero) has a [nice web interface ](https://pghero.dokkuapp.com/)that we could consider adding/securing in the future, but in the meantime we can run these command and more in the ruby console. 

````ruby
PgHero.running_queries
PgHero.long_running_queries
PgHero.index_usage
PgHero.invalid_indexes
PgHero.missing_indexes
PgHero.unused_indexes
PgHero.unused_tables
PgHero.database_size
PgHero.relation_sizes
PgHero.index_hit_rate
PgHero.table_hit_rate
PgHero.total_connections
````

https://github.com/ankane/pghero/blob/master/guides/Rails.md#methods
## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Things to know about this PR
We have pg_stat_statements enabled in our staging/production databases, but it is not considered a developer requirement at this time. There is much more we can do if we enable pg_stat_statements and run a job to capture metrics.

### CODE REVIEW

**Comment by annaswims** [comment]
An example of what kind of data it might give us, except for the part where it's not quite relevant on my nearly-empty and recently-refreshed local db.

````
PgHero.index_usage
=> [{:schema=>"public", :table=>"spatial_ref_sys", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>5757},
 {:schema=>"public", :table=>"feature_toggle_events", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>102},
 {:schema=>"public", :table=>"flipper_features", :percent_of_times_index_used=>"9", :estimated_rows=>76},
 {:schema=>"public", :table=>"flipper_gates", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>26},
 {:schema=>"public", :table=>"schema_migrations", :percent_of_times_index_used=>"88", :estimated_rows=>22},
 {:schema=>"public", :table=>"preference_choices", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>10},
 {:schema=>"public", :table=>"ar_internal_metadata", :percent_of_times_index_used=>"85", :estimated_rows=>2},
 {:schema=>"public", :table=>"accounts", :percent_of_times_index_used=>"50", :estimated_rows=>1},
 {:schema=>"public", :table=>"preferences", :percent_of_times_index_used=>"80", :estimated_rows=>1},
 {:schema=>"public", :table=>"appeals_api_higher_level_reviews", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"appeals_api_notice_of_disagreements", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"async_transactions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"base_facilities", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"beta_registrations", :percent_of_times_index_used=>"60", :estimated_rows=>0},
 {:schema=>"public", :table=>"central_mail_submissions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"claims_api_auto_established_claims", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"claims_api_power_of_attorneys", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"claims_api_supporting_documents", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"covid_vaccine_registration_submissions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"directory_applications", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"disability_contentions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"drivetime_bands", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"education_benefits_claims", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"education_benefits_submissions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"evss_claims", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"form1010cg_submissions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"form526_job_statuses", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"form526_submissions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"form_attachments", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"gibs_not_found_users", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"health_care_applications", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"id_card_announcement_subscriptions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"in_progress_forms", :percent_of_times_index_used=>"50", :estimated_rows=>0},
 {:schema=>"public", :table=>"invalid_letter_address_edipis", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"maintenance_windows", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"mhv_accounts", :percent_of_times_index_used=>"60", :estimated_rows=>0},
 {:schema=>"public", :table=>"notifications", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"persistent_attachments", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"personal_information_logs", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"pghero_query_stats", :percent_of_times_index_used=>"75", :estimated_rows=>0},
 {:schema=>"public", :table=>"preferred_facilities", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"preneed_submissions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"saved_claims", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"session_activities", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"terms_and_conditions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"terms_and_conditions_acceptances", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"user_preferences", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"va_forms_forms", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"vba_documents_upload_submissions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"versions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"veteran_organizations", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"veteran_representatives", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0},
 {:schema=>"public", :table=>"vic_submissions", :percent_of_times_index_used=>"Insufficient data", :estimated_rows=>0}]
````

**Comment by LindseySaari** [comment]
Do you see this as something that we will utilize frequently? I see that it has the capability to measure cpu and connections, but we already get things like this from our grafana graphs. Overall, this seems like a nice to have though.  

How did we zone in on the faulty query from last nights database capacity issue? Just wondering how much faster would this get us to a resolution compared to the tools we have now?

**Comment by annaswims** [comment]
I really do think we could/should use it frequently.  I think it will highlight potential issues that no one is looking at now. I've used it in the past and it was my go-to for "what's wrong with the database - I need to know RIGHT NOW".  Things like "Show me most time-consuming queries happening within a time range" are super helpful.

I don't think anyone has been looking at if our tables are properly indexed and pghero makes it easy and even suggests missing indexes and explains why that index is necessary. 


Screen Shot 2020-12-16 at 1 09 17 PM



To get query stats last night I ran this in console:  
```
sql="SELECT
  (total_time / 1000 / 60) as total,
  (total_time/calls) as avg,
  query
FROM pg_stat_statements
ORDER BY 1 DESC
LIMIT 100;"  

 results  = ActiveRecord::Base.connection.execute(sql)
```

**Comment by annaswims** [comment]
I think the last time we looked at query stats was https://github.com/department-of-veterans-affairs/va.gov-team/issues/5545

**Review by LindseySaari — APPROVED** [review]
I think this is a good idea for getting quick insight when looking into issues 👍

**Pull request merged**
