### PR TITLE
[12301] Removing Sidekiq DowntimeChecker middleware and using regular sidekiq retries instead

### PR DESCRIPTION
**Pull request by bosawt**
## Summary

- This PR removes some Sidekiq middleware that was preventing certain jobs from being retried until outside the window of 2:00 AM to 10:00 AM UTC most days. Instead, regular sidekiq retries have been added to relevant jobs, as this is a much more expected pattern

## Related issue(s)
- department-of-veterans-affairs/vets-api#12301

## What areas of the site does it impact?
- BGS Sidekiq jobs

## Acceptance criteria

- [ ]  Confirm that the retry numbers are set to an acceptable amount for the jobs that are affected
- [ ] Kinda hard to test, as this is only relevant for Sidekiq jobs that have failures, and is very dependent on the behavior of the external BGS system

### CODE REVIEW

**Review by rjohnson2011 — APPROVED** [review]

**Comment by kylesoskin** [comment]
@bosawt @data-doge did we ever figure out with BGS if they still have those downtimes? Even if they do this still should be refactored, but just curious! Thanks!

**Comment by bosawt** [comment]
> @bosawt @data-doge did we ever figure out with BGS if they still have those downtimes? Even if they do this still should be refactored, but just curious! Thanks!

I'm not sure, I suppose we'll know if there are failures during the Saturday 'downtime' period. BTW, if we do find out there are still downtime periods like this, frontend probably just shouldn't allow for these forms to be submitted during those times

**Comment by kylesoskin** [comment]
Yep, or follow the pattern of other services (like 526) where it will retry (in exponentially increasingly large intervals, up to a certain number). 

IE will attempt up to 10 times. time between attempt 1 and 2 is 30s, between 2 and 3 is 5 mins, 4 and 5 is 1 hr, etc. Usually with the final attempt at most 24 hrs away from the initial attempt, that is enough to smooth over any maitinence type issues or network issues or whatever that will get resolved in less than 24 hrs. 

All good, this hopefully is still an improvement.

**Comment by data-doge** [comment]
Thank you @bosawt, you are the best! 
- PR LGTM. I just updated the PR title and desc to remove language around regular sidekiq retries. 
- These jobs are not idempotent, and automatic retries may cause unwanted chaos. 
- BGS has true downtime periods ("downtime periods") approximately once a month, where they perform maintenance. But they also have "non-processing periods" (that's just what I'm calling them), where they _will_ still accept network requests -- but those requests will be memorialized in a db table to be run once their servers begin processing requests again. Which explains the code here, that we've removed. 
- Interestingly, the periods we removed in this PR are different than BGS's actual non-processing periods. 
- Also, if we send "bad" requests (invalid form data, etc.)  during this non-processing period, one of two things can happen: 1) we will immediately get an http error status code (e.g. their database rejects invalid data type), or 2) the request will fail _after_ it is finally processed. In the second case, we would have no way of knowing of such a failure.

**Comment by data-doge** [comment]
@bosawt 
> if we do find out there are still downtime periods like this, frontend probably just shouldn't allow for these forms to be submitted during those times (until a more sustainable solution is created)

YES! Totally agree.

**Pull request merged**
