### PR TITLE
[17432] Refactoring various SAML error codes to use descriptive namin…

### PR DESCRIPTION
**Pull request by bosawt**
…g instead of three digit code

## Description of change
This PR changes the SAML error codes so we refer to them by a descriptive name, and not the arbitrary three digit code. Shouldn't be any functional change, purely a technical debt refactor.

## Original issue(s)
department-of-veterans-affairs/va.gov-team/issues/17432

## Things to know about this PR
- This shouldn't impact production or staging
- If specs pass, we should be good to go

### CODE REVIEW

**Comment by bramleyjl** [comment]
Changes make sense and look good to me.

**Review by LindseySaari — APPROVED** [review]
Definitely like the usage of constants here for the error codes 👍

**Review by AGarcia-Clarity — APPROVED** [review]
LGTM

**Review by bramleyjl — APPROVED** [review]
LGTM

**Review by joeniquette — APPROVED** [review]

**Pull request merged**
