### PR TITLE
Bkjohnson vic fix

### PR DESCRIPTION
**Pull request by bkjohnson**
## Description of change

This is to address the [removal of the VIC schema from `vets-json-schema`](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/404).  It was strictly used in `vic-v2` in [vets-website](https://github.com/department-of-veterans-affairs/vets-website) which was not used in production.  This [unused app was removed](https://github.com/department-of-veterans-affairs/vets-website/pull/12254) in order to begin [addressing some CSP issues](https://github.com/department-of-veterans-affairs/vets-website/pull/12264).

The `vets-api` code which was written to support `vic-v2` had some breaking tests when `vets-json-schema` was updated, so this PR attempts to remove that dead code.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Things to know about this PR

It removes a lot of code.  The line between what is for the `veteran-id-card` and `vic-v2` frontend apps is blurry. It looks like a lot of the code for "v1" uses the name prefix `id_card`, but there is still some `VIC`/`vic` mixed in. I've tried not to be too aggressive in removing things.

There are still some broken tests - this is due to the commits made between what is currently the `vets-json-schema` version in this repo and the commit I made which removed the VIC schema. The commits are:

- https://github.com/department-of-veterans-affairs/vets-json-schema/commit/053ccd1ceea44e26c0743cb0e1a67a6622a33732
- https://github.com/department-of-veterans-affairs/vets-json-schema/commit/e3289458e15c2acdc0894a242aaa345cf1ca556b
- https://github.com/department-of-veterans-affairs/vets-json-schema/commit/6cccb8d86ab63853f2f841cc13d9cb9baee6306b

You can view them together [here](https://github.com/department-of-veterans-affairs/vets-json-schema/compare/4046437da2ee333c490ff7860b053062faccd65a...6cccb8d86ab63853f2f841cc13d9cb9baee6306b)

These are not related to the VIC changes and are being fixed here:
https://github.com/department-of-veterans-affairs/vets-api/pull/4187

### CODE REVIEW

**Comment by kevinmirc** [comment]
@bkjohnson version 5.0.1 of vet-json-schema will resolve the failing tests. If you upgrade your PR to that commit `0a1dbc9ba6cf0177a60ca216f74b3eaed6241271 ` or `master`, the test suite should now pass.

**Comment by jholton** [comment]
Version 5.0.1 also brings in changes to the 686C-674, 10-10CG and 526 so we still don't want to merge until the authors of those changes have been consulted.

**Comment by jholton** [comment]
Yeah, I see that we're now getting test failures due to these other schema changes.

**Comment by kevinmirc** [comment]
@jholton I merged this PR into https://github.com/department-of-veterans-affairs/vets-api/pull/4170 which resolved all breaking changes in 5.x.x. Please review.

**Comment by patrickvinograd** [comment]
Looks good to me in terms of VIC v1 vs v2; there was overlap in `lib/vic` but only the `url_helper` and `id_card_attribute_error` are used by v1.

**Comment by bkjohnson** [comment]
These changes were merged with #4170 - closing for now.

**Pull request closed without merging**
