### PR TITLE
add error handling and logging

### PR DESCRIPTION
**Pull request by rmtolmach**
## Summary

- An error was reported to me by @kjsuarez. I had also seen this error while working on https://github.com/department-of-veterans-affairs/vets-api/pull/14327
- I don't see this error in [Datadog logs](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20%22undefined%20method%20%60%3E%3D%27%20for%20nil%3ANilClass%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1687894962395&to_ts=1687895862395&live=true).
- Add logging to be able to understand what the actually error (`e`) is here. AND defensively handle the error.

## Error
Kevin's team is getting 500s when hitting `/v0/in_progress_forms/5655`

```
"errors": [
        {
            "title": "Internal server error",
            "detail": "Internal server error",
            "code": "500",
            "status": "500",
            "meta": {
                "exception": "undefined method `>=' for nil:NilClass",
                "backtrace": [
                    "/srv/vets-api/src/lib/va_profile/military_personnel/service.rb:40:in `rescue in get_service_history'",
                    "/srv/vets-api/src/lib/va_profile/military_personnel/service.rb:24:in `get_service_history'",
                    "/srv/vets-api/src/lib/hca/military_information.rb:141:in `service_history'",
                    "/srv/vets-api/src/lib/hca/military_information.rb:81:in `military_service_episodes'",
                    "/srv/vets-api/src/lib/hca/military_information.rb:63:in `service_episodes_by_date'",
                    "/srv/vets-api/src/lib/hca/military_information.rb:77:in `latest_service_episode'",
                    "/srv/vets-api/src/lib/hca/military_information.rb:73:in `hca_last_service_branch'",
                    "/srv/vets-api/src/app/models/form_profile.rb:211:in `public_send'",
                    "/srv/vets-api/src/app/models/form_profile.rb:211:in `block in initialize_military_information_vaprofile'",
                    "/srv/vets-api/src/app/models/form_profile.rb:210:in `each'",
                    "/srv/vets-api/src/app/models/form_profile.rb:210:in `initialize_military_information_vaprofile'",
                    "/srv/vets-api/src/app/models/form_profile.rb:239:in `initialize_military_information'",
                    "/srv/vets-api/src/app/models/form_profile.rb:197:in `prefill'",
                    "/srv/vets-api/src/app/models/form_profiles/va_5655.rb:32:in `prefill'",
                    "/srv/vets-api/src/app/controllers/v0/in_progress_forms_controller.rb:50:in `camelized_prefill_for_user'",
                    "/srv/vets-api/src/app/controllers/v0/in_progress_forms_controller.rb:15:in `show'",
                    "/usr/local/bundle/bundler/gems/rails-90b0266e9bfa/actionpack/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'",
                    "(eval):2:in `process_action'",
                    "/usr/local/bundle/bundler/gems/rails-90b0266e9bfa/actionpack/lib/action_controller/metal/rendering.rb:30:in `process_action'",
                    "(eval):3:in `block in process_action'",
...
```

### CODE REVIEW

**Review by ericboehs — APPROVED** [review]

**Review by tpharrison — APPROVED** [review]

**Comment by rmtolmach** [comment]
Thanks for the reviews!

**Comment by rmtolmach** [comment]
I believe the error could be found using [this Datadog query](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20%22Miscellaneous%20service%20history%20error%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1700053958812&to_ts=1700068358812&live=true). I haven't seen it yet.

**Comment by rmtolmach** [comment]
I found it in Datadog. 99% of the 120 errors I looked at were because of a `504`
```
payload {
    error  the server responded with status 504
}
```
But then a few of them had this error:
`end of file reached`

> `504 Gateway Timeout` server error response code indicates that the server, while acting as a gateway or proxy, did not get a response in time from the upstream server that it needed in order to complete the request.

With a couple exceptions, most of the errors occur in the same minute or two, and then there will be stretches of days with no error.
image

Next steps:
- [ ] Assuming this is coming from VA Profile, look at the Swagger docs for possible error codes. 
- [ ] Determine how we want to handle these responses. 
- [ ] Possibly reach out to VA Profile team.

**Comment by rmtolmach** [comment]
**More investigation:**
I looked at errors that occurred at the same time as this debug message and found this: 
```
BackendServiceException: {:source=>"VAProfile::MilitaryPersonnel::Service", :code=>"VET360_502"}
```
Which is accompanied by the message, "Received an an invalid response from the upstream server" which is from `handle_error` in [lib/va_profile/service.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/va_profile/service.rb#L43)

> look at the Swagger docs for possible error codes

Swagger docs for militaryPerson specify a very specific `500` error. It's possible we get this error on occasion (remember that most errors are `504`, not `500`).

> Determine how we want to handle these responses.

We are handling them with the `handle_error` method I linked to above. This seems acceptable to me since we don't have any control over what VA Profile returns to us.

**Pull request merged**
