### PR TITLE
only attempt to fetch icn if mvi instance variable already set

### PR DESCRIPTION
**Pull request by saneshark**

### CODE REVIEW

**Comment by robbiethegeek-usds** [comment]
Should we consider an emergency deploy?  Is this something that is breaking on Prod now if the user doesn't have an ICN or is this because test users data is inconsistent?

**Comment by jkassemi** [comment]
@robbiethegeek-usds FWIW I don't see any instances of this problem on production yet.

**Comment by robbiethegeek-usds** [comment]
Yeah I checked sentry also let's merge this in so it is on dev / staging and verify it is working before today's deploy

**Comment by omgitsbillryan** [comment]
We don't see any errors in production because the original commit is not yet in production
https://github.com/department-of-veterans-affairs/vets-api/commit/207a3ce06cbdf5480ef85980b4b158a56018f8e1

**Comment by robbiethegeek-usds** [comment]
@saneshark can you run with the revert?  Heading to a meeting

**Pull request merged**
