### PR TITLE
Update README: Get cert before running setup script

### PR DESCRIPTION
**Pull request by cvalarida**
I ran the automated script without setting up the cert first and got an error because it expected it. I got the cert, reran the script, and it all worked out.

Not sure who to ask for a review from, so I'll just @mention GitHub's suggested reviewers, @knkski, @robbiethegeek, and @markolson.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
Also tagging @omgitsbillryan because it's ID.me related.

**Comment by jcmeloni-usds** [comment]
These what you're looking for? https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Identity/Files_From_IDme/development-certificates

**Comment by jcmeloni-usds** [comment]
Oh, this isn't "i have an issue" it's "instructions need to be updated". my bad. will read better in the future.

**Comment by markolson** [comment]
Maybe we could update `bin/setup-osx` to touch (or even try to grab) those files too?

**Comment by robbiethegeek-usds** [comment]
@cvalarida this looks great, I think if you can update the setup-osx and ping @markolson and it should be merged in.

**Comment by cvalarida** [comment]
Yeah, I thought about updating the script, but I'm not super confident in my bash-fu. I'll give it the ol' college try, though!

**Comment by cvalarida** [comment]
Turns out this became more of a `fix-setup-script` than a `fix-readme` kind of branch, but that's for the better. Bash-fu to the rescue!

**Pull request merged**
