### PR TITLE
Ndb/71164 metadata validation PR

### PR DESCRIPTION
**Pull request by micahaspyr**
## Summary

- Burial and Pension forms have had issues where some special characters in a Veteran's first and/or lastname causes a failure within the Central Mail EMMS API regex
- This solution strips out any offending characters from the metadata of the saved claim submission
- Non disability team Umbrella

## Related issue(s)
- [Metadata validation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71164)

## Testing done

- Old behavior would fail the regex and an error was failing silently
- I tested locally by entering in a burial claim where the Veteran has bad characters i.e. (V.A. for the firstname)
- Testing showed that the name is stripped of bad characters and passes the regex supplied to us by the Central Mail team

## What areas of the site does it impact?
This impacts central mail claims (burials, pensions, ECC) and the metadata that is sent from these forms

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X]  No error nor warning in the console.
- [X]  Events are being sent to the appropriate logging solution
- [X]  Documentation has been updated (link to documentation)
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by Thrillberg** [comment]
Hey! 👋 Sorry to poke my nose in here, but I happened to see this PR and it looked very relevant to some work I recently did on [a `MetadataValidator` for submissions to the Benefits Intake API](https://github.com/department-of-veterans-affairs/vets-api/blob/ef2fd0bbf45ac176a7d8022a3907bfdd86f29c82/lib/simple_forms_api_submission/metadata_validator.rb#L4). Am I correct to assume that you're submitting to a different API? (Your metadata here is in a slightly different shape than my metadata for Benefits Intake API is, but there are some fields in common). Anyway, just wanted to see if there was interest in adapting and using my `MetadataValidator`. In any case, it might be helpful to call `I18n.transliterate` on first and last names so that you don't end up dropping letters entirely and, if they're in the Roman alphabet, they'll convert to "unaccented" versions of the letter.

I'd be happy to collaborate to extend the usefulness of the `MetadataValidator` beyond just Benefits Intake API! Let me know if you're interested.

**Comment by micahaspyr** [comment]
> Hey! 👋 Sorry to poke my nose in here, but I happened to see this PR and it looked very relevant to some work I recently did on [a `MetadataValidator` for submissions to the Benefits Intake API](https://github.com/department-of-veterans-affairs/vets-api/blob/ef2fd0bbf45ac176a7d8022a3907bfdd86f29c82/lib/simple_forms_api_submission/metadata_validator.rb#L4). Am I correct to assume that you're submitting to a different API? (Your metadata here is in a slightly different shape than my metadata for Benefits Intake API is, but there are some fields in common). Anyway, just wanted to see if there was interest in adapting and using my `MetadataValidator`. In any case, it might be helpful to call `I18n.transliterate` on first and last names so that you don't end up dropping letters entirely and, if they're in the Roman alphabet, they'll convert to "unaccented" versions of the letter.
> 
> I'd be happy to collaborate to extend the usefulness of the `MetadataValidator` beyond just Benefits Intake API! Let me know if you're interested.

Oh sorry @Thrillberg but I didn't have my notifications setup properly so missed this message.  I was using the regex that the EMMS/Central Mail said they were using for the current way of submitting, not what we'll use for the Benefits Intake API which is what I think yours covers.  Eventually (hopefully soon) we'll be moving to BI as well so we'll just use what you already have.  I was planning to convert/transliterate the characters as you mention above, but I believe it's best to mirror what they use on their end for the time being.

**Comment by Thrillberg** [comment]
No worries @micahaspyr ! 😄

**Review by tblackwe — APPROVED** [review]

**Comment by tblackwe** [comment]
@freeheeling take a look at this central mail metadata PR. It should cover the issues in 4142

**Comment by freeheeling** [comment]
> @freeheeling take a look at this central mail metadata PR. It should cover the issues in 4142

@tblackwe This should also work for 4142, if similarly implemented within the `DisabilityCompensationForm::Form4142Processor`.

**Review by freeheeling — APPROVED** [review]
LGTM

**Pull request merged**
