### PR TITLE
Attachments 1

### PR DESCRIPTION
**Pull request by mphprogrammer**

### CODE REVIEW

**Comment by saneshark** [comment]
@mphprogrammer can you fix the specs? As discussed, you should only ever run vcr Cassettes for lib/api/sm/apis -- not for the request specs. This will create the new vcr cassette, and then your request spec should use the value created.

Somehow here it appears as though you generated new vcr cassettes in a different path than sm_client.

**Comment by mphprogrammer** [comment]
@saneshark spec/support/vcr_cassettes/a_new_message_with_4_attachments.yml was a remnant of my diagnosing the issue. It is not used. I created no new specs for this, but it was necessary to rerecord a spec to make sure what I did worled.

**Comment by mphprogrammer** [comment]
@saneshark I yml rerecorded because the issue was in the way the request was formatted. I had to ensure that the request formatting would work - since we were not getting failing tests before and should have.

**Comment by saneshark** [comment]
LGTM

**Pull request merged**
