### PR TITLE
WIP 12410 build preferences database and models

### PR DESCRIPTION
**Pull request by kfrz**
## Background

As part of the Recommendations feature it was decided to persist the user's recommendations to a database.  Through [the discussion around the appropriate database design](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11957), we landed on a three table implmentation.  

#### Unique to this PR

- [x] Follow the [Vets-API protocol for db migrations](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Work%20Practices/Engineering/Database%20Migrations.md)
- [x] Create the three db tables per the [finalized schema proposal](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11957#issuecomment-411220501):
  - `Preference`
  - `PreferenceChoice`
  - `UserPreference`
- [x] Include indexes in migration for performance
- [x] Create the associated models
- [x] Implement the associations, per the finalized schema proposal
- [x] Establish the core model validations (i.e. `presence`, `uniqueness`, etc.) - Collaborate w/dragons on what is being validated
- [x] When prepared to merge: schedule merge with DevOps so we can merge & migrate in concert. 

#### Applies to all PRs

- [x] Appropriate logging
- [x] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [x] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by kfrz** [comment]
@hpjaj do we want to add any specific yard docs to these models?

**Comment by hpjaj** [comment]
@kfrz - Yeah, as a class definition for each of these three new classes, how about we do a real short explanation with an `@see` out to the [winning design schema](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Data/Databases/Vets.gov/Preferences%20Schema%20Design.md#the-winning-preferences-table-design) section of the Preferences Schema Design Documentation.

**Comment by kfrz** [comment]
Todo: 

- [ ] Add YARD docs
- [ ] Update factories (add `PreferenceChoices` to `Preference` factory, etc)

**Comment by kfrz** [comment]
@dhall @jkassemi cc: @hpjaj 

As I was building out #12413 I encountered some concerns with the currently proposed db table design. Specifically, calling `Preference.choices` would only return `PreferenceChoice` objects if there was a corresponding `UserPreference`. This inaccurately portrays the relationship between the concepts, imho. 

I've updated this PR to represent a slightly tweaked schema proposal. While I understand this may cause a bit of friction in regards to maintaining documentation of our choices, I feel it's a cleaner interface and a slight improvement in our approach.

I'm happy to modify or rollback changes, but here's a summary of what's different than the [proposed & accepted schema design](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Data/Databases/Vets.gov/Preferences%20Schema%20Design.md#the-winning-preferences-table-design):

* Add `dependent: :destroy` to our `has_many` blocks to prevent orphaned records
* Replace `has_many :preference_choices, through: :user_preferences` with a standard `has_many`. This more closely aligns with the idea that a `Preference` can have one-or-many `PreferenceChoices`, and each `PreferenceChoice` is a unique choice within a given set of 'questions' or `Preference`s. 
* To further extend this idea of unique `PreferenceChoice` objects mapped to a set, we replace the `has_many ... through` with a `belongs_to` on `PreferenceChoice` table. Now we can gather `PreferenceChoice` objects without requiring a `UserPreference` to be associated. 
* Add a non-unique index on `preference_choices` table & `:preference_id`. Many `PreferenceChoices` can point to the same `Preference`. 

The code now looks like this:

```ruby
class Preference < ActiveRecord::Base
  has_many :user_preferences, dependent: :destroy
  #  has_many :preference_choices, through: :user_preferences
  has_many :preference_choices, dependent: :destroy
end
 
class UserPreference < ActiveRecord::Base
  belongs_to :preference
  belongs_to :preference_choice
  belongs_to :account
end
 
class PreferenceChoice < ActiveRecord::Base
  belongs_to :preference
  has_many :user_preferences, dependent: :destroy
  # has_many :preferences, through: :user_preferences
end

class Account < ActiveRecord::Base
  has_many :user_preferences, dependent: :destroy
end
```

Now we can utilize methods to gather results, e.g., 

```rb
Account.user_preferences
Preference.choices.map(&:title)
UserPreference.preference_choices
# etc...
```

If there are no objections or opposition to this manner of change I will update the relevant [design doc](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Data/Databases/Vets.gov/Preferences%20Schema%20Design.md#the-winning-preferences-table-design). Again, totally open to thoughts, just wanted to get this up for consideration.

**Comment by hpjaj** [comment]
@kfrz and I already discussed this at length yesterday.  It will slightly impact the way we treat `Preference`s that require a boolean type response, in that they will now need unique `PreferenceChoice` record(s) for each one, but I'm fine with the trade off.  LGTM.

**Comment by dhall** [comment]
These changes sound good to me as well, thanks for digging in deep on this. LGTM!

**Comment by kfrz** [comment]
Will make plan to merge early next week in concert with devops in order to ensure migrations are properly executed.

**Pull request merged**
