### PR TITLE
Add new VAOS feature flag for new facility page

### PR DESCRIPTION
**Pull request by jbalboni**
## Description of change
Adds a new feature flag for VAOS

## Original issue(s)
department-of-veterans-affairs/va.gov-team#13175

### CODE REVIEW

**Comment by erluti** [comment]
If this is for a front-end change, the docs say there should be a PR for the corrseponding front-end change https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by jbalboni** [comment]
@erluti There will be, I just hadn't gotten to it yet because this PR has to go first.

**Comment by erluti** [comment]
> @erluti There will be, I just hadn't gotten to it yet because this PR has to go first.

The PR should be a small one for adding the flag to https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/feature-toggles/featureFlagNames.js, I don't understand how this is blocking that?

**Comment by jbalboni** [comment]
@erluti Typically we try to merge the backend feature flag PRs before the front end ones, so we don't start requesting non-existent flags. That's all I meant. 

Are you asking me to create the vets-website PR before you approve this one? That hasn't been something VSP required in the past.

**Comment by erluti** [comment]
> @erluti Typically we try to merge the backend feature flag PRs before the front end ones, so we don't start requesting non-existent flags. That's all I meant.

agreed!

> Are you asking me to create the vets-website PR before you approve this one? That hasn't been something VSP required in the past.

Yes, I'm just going by the doc which says the PRs should coexist.  This isn't the first time I've pointed someone to that doc.  I'm sorry if our team has been inconsistent.

**Comment by jbalboni** [comment]
@erluti FE PR is here: https://github.com/department-of-veterans-affairs/vets-website/pull/14150

**Review by erluti — APPROVED** [review]

**Pull request merged**
