### PR TITLE
28069 vaos service appointments param updates

### PR DESCRIPTION
**Pull request by cferris32**
This work is for [28069](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/28069), which accounts for parameter and schema updates for the appointments endpoints as part of the new VAOS service.

- preferredLanguage was added to CreateAppointmentRequest and Appointment component schemas
- PractitionerIds was changed to practitionerIds in the CreateAppointmentRequest component schema
- practitioners was removed from the CreateAppointmentRequest component schema

### CODE REVIEW

**Review by LindseySaari — APPROVED** [review]

**Review by ajmagdub — COMMENTED** [review]
VAMF recently updated their swagger and added some fields to the appointment schema. Those field should be added to the V2 appointments serializer. I think is would make sense to add those changes to this PR.

**Comment by cferris32** [comment]
> VAMF recently updated their swagger and added some fields to the appointment schema. Those field should be added to the V2 appointments serializer. I think it would make sense to add those changes to this PR.



> VAMF recently updated their swagger and added some fields to the appointment schema. Those field should be added to the V2 appointments serializer. I think it would make sense to add those changes to this PR.

Newest serializer updates should reflect these changes

**Review by LindseySaari — APPROVED** [review]

**Review by ajmagdub — APPROVED** [review]
LGTM

**Review by grossb1 — APPROVED** [review]
LGTM

**Pull request merged**
