### PR TITLE
Forms api - add 21-4142 mappings

### PR DESCRIPTION
**Pull request by gmrabian**
Forms API: adding ability to submit this form via the forms API. Follows similar pattern to other forms like 26-4555

## Summary

- Adds generated mapping and model files (updated with proper mappings)
- Adds framework for custom stamps necessary for form
- Add test fixture file with sample payload
- Enable tests for this form

## Related issue(s)
- https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/92

## Testing done

- Tested locally using frontend flow with different payloads. Verified with file generated in `tmp/` folder

## What areas of the site does it impact?
Form 21-4142 (non-prod)

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by gmrabian** [comment]
Note: I'm aware this PR is large. The biggest file here is the `.json.erb` mapping file. It is merely mapping every PDF recognized field to the corresponding value in our data - hence it is large out of nature of the number of fields in the PDF.

**Comment by ryan-mcneil** [comment]
@gmrabian I was just about to ask about any associated tests, then read your comment 😆 . Personally I would always like to see tests included in the same PR as the respective code changes. And yes, I understand that at times the large diff is unavoidable, but acceptable in the case I think. I'd say pull that commit in here and we'll be good to go!

**Comment by gmrabian** [comment]
@ryan-mcneil good call. thanks for your feedback! ready to go now 😎

**Comment by gmrabian** [comment]
@ryan-mcneil can i get a re-review here?

**Comment by jeremy6d** [comment]
@gmrabian I'm going to handle this re-review

**Review by jeremy6d — APPROVED** [review]

**Pull request merged**
