### PR TITLE
Toe submission endpoint

### PR DESCRIPTION
**Pull request by s-caso**
Add submission endpoint to forms controller and remove toe & fry-dea specific controllers

## Original issue(s)
[department-of-veterans-affairs/va.gov-team#20614
](https://jira.np.afsp.io/browse/SA-20614)

### CODE REVIEW

**Review by RachalCassity — COMMENTED** [review]
check_toe_flipper is still referenced in modules/meb_api/app/controllers/meb_api/v0/education_benefits_controller.rb

**Comment by s-caso** [comment]
@RachalCassity Good catch, I removed any reference to TOE in that controller.

**Comment by RachalCassity** [comment]
@s-caso before_action :check_flipper does not need to be called? Just want to be sure.

**Comment by s-caso** [comment]
@RachalCassity The :check_flipper call is for the MEB routes and needs to be there.  The :check_toe_flipper was only there for the toe_letter route.

**Review by RachalCassity — APPROVED** [review]

**Pull request merged**
