### PR TITLE
changes needed to support working with cookies on localhost

### PR DESCRIPTION
**Pull request by saneshark**
Tagging all team leads in addition to my team to make them aware of this change since it will affect how you invoke your rails server for local testing.

## Description of change
Changing references in Settings.yml from `localhost:3000` to `127.0.0.1:3000` to allow for testing of cookies in local development. This is critical for replacing our current authentication scheme with a cookie based solution. It will however require a change to how the rails server is invoked locally. This fixes: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14218
fixes: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14219
and unblocks other tickets in that Epic.

## Testing done
Tested that `bundle exec rails s -b 127.0.0.01` will launch a local dev server that allows me to sign in to ID.me with vets-website running side-by-side. There might be some side-effects I have not accounted for though. We might need to run vets-website using something like `npm run watch:brand-consolidation -- --host=127.0.0.1` to mitigate those affects if they exist.

## Testing planned
More extensive testing will happen naturally. No affect on staging or production environments is to be expected.

#### Unique to this PR

- [ ] _Replace this line with individual tasks unique to your PR_

#### Applies to all PRs

- [x] Appropriate logging
- [ ] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by annaswims** [comment]
Nice work!  What do you think about something like this to make 127.0.0.1 the default host?
https://stackoverflow.com/a/33249657/244177

**Comment by saneshark** [comment]
Nice find @annaswims - let me try testing with that locally and seeing if I can get it to work.

**Comment by saneshark** [comment]
NOTE: I've tested the monkey patch:

1. The monkey patch only happens if rails is invoked with ARGV of 's' or 'server,' additionally
2. The monkey patch still allows you to manually specify a binding with `-b` flag, which will override whatever is set here as the default.
3. I wrapped the monkey patch with comments specific to Rails 4.2 so hopefully we know to change or fix this in the event that causes future migration to Rails 5 issues.

**Comment by saneshark** [comment]
It looks like localhost is working just fine on chrome and firefox. Closing this, will keep the branch around if for some reason it's needed. Absolutely bizarre.  🤷‍♂️

**Pull request closed without merging**
