### PR TITLE
Adds trace service tags for auth/identity controllers

### PR DESCRIPTION
**Pull request by patrickvinograd**
## Summary
Adds the newly-created Traceable concern to auth/identity-related API controllers, and tags their services so error traces will be associated correctly in Datadog.

 This rolls up several adjacent things like inherited proofing, but authentication seems like a reasonable bucket. Open to being more granular, but this also needs to make sense to more general audiences like POs across OCTO.  

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/66141

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by patrickvinograd** [comment]
Note the child controllers of the SignIn::ApplicationController will inherit its service tag.

**Comment by bosawt** [comment]
> Note the child controllers of the SignIn::ApplicationController will inherit its service tag.

Would this be permanent? Or if you added an additional declaration within the sub controllers, will it prioritize that definition? Just asking because the `Mobile::ApplicationController` inherits from this controller, and I assume we want to tag these with 'Mobile' instead of 'Authentication'

**Comment by patrickvinograd** [comment]
Yes, you can override service tags in child controllers. Mobile::ApplicationController is already tagged as `mobile-app`

**Comment by bosawt** [comment]
> Yes, you can override service tags in child controllers. Mobile::ApplicationController is already tagged as `mobile-app`

Sounds good. Could we tag these with `identity` rather than `authentication`? I don't foresee there being confusion over `identity`, but I could see there being confusion over `authentication` here versus, say, OpenID authentication for Ligthhouse routes

**Comment by rileyanderson** [comment]
@patrickvinograd did you see [Trevor's comment](https://github.com/department-of-veterans-affairs/vets-api/pull/14348#issuecomment-1789801318) about using `identity` instead of `authentication`?

**Comment by patrickvinograd** [comment]
I've been pretty intentional about tagging everything Lighthouse related as `lighthouse-foo` especially since those are good candidates to move out of vets-api over time. But if `identity` makes more sense to y'all I can update accordingly.

**Comment by patrickvinograd** [comment]
Updated service tag to be `identity` and updated ddog service catalog accordingly

**Review by dickdavis — APPROVED** [review]
LGTM, thanks for incorporating Trevor's feedback.

**Pull request merged**
