### PR TITLE
VaNotify - 527ez confirmation email

### PR DESCRIPTION
**Pull request by nathanbwright**
## Summary

- Adds email confirmation to the 527ez form submission (sent via VaNotify).
- Sending email is behind a feature flag which will be removed once once we have incrementally rolled this out and verified that it is working as expected.

## Related issue(s)
- https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/department-of-veterans-affairs/vanotify-team/679

## Testing done

- Added automated testing for sending confirmation email to the `SavedClaim::Pension`.
- We will do testing in staging before rolling this out in prod.

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
Kicks off an sidekiq job to send an email confirmation to veterans when they have successfully submitted a 527ez form.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation) - **No documentation updates**
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable) **Nothing built specifically for this feature**
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected - **No change to existing routes**
- [ ]  I added a screenshot of the developed feature - **No changes to existing UI**

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by holdenhinkle — COMMENTED** [review]
Hey @nathanbwright, I'm happy to review this, but first, please update the PR description using the template you deleted - https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Thanks!

**Comment by nathanbwright** [comment]
> Hey @nathanbwright, I'm happy to review this, but first, please update the PR description using the template you deleted - https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/PULL_REQUEST_TEMPLATE.md
> 
> Thanks!

Sorry @holdenhinkle - will do.

**Comment by nathanbwright** [comment]
Updated the description @holdenhinkle. Let me know if you need anything else.

**Review by holdenhinkle — APPROVED** [review]
Thanks for the updated description; I appreciate it.

Looks good 👍

**Pull request merged**
