### PR TITLE
4824 update gender identity values

### PR DESCRIPTION
**Pull request by cadibemma**
## Summary

- Upstream values to gender identity are being updated and we have them hardcoded so need to update along side them

## Related issue(s)
- department-of-veterans-affairs/va-mobile-app#4824
- department-of-veterans-affairs/va.gov-team#53038

## Testing done

- Updated tests to match new values where necessary

## What areas of the site does it impact?
- None

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by kpethtel — DISMISSED** [review]
🚀

**Review by aherzberg — CHANGES_REQUESTED** [review]
Looks good. Could you regenerate our docs as well?

**Comment by cadibemma** [comment]
> Looks good. Could you regenerate our docs as well? Going to request @tpharrison look at this as well since this is touching their code.

sure! - forgot to do that

**Review by aherzberg — APPROVED** [review]
LGTM

**Comment by tpharrison** [comment]
Thanks for keeping me in the loop - LGTM!

**Review by rjohnson2011 — APPROVED** [review]

**Pull request merged**
