### PR TITLE
Lighthouse BRD passthrough wrapper for front end.

### PR DESCRIPTION
**Pull request by kylesoskin**
## Description of change
This PR adds a generic API method that is essentially just a passthrough for any component of the front-end to hit/use the Lighthouse Benefits Data Reference API

It is just a pass-through, just hit the same path with the same args as the data you want, but with a different base url

IE
```
LH BRD End-point
https://sandbox-api.va.gov/services/benefits-reference-data/v1/contention-types?page=1&pageSize=2
To get that data from the front-end
${vets-api}/v0/benefits_reference_data/contention-types?page=1&pageSize=2
```

This is being made primarily for benefits team to make use of in forms, BUT ANYONE CAN USE THIS for brd data.

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/37771

## Related
- https://github.com/department-of-veterans-affairs/devops/pull/11954
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/866
- https://github.com/department-of-veterans-affairs/devops/pull/12050
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/923

## Things to know about this PR

* Are there additions to a `settings.yml` file? Do they vary by environment? (Yes, for now, but want to see if there is a general api key already in there for opendata)(there is, Im using lighthouse.api_key that is already in there)
* Is there a feature flag? What is it? (no)
* Is there some Sentry logging that was added? What alerts are relevant? (no)
* Are there any Prometheus metrics being collected? What Grafana dashboard were they added do? (no)
* Are there Swagger docs that were updated? (yes, bare-bones one)
* Is there any PII concerns or questions? (no)

TODO:

- [x] Check for generic/general api key already in settings.yml so I dont have to add a specific one for this service
- [x] Add swagger docs
- [x] Add tests
- [x] Use different Error handler that the base one. I want to return better messaging, the current base error handling is not sufficient
- [x] Change from v0 to v1 to align with LH BRD version? Maybe?

### CODE REVIEW

**Review by LindseySaari — APPROVED** [review]
👍

**Comment by kylesoskin** [comment]
I am on paternity leave for 2 weeks, this change requires additional changes in the DevOps repo before being merged. So no one merge this yet!! I will when I get back. 

It can be sent back into draft state if needed. I planned to merge and do prd required DevOps changes today but baby came sooner than expected.

**Comment by kylesoskin** [comment]
TODO later: Support multiple api versions

**Review by LindseySaari — APPROVED** [review]

**Comment by kylesoskin** [comment]
TODO (maintenance task/improvements): being tracked in ticket https://app.zenhub.com/workspaces/benefits-team-1-6138d7b57a2631001a4b7562/issues/department-of-veterans-affairs/va.gov-team/37771

-  request and get dedicated api_key instead of using existing team's key
-  put in MRs to apply new api_key
-  fix code portion of https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/benefits_reference_data
-  Support multiple api versions
-  Maybe change from benefits_reference_data -> benefits-reference-data ?

**Pull request merged**
