### PR TITLE
Notice of Disagreement | Remove disable submit feature flag

### PR DESCRIPTION
**Pull request by rocio-desantiago**
## Summary

- *(Summarize the changes that have been made to the platform)*
  > We completed user research that prevented Notice of Disagreement (NOD) submission during this testing, so we're removing the feature toggle (accidentally labeled with `hlr`) that disabled the submit button on the review & submit page. 

- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution)*
  > No longer needed as testing is over.
- *(Which team do you work for, does your team own the maintainence of this component?)*
  > Benefits decision reviews
- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*

## Related issue(s)

- [#58229](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58229)
- [#58333](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58833)
- [#24323](https://github.com/department-of-veterans-affairs/vets-website/pull/24323)

## Testing done

- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected*
- *Describe the tests completed and the results*

## Screenshots

N/A

## What areas of the site does it impact?

Board appeals | Notice of Disagreement form

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by ryan-mcneil — APPROVED** [review]
👌

**Comment by rocio-desantiago** [comment]
@ryan-mcneil should I have avoided pressing "update branch" before merging? Tests keep failing from timeout it seems.

**Comment by ryan-mcneil** [comment]
> @ryan-mcneil should I have avoided pressing "update branch" before merging? Tests keep failing from timeout it seems.

@rocio-desantiago As far as I know, if it says it's ok to merge, you can do so. It knows how to apply the commit to the current version of master. Sometimes it requires you to update, especially if it's seeing conflicts

**Comment by rocio-desantiago** [comment]
@ryan-mcneil awesome. Thank you for that confirmation 😁

**Pull request merged**
