### PR TITLE
Preneeds attachments soap

### PR DESCRIPTION
**Pull request by lihanli**
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5936

### CODE REVIEW

**Comment by rlbaker** [comment]
Still reviewing this but it might be good to loop in some of the other devs on this one for the FactoryGirl -> FactoryBot rename since they are pretty sweeping changes, just so everyone is up to date on the new library name.

**Comment by kreek** [comment]
Could this be two PRs, one with just the FactoryBot stuff in case one or the other has to be rolled back?

**Comment by lihanli** [comment]
@kreek preneeds is not released yet in production and the factorybot changes only affect specs and the specs are passing so neither change should need to be rolled back

**Comment by kreek** [comment]
@lihanli We've always had gem updates as separate PRs. It's good git etiquette/hygiene to keep PRs focused and as small as possible, helps speed up your reviews when the reviewer can focus on one thing. Also makes the git history easier to parse. This is a [good guide](https://gist.github.com/mikepea/863f63d6e37281e329f8) see also [Why and how to make smaller pull requests](https://robertheaton.com/2015/10/26/why-and-how-to-make-smaller-pull-requests/).

**Comment by saneshark** [comment]
I think I agree with @kreek it's not at all clear to me why FactoryGirl needed to be updated to the new FactoryBot to support this PR. If that change needs to be made, it makes sense to have it as its own PR.

**Pull request merged**
