### PR TITLE
Api 24300 icn to ssn lookup stats

### PR DESCRIPTION
**Pull request by michelpmcdonald**
## Summary

- In preparation for getting rid of ssn required when calling our API and replacing ssn with icn, we decided to start collecting stats on how often given consumer provided icn, we can lookup a user via MPI by icn and fetch the users ssn.  The idea being OUR consumer facing api will no longer require ssn, but we still need ssn for upstream services that still require ssn that we rely on.
- Part of the general push at the VA to get away from using ssn due to pii concerns
- team banana peels, i'm in, we own
- no flipper, this is a stand alone sidekiq job that logs to statsd

## Related issue(s)
https://jira.devops.va.gov/browse/API-24300

## Testing done

Unit test exercise all 4 expected combinations of outcome

## What areas of the site does it impact?
Touches Appeals, but no actual impact since its an advestory\logging sidekiq job

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  Events are being sent to the appropriate logging solution
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by mathisto — APPROVED** [review]
Really thorough tests. Hot damn, Mav!
Not a blocker, but my only question is on the use of a method for `retry_limits_for_notification`. Should this just be a constant?

**Comment by bosawt** [comment]
Couple things here:
- You shouldn't be passing ssn as a sidekiq argument (alternate would prob be creating a redis object with the ssn and sending the key for that object as a sidekiq param)
- How are you getting the ICN here? I would say you can be confident that a verified user's ICN will properly map to an SSN, which would make this 'test' unnecessary (you should just be able to assume you can always get an SSN given the ICN). But maybe I'm making an incorrect assumption? 

If you're interested in talking further about the capabilities and what you can expect from MPI lemme know, I can give you the down-low.

**Comment by michelpmcdonald** [comment]
> Really thorough tests. Hot damn, Mav! Not a blocker, but my only question is on the use of a method for `retry_limits_for_notification`. Should this just be a constant?

Yea, so we are relying on the Sidekiq::MonitoredWorker included as this class, and monitored worker requires an implementation of a retry_limits_for_notification method that contains count of any fails to retry.

I did think about what your saying and i did create a constant that I use for both setting the max number of retries and in retry_limits_for_notification

**Comment by michelpmcdonald** [comment]
> Not a blocker, but my only question is on the use of a method for `retry_limits_for_notification`. Should this just be a constant?

Yea, so we are relying on the Sidekiq::MonitoredWorker included as this class, and monitored worker requires an implementation of a _retry_limits_for_notification method_ that contains an array of failed retry attempt counts to report to slack.  So, for example, in this case, I just want a slack notification if the last attempt fails, thus that single element [11] array in the _retry_limits_for_notification method_

I did think about what your saying and i did create a constant that I use for both setting the max number of retries and in retry_limits_for_notification returned array.

**Comment by michelpmcdonald** [comment]
> You shouldn't be passing ssn as a sidekiq argument 
Yep, thank you, I changed that around, no longer passing in ssn\icn to perform

>How are you getting the ICN here? 
The intent is to catch the ICNs that external VSOs provide us when calling our API, presumability external callers don't get the ICN from MPI.

However, the reality that your comment brought to light to me is that currently, appeals API is "internal only", so only va.gov uses it, and va.gov is getting ICN from a va.gov logged in user, so I'm assuming the ICN for a va.gov logged in user comes from.....yea..MPI..so this is an entirely circular check that now seem pointless...

Going to close this right now, will discuss with team.

**Comment by michelpmcdonald** [comment]
Closed, currently appeals is internal only, so the only consumer is va.gov.
va.gov gets the appellants(ie vet in most cases) ICN from mpi, so in that case calling mpi with that icn is a completely circular check.(The icn va.gov provides comes from mpi via a va.gov logged in user session, so there is no point in turning around and querying that icn in mpi to see if it's valid).

Perhaps this approach could be used when Benefits Intake starts taking ICN.  Benefits intake does allow 3rd party consumers, and it's not clear where 3rd party consumers would source icns.

**Pull request closed without merging**
