### PR TITLE
Dont run simplecov with guard

### PR DESCRIPTION
**Pull request by lihanli**

### CODE REVIEW

**Comment by plusjeff** [comment]
@lihanli Could you describe more of the motivation behind this PR?

**Comment by lihanli** [comment]
this speeds up guard by not running simplecov on every file change. running tests outside of guard will still generate coverage and travis will still check coverage so it shouldn't be an issue

**Comment by saneshark** [comment]
@plusjeff the track_files will also ensure that any ruby files in lib and app are looked at by simplecov, irrespective of the files being invoked. Simplecov by default will only report coverage on files that are actually invoked. We can add additional directories there in the future (ie. config/initializers). But anything in initializers is automatically invoked when Rails loads into memory anyway, so its less necessary.

This LGTM if it looks good to you you @plusjeff

**Comment by plusjeff** [comment]
Awesome! Thanks for the context both of you! LGTM!

**Pull request merged**
