### PR TITLE
API-20648 Removal of Parent Controller

### PR DESCRIPTION
**Pull request by dmekala-va**
## Summary

- This PR is to remove the openidcontroller and its dependencies now that the calls can be routed to lighthouse-auth. This includes the controller itself, routing, rspecs, and other dependent classes like the key service. The module apps_api was also a part of the deletion, as it is a dependency of the openidcontroller. 
- Lighthouse Team Pivot!

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#API-20648
-[ *Link to ticket created in va.gov-team repo*](https://jira.devops.va.gov/browse/API-20648)

## Testing done

- Removed all related rspecs and vcr cassettes

## Screenshots
_Note: Optional_

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by kpethtel — COMMENTED** [review]
It's not clear to me why you'd be removing the mobile user request specs. Can you please explain?

**Comment by bosawt** [comment]
You should probably leave the migrations files. If you want to remove any tables it should be through additional migrations.

**Comment by dmekala-va** [comment]
> It's not clear to me why you'd be removing the mobile user request specs. Can you please explain?

Makes sense not to remove. Added back the mobile user request spec.

**Comment by dmekala-va** [comment]
> You should probably leave the migrations files. If you want to remove any tables it should be through additional migrations.

Sounds good. I added back the migration files

**Pull request closed without merging**
