### PR TITLE
Api 31569 claims status OAS documentation updates

### PR DESCRIPTION
**Pull request by mchristiansonVA**
## Summary

- Updates to OAS technical documentation based on feedback from UX team.

## Related issue(s)
[API-31569](https://jira.devops.va.gov/browse/API-31569)

## Testing done

- Rspec
- Confirmed correct updates locally

## What areas of the site does it impact?
modules/claims_api/app/swagger/claims_api/description/v2.md
modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
modules/claims_api/spec/requests/v2/veterans/rswag_claims_request_spec.rb
spec/support/schemas/claims_api/v2/veterans/claims/claim.json
spec/support/schemas/claims_api/v2/veterans/claims/claims.json

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by stiehlrod — COMMENTED** [review]
@mchristiansonVA This looks great, and there is only one thing I found. 
```
Update documentation for GET /veterans/{veteranID}/claims/{id} endpoint: 
Add a period at the end of the one-line description to match the others.
```
If I am reading this correctly, we should place a period at the end of each sentence description.

**Comment by FonzMP** [comment]
Production Swagger updates please, unless the plan is to have UX approve before we send them to production? 

Even if so, we have between the daily deploys to merge and see in dev / staging. I believe this was just an oversight to not update `production/swagger.json`

Also FYSA @stiehlrod

**Comment by mchristiansonVA** [comment]
> @mchristiansonVA This looks great, and there is only one thing I found.
> 
> ```
> Update documentation for GET /veterans/{veteranID}/claims/{id} endpoint: 
> Add a period at the end of the one-line description to match the others.
> ```
> 
> If I am reading this correctly, we should place a period at the end of each sentence description.

I followed-up with Melinda, and she said we should just add a period to the endpoint description for /veterans/{veteranId}/claims/{id}.
I added a period to the end of **Find claim by ID** which follows the link at the top level, as it was missing one.

**Comment by mchristiansonVA** [comment]
> Production Swagger updates please, unless the plan is to have UX approve before we send them to production?
> 
> Even if so, we have between the daily deploys to merge and see in dev / staging. I believe this was just an oversight to not update `production/swagger.json`
> 
> Also FYSA @stiehlrod

That's noted in the acceptance criteria, so I held off adding production swagger:
4. Melinda Cuerda to confirm updates in dev/staging before promoting updates to production.

**Comment by stiehlrod** [comment]
> > Production Swagger updates please, unless the plan is to have UX approve before we send them to production?
> > Even if so, we have between the daily deploys to merge and see in dev / staging. I believe this was just an oversight to not update `production/swagger.json`
> > Also FYSA @stiehlrod
> 
> That's noted in the acceptance criteria, so I held off adding production swagger: 4. Melinda Cuerda to confirm updates in dev/staging before promoting updates to production.

@FonzMP are we good then? We could spin up another PR branched off of this one with the prod swagger so it would be ready to go. thoughts?

**Comment by FonzMP** [comment]
if the ticket asks us to operate under the assumption that we'll do the production swagger later, that is fine. it's a bit of a nuisance because now ALL Dash engineers will need to know to revert the changes to the production swagger once this gets merged in? 🤷  

when we merge we probably want to announce in the Dash channel so engineers know and they'll have to specifically revert the changes in respect to this PR.

**Review by FonzMP — DISMISSED** [review]
:shipit:

**Review by stiehlrod — APPROVED** [review]

**Pull request merged**
