### PR TITLE
Dont autorequire fakeredis

### PR DESCRIPTION
**Pull request by lihanli**

### CODE REVIEW

**Comment by saneshark** [comment]
hmmmm, i don't really understand why all of this is necessary? Is this simply because we added the spring bin stubs or was this an existing issue -- according to fakeredis documentation, you should not need to set Redis.current, because it overrides the constant.

**Comment by lihanli** [comment]
@saneshark it's not related to spring, i think it's a fakeredis bug. if you have a local redis server turn it off then run the tests (with or without spring) with "Redis.current = FakeRedis::Redis.new" commented out and they won't work. if you put that line back in then it works. the rspec configure block i added though wasn't needed once i fixed Redis.current

**Comment by saneshark** [comment]
That wasn't the case prior to these other changes, if it were, then tests would have never passed.

**Comment by lihanli** [comment]
it works without that when "require: false" in the Gemfile isn't there

**Comment by saneshark** [comment]
Oh, I see. That makes sense. And you don't want fakeredis to do its magic outside of the specific tests that call for it? See I personally don't think it should slow down specs that much, and now we're getting into prematurely optimizing specs for no good reason other than to get guard working. Am I missing something?

**Comment by lihanli** [comment]
i figured that was the original intention since require fakeredis was only added to the specs that needed it instead of rails_helper? also this allows us to make integration specs that actually use redis. if redis isn't needed then we don't need it but we still don't want to require it in development.

**Comment by saneshark** [comment]
I say add it to spec_helper, get rid of require: false, only include it in test group. That way you don't need all the extra flushall stuff. Individual specs not requiring fakeredis might be ever so slightly slower, but redis is a hard dependency on the repo, so simulating its presence for all specs... in short, having Redis.current set, should be the more accurate way to go.

**Comment by saneshark** [comment]
While you're at it, does simplecov and webmock need to be available in development group?

**Comment by lihanli** [comment]
ok i did the changes

**Comment by saneshark** [comment]
This looks good to me! And thanks for fixing my fakeredis stuff, didn't realize that was getting required in development group. OOPS. :)

**Pull request merged**
