### PR TITLE
Completed folders endpoint, removed unnecessary comments in triage.

### PR DESCRIPTION
**Pull request by mphprogrammer**
Completed show, and index actions on folders.
Removed superfluous comments in triage.
Added recipients path for triage teams.
Converted dashes to underscores in JSON and Serializer spec.

### CODE REVIEW

**Comment by mphprogrammer** [comment]
@ayaleloehr @saneshark Could you take a peek, and I will move on to messages.

**Comment by saneshark** [comment]
@mphprogrammer could you please update specs to expect underscore instead of dash?

**Comment by mphprogrammer** [comment]
@saneshark its up, thanks.

**Comment by saneshark** [comment]
LGTM

**Pull request merged**
