### PR TITLE
account scopes use none

### PR DESCRIPTION
**Pull request by erluti**
[This PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5529) was rolled out in an emergency and this adds some tests

### CODE REVIEW

**Review by LindseySaari — APPROVED** [review]
I think this is cleaner, but there could be a specific reason for the where('1 = 0') that i'm not aware of. Approving, but maybe we should wait to merge until we hear back from @annaswims

**Review by annaswims — CHANGES_REQUESTED** [review]
It's possible/likely for a user to have either a nil `idme_uuid` or `sec_id`.  We want to find all Accounts with ONLY matching id's.  We don't want to run the risk of someone calling `idme_uuid_match(nil)`, thinking they're getting only matching accounts when in fact they're getting all accounts with a nil `idme_uuid`

**Comment by annaswims** [comment]
`"accounts"."sec_id" IS NULL AND "accounts"."sec_id" IS NOT NULL` is an expensive table scan for something that will never be true, so we do the cheap version with `1 = 0`

**Comment by edmangimelli** [comment]
Nice catch, Anna! I did not know that about scopes:
> Adds a class method for retrieving and querying objects. The method is intended to return an ActiveRecord::Relation object, which is composable with other scopes. If it returns nil or false, an all scope is returned instead.

https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html#method-i-scope

**Comment by edmangimelli** [comment]
+1 to adding a comment to the `1 = 0` line. It makes sense now (why we're returning a relation that by definition will always be empty) that I know how I footgun-y returning nil in a _scope's lambda_ is

**Comment by erluti** [comment]
added some tests and used `none`

**Review by annaswims — APPROVED** [review]
Ah, yes! That's more clear.

**Review by bosawt — APPROVED** [review]
Thanks for the tests! Agree that `none` here makes it more clear what's going on when the id is nil as well.

**Pull request merged**
