### PR TITLE
75639 - Appointment cancellation using VPG

### PR DESCRIPTION
**Pull request by devin-mccurdy**
## Summary

- Changes are behind the `va_online_scheduling_enable_OH_cancellations` feature flag

- Appointment cancellation requests are made through a new endpoint within va-mobile.  Previously this used `/vaos/v1` , but now will go to `/vpg/v1` in order to provide the ability to cancel appointments in Oracle Health.

## Related issue(s)

- https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea522640e4d09393b/issues/gh/department-of-veterans-affairs/va.gov-team/75639

## Testing done

- [x] *New code is covered by unit tests*
- In order to minimize changes needed in vets-api, VPG handles non-Oracle Health appointment cancellations the same as  
- The ability to cancel Oracle Health appointments is currently not implemented in vets-website.

## What areas of the site does it impact?
These changes only impact appointment cancellations (other appoint functionality such as scheduling are not affected)

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution

### CODE REVIEW

**Review by drewconnelly — DISMISSED** [review]
LGTM

**Review by cferris32 — DISMISSED** [review]
LGTM

**Review by cferris32 — APPROVED** [review]

**Review by kpethtel — APPROVED** [review]
LGTM. It looks like we're switching to a different upstream endpoint on the same server. Am I reading that right?

**Comment by devin-mccurdy** [comment]
> LGTM. It looks like we're switching to a different upstream endpoint on the same server. Am I reading that right?

Correct 👍

**Pull request merged**
