### PR TITLE
90381 add Parent attribute to facility

### PR DESCRIPTION
**Pull request by Mitch-A6**
## Summary
- *This work is behind a feature toggle (flipper):* NO
- Adds a `parent` attribute to the Facilities retrieved from Lighthouse.
- This matches the new v1 return value structure, since v0 didn't have the attribute
- We will use this value in the Caregiver signup process to make sure that if a Veteran's main medical facility doesn't have the Caregiver Support service, we assign the Caregiver to a facility that does.
- 10-10EZ/CG Health Enrollment team
- No Flipper is necessary since this is purely additive - we're not taking away or changing anything anyone could rely on.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90381

## Testing done

- [x] *New code is covered by unit tests*
- Previously the model ignored the `parent` attribute, even though Lighthouse started sending it in v1.
- Now the model extracts the `parent` value from its response attributes.
- To reproduce, launch a local rails console with `bundle exec rails c`, then run:
```
require 'lighthouse/facilities/v1/client'
lighthouse_facilities_service ||= Lighthouse::Facilities::V1::Client.new
lighthouse_facilities_service.get_facilities(state: 'VT').map{|a| [a.id, a.unique_id, a.parent]}
```
- ... or the equivalent for another state. Confirm that the model gets the `parent` value for any facilities that have one, equal to the facility's ID without any trailing letters after the station number, e.g.,
- `["vha_405GA", "405GA", {"id"=>"vha_405", "link"=>"https://sandbox-api.va.gov/services/va_facilities/v1/facilities/vha_405"}],`
- note that a parent facility will list itself as its own parent, e.g., `["vha_405", "405", {"id"=>"vha_405", "link"=>"https://sandbox-api.va.gov/services/va_facilities/v1/facilities/vha_405"}],`
- non-health facilities may have none, e.g., `["nca_061", "061", nil],`
- *What is the testing plan for rolling out the feature?*
    - This will be tested through the frontend once that's built.

## What areas of the site does it impact?
None for now. CG signup when the frontend work is done.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by jilladams** [comment]
@Mitch-A6 the PR template is not really filled out - could you explain why this PR is necessary?

**Comment by Mitch-A6** [comment]
> @Mitch-A6 the PR template is not really filled out - could you explain why this PR is necessary?

pardon, will do.

**Comment by Mitch-A6** [comment]
> @Mitch-A6 the PR template is not really filled out - could you explain why this PR is necessary?

Story's updated and ready for review!

**Comment by eselkin** [comment]
@Mitch-A6 You should ask Mobile if this affects them at all. They are currently using this lib facility serializer.

**Comment by jilladams** [comment]
@aherzberg helped update for LH V1, and may be able to review or suggest who else from mobile might review.

**Comment by Mitch-A6** [comment]
> @Mitch-A6 You should ask Mobile if this affects them at all. They are currently using this lib facility serializer. If it doesn't affect them, I will approve from our group.

Approved by Mobile:
https://dsva.slack.com/archives/C018V2JCWRJ/p1724686140111519?thread_ts=1724679120.492379&cid=C018V2JCWRJ

**Review by ericboehs — APPROVED** [review]

**Review by coope93 — APPROVED** [review]

**Review by ericboehs — APPROVED** [review]

**Review by eselkin — APPROVED** [review]
LGTM

**Pull request merged**
