### PR TITLE
add toggle for privacy policy

### PR DESCRIPTION
**Pull request by adamwhitlock1**
## Summary

- Adds a toggle for profile privacy policy work
- Also removed a trailing space on one toggle for cleanliness

Timeframe: toggle will be removed within a month of privacy statement being launched in production. Tentative date of removal would be end of August, depending on when final work lands in production. 

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85603

## Testing done

Test locally, just a single toggle being added

## Screenshots

No UI changes

## What areas of the site does it impact?

Profile

## Acceptance criteria

- [x] Toggle added
- [x]  No error nor warning in the console.

### CODE REVIEW

**Review by asiisii — APPROVED** [review]
LGTM 🚀

**Comment by ryan-mcneil** [comment]
@adamwhitlock1 can you please add some info to the PR description that clarifies the criteria/timeframe for which the toggle will be removed? Thanks!

**Comment by adamwhitlock1** [comment]
@ryan-mcneil I have added timeframe for toggle removal. Thanks!

**Review by ryan-mcneil — APPROVED** [review]
Perfect, thanks! ✅

**Pull request merged**
