### PR TITLE
Updating production

### PR DESCRIPTION
**Pull request by knkski**

### CODE REVIEW

**Comment by ayaleloehr** [comment]
This is a difficult PR to review. Seems like we're just updating production to what is in master, which seems reasonable.  Other people like @robbiethegeek @aub @plusjeff or @jkassemi have thoughts?

**Comment by knkski** [comment]
Yep, this is just updating `production` to where `master` is currently at, as `production` deploys are broken in Jenkins at the moment.

**Comment by ayaleloehr** [comment]
I think the main question is less around code review and more "is this how we want to do production deploys?"  From me this LGTM in that regard (just merging master to production). do we squash the commits though?

**Comment by patrickvinograd** [comment]
I propose that we don't squash commits for master -> production merges since it loses git history. Of the other two options (rebase and merge vs. merge commit), I think it's largely academic. We should not have particularly complicated branching happening between master and production, so production should just look like a series of merge commits, each of which has parent commits tracking the commit history from prod and master. So I am opting for "Create a merge commit". We can adjust in the future, but I'm going ahead with submitting this one for purposes of verifying some prod deployment issues.

**Pull request merged**
