### PR TITLE
Profile doc update

### PR DESCRIPTION
**Pull request by omgitsbillryan**
- Updated `/v0/user` doc
- Created authentication doc for `/v0/sessions`

### CODE REVIEW

**Comment by omgitsbillryan** [comment]
@kreek would you mind taking a look - especially at the `va_profile`.`active_status`?  I don't know what the possible values are for that json key.

**Comment by kreek** [comment]
@omgitsbillryan va_profile.active_status is either 'active' or 'new', and for existing users it's always 'active' so I don't think need to send this to the client anymore. Other than that LGTM.

**Comment by omgitsbillryan** [comment]
@kreek so we never need to send va_profile.active_status anymore?  Can you create an issue for that?

In the mean time, I will update the doc with the possible return values for this PR.

**Comment by robbiethegeek** [comment]
@omgitsbillryan any outstanding updates still needed for this?

**Pull request merged**
