### PR TITLE
Return empty vaprofile if mvi nil

### PR DESCRIPTION
**Pull request by kreek**

### CODE REVIEW

**Comment by omgitsbillryan** [comment]
So effectively the JSON from `/profile` will no longer have the `va_profile` element whereas before it would return `"va_profile":{}`?

**Comment by jcmeloni** [comment]
conceptually LGTM, non-binding 👍 :)

**Comment by kreek** [comment]
@omgitsbillryan va_profile will be `null` for all LOA1 users and for LOA3 users who have not MVI data (because it's down or the record wasn't found). LOA3 users who are found in MVI will have va_profile like:

```json
{
  "birthdate": "19800115",
  "family_name":  "Smith",
  "gender": "M",
  "given_names":  ["John", "W"],
  "status": "active"
}
```

**Comment by robbiethegeek** [comment]
@crwallace FYI

**Pull request merged**
