### PR TITLE
Vfep 550 - email spool files on staging

### PR DESCRIPTION
**Pull request by GcioGregg**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- Vfep 550 - email spool files on staging
- *(If bug, how to reproduce)* N/A
- *(What is the solution, why is this the solution)* N/A
- *(Which team do you work for, does your team own the maintainence of this component?)* VFEP
- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)* N/A

## Related issue(s)
- [VFEP-550](https://vajira.max.gov/browse/vfep-550)
- *Link to ticket created in va.gov-team repo* N/A
- *Link to previous change of the code/bug (if applicable)* N/A
- *Link to epic if not included in ticket* N/A

## Testing done
-  rspec and rubocop tests pass, user testing passed on local
- *Describe what the old behavior was prior to the change* no spool files emailed on staging
- *Describe the steps required to verify your changes are working as expected* spool files from staging get emailed
- *Describe the tests completed and the results*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by ryan-mcneil** [comment]
@GcioGregg Is this code temporary? I understand it's for staging, but lack of tests for this mailer would ultimately affect code coverage

**Comment by GcioGregg** [comment]
@ryan-mcneil while the code is not temporary, it is only used for our internal QA to be able to match a spool file with the form they submitted during their testing on staging.  This does not affect production.

**Comment by ryan-mcneil** [comment]
@GcioGregg Can we perhaps create a spec file that at least is testing that it wouldn't be delivered in a production environment? At least we'll be covering the lines of code and not dropping our coverage

**Review by ryan-mcneil — APPROVED** [review]
Approved with the understanding that @GcioGregg will circle back and add a couple quick tests to ensure code coverage.

**Comment by GcioGregg** [comment]
Here is the ticket to add tests:  [VFEP-571](https://vajira.max.gov/browse/VFEP-571)

**Pull request merged**
