### PR TITLE
Logging to determine user success/failure access rate

### PR DESCRIPTION
**Pull request by hpjaj**
## Background

Background is outlined in detail in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10478

## Definition of done

- [x] Logging to determine the success/failure percentages for the EVSS Pundit policy being met

### CODE REVIEW

**Comment by wyattwalter** [comment]
Hi @hpjaj!

The only concern that I'd have about any real impact on performance here would be around the size of the `info` object in this context. We'd have to setup a metric on CloudWatch Logs to count these messages to start getting metrics from it.

You shouldn't need anything outside of the app to get metrics going to StatsD, and would be a more direct way of gathering the measurements you're after here. All that should be necessary is to initialize the counter: https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/statsd.rb Then you can start incrementing it in the app code: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/sessions_controller.rb#L120

StatsD supports tags, but there's two things to be aware of with tags: 1) always create metrics of the same name with the same tag names, only the values should change and 2) be careful to not let user input spill into the tag values as that can cause a huge number of unique time series in Prometheus.

My recommendation would be a metric for success and a metric for failure, and we can use that to calculate totals.

I can help build out a dashboard and review code (or even help implement it here if you'd like).

**Comment by hpjaj** [comment]
@wyattwalter - Perfect!  I'll refactor this PR to favor the StatsD implementation you've described, and follow up with you once that is in place, to discuss the building out of the dashboard piece.

Thanks!

**Comment by hpjaj** [comment]
Hey @wyattwalter , I completed the StatsD implementation.  For next steps, can you pls:

1. Verify my implementation?
2. Let me know when I should ship this PR
3. Build out the "dashboard and review code" that you mentioned above?
4. Let me know if there is anything else I can do to help?

Thanks!

**Comment by hpjaj** [comment]
@wyattwalter - Awesome...that is going to be a great resource.  Thanks!

**Pull request merged**
