### PR TITLE
Sentry warning

### PR DESCRIPTION
**Pull request by lihanli**
## Description of change

add warning to sentry-raven gem to ensure compatibility with the sentry server

#### Applies to all PRs

- [x] Appropriate logging
- [x] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [x] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by saneshark** [comment]
Oops... Tagging @kreek here because his PR recently updated the sentry gem. @lihanli @annaswims upgraded Sentry very recently. Was there something that caused issues in the latest gem? I would have thought that @kreek changes were ok, given that we upgraded the server so recently.

**Comment by lihanli** [comment]
yea we ran into issues with the last gem upgrade https://github.com/department-of-veterans-affairs/vets-api/pull/2786#issuecomment-462488138

**Comment by annaswims** [comment]
We upgraded the sentry-server recently, but self-hosted sentry server is far behind sentry master. https://forum.sentry.io/t/is-sentry-v10-coming-soon/5093 
sentry-raven 2.7.4 is the last version released before the version of sentry-server we're using so I thought I should make that clear.  The gem is released with the assumption that most people are using hosted sentry.

**Comment by saneshark** [comment]
closing in favor of already merged https://github.com/department-of-veterans-affairs/vets-api/pull/2805

**Comment by lihanli** [comment]
@saneshark this is a different change which adds a warning message to the gemfile

**Comment by saneshark** [comment]
My bad. Sorry @lihanli - I'll let @annaswims advise.

**Comment by annaswims** [comment]
Thanks @lihanli! I should've left this comment earlier.

**Pull request merged**
