### PR TITLE
Deep freeze 1010 schemas

### PR DESCRIPTION
**Pull request by lihanli**
## Summary
Deep freeze 1010 form schemas to prevent errors caused by mutated schemas
- *(Which team do you work for, does your team own the maintainence of this component?)*
I work for the 1010 team, we own this component.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/56220

## Testing done
unit tests

## What areas of the site does it impact?
1010 forms

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by ryan-mcneil — DISMISSED** [review]
LGTM!

**Comment by ryan-mcneil** [comment]
@lihanli are you waiting for approval here? I see my last approval was dismissed. If this is still in-progress, please set it to a Draft state. We have a lot of PRs coming through, so it makes it easier for us to keep track of who needs approvals and who is still working. Thank you!

**Comment by lihanli** [comment]
@ryan-mcneil hey, i am still waiting for approval on this PR. i didn't choose to dismiss your review, it was dismissed automatically because of a merge conflict with master.

**Review by ryan-mcneil — APPROVED** [review]
👌

**Pull request merged**
