### PR TITLE
Revert "[CST] Moved failure notification emails into their own sidekiq jobs"

### PR DESCRIPTION
**Pull request by ericboehs**
Reverts department-of-veterans-affairs/vets-api#19222

Causing CI failures in master.
Screenshot 2024-12-12 at 13 13 26@2x

### CODE REVIEW

**Comment by jerekshoe** [comment]
Those tests that are failing aren't listed in this PR??

**Comment by kayline** [comment]
That looks like test from a recent PR of mine. I thought a fix went into master. Is there a current PR that is failing?

**Comment by shaunburdick** [comment]
The tests in that screenshot look to be ones we moved to the new Decision Reviews module, I think it's this PR? [#19725](https://github.com/department-of-veterans-affairs/vets-api/pull/19725/)

**Comment by samcoforma** [comment]
This PR revert is incorrect and should be closed and not merged

**Comment by samcoforma** [comment]
This should be closed in favor of this PR which actually fixes the issue instead: https://github.com/department-of-veterans-affairs/vets-api/pull/19867

@ericboehs

**Comment by ericboehs** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/vets-api/pull/19867

**Pull request closed without merging**
