### PR TITLE
Add Controller to return a user's profile permissions

### PR DESCRIPTION
**Pull request by tpharrison**
## Summary
Add `V0::Profile::UserPermissionsController`.  This controller will be called when the Profile page loads. It will return user permissions as they relate to a user's profile.  The FE can use this to determine which profile endpoints can/should be called on behalf of the user. The intent is to reduce the amount of traffic between the FE and BE.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/68254

## Testing done
Added specs at `spec/controllers/v0/users_permissions_controller_spec.rb`

### CODE REVIEW

**Review by adamwhitlock1 — APPROVED** [review]
This LGTM. It's still in draft, but otherwise 🚀

**Comment by rmtolmach** [comment]
@tpharrison To get the **Validate changes to DataDog Service Catalog Files** check passing, please update your branch with the latest changes from `master`. Thanks!

**Review by ericboehs — DISMISSED** [review]

**Comment by adamwhitlock1** [comment]
@tpharrison Since the topic came up recently, do you think the fiduciary/deceases/incompetent indicators should be added to this endpoint so that it could be used in a more widely scoped application like a form?

[Slack thread for context here](https://dsva.slack.com/archives/C909ZG2BB/p1701180002543539)

**Comment by tpharrison** [comment]
Good call.  I'll open a ticket.

**Comment by adamwhitlock1** [comment]
Our lovely github bot marked this as stale, so I removed the label so it doesn't get auto-closed. Were you still working on this, or are there other considerations that you need to address @tpharrison?

**Comment by tpharrison** [comment]
I'm held off on this because I was thinking of making a few small changes, but it fell off my radar.  I'll get this merged by next week.

**Pull request closed without merging**
