### PR TITLE
Dockerize Kong

### PR DESCRIPTION
**Pull request by ATeal**
## Description of change
Running kong locally has been a big pain for the lighthouse team, this seeks to resolve that pain

## Testing done
- local curls and whatnot

#### Applies to all PRs

- [x] Appropriate logging
- [x] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [x] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by dvogel** [comment]
Thanks for putting this together. It feels super useful. I see how it can help solve pain points around vets-api. However, it feels like it's utility will be limited by being part of vets-api. For example, I could see using it to do local testing of other endpoints like the developer portal sign-up lambda. Could this be pulled out into it's own repo?

**Comment by ATeal** [comment]
Definitely could be! Should be able to just submodule vets-api in another repo. I was conflicted adding it here anyways due to the limited part of vets-api. I'm not sure what the process is for creating a new repo. Any suggestions on a name :P (naming is one of the hardest things in programming)

**Comment by bastosmichael** [comment]
@ATeal you should be able to create your own private repo in department-of-veterans-affairs which we can make public later on potentially. I'm the one that's always championing things needing their own repos so I'm good with that approach as well, are you going to do it as a rake task as well or do you want to do something more fun like Thor https://github.com/erikhuda/thor ?

**Comment by dvogel** [comment]
> Definitely could be! Should be able to just submodule vets-api in another repo. I was conflicted adding it here anyways due to the limited part of vets-api. I'm not sure what the process is for creating a new repo. Any suggestions on a name :P (naming is one of the hardest things in programming)

The name is a good question. I wonder if we want this new repo to hold this tool as well as other tools for actually applying our kong config in the future. I'm thinking we might want to include custom kong plugins we make in the future. If so maybe `kong-utils` or `kong-contrib` or `kong-configs`

**Comment by ATeal** [comment]
Closing this pull request, was spun out into it's own repo

**Pull request closed without merging**
