### PR TITLE
Add authorization to SM

### PR DESCRIPTION
**Pull request by aub**
Only let users access SM if they are LOA3 and have a MHV correlation ID. This pretty much just makes the SM code be in line with the changes @saneshark made for Rx. I made some slight rearrangements to the Rx controller, but the functionality is exactly the same there. This looks like a big change, but almost all of it is in the specs.

@saneshark do we need to temporarily comment this out as you have done with the Rx controller?

### CODE REVIEW

**Comment by saneshark** [comment]
@aub Aside from re-running the vcr_cassettes, the diff would suggest that there were more changes. Is this just some weird github issue for diffs on yaml files?

**Comment by saneshark** [comment]
Was it necessary to re-run cassettes for this change?

**Comment by saneshark** [comment]
@aub I think this LGTM, but lets not merge it until later in the week. Per conversation in sprint planning. CC: @ayaleloehr

**Comment by aub** [comment]
@saneshark I didn't rerun cassettes (don't know how to), I just copied the session request with some modifications from the Rx cassettes to the SM ones because the specs were failing without the ability to respond to that request. If that's a bad idea I'm happy to fix it.

**Comment by saneshark** [comment]
Yea, let's not modify the vcr_cassettes. I've set them such that they should only be run for specs in `lib/sm/api/`  and then specs in `request/` just use those same existing cassettes. You'll notice that the specs in lib, initialize a single session that is shared in a before(:all), so you could if you want setup a before all or, alternately just stub client.authenticate -- `expect_any_instance_of(SM::Client).to receive(:authenticate)` in a before(:each)

**Comment by robbiethegeek** [comment]
Can this get merged once the frontend readds the login?  @ayaleloehr

**Comment by ayaleloehr** [comment]
Looks like @saneshark and @aub need to work out their differences on VCR cassettes before this gets merged.

**Comment by aub** [comment]
I'm taking care of that now. Should be ready shortly.

**Comment by saneshark** [comment]
@aub  can you do `git checkout spec/support/vcr_cassettes/ -- master` maybe? I may have updated some, I can't recall -- might be what is causing issues?

**Comment by aub** [comment]
@saneshark ok I rolled back the cassettes changes. They still show a diff, but it's just whitespace changes from my editor.

**Comment by saneshark** [comment]
@aub LGTM, other than the rubocop complaint. Which editor just out of curiosity? atom does this for EOL for me, but hadn't noticed it with inline whitespace.

**Comment by aub** [comment]
@saneshark it's Atom, and the whitespace was EOL.

**Comment by ayaleloehr** [comment]
Good to merge from my side, as we just merged the front end login as well.

**Comment by aub** [comment]
It's going to pass checks here in a sec, and then I'll get it merged. Thanks all

**Comment by saneshark** [comment]
@aub merging, because I need your changes your to user factory for doing the same thing to prescriptions.

**Pull request merged**
