### PR TITLE
13281 Do not auto/eager-load lib directory

### PR DESCRIPTION
**Pull request by erluti**
Until this PR is merged, `config/application.rb` manually added the `/lib` directory to the auto/eager-load path. This is non-standard Rails configuration and has lead to some practices that make it difficult to switch over to the zeitwerk loader. This change is to remove that code and prepare the way for zeitwerk.

**Please test on your features locally!**

### CODE REVIEW

**Comment by annaswims** [comment]
When I start my server locally I see:

````
2020-09-14 16:27:34.473342 W [34062:70347189854240] Rails -- DEPRECATION WARNING: Initialization autoloaded the constants VAOS::Middleware,
 VAOS::Configuration,
 UserSessionForm,
 V1,
 AuthenticationAndSSOConcerns,
 ApplicationController,
 V1::SessionsController,
 V0,
 IgnoreNotFound,
 V0::Post911GIBillStatusesController,
 EVSS::DisabilityCompensationForm::JobStatus,
 EVSS::DisabilityCompensationForm::Job,
 EVSS::DisabilityCompensationForm::SubmitForm526,
 SentryJob,
 Form1010cg,
 Form1010cg::Service,
 EVSS::DisabilityCompensationForm::SubmitUploads,
 CentralMail::SubmitForm4142Job,
 EVSS::DisabilityCompensationForm::SubmitForm0781,
 EVSS::DisabilityCompensationForm::SubmitForm8940,
 and EVSS::DisabilityCompensationForm::SubmitForm526Cleanup.

````

Will all these classes be affected by this chage?

**Comment by erluti** [comment]
> Will all these classes be affected by this change, or is this entirely irrelevant?

The rest of the message is this:
```
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload VAOS::Middleware, for example,
the expected changes won't be reflected in that stale Module object.

`config.autoloader` is set to `classic`. These autoloaded constants would have been unloaded if `config.autoloader` had been set to `:zeitwerk`.
```
The goal of all these changes is to eventually change `config.autoloader` to `:zeitwerk`.  Since it's a deprecation warning I don't think there's any issue yet, and I'll be sure this is taken care of by the time all the zeitwerk changes are complete.
I created this ticket to circleback to this as part of the zeitwerk changes https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13562

**Review by kfrz — APPROVED** [review]

**Comment by annaswims** [comment]
Could you be more clear about what your expectations are on `Please test on your features locally`?  We're not aware of what kind of testing you have done.  

Are you concerned that all the requires that are part of specs will hide production issues?  On Friday @f1337 said that this is likely to cause production issues.  What is the likely human cost be to these production issues?

**Comment by annaswims** [comment]
Has @department-of-veterans-affairs/va-api-engineers given a 👍 ?  They seem to do more explicit requires within their specs, which means that their code might be more vulnerable.

**Comment by erluti** [comment]
> Could you be more clear about what your expectations are on `Please test on your features locally`? We're not aware of what kind of testing you have done.
> Are you concerned that all the requires that are part of specs will hide production issues?

The developers best know how their code is intended to function and we've not been able to test all features in vets-api one-by-one.  The failure that identified the need for a rollback was in a gap in test coverage.  I'm not concerned that requires in specs are hiding production issues, is there a place you're concerned about?

**Comment by f1337** [comment]
A thought that occurred to me this weekend: Have we tried to `grep -r 'require(' spec/` in vets-api? I have a feeling the results might highlight some proactive fixes we can make before merging.

**Comment by annaswims** [comment]
I'd say maybe half of the functionality was written by developers who are no longer around and are not under any sort of development.  There's so much code that has no clear owner. Those will be the most painful to triage.

**Comment by annaswims** [comment]
Don't forget the specs in modules `grep -r "require '" modules/**/spec/`

**Comment by golavarr-va** [comment]
Lighthouse reviewed the APIs on its end and everything appears to be good to go. However, given a situation where something could've been missed, we need to be prepared for a rollback / path forward to restore interrupted services ASAP if they were to occur.

**Comment by erluti** [comment]
> A thought that occurred to me this weekend: Have we tried to `grep -r "require '" spec/` in vets-api? I have a feeling the results might highlight some proactive fixes we can make before merging.

PR to address the grep https://github.com/department-of-veterans-affairs/vets-api/pull/4943
I will probably create a different one for searching the module directories

**Comment by erluti** [comment]
PR for cleaning up requires in specs for modules https://github.com/department-of-veterans-affairs/vets-api/pull/4975

**Pull request merged**
