### PR TITLE
Use custom serializer for VYE serializers

### PR DESCRIPTION
**Pull request by stevenjcumming**
## Summary

In an effort to remove AMS serializers, this non-JSON:API serializer needs a custom serializer

- Convert AMS serializer to custom serializer
- The response is identical to the AMS serializer response

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88861

## Testing done

- [x] Verified response is identical 

## Acceptance criteria

- [x] Unit specs don't rely on AMS or jsonapi-serializers
- [x] Serializers don't use AMS, jsonapi-serializers, or blueprinter
- [x] Each serializer has `to_json` and `serializable_hash` methods

### CODE REVIEW

**Comment by stevenjcumming** [comment]
@binq @jsimonVA Would you mind reviewing this?

**Comment by binq** [comment]
Can you create specs that serializes using the existing way, and also the new way to confirm that the JSON results are the same?

**Comment by stevenjcumming** [comment]
> Can you create specs that serializes using the existing way, and also the new way to confirm that the JSON results are the same?

@binq I can expand the request specs to verify this

**Comment by stevenjcumming** [comment]
@binq update the show request spec:

It includes a test for the structure (ie not JSON:API), verifies the has_many associations, and verifies the dates are ruby strings  

https://github.com/department-of-veterans-affairs/vets-api/pull/17798/files#diff-bb8c5796b3d67e097abe40df75ffbaa8e03d97b8da097e1817b9c1731a4241a4

**Comment by binq** [comment]
@jsimonVA can you confirm that this looks good to you?

**Review by jsimonVA — APPROVED** [review]
Sorry for the delay on this @stevenjcumming LGTM

**Review by rmtolmach — APPROVED** [review]

**Pull request merged**
