### PR TITLE
Ndbex silent failure updates

### PR DESCRIPTION
**Pull request by evansmith**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *This work is behind a feature toggle (flipper): NO*
- Reworked the silent failure calls so that there is a call to silent failure avoided in the exhaustion scenarios in the sidekiq jobs
- Alter the monitor to check for the email and decide which notification to create. pass only the email to the email calls. refactor where necessary.
- VA Benefits and Claims
- *(If introducing a flipper, what is the success criteria being targeted?)*

## Related issue(s)

- [*Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95830)
(ticket is one of the trigger tickets, but it spans 686c-674, vre, and pcpg)

## Testing done

- [x] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by micahaspyr — APPROVED** [review]
LGTM

**Review by stevenjcumming — COMMENTED** [review]
Can you resolve the `Layout/LineLength` rubocop warnings?

**Comment by evansmith** [comment]
@stevenjcumming I've fixed it up so the two new linelength checks i added have been removed. One previous instance is still present in submit_career_counseling_job, but I think it might be best left as it is.

**Comment by evansmith** [comment]
@stevenjcumming can I get a re-review on this?

**Review by micahaspyr — APPROVED** [review]
LGTM

**Review by stevenjcumming — APPROVED** [review]

**Pull request merged**
