### PR TITLE
92457-89743: Remove Toggles for Direct Deposit Single Form

### PR DESCRIPTION
**Pull request by asiisii**
## Summary

This PR removes the following four toggles that were previously used to control various aspects of the direct deposit single form on the Profile page. Now that we are using the single form for the Direct Deposit page in production, these toggles are no longer needed:

### Removed Toggles:

1. **`profile_show_direct_deposit_single_form`:** 
   - **Description:** Show/hide the single direct deposit form in profile for all users.
   
2. **`profile_show_direct_deposit_single_form_uat`:** 
   - **Description:** Show/hide the single direct deposit form just for users during UAT only.
   
3. **`profile_show_direct_deposit_single_form_alert`:** 
   - **Description:** Show/hide an alert with information around migrating to a single direct deposit form in profile.
   
4. **`profile_show_direct_deposit_single_form_edu_downtime`:**
   - **Description:** Show/hide the EDU direct deposit form and instead display a downtime message in its place.

Since we are now fully using the single form for Direct Deposit in production, these toggles no longer serve any purpose and are being removed.

### Changes

- Removed the four toggles listed above.
- Cleaned up any references to these toggles from the codebase.

**Timeframe for toggle**

These toggles were introduced to manage the rollout and testing of the single direct deposit form in various environments. Now that the single form is fully live in production, the toggles are no longer required. The toggles can be safely removed, as all users are now using the single form.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89743
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92457

## Testing done

Test locally

## Screenshots

No UI changes

## What areas of the site does it impact?

Profile > Direct Deposit

## Acceptance criteria

- [x] Toggle removed
- [ ]  No error nor warning in the console.

### CODE REVIEW

**Review by allisonlu — DISMISSED** [review]

**Comment by tpharrison** [comment]
@asiisii Can you hold off on this?  Maybe put it in draft status?  I noticed that one of the feature toggles is still referenced in a controller.

**Comment by tpharrison** [comment]
@asiisii Can you remove this line from the `/spec/controllers/v0/profile/direct_deposits_controller_spec.rb` file? 
```
Flipper.disable(:profile_show_direct_deposit_single_form)
```

I should have removed this in an earlier PR.  Thanks!

**Comment by tpharrison** [comment]
@asiisii I think we can leave that.  It's testing a case where the account is missing the EDU flag.  Let me know if you want to discuss further.

**Review by tpharrison — APPROVED** [review]

**Review by ryan-mcneil — APPROVED** [review]
👏

**Pull request merged**
