### PR TITLE
API-27012 Raise limit on attachment parameters to 10

### PR DESCRIPTION
**Pull request by mchristiansonVA**
## Summary

- Updates the /attachments endpoint logic to raise the limit on the allowed number of attachment parameters to 10.

## Related issue(s)
[API-27012](https://jira.devops.va.gov/browse/API-27012)

## Testing done

- Rspec
- Postman
- request_url:
{{uri}}/services/claims/v2/veterans/{{veteran_id}}/526/823e08cc-2578-49b8-a285-708888adae9a/attachments

## What areas of the site does it impact?
modules/claims_api/app/controllers/claims_api/v2/veterans/disability_compensation_controller.rb

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by rmtolmach** [comment]
@mchristiansonVA To get the **Validate changes to DataDog Service Catalog Files** check passing, please update your branch with the latest changes from `master`. Thanks!

**Review by rockwellwindsor-va — DISMISSED** [review]
Postman and RSpec all looked good

**Review by FonzMP — DISMISSED** [review]
:shipit:

**Review by rockwellwindsor-va — APPROVED** [review]
LGTM!

**Pull request merged**
