### PR TITLE
WIP Base MHV Account API

### PR DESCRIPTION
**Pull request by austin-martinez**

### CODE REVIEW

**Comment by robbiethegeek-usds** [comment]
What is the state of this PR?

**Comment by saneshark** [comment]
@robbiethegeek I'm picking this one up this week. Austin got a good jump start on it and we were hoping to have some curl scripts output, but MHV has been swamped and only provided us with a host to test with late last week. So to answer your question, this is still very much a WIP, but the plan is to get something merged in this week.

**Comment by saneshark** [comment]
Note: this build is probably broken, pending specs. I just wanted to push my changes up for transparency.

**Comment by saneshark** [comment]
I do not understand why these specs keep failing Jenkins, but not my local machine.

**Comment by saneshark** [comment]
Closing this PR for now. Will open two separate PRs to address preferences vs account creation.

**Pull request closed without merging**
