### PR TITLE
add covid vaccine opt out / opt in feature

### PR DESCRIPTION
**Pull request by saneshark**
## Description of change
Adds support for new VEText interface to opt/out and opt/in on emails for a registration submission.

## Original issue(s)
None

### CODE REVIEW

**Comment by saneshark** [comment]
Specs are passing, but should probable record VCR cassettes properly. The cassettes are just made up manually right now and no error handling has been added yet.

**Review by kfrz — APPROVED** [review]
Approved, but should probably add the error handling as mentioned in your earlier comment.

**Comment by patrickvinograd** [comment]
was getting a bundle-audit failure so rebased and pushed

**Comment by saneshark** [comment]
LGTM Patrick!

**Review by patrickvinograd — APPROVED** [review]

**Pull request merged**
