### PR TITLE
Transition Settings to use New Naming Conventions 

### PR DESCRIPTION
**Pull request by stevenjcumming**
## Summary

- The new naming convention for this PR is adding the module in which the setting is used
- For example `Settings.ppms.url` is used in the `facilities_api` module so under the new convention the value is accessed via `Settings.facilties_api.ppms.url` which comes from `ENV['SETTINGS__FACILITIES_API__PPMS_URL']`
- This updated settings from the 128 listed in the related issue

Updated Settings 
- Settings.evss.s3.**
- Settings.modules_appeals_api.slack.**
- Setting.mvi.url
- Settings.ppms.url

## Related issue(s)

- Task 1 of https://github.com/department-of-veterans-affairs/va.gov-team/issues/96548

## Testing done

- [ ] Confirmed ENV vars are accessible in dev, staging, sandbox, and prod

## Acceptance criteria

- [ ] Settings values match the corresponding value in the Param Store

### CODE REVIEW

**Comment by bosawt** [comment]
@stevenjcumming Can you describe the proposed naming convention for Settings that are used in both a module and the main app (or multiple modules)? The `mocked_authentication` module uses the standard `Settings.mvi` settings, it does not define it on its own.

**Review by bosawt — CHANGES_REQUESTED** [review]
The mocked authentication changes will break things as is.

Also, the approach as-is will generally not work. It needs to go like this (probably doesn't necessarily have to be distinct 5 steps like this but there needs to be a proper transition on both vets-api and application manifests definitions):
- Additional settings added to vets-api `Settings` file
- Updates made to all stacks in application manifests repository
- vets-api usage of Settings transitioned to new settings
- Removal of old settings in application manifests
- Removal of old settings in vets-api

**Comment by stevenjcumming** [comment]
> @stevenjcumming Can you describe the proposed naming convention for Settings that are used in both a module and the main app (or multiple modules)? The `mocked_authentication` module uses the standard `Settings.mvi` settings, it does not define it on its own.

@bosawt this is PR is on hold while we re-evaluate how to add the values to the Settings. I will put in a draft state for now

The convention as of 11/20/24:

If a settings is....

- only in a single module it will have the module name (e.g. `Settings.claims_api.evss.s3.bucket`)
- not only in a single module it will have the common name ( e.g. `Settings.common.hostname)`

I wasn't including folders like `lib` or `config`, but maybe I should reconsider including them to be more clear

**Comment by stevenjcumming** [comment]
> The mocked authentication changes will break things as is.
> 
> Also, the approach as-is will generally not work. It needs to go like this (probably doesn't necessarily have to be distinct 5 steps like this but there needs to be a proper transition on both vets-api and application manifests definitions):
> 
> * Additional settings added to vets-api `Settings` file
> * Updates made to all stacks in application manifests repository
> * vets-api usage of Settings transitioned to new settings
> * Removal of old settings in application manifests
> * Removal of old settings in vets-api

We are transitioning the settings generally using the 5 steps detailed above.

**Pull request closed without merging**
