### PR TITLE
Pv rake mvi mockdump

### PR DESCRIPTION
**Pull request by patrickvinograd**
Fixes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2812

Adds a rake task to generate mock_mvi_responses.yml from MVI staging, based on the contents of mvi_users_s1a.csv (which is not any sort of canonical format but that's the form in which we have all the Stage 1a users). 

Checked in the results. Of the 266 rows in the CSV, 190 come back with an MVI profile. Some others are probably in MVI but one or more of the fields in the CSV are wrong (e.g. there are a bunch of rows with duplicate names). A few fail validation when instantiating the User object, e.g. because gender is 'U' instead of 'M' or 'F' in the CSV.

Of the 190 profiles we get back, only 12 have MHV correlation IDs. Which means for testing MHV account creation we should have plenty of users we can enroll.

I think there will be a follow-up task to align the rake create_sessions task with this change although it's not critical and I want to un-block any account creation work.

### CODE REVIEW

**Comment by saneshark** [comment]
@patrickvinograd I think we're missing address information. This will be required for making the request to MHV.

**Comment by patrickvinograd** [comment]
Some of the entries have addresses:

**Comment by saneshark** [comment]
Of these attributes (ignoring the sign_in_partners) these will be the values we will need from the mock service in dev. Just FYI: https://github.com/department-of-veterans-affairs/vets-api/blob/aab7c9b6fe60dc1aa382c96cba9542bd624bdea9/spec/lib/mhv_ac/client_spec.rb#L23-L35

**Comment by saneshark** [comment]
I see the address info in the yaml now, my bad. LGTM.

**Pull request merged**
