### PR TITLE
80792 remove redis client refactor feature flag

### PR DESCRIPTION
**Pull request by randomsync**
## Summary
This PR removes the travel claim redis client refactor flag. The code has been running in production successfully and this flag is no longer necessary.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80792

## Testing done
- [x] rspecs

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).

### CODE REVIEW

**Comment by rmtolmach** [comment]
@randomsync tag me once you have a teammate's review and then I'll take a look.

**Review by kanchanasuriya — APPROVED** [review]
LGTM

**Comment by randomsync** [comment]
> @randomsync tag me once you have a teammate's review and then I'll take a look.

@rmtolmach ... approved by my team member. please review

**Review by rmtolmach — APPROVED** [review]
This looks right to me. Nice work finishing up the feature!

@randomsync You'll also need to manually remove `check_in_experience_travel_claim_redis_client_refactor` from dev, staging, sandbox and prod. See step 3 here: https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles

Please @ me if you or someone on your team doesn't have access to argo in an environment and I can do it for you :)

**Comment by rmtolmach** [comment]
✅ flippers removed in all environments.

**Pull request merged**
