### PR TITLE
Rename request spec example groups

### PR DESCRIPTION
**Pull request by stevenjcumming**
## Summary

- For better searchability the request spec example group names should be the controller class name
- In some cases the request spec only tests one action and the name action name should be include in the example group name
- There are no functional changes
- Couldn't determine the controller for some request specs

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88996

## Testing done

- [x] No new tests

## Acceptance criteria

- [x] all request specs (except swagger_spec.rb) uses the controller class name as the example group name*
     -  *some requests couldn't be determined

### CODE REVIEW

**Comment by bosawt** [comment]
I'm not sure if this should be a holistic change across the entire codebase. In https://rspec.info/features/6-0/rspec-rails/request-specs/request-spec/, it describes request specs can be used `specify multiple requests across multiple controllers`, and I don't really think of them as directly associated with a controller. I think it's better to think of them as an integration spec, so should be associated with the route, not necessarily the controller

**Comment by stevenjcumming** [comment]
> I'm not sure if this should be a holistic change across the entire codebase. In https://rspec.info/features/6-0/rspec-rails/request-specs/request-spec/, it describes request specs can be used `specify multiple requests across multiple controllers`, and I don't really think of them as directly associated with a controller. I think it's better to think of them as an integration spec, so should be associated with the route, not necessarily the controller

@bosawt I understand that the intention of the request specs are to test a single or group of requests. And that this breaks the spirit of a request spec. But practically speaking, request specs are usually associated with a single controller. When it's not associated with a controller or doesn't follow conventions, finding the spec can be difficult (or at least more difficult than necessary). For example:

If I was looking for specs related to this controller and its actions `V0::DisabilityCompensationFormsController`, I have a 50/50 chance the the file is in specs/controller or specs/requests. So I can start off by guessing requests. I would expect, based on convention, the spec to be at `spec/requests/v0/disability_compensation_forms_spec.rb`. But it's not. 

So then, I would to search "disability_compensation_forms" and hope the filename matches. If the filename doesn't match, I'll have to search by the potential example group name or the route path. 

In the above example it's at `spec/requests/disability_compensation_form_request_spec.rb` but it's also here `spec/requests/rating_info_request_spec.rb` and as a controller spec here `app/controllers/v0/disability_compensation_forms_controller.rb`

I'm not advocating to mandate that the example group name be a controller class name, but it makes things easier to find, given the unpredictable, unconventional nature of the repo, especially the request specs.

**Comment by bosawt** [comment]
> > I'm not sure if this should be a holistic change across the entire codebase. In https://rspec.info/features/6-0/rspec-rails/request-specs/request-spec/, it describes request specs can be used `specify multiple requests across multiple controllers`, and I don't really think of them as directly associated with a controller. I think it's better to think of them as an integration spec, so should be associated with the route, not necessarily the controller
> 
> @bosawt I understand that the intention of the request specs are to test a single or group of requests. And that this breaks the spirit of a request spec. But practically speaking, request specs are usually associated with a single controller. When it's not associated with a controller or doesn't follow conventions, finding the spec can be difficult (or at least more difficult than necessary). For example:
> 
> If I was looking for specs related to this controller and its actions `V0::DisabilityCompensationFormsController`, I have a 50/50 chance the the file is in specs/controller or specs/requests. So I can start off by guessing requests. I would expect, based on convention, the spec to be at `spec/requests/v0/disability_compensation_forms_spec.rb`. But it's not.
> 
> So then, I would to search "disability_compensation_forms" and hope the filename matches. If the filename doesn't match, I'll have to search by the potential example group name or the route path.
> 
> In the above example it's at `spec/requests/disability_compensation_form_request_spec.rb` but it's also here `spec/requests/rating_info_request_spec.rb` and as a controller spec here `app/controllers/v0/disability_compensation_forms_controller.rb`
> 
> I'm not advocating to mandate that the example group name be a controller class name, but it makes things easier to find, given the size and unpredictable/unconventional nature of the repo, especially the request specs.

I would argue that your initial attempt to locate the request spec for `V0::DisabilityCompensationFormsController` was based off of thinking of this from a controller spec perspective. Here's what I would have suggested:
- Discover the routes that are defined by the `DisabilityCompensationFormsController`: `bundle exec rails routes | grep v0/disability_compensation_forms` (could be other ways to do this, this is the relevant part of the output):

> GET /v0/disability_compensation_form/rated_disabilities(.:format)       
GET /v0/disability_compensation_form/rating_info(.:format)              
GET /v0/disability_compensation_form/submission_status/:job_id(.:format)
POST /v0/disability_compensation_form/submit_all_claim(.:format)         
GET /v0/disability_compensation_form/suggested_conditions(.:format)     
GET /v0/disability_compensation_form/user_submissions(.:format)         
GET /v0/disability_compensation_form/separation_locations(.:format)     


And then you should be able to search for each of these and see a request spec:
image

So I would say this request spec description is actually named exactly what it should be. There are plenty of request specs that are named other weird things in our repo that should probably be fixed but it seems weird to me to change the ones that are currently following convention

**Comment by stevenjcumming** [comment]
> I would argue that your initial attempt to locate the request spec for `V0::DisabilityCompensationFormsController` was based off of thinking of this from a controller spec perspective. Here's what I would have suggested:
> 
> * Discover the routes that are defined by the `DisabilityCompensationFormsController`: `bundle exec rails routes | grep v0/disability_compensation_forms` (could be other ways to do this, this is the relevant part of the output):
> 
> > GET /v0/disability_compensation_form/rated_disabilities(.:format)
> > GET /v0/disability_compensation_form/rating_info(.:format)
> > GET /v0/disability_compensation_form/submission_status/:job_id(.:format)
> > POST /v0/disability_compensation_form/submit_all_claim(.:format)
> > GET /v0/disability_compensation_form/suggested_conditions(.:format)
> > GET /v0/disability_compensation_form/user_submissions(.:format)
> > GET /v0/disability_compensation_form/separation_locations(.:format)
> 
> And then you should be able to search for each of these and see a request spec: 
> 
> So I would say this request spec description is actually named exactly what it should be. There are plenty of request specs that are named other weird things in our repo that should probably be fixed but it seems weird to me to change the ones that are currently following convention

It's still an extra step, but also limited to request specs. If I'm testing an update in a controller, I'll want to test all specs related to that. And the quickest way to do that (that I can think of) is to search `V0::DisabilityCompensationFormsController` which will give me the controller spec and the request spec(s).

In the change I'm proposing, you can still search the way you've suggested. And I agree `GET /v0/disability_compensation_form/rated_disabilities` should be the example group name for that request. However, it doesn't address what the top-level example group name should be. I would prefer something like:

```ruby
# spec/requests/v1/examples_spec.rb

RSpec.describe V1::ExamplesController, type: :request do

  describe 'GET /v1/examples' do
  end 

end
```

**Comment by bosawt** [comment]
> > I would argue that your initial attempt to locate the request spec for `V0::DisabilityCompensationFormsController` was based off of thinking of this from a controller spec perspective. Here's what I would have suggested:
> > 
> > * Discover the routes that are defined by the `DisabilityCompensationFormsController`: `bundle exec rails routes | grep v0/disability_compensation_forms` (could be other ways to do this, this is the relevant part of the output):
> > 
> > > GET /v0/disability_compensation_form/rated_disabilities(.:format)
> > > GET /v0/disability_compensation_form/rating_info(.:format)
> > > GET /v0/disability_compensation_form/submission_status/:job_id(.:format)
> > > POST /v0/disability_compensation_form/submit_all_claim(.:format)
> > > GET /v0/disability_compensation_form/suggested_conditions(.:format)
> > > GET /v0/disability_compensation_form/user_submissions(.:format)
> > > GET /v0/disability_compensation_form/separation_locations(.:format)
> > 
> > 
> > And then you should be able to search for each of these and see a request spec:
> > So I would say this request spec description is actually named exactly what it should be. There are plenty of request specs that are named other weird things in our repo that should probably be fixed but it seems weird to me to change the ones that are currently following convention
> 
> It's still an extra step, but also limited to request specs. If I'm testing an update in a controller, I'll want to test all specs related to that. And the quickest way to do that (that I can think of) is to search `V0::DisabilityCompensationFormsController` which will give me the controller spec and the request spec(s).
> 
> In the change I'm proposing, you can still search the way you've suggested. And I agree `GET /v0/disability_compensation_form/rated_disabilities` should be the example group name for that request. However, it doesn't address what the top-level example group name should be. I would prefer something like:
> 
> ```ruby
> # spec/requests/v1/examples_spec.rb
> 
> RSpec.describe V1::ExamplesController, type: :request do
> 
>   describe 'GET /v1/examples' do
>   end 
> 
> end
> ```

I understand, but you're still describing controller specs conventions, which we still have in our repository and teams could use if they prefer that style.

From: https://rspec.info/features/6-0/rspec-rails/controller-specs/

```ruby
RSpec.describe TeamsController do
  describe "GET index" do
    it "assigns @teams" do
      team = Team.create
      get :index
      expect(assigns(:teams)).to eq([team])
    end

    it "renders the index template" do
      get :index
      expect(response).to render_template("index")
    end
  end
end
```

From: https://rspec.info/features/6-0/rspec-rails/request-specs/request-spec/

```ruby
RSpec.describe "Widget management", type: :request do

  it "creates a Widget and redirects to the Widget's page" do
    get "/widgets/new"
    expect(response).to render_template(:new)

    post "/widgets", :params => { :widget => {:name => "My Widget"} }

    expect(response).to redirect_to(assigns(:widget))
    follow_redirect!

    expect(response).to render_template(:show)
    expect(response.body).to include("Widget was successfully created.")
  end

  it "does not render a different template" do
    get "/widgets/new"
    expect(response).to_not render_template(:show)
  end
end
```

**Comment by stevenjcumming** [comment]
Going to take a different approach

**Pull request closed without merging**
