### PR TITLE
[8549] Fixing failing create ch31 submissions spec

### PR DESCRIPTION
**Pull request by bosawt**
## Description of change
This spec seems to fail regularly and this fixes it

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33428

## Things to know about this PR
- For more details, this is happening because of a timezone mismatch in the spec claims creation and the time range defined in the worker
- When we're on a date boundary in UTC (4 PM PST), we see this:
`Time.zone.now.yesterday => Tue, 30 Nov 2021 00:40:12.801226000 UTC +00:00`
- But the range being built is in eastern time:
`build_range(date).  => Tue, 30 Nov 2021 00:00:00.000000000 EST -05:00..Tue, 30 Nov 2021 23:59:59.000000000 EST -05:00`
- It looks like the original time is within the range from `build_range`, but because of timezone mismatch it actually isn't for a few hours

### CODE REVIEW

**Review by RudyOnRails — APPROVED** [review]
Ahh yes, I remember this thought when working on it and never implemented. 

thank you @bosawt! 🙇

**Comment by bosawt** [comment]
> 



> Ahh yes, I remember this thought when working on it and never implemented.
> 
> thank you @bosawt! 🙇

Also, I haven't fully thought it through, so might still fail at certain times. I think overall the issue is that the time range is being force-converted to Eastern time, but the date  to build the range off of is UTC. For example:
It's 5:00 PM PST, which is currently 'tomorrow' for UTC. In the `CreateCh31SubmissionsReport` job, it first takes the Sidekiq argument and sets it to yesterday, this is given based off the current `UTC` time. This means at this moment the worker doesn't give me yesterday's date, it gives me today's date. This is fine, but we force convert it to eastern, and try to find the submissions from the beginning to end of `today` in Eastern time, where the intention was to do that with `yesterday` in Eastern time.

My recommendation for solving it would probably be to calculate the date itself to calculate the range from, from an Eastern time zone perspective. Something like `Time.zone.at(epoch).in_time_zone('Eastern Time (US & Canada)').yesterday.strftime('%Y-%m-%d')`

**Comment by bosawt** [comment]
> > Ahh yes, I remember this thought when working on it and never implemented.
> > thank you @bosawt! 🙇
> 
> Also, I haven't fully thought it through, so might still fail at certain times. I think overall the issue is that the time range is being force-converted to Eastern time, but the date to build the range off of is UTC. For example: It's 5:00 PM PST, which is currently 'tomorrow' for UTC. In the `CreateCh31SubmissionsReport` job, it first takes the Sidekiq argument and sets it to yesterday, this is given based off the current `UTC` time. This means at this moment the worker doesn't give me yesterday's date, it gives me today's date. This is fine, but we force convert it to eastern, and try to find the submissions from the beginning to end of `today` in Eastern time, where the intention was to do that with `yesterday` in Eastern time.
> 
> My recommendation for solving it would probably be to calculate the date itself to calculate the range from, from an Eastern time zone perspective. Something like `Time.zone.at(epoch).in_time_zone('Eastern Time (US & Canada)').yesterday.strftime('%Y-%m-%d')`

@RudyOnRails Actually I'm relatively confident that will solve your issue, I updated the PR to reflect that submission, but that actually changes code now so feel free to reject or take this in another direction (I didn't do any dev acceptance testing since I'm not really sure how to with this feature)

**Comment by RudyOnRails** [comment]
@bosawt - it's a bit late over here and brain is a bit mushy but I will work on it if it's holding up PR merging or deploys etc.

Otherwise I will take all your efforts here and wrap up in the morning. I wonder if I should time travel it all and lock it down that way.

**Comment by bosawt** [comment]
> @bosawt - it's a bit late over here and brain is a bit mushy but I will work on it if it's holding up PR merging or deploys etc.
> 
> 
> 
> Otherwise I will take all your efforts here and wrap up in the morning. I wonder if I should time travel it all and lock it down that way.

Yeah, no rush. I'm done for the day. It's not holding me up or anything, just something I saw that didn't look too difficult to resolve

**Review by rileyanderson — DISMISSED** [review]

**Comment by bosawt** [comment]
@RudyOnRails Should I do anything with this? Just curious if you'd tested it or gotten your own solution out, or if there's enough confidence that this PR is good to go and can be merged

**Comment by RudyOnRails** [comment]
@bosawt I ended up having to take my wife to the ER yesterday so today I am closing it up.

**Comment by bosawt** [comment]
> @bosawt I ended up having to take my wife to the ER yesterday so today I am closing it up.

Sounds good! No worries! Hope everything turned out fine

**Review by RudyOnRails — APPROVED** [review]
LGTM 😉

**Comment by RudyOnRails** [comment]
@bosawt Let me know if you're cool with this result. I wanted to keep the implementation the same and fix the test. Do you see any reason, inside the actual worker, that we need to force the `epoch` to Eastern time? In UTC it will always be ahead of Eastern and yesterday will always give us what we want.

**Comment by bosawt** [comment]
> @bosawt Let me know if you're cool with this result. I wanted to keep the implementation the same and fix the test. Do you see any reason, inside the actual worker, that we need to force the `epoch` to Eastern time? In UTC it will always be ahead of Eastern and `.yesterday` will always give us what we want.

That's fine by me. It'll ensure the spec won't fail, which is all I truly care about, haha. I believe this will perform unexpectedly if you run the report in the evening though, you can test it with:

>     def build_range(report_date)
>       zone = 'Eastern Time (US & Canada)'
>       begin_time = ActiveSupport::TimeZone[zone].parse("#{report_date} 00:00:00")
>       end_time = ActiveSupport::TimeZone[zone].parse("#{report_date} 23:59:59")
>       begin_time..end_time
>     end
>
>     def time_test(time)
>       date = Time.zone.at(time.to_i).yesterday.strftime('%Y-%m-%d')
>       range = build_range(date)
>       puts "Input time is\n#{time},\nconverted to yesterday's date:\n#{date},\ncalculated time range is\n#{range}"
>     end
>

Then:

> time_test(Time.now.utc)
Input time is
2021-12-03 14:35:19 UTC,
converted to date:
2021-12-02,
calculated time range is
2021-12-02 00:00:00 -0500..2021-12-02 23:59:59 -0500

Which is fine
But, when utc is 'tomorrow' and it's not yet tomorrow in Eastern Time:

> time_test(Time.now.utc + 12.hours)
Input time is
2021-12-04 02:35:23 UTC,
converted to date:
2021-12-03,
calculated time range is
2021-12-03 00:00:00 -0500..2021-12-03 23:59:59 -0500

And that shows the issue. 

You might think it seems it's 'technically' working, just on UTC today versus yesterday. but it also fails if you explicitly put in a time object with eastern time zone:

> time_test(Time.now.in_time_zone('Eastern Time (US & Canada)') + 12.hours)
Input time is
2021-12-03 21:42:11 -0500,
converted to date:
2021-12-03,
calculated time range is
2021-12-03 00:00:00 -0500..2021-12-03 23:59:59 -0500

As you can see, this was run 12 hours from now, so at 9ish PM Eastern, but the report gives today's range, not yesterday

**Review by rileyanderson — APPROVED** [review]

**Comment by RudyOnRails** [comment]
@bosawt I see what you mean about running the report when it is Saturday in UTC, where `yesterday` would give us Friday and the data we want is for Thursday. 

The scenario to target is the `sidekiq_scheduler` always sparking the report at `00:00:01` Eastern Time. I don't think this will change or a reason it would since as soon as the day is done in Eastern Time (US & Canada), the report will be generated, and the argument will be persisted to Redis inside the job.

And I added the 2nd arg to run the report at any time for a specific date, so there is no calculation to get a previous date, it's an explicit string.

Thanks for bringing this up and I hope I did not disappoint the way it resulted. If you still see a potential problem after what I've explained, let's take it further, but for now I'm going to merge in the spec fixes so people like yourself don't have to suffer in the evenings!

**Comment by bosawt** [comment]
> @bosawt I see what you mean about running the report when it is Saturday in UTC, where `yesterday` would give us Friday and the data we want is for Thursday.
> 
> The scenario to target is the `sidekiq_scheduler` always sparking the report at `00:00:01` Eastern Time. I don't think this will change or a reason it would since as soon as the day is done in Eastern Time (US & Canada), the report will be generated, and the argument will be persisted to Redis inside the job.
> 
> And I added the 2nd arg to run the report at any time for a specific date, so there is no calculation to get a previous date, it's an explicit string.
> 
> Thanks for bringing this up and I hope I did not disappoint the way it resulted. If you still see a potential problem after what I've explained, let's take it further, but for now I'm going to merge in the spec fixes so people like yourself don't have to suffer in the evenings!

👍 Totally fine by me. Yeah, from your description of the actual usage I see no problems!

**Comment by RudyOnRails** [comment]
> > @bosawt I see what you mean about running the report when it is Saturday in UTC, where `yesterday` would give us Friday and the data we want is for Thursday.
> > The scenario to target is the `sidekiq_scheduler` always sparking the report at `00:00:01` Eastern Time. I don't think this will change or a reason it would since as soon as the day is done in Eastern Time (US & Canada), the report will be generated, and the argument will be persisted to Redis inside the job.
> > And I added the 2nd arg to run the report at any time for a specific date, so there is no calculation to get a previous date, it's an explicit string.
> > Thanks for bringing this up and I hope I did not disappoint the way it resulted. If you still see a potential problem after what I've explained, let's take it further, but for now I'm going to merge in the spec fixes so people like yourself don't have to suffer in the evenings!
> 
> 👍 Totally fine by me. Yeah, from your description of the actual usage I see no problems!

:party_parrot:

**Pull request merged**
