### PR TITLE
WIP: Remove unused factories, lint existing factories

### PR DESCRIPTION
**Pull request by johnpaulashenfelter**
## Description of change

We have a lot of factories and they are haphazardly tested if at all. Now that we've got FactoryBot 5.x, we can use the built-in linting option.

In this PR, we're going to:
 - [ ] Use `factory_trace` to identify unused factories and traits to remove from app
 - [ ] Add automatic linting to all factories that remain in the app
 - [ ]  Lint new factories by default

## Testing done

If specs still pass, we're fine

## Acceptance Criteria (Definition of Done)
- [ ] All unused factories are removed
- [ ] Existing factories are appropriately linted
- [ ] New factories are linted automatically
- [ ] CI runs the linting process

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Swagger docs have been updated, if applicable
- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub
- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by johnpaulashenfelter** [comment]
@bastosmichael I reran the trace using the `rake` task instead of `rspec`, which thanks to @annaswims recent PR #3283 runs all the specs including in modules.

```
total number of unique used factories & traits: 215
total number of unique unused factories & traits: 20
unused factory configuration
unused factory disability_compensation_submission
unused factory access_satisfaction
unused factory access_wait_time
unused trait system_folder of factory folder
unused trait with_counts of factory folder
unused factory id_card_announcement_subscription
unused factory maintenance_window
unused factory nca_gis_record_v1
unused factory nca_gis_record_v2
unused factory mhv_user_identity
unused factory dslogon_user_identity
unused factory mhv_user_identity_attrs
unused factory dslogon_user_identity_attrs
unused factory va0994_minimum_form
unused factory vet360_message
unused factory vha_gis_record
unused factory vha_gis_record_v3
unused factory invalid_auto_established_claim
unused global trait loa3
```

**Comment by kfrz** [comment]
If this is a [WIP] and not ready for review-and-merge, it should utilize [draft pr](https://help.github.com/en/articles/changing-the-stage-of-a-pull-request) feature. 

Very exciting, though

**Comment by kfrz** [comment]
@johnpaulashenfelter any updates on this? Can we link this PR to a tech debt ticket? Can this be merged?

**Comment by saneshark** [comment]
If you look in the Gemfile, FactoryBot is both in the dev and test namespaces. I know on VAOS we use FactoryBot all the time in the dev console for loading form objects. Those same bots happen to be used by specs. My point though is that FactoryBot is not necessarily exclusively used by Rspec, sometimes it could be used as a convenient way of loading certain data for testing.

**Comment by kfrz** [comment]
@saneshark has a good point about factories being used outside of specs. I'd argue, though, that if a factory is used outside of specs but not *within* the specs, maybe that indicates we're missing some crucial spec coverage :) 

At any rate - I am going to suggest splitting this PR in two. To wit, I've retconned two tickets: #4381 and #4382

**Comment by johnpaulashenfelter** [comment]
Closed due to (my) inaction

**Pull request closed without merging**
