### PR TITLE
65684 sign in service terms of use flow

### PR DESCRIPTION
**Pull request by bosawt**
## Summary

- This PR adds terms of use functionality to the sign in service authentication flow.
- If a sign in service client is set up with `enforced_terms` and have a defined `terms_of_use_url`, then the authenticating user will be redirected to a terms of use page before authentication is complete (unless they have previously accepted a terms of use)

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#65684

## Testing done

- Authenticate with a user on sign in service, confirmed `/callback` redirected to terms of use page
- Manually accepted terms on rails console backend
- Authenticated again, confirmed standard redirect occurred, not redirect to terms of use page

## What areas of the site does it impact?
Terms of Use
Authentication

## Acceptance criteria

- [ ] Authenticate with users who have not previously accepted terms of use and confirm they are redirected to terms of use page (frontend won't properly deal with this yet as it is not functional with sign in service yet
- [ ] Authenticate with users who have previously accepted terms of use and confirm authentication occurs as expected, without redirect to terms of use page
- [ ] Create a new sign in service `ClientConfig`, with a new `terms_of_use_url` setting, confirm users without a terms of use are redirected to the new url
- [ ] Create a new sign in service `ClientConfig`, with `enforced_terms` set to `nil`, confirm users without a terms of use are not redirected to the terms of use page

### CODE REVIEW

**Review by bramleyjl — COMMENTED** [review]
I've been able to perform the following steps:

* ran `rails db:seed` to re-seed the ClientConfigs with necessary ToU attributes
* performed SiS auth for `vaweb` client_id & was redirected to ToU page
* copied the `code` param and used it to obtain a valid access_token in Postman (hit `/user` and received user attributes)
* made a POST to `/v0/terms_of_use_agreements/v1/<accept/decline>` with the copied `terms_code` and `vagov_access_token` cookie header

I am only able to get a 403 invalid auth token error here, not sure why.

- [x] Authenticate with users who have not previously accepted terms of use and confirm they are redirected to terms of use page (frontend won't properly deal with this yet as it is not functional with sign in service yet
- [ ] Authenticate with users who have previously accepted terms of use and confirm authentication occurs as expected, without redirect to terms of use page
- [ ] Create a new sign in service `ClientConfig`, with a new `terms_of_use_url` setting, confirm users without a terms of use are redirected to the new url
- [ ] Create a new sign in service `ClientConfig`, with `enforced_terms` set to `nil`, confirm users without a terms of use are not redirected to the terms of use page

**Comment by bosawt** [comment]
> I've been able to perform the following steps:
> 
> * ran `rails db:seed` to re-seed the ClientConfigs with necessary ToU attributes
> * performed SiS auth for `vaweb` client_id & was redirected to ToU page
> * copied the `code` param and used it to obtain a valid access_token in Postman (hit `/user` and received user attributes)
> * made a POST to `/v0/terms_of_use_agreements/v1/<accept/decline>` with the copied `terms_code` and `vagov_access_token` cookie header
> 
> I am only able to get a 403 invalid auth token error here, not sure why.
> 
> * [x]  Authenticate with users who have not previously accepted terms of use and confirm they are redirected to terms of use page (frontend won't properly deal with this yet as it is not functional with sign in service yet
> * [ ]  Authenticate with users who have previously accepted terms of use and confirm authentication occurs as expected, without redirect to terms of use page
> * [ ]  Create a new sign in service `ClientConfig`, with a new `terms_of_use_url` setting, confirm users without a terms of use are redirected to the new url
> * [ ]  Create a new sign in service `ClientConfig`, with `enforced_terms` set to `nil`, confirm users without a terms of use are not redirected to the terms of use page

One amendment to your testing process: `made a POST to /v0/terms_of_use_agreements/v1/<accept/decline> with the copied terms_code and vagov_access_token cookie header` <- with this step, don't pass the `vagov_access_token`. The reason is that when you're accepting terms on Sign in Service flow you won't actually have the access token yet (this is why we have to use the `terms_code` as a partial auth)

**Comment by bramleyjl** [comment]
> One amendment to your testing process: `made a POST to /v0/terms_of_use_agreements/v1/<accept/decline> with the copied terms_code and vagov_access_token cookie header` <- with this step, don't pass the `vagov_access_token`. The reason is that when you're accepting terms on Sign in Service flow you won't actually have the access token yet (this is why we have to use the `terms_code` as a partial auth)

I actually originally tried without the access_token and only started adding it after I got the 403 `Invalid Authenticity Token` response. It looks like it's the anti-CSRF validation that's failing:
```ruby
Rails -- Started POST "/v0/terms_of_use_agreements/v1/accept?terms_code=FILTERED" for ::1 at 2023-09-26 11:51:17 -0600
Rails -- Processing by V0::TermsOfUseAgreementsController#accept as JSON
Rails --   Parameters: {"terms_code"=>"FILTERED", "version"=>"FILTERED"}
V0::TermsOfUseAgreementsController -- Can't verify CSRF token authenticity.
Rails -- ActionController::InvalidAuthenticityToken.
Rails -- /home/john/Projects/va/vets-api/vendor/bundle/ruby/3.2.0/bundler/gems/rails-90b0266e9bfa/actionpack/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
```

**Review by bramleyjl — DISMISSED** [review]

**Review by asg5704 — DISMISSED** [review]
Unauth SiS = Works as expected when updating ToU
Auth SiS = Works as expected when updating ToU

Not sure if its an issue but when accepting the ToU, then going back and declining the ToU I noticed that after I re-authenticate with the same user (220) that I am not re-prompted for ToU.

**Review by bramleyjl — DISMISSED** [review]

**Comment by bosawt** [comment]
@bramleyjl @asg5704 Should have resolved the issue where user 'accepts', then 'declines'. ToU should be properly shown now until they 'accept' again

**Review by asg5704 — APPROVED** [review]

**Review by rmtolmach — APPROVED** [review]

**Pull request merged**
