### PR TITLE
log ssns in user metadata for ppiu errors

### PR DESCRIPTION
**Pull request by lihanli**
## Description of change
https://github.com/department-of-veterans-affairs/va.gov-team/issues/2074#issuecomment-539477542
log ssns in user metadata for ppiu errors

## Testing done
automated tests

## Testing planned
test in staging

#### Applies to all PRs

- [x] Appropriate logging
- [x] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [x] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by lihanli** [comment]
we're already storing SSNs in this table so this wouldn't add any new security risks, but i emailed adam to see if they can lookup users without using sensitive identifiers

**Comment by lihanli** [comment]
the `PersonalInformationLog` table was created to temporary store PII for debugging purposes since it can't be stored in sentry or cloudwatch

**Comment by johnpaulashenfelter** [comment]
@lihanli is this blocked until you here back from Adam? There's nothing wrong with the code here, so its really just verifying this is the best way. Just @ one of us with that update and we'll be good to go.

**Comment by lihanli** [comment]
@annaswims @johnpaulashenfelter i received a reply from adam kinder, he says he needs SSNs in order to lookup users on his end

**Pull request merged**
