### PR TITLE
[WIP - sync with devops] Make mvi processing code env var i451

### PR DESCRIPTION
**Pull request by kreek**
During MVI demo we found out 'processingCode' in MVI XML messages should be 'T' in all envs other than prod, where it should be 'P'.

### CODE REVIEW

**Comment by robbiethegeek** [comment]
@kreek did you work with devops to get these ENV variables set per env?

**Comment by kreek** [comment]
@robbiethegeek just made ticket https://github.com/department-of-veterans-affairs/devops/issues/1013

**Comment by robbiethegeek** [comment]
:shipit: LGTM

**Comment by robbiethegeek** [comment]
Once you get DevOps onboard and tests pass LGTM

**Pull request merged**
