### PR TITLE
production deploy

### PR DESCRIPTION
**Pull request by lihanli**
need to fix 2 errors in production for education benefits
- spool file retries overwriting existing files in the sftp
- validation error in phone numbers

### CODE REVIEW

**Comment by lihanli** [comment]
don't know why there are merge conflicts but we could force push master into production when we are ready

**Comment by omgitsbillryan** [comment]
You're OP confuses me.  The 77 commits from master include _much_ more than the 2 fixes for education benefits that you mention.  Are we doing another prod release with this merge?

**Comment by lihanli** [comment]
it would be another prod release, the commits we want are last on the list and can't be cherry picked because they depend on previous commits

**Comment by omgitsbillryan** [comment]
Do we have `prod` deploy strategy in place?  Merging all of `master` into `production` just for a bug fix seems like killing an ant with a bazooka.  Maybe you want to commit to `production` directly? - but that has it's own challenges.

I need some clarity on our hotfix and deploy-to-prod strategies.

**Comment by lihanli** [comment]
if we commit to prod directly we can't test on staging first

**Comment by jkassemi** [comment]
Not sure if this observation already made it out:

```
└─▪ git cat-file -p 8e8b1ce92763da672d3fed2898c01fcae951c4fc
tree 50fb0e957277e04d0a7790c9d693e997b9406dc7
parent 98a32e73f42021c51d255a63f53e68a451aad1c8
author lihan <frankieteardrop@gmail.com> 1478553029 -0500
committer GitHub <noreply@github.com> 1478553029 -0500

production deploy (#461)
```

was a squash commit on the last production deployment, and I don't believe production was merged back into master.

conflicts will need to be resolved manually. Create a release branch from master afterward, we'll need to be sure a merge commit gets used when it gets merged into production, and then make sure to get production merged back into master right afterward...

(should be pretty easy to resolve them though, since the latest changes are the valid ones)

I'm hoping to see #498 make it into this release.

**Pull request closed without merging**
