### PR TITLE
squash migrations

### PR DESCRIPTION
**Pull request by kreek**
- Squashes migrations into one file tagged with the latest schema_migrations timestamp `20180503172030`
- Configures active record schema format to be SQL rather than Ruby to preserve postgres specific commands

### CODE REVIEW

**Comment by kreek** [comment]
@wyattwalter looks like psql is needed once we move to structure.sql from schema.rb, do we need to add this to docker and/or any other build tools?

> failed to execute:
psql -q -f /src/vets-api/db/structure.sql vets_api_development
Please check the output above for any errors and make sure that `psql` is installed in your PATH and has proper permissions.

**Comment by jkassemi** [comment]
@kreek - I made a quick update to use postgres-9.5 with docker, which now lines up with RDS. I took a stab at the initial merge conflict resolution, but it would be great if you could clean up the ordering and make sure everything's still looking good.

I'm fine locking us to an explicit database version, but I'm not sure if we'll need folks to update their local setup to maintain consistency (I think you're running 10.0?). Which change was it that was incompatible?

**Comment by kreek** [comment]
@jkassemi 👍thanks, I'll downgrade postgres, wasn't for a specific feature I think I just did a `brew install postgres` instead of `postgresql@9.5`. We could add a check for local installs. I'll clean up the ordering etc.

**Comment by kreek** [comment]
@jkassemi @wyattwalter looks like it's running the build against the cached postgres service
```
pg_dump: server version: 9.6.8; pg_dump version: 9.5.13
pg_dump: aborting because of server version mismatch
```
is there a way to force it to build from scratch?

**Comment by wyattwalter** [comment]
🤔 the beginning of the build does:

```
Pulling postgres (postgres:9.5-alpine)...

9.5-alpine: Pulling from library/postgres
```

**Comment by wyattwalter** [comment]
Looks like what was happening is that the `make clean` at the end of the didn't fire because `archive` step in the Jenkinsfile didn't have anything to archive and the pipeline bailed. Will need to fix that up. For the moment, it's failing for a different reason! 😛

**Comment by wyattwalter** [comment]
Seems like the most recent errors center around the `consumer_name` attribute on the most recent migration for the VBA Documents. I'm not familiar with how this should work with Rails engines, but I think we are missing migrations from the modules dir, so the field is not available when Rails is looking for it on the object.

**Comment by kreek** [comment]
I added a break point and it hits the engine initializer which should append migrations https://github.com/department-of-veterans-affairs/vets-api/blob/d7f476f7bdd1a2d644da8b241c4257a8017805de/modules/vba_documents/lib/vba_documents/engine.rb#L12 but they obviously don't run 🤔 

The structure.sql file does have the `consumer_name` column, @jkassemi was switching to `db:create` from `db:setup` for ci in the Makefile to fix another issue?

**Comment by kreek** [comment]
First comment on [this post](https://content.pivotal.io/blog/leave-your-migrations-in-your-rails-engines) suggests an issue with chained rake commands:
>On it's own "rake db:migrate" will pull in the changes just fine, however if you chain multiple commands like "rake db:drop db:create db:migrate" it does not include migrations from the engine.

**Comment by jkassemi** [comment]
Huh, that's interesting. 

I was trying to use db:migrate vs setup so we could test migrations from start to finish with CI.

**Comment by johnpaulashenfelter** [comment]
@jkassemi Is this still a valid PR? Been open for a while and I'm not sure about its status.

**Comment by johnpaulashenfelter** [comment]
@kreek Is this still a valid PR?

**Comment by kreek** [comment]
@johnpaulashenfelter We can close this one. If VSP still wants to do this I'd open a new PR that squash's migrations to a more recent point in time.

**Pull request closed without merging**
