### PR TITLE
API-38535-enable-hardcoded-wsdl-org-web-service

### PR DESCRIPTION
**Pull request by stiehlrod**
## Summary

- Hard codes OrgWebService. Adds a test file for find_definition.

## Related issue(s)

- [API-38634](https://jira.devops.va.gov/browse/API-38634)

## Testing done

- [X] *New code is covered by unit tests*
- To test in Postman
1. call `{{uri}}/services/claims/v1/forms/2122`
2. place break point [here](https://github.com/department-of-veterans-affairs/vets-api/blob/API-38535-enable-hardcoded-wsdl-org-web-service/modules/claims_api/lib/bgs_service/local_bgs.rb#L320)
3. look at the endpoint variable, and it should be `PersonWebServiceBean/PersonWebService` or `ClaimantServiceBean/ClaimantWebService` 
4. determine if the definition is found

## What areas of the site does it impact?
	modified:   modules/claims_api/app/clients/claims_api/bgs_client/definitions.rb
	modified:   modules/claims_api/lib/bgs_service/local_bgs.rb
	modified:   modules/claims_api/spec/lib/claims_api/find_definition_spec.rb

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by rockwellwindsor-va — APPROVED** [review]
Definition found, LGTM!

Screenshot 2024-07-31 at 10 21 02 AM

**Comment by FonzMP** [comment]
is this for Person or Org or Claimant? Ticket # is associated to the overall WSDL changes, but the subtask moved to review says Org. PR name says Org. Changes reflect Person. Testing mentions Person and Claimant. 
just want to make sure we're aligned here with tickets <> PRs <> changes.

**Comment by stiehlrod** [comment]
> is this for Person or Org or Claimant? Ticket # is associated to the overall WSDL changes, but the subtask moved to review says Org. PR name says Org. Changes reflect Person. Testing mentions Person and Claimant. just want to make sure we're aligned here with tickets <> PRs <> changes.

Aligned

**Review by FonzMP — APPROVED** [review]
:shipit:

**Pull request merged**
