### PR TITLE
Update vets_json_schema

### PR DESCRIPTION
**Pull request by opticbob**
## Summary

- *This work is behind a feature toggle (flipper): NO*
- *(Summarize the changes that have been made to the platform)* I've updated the `vets_json_schema` gem to the latest version.
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution?)*
- *(Which team do you work for, does your team own the maintenance of this component?)* FAR/ARM, we don't own the maintenance.
- *(If introducing a flipper, what is the success criteria being targeted?)*

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93506
- https://github.com/department-of-veterans-affairs/vets-json-schema/pull/949
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)* This just touches the `vets_json_schema` gem.

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by holdenhinkle — APPROVED** [review]

**Review by rmtolmach — APPROVED** [review]
matches https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/package.json#L3 👍

**Comment by rmtolmach** [comment]
oh, your specs had timed out. I'm re-running them for you.

**Comment by rmtolmach** [comment]
oh, now you're hitting a failing test in `master`. I'm working with that test owner to get it resolved and then we can update your branch.

**Comment by opticbob** [comment]
@rmtolmach That sounds great thanks!  I was just looking at this and it looks like there were a couple of updates and version bumps to the vets-json-schema repo besides mine that never updated the vets_json_schema gem.  One update before mine and one after.  Do you think the failing tests are related?

**Comment by rmtolmach** [comment]
The test is fixed in `master`, but you're getting failures on your branch (they're not the same ones that were in master) 😕 See here:
- https://github.com/department-of-veterans-affairs/vets-api/runs/33161061865 (you can ignore the `Error processing result file` one–that's there when the tests time out).
- https://github.com/department-of-veterans-affairs/vets-api/runs/33161545875

Can you investigate those?

**Comment by opticbob** [comment]
Yep, I'll check them out.  Thanks @rmtolmach !

**Comment by opticbob** [comment]
Hey @rmtolmach, I need some clarification on how to move forward with this.  I'm going to refer to [vets-json-schema's package.json history](https://github.com/department-of-veterans-affairs/vets-json-schema/commits/master/package.json) for my timeline.

In https://github.com/department-of-veterans-affairs/vets-json-schema/commit/199861abd279bd35966cc659fc46612d30e0a714 two weeks ago some regexes were changed around the processing of form 40-10007.  The package.json was bumped from 24.5.2 to 24.5.3 in the vets-json-schema repo.  The vets_json_schema gem was never updated here in vets-api to reflect that update.

My vets-json-schema PR bumped the version to 24.5.4.  It has since been bumped one more time to 24.5.5.

As far as I can tell those earlier vets-json-api changes are causing the test errors we're seeing in this PR now.  There is a similar situation going on in the [matching PR on vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/32997/).

How should I move forward with this?  Do I need to modify another team's tests here in vets-api so they pass?  Should I revert their changes to vets-json-schema so they pass without changes in this repo?  Is there another way to make sure the changes I made to vets-json-schema can be used here in the vets_json_schema gem without the test breaking changes coming along for the ride?

**Comment by rmtolmach** [comment]
I will pass this on to @RachalCassity. She's on support tomorrow and can help.

**Comment by opticbob** [comment]
It looks like there is a PR that would go a long way toward fixing these tests: https://github.com/department-of-veterans-affairs/vets-api/pull/19294.  I'm not sure why it hasn't been merged.

**Review by RachalCassity — APPROVED** [review]

**Comment by opticbob** [comment]
Hello @RachalCassity !  Do you have a suggestion how I can move forward with this PR as written up [above?](https://github.com/department-of-veterans-affairs/vets-api/pull/19442#issuecomment-2484239366)

**Comment by holdenhinkle** [comment]
Hi @RachalCassity ! I'm only following this from a high-level, but it looks like this PR needs to be merged first? https://github.com/department-of-veterans-affairs/vets-api/pull/19294

It got approvals 2 weeks ago but the author hasn't merged it.

cc @opticbob

**Comment by opticbob** [comment]
This PR was superseded by https://github.com/department-of-veterans-affairs/vets-api/pull/19294 which has now merged.  The changes I made to vets-json-schema are now available in vets-api.

This PR can be closed without merging.

**Pull request closed without merging**
