### PR TITLE
release-20161130a

### PR DESCRIPTION
**Pull request by aub**
Today's Production Release

### CODE REVIEW

**Comment by kreek** [comment]
LGTM :shipit: 🚀

**Comment by omgitsbillryan** [comment]
Did we not do a release yesterday?  My commit 302c7c212eb25e04ad3abedc4d29794c5742f0cb made it into master yesterday before 3pm EST, so I'm surprised to see it on the list of commits for todays release.

**Comment by jkassemi** [comment]
@omgitsbillryan - looks like we didn't get to merging https://github.com/department-of-veterans-affairs/vets-api/pull/575.

**Comment by jkassemi** [comment]
I'll pay more attention to the daily deployment. @aub's had to mention this in slack every day, which shouldn't be necessary.

**Pull request merged**
