### PR TITLE
Removing hard coded logout values -- ticket 56883

### PR DESCRIPTION
**Pull request by achievedaniel**
Summary

Remove hard-coded client_id field in Sign in Service `/logout` call

Related issue(s)
- department-of-veterans-affairs/va.gov-team#56883

Testing done
Logged in using a test account locally and logged out with no issues
Also changed the spec file to include the logout method

What areas of the site does it impact?
Authentication

Acceptance Criteria
When testing please ensure that the logging in and out through the front end is successful.

### CODE REVIEW

**Review by asg5704 — DISMISSED** [review]

**Review by bosawt — CHANGES_REQUESTED** [review]
Can you update the specs as well? There actually are some already written specs that I had just disabled so hoping you should just be able to re-enable those

**Comment by achievedaniel** [comment]
> Can you update the specs as well? There actually are some already written specs that I had just disabled so hoping you should just be able to re-enable those

I believe you are referring to this spec?

` context 'when client_id is not given', skip: 'will enable this once frontend adds client_id param' do
      let(:client_id_value) { nil }
      let(:expected_error_status) { :ok }
      let(:expected_error) { SignIn::Errors::MalformedParamsError }
      let(:expected_error_message) { 'Client id is not valid' }
      let(:logout_redirect_uri) { nil }

      it_behaves_like 'error response'
    end`

**Comment by bosawt** [comment]
> > Can you update the specs as well? There actually are some already written specs that I had just disabled so hoping you should just be able to re-enable those
> 
> I believe you are referring to this spec?
> 
> ` context 'when client_id is not given', skip: 'will enable this once frontend adds client_id param' do let(:client_id_value) { nil } let(:expected_error_status) { :ok } let(:expected_error) { SignIn::Errors::MalformedParamsError } let(:expected_error_message) { 'Client id is not valid' } let(:logout_redirect_uri) { nil } it_behaves_like 'error response' end`

Yup, exactly!

**Comment by bosawt** [comment]
One more thing, can you update the PR description for a little more information?

* Since it does technically change prod, there should be a 'testing done' section. In this case, you should be able to test successfully just by authenticating with sign in service and then logging out (if things didn't work, you'd see an error from that `client id is not valid`, if it did work you should log out successfully). Just make sure you authenticated with Sign in Service (you'll know this because there will be an `oauth=true` param on the sign in modal)
image
* Can you add 'What Areas of the Site does it impact' section and just add 'Authentication' as the description?
* Under Acceptance Criteria, can you add what you'd like a reviewer to specifically test? (In this case, prob just say to 'authenticate with sign in service and then log out and prove it didn't crash', something like that)

**Review by bosawt — APPROVED** [review]
Looks good!

Authenticated with Sign in Service, logged out, and confirmed `Client id is not valid` error did not occur and that user was successfully logged out

**Pull request merged**
