### PR TITLE
VACMS 18487 - remove /v1/facilities/va endpoint and tests

### PR DESCRIPTION
**Pull request by eselkin**
## Summary

- *This work is behind a feature toggle (flipper): NO*
- *Removes the controller for /v1/facilities/va and tests that use it*
- *v1 was hitting Lighthouse v0 which is no longer working*
- *Sitewide Facilities*

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18487

## Testing done
- No new code, removing old code that should not be maintained anymore. Not removing the libraries, just the controller stuff for facilities and facilities/va that were using v0 lighthouse.
- [x] *New code is covered by unit tests* N/A
- *Check that only /v1/facilities/\* are no longer working*

## Screenshots
None

## What areas of the site does it impact?
Affects the vfs-facilities endpoint that is no longer being maintained

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation) (removed swagger for removed controllers)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog (if applicable) (N/A)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

Check any unintended effects for non facilities routes

### CODE REVIEW

**Review by SnowboardTechie — DISMISSED** [review]
Not sure why those unrelated tests are failing, this all LGTM 👍🏻

**Comment by eselkin** [comment]
@RachalCassity we still have endpoints but under the /facilities_api/v2/ routes. They would hopefully be labeled with facility-locator, but will check.

**Comment by eselkin** [comment]
@RachalCassity Yes, the `modules/facilities_api/app/controllers/facilities_api/application_controller.rb` and `modules/facilities_api/app/controllers/facilities_api/v2/apidocs_controller.rb` use the service tag `facility-locator`

**Review by rmtolmach — APPROVED** [review]
👍

**Pull request merged**
