### PR TITLE
Moved prescription docs from old prescriptions-api

### PR DESCRIPTION
**Pull request by mphprogrammer**
Not sure where in the doc structure you wanted them.
@ayaleloehr @saneshark

### CODE REVIEW

**Comment by saneshark** [comment]
@ayaleloehr @mphprogrammer do we want to open this PR up against master? My understanding was that master was to only be used for priority stuff that has to go in before 11/11

**Comment by mphprogrammer** [comment]
Agreed, I would think it best to leave it be for now. I'll put a do not merge on the title.

**Comment by saneshark** [comment]
LGTM, we can change it to resemble secure messaging more but we will likely look to replace with more robust solution such as slate which also supports Markdown

**Comment by ayaleloehr** [comment]
@mphprogrammer isn't this missing the main file, found here: https://github.com/department-of-veterans-affairs/prescriptions-api/blob/master/api-doc.md

This seems to include only the examples but not that file.

**Comment by saneshark** [comment]
LGTM, @ayaleloehr want to give it a final look before merge?

**Comment by ayaleloehr** [comment]
LGTM. At some point we're going to need consistency in our documentation across vets-api, but this PR at least gets the Rx docs in the right repo, so is better than without it. :)

Thanks @mphprogrammer !

**Comment by mphprogrammer** [comment]
@ayaleloehr Merging PR when master upmerged.

**Pull request merged**
