### PR TITLE
[SIMPLE_FORMS] fix: update attachment handling to account for path names instead of objects

### PR DESCRIPTION
**Pull request by pennja**
## Summary

- This work updates the attachment handling logic to account for the correct data type

## Related issue(s)

- [Form Submission Remediation - Test remediation process and make updates in accordance with findings](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1956)

## Testing done

- [x] This new logic is covered by unit test coverage

## Requested Feedback

Any

### CODE REVIEW

**Review by Thrillberg — DISMISSED** [review]
Looks good! Are attachments already coming in as file paths rather than guids?

**Comment by pennja** [comment]
> Looks good! Are attachments already coming in as file paths rather than guids?

@Thrillberg Yessir, that's something I missed originally. Turns out that the `get_attachments` method for VBA2010207 returns an array of temp file path's to generated attachments instead of the attachment objects themselves

**Comment by pennja** [comment]
> @pennja How do you know this works if you haven't tested it?
> 
> Also, I can't open the issue you linked and I can't find it in GitHub. Can you link to a different format or paste the ticket description?

@rmtolmach I had tested it locally and was hesitating on adding test coverage because this specific test suite was causing flaky errors in the build pipeline. I went ahead and updated the entire spec file to alleviate the issues. Looks like someone moved my linked ticket which deleted that link. I've updated that link now.

**Review by rmtolmach — APPROVED** [review]
Thanks for the tests! I noticed argocd access was mentioned in your ticket. The template to request access is linked [in this doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Access) if you need it.

**Comment by pennja** [comment]
> Thanks for the tests! I noticed argocd access was mentioned in your ticket. The template to request access is linked [in this doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Access) if you need it.

Thank you @rmtolmach!!

**Pull request merged**
