### PR TITLE
Mobile: Update docs to match reality

### PR DESCRIPTION
**Pull request by Tonksthebear**
## Summary
Updates mobile docs to reflect reality

## Related issue(s)
- [department-of-veterans-affairs/va.gov-team#7561](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7561)

## Testing done
None necessary

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
Docs

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by Tonksthebear** [comment]
I noticed `eCheckinAllowed` was still in the docs even though it was removed from our serializer/model. Was that intentional? I removed it from the docs in case it was an oversight

**Review by kpethtel — CHANGES_REQUESTED** [review]
I think I wrote the ticket too quickly and didn't include enough detail because I wasn't entirely sure what all the differences were so I left it vague, but while reviewing this I remembered that it had something to do with the checkin windows. In `modules/mobile/docs/schemas/Appointments.yml` you'll see that the `required` section contains these:

```
      - minutesCheckinEarlyWindow
      - minutesCheckinLateWindow
```

I believe those are leftover from Andrew's initial implementation and never got updated. They should be replaced with `checkinWindow`.

**Comment by Tonksthebear** [comment]
> I think I wrote the ticket too quickly and didn't include enough detail because I wasn't entirely sure what all the differences were so I left it vague, but while reviewing this I remembered that it had something to do with the checkin windows. In `modules/mobile/docs/schemas/Appointments.yml` you'll see that the `required` section contains these:
> 
> ```
>       - minutesCheckinEarlyWindow
>       - minutesCheckinLateWindow
> ```
> 
> I believe those are leftover from Andrew's initial implementation and never got updated. They should be replaced with `checkinWindow`.

I thought that was a fancy way of writing what's required because the actual example is with `checkinWindow`. The documentation also shows `checkinWindow` so I think it is working properly?

**Comment by kpethtel** [comment]
> > I think I wrote the ticket too quickly and didn't include enough detail because I wasn't entirely sure what all the differences were so I left it vague, but while reviewing this I remembered that it had something to do with the checkin windows. In `modules/mobile/docs/schemas/Appointments.yml` you'll see that the `required` section contains these:
> > ```
> >       - minutesCheckinEarlyWindow
> >       - minutesCheckinLateWindow
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe those are leftover from Andrew's initial implementation and never got updated. They should be replaced with `checkinWindow`.
> 
> I thought that was a fancy way of writing what's required because the actual example is with `checkinWindow`. The documentation also shows `checkinWindow` so I think it is working properly?

@Tonksthebear i see what you mean about the docs being correct, but if you look closer, you'll see that it does not say `checkinWindow` is required. It shows checkinWindow because it's in the list of properties, but it doesn't say it's required because it's not in the required list. So these two are just required properties are just junk because they don't match up with anything in the properties list. And the checkinWindow is a required part of the schema, so we should mark it as such. 

image

**Comment by Tonksthebear** [comment]
@kpethtel I see your concern. I just updated it accordingly

**Review by kpethtel — APPROVED** [review]
👍

**Review by aherzberg — APPROVED** [review]
LGTM

**Pull request merged**
