### PR TITLE
Mobile: Add extra specs for access rights to various features

### PR DESCRIPTION
**Pull request by Tonksthebear**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary
This adds additional testing to various specs in order to test access policies

## Related issue(s)
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7993

## Testing done
None, no code changes

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by stevenjcumming — CHANGES_REQUESTED** [review]
@Tonksthebear please bundle with the license for Sidekiq Enterprise to add back the `sidekiq-ent` and `sidekiq-pro` gems

Step 3 under Base Setup:
https://github.com/department-of-veterans-affairs/vets-api?tab=readme-ov-file#base-setup

**Comment by Tonksthebear** [comment]
> @Tonksthebear please bundle with the license for Sidekiq Enterprise to add back the `sidekiq-ent` and `sidekiq-pro` gems
> 
> Step 3 under Base Setup: https://github.com/department-of-veterans-affairs/vets-api?tab=readme-ov-file#base-setup

Whoops, didn't mean to make changes to the Gemfile.lock. Sorry!

**Review by kpethtel — CHANGES_REQUESTED** [review]
Can you please remove all the uses of `allow_any_instance_of` here? I spent quite a bit of time removing all of those stubs when I switched the specs to use SIS and I don't want to see us falling back to it unnecessarily. It really shouldn't be necessary anymore, except maybe in some rare cases where the factories are difficult to work with because the user model uses other models, like identity and mpi profile. The one case I see here that might be slightly atypical are the `loa` stubs, which I think you can fix by doing `sis_user(:loa1)`. If you have any trouble with these, just LMK and I can try to help. 

I see that Andrew recently added some other user stubs. A couple of those are for more complex use cases, and now that I see them I will try to change them in another PR.

**Review by stevenjcumming — APPROVED** [review]

**Review by kpethtel — APPROVED** [review]
LGTM. Thanks for switching over to factories.

**Pull request merged**
