### PR TITLE
Update settings.yml

### PR DESCRIPTION
**Pull request by kylesoskin**
Editing my flipper email

### CODE REVIEW

**Review by rjohnson2011 — COMMENTED** [review]
Is there a reason why you're changing the settings from your work email to a personal gmail account? I haven't seen this done before.

**Comment by kylesoskin** [comment]
@rjohnson2011 This is due to the requirement that the account be a "verified" account. 

Prior to even working at this job I already had a "verified" id.me account, that is tied to my SSN. So I cannot create any other "verified" id.me accounts.

So either I need to add a personal email in here, or figure out a way to get my adhoc email associated with my id.me account. Since it is possible I use my id.me account for other things, that is not what I want to do.

**Comment by kylesoskin** [comment]
I also cannot add my work email to my id.me since I already created an id.me account with it as well (that I cannot verify because my SSN is already tied to my other account). But I may be able to remove it from that account, and then put it on my personal account, but I would rather not.

**Comment by kylesoskin** [comment]
I think I was able to add the work email to my personally verified id.me account and make it primary. I will confirm it works, then close this PR

**Pull request closed without merging**
