### PR TITLE
update appointment date range

### PR DESCRIPTION
**Pull request by aherzberg**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary
It was found that VAOS defaults appointments index by looking 390 days in the future while we only look 1 year in the future. To help create a consistent experience, this updates ours 390 days as well.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/4903

## Testing done
specs 

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
Mobile only 

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by kpethtel — APPROVED** [review]
LGTM

**Review by kpethtel — CHANGES_REQUESTED** [review]
Upon second thought... the one other thing you need to do is change test descriptions, which currently say "one year from now".

**Comment by aherzberg** [comment]
> Upon second thought... the one other thing you need to do is change test descriptions, which currently say "one year from now".

good catch. fixed

**Review by kpethtel — APPROVED** [review]
👍

**Pull request merged**
