### PR TITLE
Mobile: Update Flipper.enable to Flipper.enable_actor when necessary in specs

### PR DESCRIPTION
**Pull request by Tonksthebear**
## Summary
Update Flipper.enable to Flipper.enable_actor when necessary in specs

## Related issue(s)
- [department-of-veterans-affairs/va.gov-team#6979](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6979)

## Testing done
Existing tests cover changes

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
None

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by kpethtel — APPROVED** [review]
👍

**Review by aherzberg — CHANGES_REQUESTED** [review]
Looks like there's another instance of a user flipper in `modules/mobile/spec/request/claims_decision_request_spec.rb` and `modules/mobile/spec/request/legacy_claims_document_upload_spec.rb`

**Comment by Tonksthebear** [comment]
Huh, it seems I have a git issue on hand... I changed those locally and it's not showing any changes, yet this pr doesn't show those

**Comment by Tonksthebear** [comment]
@aherzberg I think you were checking on an outdated branch. Master has those already changed

**Review by aherzberg — APPROVED** [review]
yeah, looks like I was on an old branch.

**Pull request merged**
