### PR TITLE
Api 24646 handling bgs error no pid

### PR DESCRIPTION
**Pull request by stiehlrod**
## Summary

- Identify and address response when upstream service can not find a participant id

## Related issue(s)
- [API-24646](https://vajira.max.gov/browse/API-24646)

## Testing done

- rswag
- Postman, set `pid` to "0"
   received nil, added a catch for nil

## What areas of the site does it impact?
vets-api/modules/claims_api intent_to_file

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by FonzMP** [comment]
these changes are to the ITF controller. This ticket was in respect to the claims index for v2. With that in mind, we should look to find a way to handle this in any scenario, so maybe a shared method in the v2 app controller that we can utilize across the various controllers?

**Review by mchristiansonVA — APPROVED** [review]
Pulled down branch and tested locally, setting participant ID passed to BGS `find_intent_to_file_by_ptcpnt_id_itf_type_cd` to "0" in IntentToFileController and calling /intent-to-file/:type using Postman. Confirmed expected error message and HTTP 404 returned.

**Comment by FonzMP** [comment]
referring to the original ticket and sentry error, and I'm still seeing a 500 because it is failing during the call to BGS in `/claims` (`find_benefit_claims_status_by_ptcpnt_id`). Using `1012829910V765228`, we get a 500 because it can't find an individual via the provided participant ID.

**Comment by FonzMP** [comment]
We should add this to the `show` functionality at some point as well, but since this is an index reported issue, let's call this good.

**Review by FonzMP — APPROVED** [review]
:shipit:

**Pull request merged**
