### PR TITLE
SA-58801 email phone duplicate

### PR DESCRIPTION
**Pull request by s-caso**
## Summary
- Sets up route and service for handling the call to check for duplicate email or cell phone values (described below)

IF the email applicant enters already exists on an application the following will occur:

On the contact information page:

Both prefilled mobile phone and email information will be checked for duplicates.
Users who enter in a new valid USA or Puerto Rico mobile number in the field will also be checked for duplicates
A claimant will be notified upon entry if duplicate mobile number or email address already exists within the claimant service database on the "Contact Information" section in MEB
Custom phone number component input component is created that is either prefilled with the users mobile phone information from their VA profile and/or is a field where users can enter their valid 10 digit USA or Puerto Rico mobile phone number
The mobile phone field is an optional field
Custom email input component is created that is either prefilled with the users email from their VA profile and/or is a field where users can enter a valid email address
The email field is a required field
Input values are checked for duplicates and the custom components are wired up components to global state where the return value of the data (whether or not it is a duplicate value for an existing claimant in DGI) will be sent back based on mobile phone and/or email on the application.  
IF only a duplicate email is found a warning message pop-up will appear and say: 
"We have this email on file for another person with education benefits"
"This will impact how we":
"Contact you if we have questions about your application"
"Tell you important information about your benefits" 
"Prompt you to verify your enrollment"
Warning will be dynamic and will only mention if claimant has duplicate email or mobile or both 
Claimant can continue application if no change to mobile phone or email address after message appears
A "Back" button and a "Continue" button will be at the bottom of the warning alert. The back button will click users out of the warning and the "continue" button will advance them to the next page of the form
Users can continue on even with duplicate mobile phone and/or email address
On the contact preference page:

Only non-duplicate contact methods will appear as options under contact method "How should we contact you if we have questions about your application?"
Claimant will not have contact preference question appear (second question on page) if they have both duplicate mobile phone number and duplicate email entered, only the warning alert will be shown.
contact preference will appear if user has either only a duplicate mobile phone number or only a duplicate email. The contact preference question will not appear if user has duplicates for both mobile phone and email.
Contact preference question scenarios: "Would you like to receive text message notifications about your education benefits?"

If duplicate data is detected for only email:
The following warning message will appear "You can't choose to get email notifications because your email is on file for another person with education benefits"
"Learn more about the Enrollment Verifications"
"Learn more about the Enrollment Verifications" will be hyperlinked to https://www.va.gov/education/verify-school-enrollment
 The change notification method will be hyperlinked to redirect claimants to the notification preference section of the MEB application

## Related issue(s)
[- department-of-veterans-affairs/va.gov-team#SA-58567
](https://jira.np.afsp.io/browse/SA-58567)- *Link to ticket created in va.gov-team repo*
[- department-of-veterans-affairs/va.gov-team#SA-53641
](https://jira.np.afsp.io/browse/SA-53641)- *Link to ticket created in va.gov-team repo*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by bradbergeron-us — APPROVED** [review]

**Comment by ryan-mcneil** [comment]
@s-caso Hi, is this ready to go? It was kind of hard for us to track, as review was requested weeks ago, yet checks weren't passing until perhaps today? It would really help us out if a) PRs are left in a draft state until ready, and b) larger PRs (more than just a couple obvious lines) have approval from a teammate. I see you did request review from someone else (thanks!!) but have since added a few commits. Lastly, feel free to create a support issue if you've been waiting more than a day or 2 and we somehow missed it, and it'll become a priority. Thank you!

**Comment by s-caso** [comment]
@ryan-mcneil Hello!  Yeah this is ready to be reviewed.  Will do as far as keeping it in draft.

**Comment by ryan-mcneil** [comment]
@s-caso I hadn't gotten far enough into the PR before, but can we get specs written for the applicable files here (at least the controller and service, unless you think something else would be needed for code coverage). Thanks!

**Comment by s-caso** [comment]
@ryan-mcneil Added specs and cleaned up rubocop issues.  Ready for review when you have some time.

**Comment by ryan-mcneil** [comment]
@s-caso for future reference, please raise tickets in #vfs-platform-support, as I'm no longer on the support team, and all approving engineers will be rotating through the position.

Please have someone from your team approve this first (this a standard requirement for approvals moving forward).

Also, please note that 90% of tags/mentions in GH will get lost in the noise, as we get hundreds of emails/notifications per day. Please use slack to bump the support team once approvals have been received. Thank you!

**Review by bradbergeron-us — APPROVED** [review]

**Review by holdenhinkle — APPROVED** [review]
LGTM!

**Pull request merged**
