### PR TITLE
Implement fallback for when Intent API is down

### PR DESCRIPTION
**Pull request by Thrillberg**
## Summary
This PR implements a fallback while we continue figuring out why the Intent API is returning `422`s. This will redirect those submissions back to the PDF -> Central Mail route rather than try the Intent API.

## Related issue(s)
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/86870

## Testing done

- [X] *New code is covered by unit tests*

### CODE REVIEW

**Review by tblackwe — DISMISSED** [review]

**Comment by tblackwe** [comment]
concept looks good, just some linting to cleanup

**Review by LindseySaari — DISMISSED** [review]

**Comment by Thrillberg** [comment]
**!Alert!** I'm skipping the test I wrote for this. It's been failing on CI but passing for me locally. I don't know why. But I want to merge and get this deployed asap since we basically have a whole form down right now. Happy to work through ideas on how to make CI pass, though! 😄

**Review by tblackwe — APPROVED** [review]
LGTM

**Review by pennja — APPROVED** [review]
Looks good, great work! 👍

**Pull request merged**
