### PR TITLE
production deploy

### PR DESCRIPTION
**Pull request by lihanli**
we want to start testing the daily report emails on production

### CODE REVIEW

**Comment by plusjeff** [comment]
If there are any changes that depend on vets-website modifications, let's hold until we have the clear from @crwallace on homepage changes to come.

**Comment by plusjeff** [comment]
Adding in the tech leads have changes in this PR to sign-off, including @ayaleloehr @austin-martinez @robbiethegeek @akainic . If everyone is OK with these changes going in, this merge is fine by me.

**Comment by robbiethegeek** [comment]
I think this looks ok with me, would like to have @crwallace signoff since there will be things in vets-website that will be affected. :shipit:

**Comment by akainic** [comment]
I'm good with anything education related.

**Comment by plusjeff** [comment]
Cool - will add @crwallace to the assignees list.

**Comment by plusjeff** [comment]
If there are things in here that require updates to `vets-website`, can those be called out via a comment? That'll help us know when `vets-website` is in line with these changes.

**Comment by robbiethegeek** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/461/commits/3ac2d1237b589d9089e96e5008d1c944786520c4 requires vets-website

**Comment by robbiethegeek** [comment]
pretty sure that https://github.com/department-of-veterans-affairs/vets-api/pull/461/commits/4e9b05a8601ae488b7d945ae235f42fc22c84cdc requires vets-website

**Comment by crwallace** [comment]
`3ac2d12` looks good and `4e9b05a` is not integrated in to `vets-website` yet for logout but it will be.

**Comment by robbiethegeek** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/461/commits/2d8f2f49f62c7d572002a518f0b153f0fba3cb9f is the backend for SLO, session destruction and MHV audit logout but the frontend is backlogged for the moment

**Comment by austin-martinez** [comment]
Look good for claim status

**Comment by ayaleloehr** [comment]
A glance at the commits looks fine from here. 

There will be more Facility Locator changes that @patrickvinograd is working on, but we don't have our API sources finalized yet so can't get those in until tonight or tomorrow.

**Comment by plusjeff** [comment]
Thanks for the review everyone! I'll leave @crwallace and @robbiethegeek on as assignees so that we know when this can go live.

**Comment by robbiethegeek** [comment]
I am ok with this PR getting merged in! LGTM

**Comment by crwallace** [comment]
LGTM!

**Comment by plusjeff** [comment]
In the future, let's let the DevOps team merge. If there were configuration changes required, this is the sort of thing that could break production.

**Pull request merged**
