### PR TITLE
84332: Update vets-json-schema version and SavedClaimStatusUpdaterJob tests

### PR DESCRIPTION
**Pull request by dfong-adh**
## Summary

This replaces outdated schemas being used for schema validation for Decision Review V2 SHOW endpoint responses.

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/84332

## Testing done

- [x] *New code is covered by unit tests*
`SchemaValidationErrors` would be raised when processing V2 response values from the SHOW endpoints.
This was tested locally and with spec tests

## What areas of the site does it impact?
This impacts the DecisionReviewV1 service SHOW endpoints for HLR, NOD, and SC, currently only being used for form status updater jobs.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by shaunburdick — APPROVED** [review]
```json
{
  "type": "string",
  "const": "LGTM"
}
```

**Comment by RachalCassity** [comment]
I noticed that [notice_of_agreements](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/swagger/swagger/v1/schemas/appeals/notice_of_disagreement.rb#L28) still fetches `NOD-SHOW-RESPONSE-200_V1 `. Does this need to be updated as well?

**Comment by dfong-adh** [comment]
> I noticed that [notice_of_agreements](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/swagger/swagger/v1/schemas/appeals/notice_of_disagreement.rb#L28) still fetches `NOD-SHOW-RESPONSE-200_V1 `. Does this need to be updated as well?

Thanks for catching that, I've updated the associated swagger schema files accordingly.

**Comment by RachalCassity** [comment]
Is there another pull request to remove the unused V1 vcr?

**Review by RachalCassity — APPROVED** [review]

**Pull request merged**
