### PR TITLE
arf.93199 clean up ARP engine

### PR DESCRIPTION
**Pull request by gabezurita**
## Summary
Quick PR to clean up a few straggling items before delivering the ARP engine:

## Related issue(s)
https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/93199

## Testing done
specs

## What areas of the site does it impact?
ARP

### CODE REVIEW

**Review by nihil2501 — APPROVED** [review]
LGTM

**Comment by gabezurita** [comment]
@nihil2501, I made a few more changes. Re-requesting review!

**Review by nihil2501 — CHANGES_REQUESTED** [review]
This isn't leveraging existing `vets-api` error handling to the extent that I would consider it production code. Are we aiming to have production code or at least express that we are on some path to production code?

I see that we get [`ExceptionHandling`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/concerns/exception_handling.rb) from inheritance which makes use of Sentry and  Datadog. The only other application I see doing generic error logging is [ask_va_api](https://github.com/department-of-veterans-affairs/vets-api/blob/b818f92bfe34ccbc374db9feb0f26b2fa329481f/modules/ask_va_api/app/controllers/ask_va_api/application_controller.rb#L9-L15) and [not in every controller](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-api+handle_exceptions+path%3A%2F%5Emodules%5C%2Fask_va_api%5C%2Fapp%5C%2Fcontrollers%5C%2Fask_va_api%5C%2Fv0%5C%2F%2F&type=code). Also I see that there are some library conveniences for structured logging that is coupled to Sentry:
- [generic concern](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/sentry_logging.rb)
- [controller concern](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/concerns/sentry_controller_logging.rb)

**Review by nihil2501 — APPROVED** [review]
Not aiming for production code yet.

**Comment by gabezurita** [comment]
> Not aiming for production code yet.

Agreed!

The `handle_exceptions` addition is so we can get clearer Datadog errors that point to ARP in the case of 500 internal server errors:
[https://github.com/department-of-veterans-affairs/vets-api/blob/dadf81ce4ae96f3d44[…]lers/accredited_representative_portal/application_controller.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/dadf81ce4ae96f3d4474b8c8e574ebd9eb461dc0/modules/accredited_representative_portal/app/controllers/accredited_representative_portal/application_controller.rb#L16-L21)
[https://github.com/department-of-veterans-affairs/vets-api/blob/dadf81ce4ae96f3d44[…]ec/requests/accredited_representative_portal/v0/form21a_spec.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/dadf81ce4ae96f3d4474b8c8e574ebd9eb461dc0/modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/form21a_spec.rb#L104-L107)

It's more for staging troubleshooting on the way to prod

**Comment by gabezurita** [comment]
@department-of-veterans-affairs/backend-review-group - this is ready for your review!

**Review by ryan-mcneil — APPROVED** [review]

**Comment by ryan-mcneil** [comment]
@gabezurita I think I'll have to override and merge this one, so please ping me when you're ready for me to do so. thanks!

**Comment by gabezurita** [comment]
> @gabezurita I think I'll have to override and merge this one, so please ping me when you're ready for me to do so. thanks!

Ready when you are!

**Comment by gabezurita** [comment]
> @gabezurita I think I'll have to override and merge this one, so please ping me when you're ready for me to do so. thanks!

Thanks @ryan-mcneil! Ready when you are!

**Comment by gabezurita** [comment]
> > Not aiming for production code yet.
> 
> Agreed!
> 
> The `handle_exceptions` addition is so we can get clearer Datadog errors that point to ARP in the case of 500 internal server errors:
> 
> * [https://github.com/department-of-veterans-affairs/vets-api/blob/dadf81ce4ae96f3d44[…]lers/accredited_representative_portal/application_controller.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/dadf81ce4ae96f3d4474b8c8e574ebd9eb461dc0/modules/accredited_representative_portal/app/controllers/accredited_representative_portal/application_controller.rb#L16-L21)
> * [https://github.com/department-of-veterans-affairs/vets-api/blob/dadf81ce4ae96f3d44[…]ec/requests/accredited_representative_portal/v0/form21a_spec.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/dadf81ce4ae96f3d4474b8c8e574ebd9eb461dc0/modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/form21a_spec.rb#L104-L107)
> 
> It's more for staging troubleshooting on the way to prod

Update: Overriding handle_exceptions did the trick, and we're now seeing the error we were expecting in staging:
image
https://vagov.ddog-gov.com/apm/error-tracking?query=service%3Aaccredited-representative-portal%20env%3Aeks-staging&fromUser=false&issueId=5cf40b0c-786a-11ef-841c-da7ad0900007&refresh_mode=sliding&source=all&from_ts=1727115367894&to_ts=1727118967894&live=true

**Pull request merged**
