### PR TITLE
MhvAccount va_patient method

### PR DESCRIPTION
**Pull request by patrickvinograd**
The logic is right, and the tests are pretty comprehensive, but not attached to either. In particular:
- initializing constant from settings seems off
- test cases could definitely be DRYer 

Open to suggestions for how, otherwise I'll look at this with fresh eyes tomorrow morning.

### CODE REVIEW

**Comment by saneshark** [comment]
I think this is fine, can revisit later if necessary. Not entirely convinced that Settings.yml is best the place for the constants though. MHVAccount is good enough and it will be easier to change / modify if needed.

**Comment by patrickvinograd** [comment]
Yeah, I'm gonna go with the YAGNI approach and pull the unnecessary config out, along with the list of ranges stuff, esp. since we know there are some users we can use in staging.

**Comment by patrickvinograd** [comment]
However as soon as I merge this and the other PR goes in, our standard test users (+261 - +264) will no longer have access because none of them are VA patients. I think we need to put in a request to have a VHA identifier added for all of them.

**Comment by saneshark** [comment]
Ahh, good catch on that last point. Would we have to make that request to MVI to add the VHA identifiers? Might be something MHV can do for us too (they have the ability to push to MVI).

**Comment by patrickvinograd** [comment]
I think we should go through MHV-Liana - I don't know if it's that something needs to get added to VistA and from there to MVI, or just MVI, or what. 

We can also add identifiers to mock_mvi_responses.yml in the kudos-launch branch to unblock this on dev.

**Comment by patrickvinograd** [comment]
Added phony patient IDs to mock MVI for +261 through +264 users. Merging to kudos-launch

**Pull request merged**
