### PR TITLE
Support for form 4142 for supplemental claims, plus additional logging

### PR DESCRIPTION
**Pull request by kylesoskin**
## Description of change
This change add supporting code to process the optionally included "form4142" portion of data provided with a supplemental claim submission. 

It takes the provided data and stamps it onto a PDF before forwarding to Central Mail.

This feature is not released or enabled yet so this should not have much impact, however I would like this merged so I can refactor further later in more PRs that require this to be in place. 

### Related
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1075
https://github.com/department-of-veterans-affairs/devops/pull/12253

## Things to know about this PR
This also adds logging and performance tracking (toggleable via the settings). The related PR with that setting added is linked above.

### CODE REVIEW

**Review by holdenhinkle — COMMENTED** [review]
@kylesoskin Are you going to write tests against the code in this PR?

**Comment by kylesoskin** [comment]
> @kylesoskin Are you going to write tests against the code in this PR?

@holdenhinkle 

I am yes. I have some written that just need committed and pushed an another 1 or 2 I would like to write tomorrow. I can put this back into draft state until then.

**Comment by kylesoskin** [comment]
Hi @holdenhinkle , test case has been added here: 

https://github.com/department-of-veterans-affairs/vets-api/pull/10990/files#diff-0e85fbe3a6d5957a85ced680398008635bf95da2e53f0b8054c55aeb0a04f6e4R53

It is, as expected, even more lines than the limit now.

**Review by holdenhinkle — APPROVED** [review]
Nice code coverage. Thanks for that.

LGTM!

**Pull request merged**
