### PR TITLE
add puma statsd plugin

### PR DESCRIPTION
**Pull request by tskinn**
## Description of change
This PR provides a solution to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14065. Using the [puma statsd plugin](https://github.com/yob/puma-plugin-statsd) will give use more insight as to the state of puma.

The puma server provides several metrics but we currently do not have any insight into them. We run a statsd-exporter along with vets-api to get various metrics from vets-api and the instance its running on into prometheus. The purpose of the puma statsd plugin is to fill that gap and get those puma metrics into promtheus via the statsd-exporter.

The changes in this PR include adding puma-plugin-statsd to the Gemfiles and creating a simple config file for puma to enable the plugin.

The changes in this PR should not go out before https://github.com/department-of-veterans-affairs/devops/pull/3497. It contains necessary config/deploy changes for this PR to work.

## Testing done

To verify this is working, the puma plugin should be exporting metrics to statsd.

You can test this change locally by modifying the docker-compose.yml file:
Add another container that runs statsd. For example:
```
  statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
```

and then modify the vets-api container so that it links with the statsd container and has a few extra environment variables set like so:

```
  vets-api:
    build:
      context: .
      args:
        exclude_sidekiq_ent: "${EXCLUDE_SIDEKIQ_ENTERPRISE:-false}"
        sidekiq_license: "${BUNDLE_ENTERPRISE__CONTRIBSYS__COM}"
    image: "vets-api:${DOCKER_IMAGE:-latest}"
    volumes:
      - .:/src/vets-api:cached
      - "../vets-api-mockdata:/cache"
    ports:
      - "3000:3000"
    environment:
      "Settings.database_url": "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-vets_api_development}?pool=4"
      "Settings.saml.cert_path": "/src/vets-api/config/certs/vetsgov-localhost.crt"
      "Settings.saml.key_path": "/src/vets-api/config/certs/vetsgov-localhost.key"
      "Settings.redis.host": "redis"
      "Settings.redis.port": "6379"
      "Settings.binaries.clamdscan": "clamscan" # Not running a separate process within the container for clamdscan, so we use clamscan which requires no daemon
      "Settings.statsd.host": "statsd"
      "Settings.statsd.port": "8125"
      POSTGRES_HOST: "${POSTGRES_HOST:-postgres}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      STATSD_HOST: "statsd"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
      - statsd
```

Once you run `make up` and the containers are running you can verify that the statsd puma plugin is working by querying statsd to see if the puma metrics are being reported by running the following command:
```
echo "gauges" | nc 127.0.0.1 8126
```
This should cause a list of metrics to be printed to the screen. The list should include several metrics labeled `puma.*`.

*Statsd has an [admin tcp interface](https://github.com/etsy/statsd/blob/master/docs/admin_interface.md) that you can send commands to and that is exactly what we are doing above. You will need netcat installed for this command to work.

## Acceptance Criteria (Definition of Done)
vets-api functions as normal and exports puma metrics to statsd.

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by annaswims** [comment]
add `# frozen_string_literal: true` on the first line of `config/puma.rb` with a blank line after to make rubocop happy.  Not sure why it doesn't show in the test output, but running `rubocop` locally shows that that is the issue.

**Comment by annaswims** [comment]
also, if you run `overcommit overcommit --install --sign` you'll get some git hooks that run checks.

**Comment by annaswims** [comment]
Can you confirm that this is how we start the server in prod?  https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/vets-api/tasks/main.yml#L115

In development, all instructions say to start the server with `rails server` which I don't believe will read what's in `config/puma.rb`

**Comment by tskinn** [comment]
This is the corresponding PR for the necessary changes in devops https://github.com/department-of-veterans-affairs/devops/pull/3497

**Pull request merged**
