### PR TITLE
Add Processing Facility mapping for Pension/Burial

### PR DESCRIPTION
**Pull request by markolson**

### CODE REVIEW

**Comment by lihanli** [comment]
is this used by only background jobs? maybe we can put it in a cached variable to reduce memory usage

**Comment by markolson** [comment]
@lihanli what do you mean by cached? As a constant, it should just be loaded once when the app starts up in production - I'd rather do that than read it each request or setup and populate a table just for this lookup.

**Comment by lihanli** [comment]
if it used only by background jobs and not by the main api server, then you can put it into a variable `@foo ||= hash` and reduce the main api server memory usage

**Comment by markolson** [comment]
It will be used by the controller as well to return the mailing address (PO Box, really) on a successful submission.

**Pull request merged**
