### PR TITLE
API 000 Veteran verification removal

### PR DESCRIPTION
**Pull request by dmekala-va**
## Summary

- This PR is to remove veteran verification files and rspecs in preparation for deleting the openId_application controller. These files use the openid_application controller therefore the goal is to remove all files that include reference to it and ultimately remove the file. 
- Lighthouse Team Pivot!

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#[API-20648]
- https://jira.devops.va.gov/browse/API-20648
- This relates to the above links and in preparation for the story

## Testing done

- Deleting rspecs and relevant vcr cassettes not used anymore

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by rmtolmach** [comment]
@dmekala-va Are there follow-up issues to remove the rest of the files in the veteran verification module?

@ me once you get a review from a teammate and I can override the Danger check.

**Comment by dmekala-va** [comment]
> @dmekala-va Are there follow-up issues to remove the rest of the files in the veteran verification module?
> 
> @ me once you get a review from a teammate and I can override the Danger check.

Only deleting files that relate to the openid_applicationController so not all files have to go, I believe. Can double check, thank you!

**Comment by RachalCassity** [comment]
Is this PR still relevant or can this PR be closed?

**Comment by dmekala-va** [comment]
> Is this PR still relevant or can this PR be closed?

This PR is still relevant but waiting for some dependencies to get resolved first so can be closed for now and reopened later.

**Pull request closed without merging**
