### PR TITLE
Pessimistic Gemfile Versioning #207

### PR DESCRIPTION
**Pull request by saneshark**
For now this PR is just reorganizing Gemfile for clarity of intent into subcategories identified by comments.

Some of the gems in the subcategories specify in their README to use pessimistic versioning and those should always have them. In addition, I have attempted to identify what I characterize as core libraries. Ones that could introduce hard to debug issues and are somewhat notorious for causing issues when not versioned.

I will be going through each and every README for these gems and making sure we are following the best practices for how to use the gem in Gemfile.

This will fix: https://github.com/department-of-veterans-affairs/vets-api/issues/207

### CODE REVIEW

**Comment by saneshark** [comment]
OK folks, I'm going to push up changes after I did a `bundle update` just so everyone can see and we can comment -- don't panic and think I'm trying to necessarily introduce these changes before 11/11, but I want everyone to see what's changed in the diff and for us to have a discussion. I can roll back the Gemfile.lock to current master if we don't want to do this.

**Comment by saneshark** [comment]
Other than byebug and mime-types nothing actually had a Major release, but a number of them had minor releases, and quite a few had tiny releases.

Interestingly mime-types dropped down to an older version of the gem because of the dependency on govdelivery-tms in which they hardcoded to < 3.0 for whatever reasons, I'll have to look into that.

Curious to hear thoughts on whether or not we should do this update or not, at the very least I would think it would be nice to get brakeman in there because its not a production dependency.

**Comment by aub** [comment]
I'm not sure what we have to gain from doing this, especially so close to the release. I always want to get the newest updates as well, but AFAICT there's not any real reason to do so here.

**Comment by saneshark** [comment]
Agreed, but just wanted to get another set of eyes on what **would** change. I'll revert the Gemfile.lock to master.

As for the pessimistic gem versioning specifically though, issue #270 has the veterans-day tag on it so I want identify the the gems we want to have versioning and get that merged.

**Comment by omgitsbillryan** [comment]
Looks like the gems have been moved around, but I cant quite tell which ones were added or removed

**Comment by saneshark** [comment]
@omgitsbillryan nothing has been removed, only moved. The goal was to first organize the Gemfile, then identify the candidates that need pessimistic versioning.

**Comment by saneshark** [comment]
OK, I'm all done going through the Gemfile. I believe all of the gems that should have pessimistic versioning now have it, further I've organized the gems in the Gemfile into sections.

Moving forward, when we encounter a new gem being introduced in code review, we should double check the readme for the gem and make sure it is being properly versioned.

Ready for review.

**Comment by aub** [comment]
I don't really want to open a can of worms here, but what's the point of the pessimistic versioning? My strategy has been to never lock a gem to a version unless you have some specific reason why it's important to use that version, and then add a comment about why in the Gemfile. Since the gems have to be bumped manually, it's not like there's some danger of them accidentally being upgraded.

**Comment by saneshark** [comment]
@aub I'm 100% with you on that. For what it's worst, the pessimistic version that's being added here is ONLY being done for gems that suggest it explicitly within their README.

**Comment by aub** [comment]
Ok, well that's better. Is it your opinion that these gems recommending locking to a specific version are doing so for a good reason? I think people are accustomed to putting the versions in their Gemfile even though there's no good reason to, and the same logic extends to the README files for gems. I looked up the Redis gem, and they don't give any good reason for locking the version, and I can't think of a good reason why a gem would do so. In the case of Redis, the README would have you two versions behind, and I just can't think of why they would suggest that unless the 3.3 series is broken and has been since April of last year.

**Comment by saneshark** [comment]
It is possible that they forgot to update their README. I'll grant that, but in the case of redis, since it relies on the backend service being available it might be a good idea to go ahead and include versioning per the instructions and we can update alongside any changes to the underlying service when it comes time to verify if the gem supports those new changes.

WillPaginate is probably not in the same boat, but I don't really care if they add new features as those new features will probably be more suited to someone using its view helpers in some form. The README recommends the versioning, and I say we let it ride.

I think we could have quarterly audits of gems. And ideally updating all gems that we can every couple sprints.

**Comment by aub** [comment]
We've already spent entirely too much time on this, but I think your logic here is flawed. AFAICT none of these gems provide specific instructions that you should lock your Gemfile to an old version, and to do so would be really weird. Would they be telling us that we should avoid using newer releases? In the case of redis, the lockfile is already set to ~3.2, so what's the point of adding the requirement to the Gemfile?

I'm also going to disagree rather strenuously with the idea that we should update gems every couple of sprints. Why introduce the possibility of a regression when you have no specific goal you're trying to achieve? Gems should be upgraded if there is a specific feature in the new version, if there is a security problem in the old version, or if the old version is no longer supported. It's always been my inclination to keep the gems updated as well, but if you think about it what's the point?

**Comment by saneshark** [comment]
@aub again, I'm 100% with you and if you see the thread in #270 I was very much in the same camp as you with respect to most of what you're saying, particularly with versioning gems. In that thread at least @robbiethegeek and a handful of others were fairly adamant about pessimistic versioning and I think what I've proposed here is a compromise. I feel like with you I'm playing devil's advocate more than anything. I'm surprised no one is being as vocal as they were in the issue that this was meant to address.

That being said, I've found that updating gems every iteration, regardless of whether or not you plan to use the new features makes it much more manageable in the long term, particularly if you're just updating minor releases. There should always be careful attention to CHANGELOG when doing so. A lot of gems share interdependencies. If you don't address them as you move along, you're left with a lot of headaches when it comes time to address a security vulnerability.

**Comment by saneshark** [comment]
Also, pessimistic versioning is not at all akin to locking your Gemfile to a specific version. You still get minor bug fixes and security patches. It's more a precaution in case a major version bump introduces unforeseen changes. That being said, diligence in doing updates and reading CHANGELOG as you update addresses that problem as well. We're 100% agreement on that, I'm sure.

**Comment by kreek** [comment]
I will keep my comment short 😀 I like [Thoughbot's style](https://github.com/thoughtbot/guides/tree/master/best-practices#bundler):

Bundler
-------

* Specify the [Ruby version] to be used on the project in the `Gemfile`.
* Use a [pessimistic version] in the `Gemfile` for gems that follow semantic
  versioning, such as `rspec`, `factory_girl`, and `capybara`.
* Use a [versionless] `Gemfile` declarations for gems that are safe to update
  often, such as pg, thin, and debugger.
* Use an [exact version] in the `Gemfile` for fragile gems, such as Rails.

[Ruby version]: http://bundler.io/v1.3/gemfile_ruby.html
[exact version]: http://robots.thoughtbot.com/post/35717411108/a-healthy-bundle
[pessimistic version]: http://robots.thoughtbot.com/post/35717411108/a-healthy-bundle
[versionless]: http://robots.thoughtbot.com/post/35717411108/a-healthy-bundle

**Comment by saneshark** [comment]
And here: https://robots.thoughtbot.com/a-healthy-bundle

> Security vulnerabilities are discovered, new features arrive to increase productivity, and bugs are fixed. Interdependencies will force you to update more gems than you intend to, and each upgrade requires debugging and fixing incompatibilities in your application. Therefore, it’s best to upgrade continually, in little steps.


> If you tighten the reins too much on your dependencies, it will discourage you from updating frequently. Find a balance that works for your application, your team, and your dependencies, but make sure that you give yourself enough room for continuous updates.

**Comment by saneshark** [comment]
But let's be optimistic. :)

**Comment by aub** [comment]
Ok, apologies for not doing a very good job of being helpful in this conversation. I was frustrated about spending so much time on it, but instead of just saying that I managed to multiply the time spent by being overly argumentative. I think there are multiple valid approaches to this stuff, and ultimately it doesn't matter all that much as long as we're not constantly upgrading gems at inappropriate times. @saneshark thanks for taking the time here, both to do the work and to explain the background. From your closing the PR, I'll assume we've decided to maintain the status quo for now, but if it comes up again I'll do my best to be more helpful and less of a jerk.

**Pull request closed without merging**
