### PR TITLE
Add migration for pension_ipf_notifications table

### PR DESCRIPTION
**Pull request by danlim715**
## Summary
This PR creates a new migration for the new `pension_ipf_notifications` table.

This table will store encrypted VANotify payloads received by the `v1/callbacks` endpoint.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/69766
- [PR for endpoint changes](https://github.com/department-of-veterans-affairs/vets-api/pull/15883)
- [PR for Pension IPF script](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1532)

## Testing done

- This is a new feature so there is no old behavior prior to this change

## What areas of the site does it impact?
* N/A

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by LindseySaari** [comment]
It appears that there's quite a few `precision: nil` removed. Is this intentional?

**Comment by danlim715** [comment]
> It appears that there's quite a few `precision: nil` removed. Is this intentional?

@LindseySaari no, this was just the result of schema when i ran `rails db:migrate` locally.

**Comment by LindseySaari** [comment]
> > It appears that there's quite a few `precision: nil` removed. Is this intentional?
> 
> @LindseySaari no, this was just the result of schema when i ran `rails db:migrate` locally.

I think It's usually a good practice to explicitly set the precision. I think if it's not defined, it will use the default, which will differ from precision: nil

**Comment by danlim715** [comment]
> > > It appears that there's quite a few `precision: nil` removed. Is this intentional?
> > 
> > 
> > @LindseySaari no, this was just the result of schema when i ran `rails db:migrate` locally.
> 
> I think It's usually a good practice to explicitly set the precision. I think if it's not defined, it will use the default, which will differ from precision: nil

For some reason, when i run migrations locally, those precision changes all disappear. Is there a config setting that keeps those `precision:nil` lines in my generated schema? I had to manually modify my `schema.rb` in this PR which is something that we should not be doing.

**Review by LindseySaari — APPROVED** [review]

**Pull request merged**
