### PR TITLE
add mobile as preferred contact method in definitions

### PR DESCRIPTION
**Pull request by zurbergram**
## Description of change

Vets-json-schema update for https://github.com/department-of-veterans-affairs/vets-json-schema/pull/526

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by LindseySaari** [comment]
From my understanding, you should merge the vets-json-schema change first and then run `bundle update vets_json_schema` in vets-api. Not sure that we should be pointing to a branch other than master

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend/vets-website/creating-form-schema.md#finishing-up

**Comment by zurbergram** [comment]
@LindseySaari you are correct, this should have remained a draft until vets-json-schema was merged in

**Comment by zurbergram** [comment]
@LindseySaari this PR has been corrected to use correct master commit hash

**Review by LindseySaari — APPROVED** [review]

**Pull request merged**
