### PR TITLE
KmsEncryptionVerificationJob modifications

### PR DESCRIPTION
**Pull request by LindseySaari**
## Description of change

**NOTE:** [This PR](https://github.com/department-of-veterans-affairs/vets-api/pull/8570) (which adds a migration) needs to be merged first. Ignore the danger warning, just wanted to see if tests pass. 

This PR updates the `KmsEncryptionVerificationJob` to use/update the `verified_decryptable_at` field. 

This is needed because as the `KmsEncryptionVerificationJob` runs, we are seeing quite a few `Seahorse::Client::NetworkingError`'s come through in [Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/57920/?environment=production&project=3&query=is%3Aunresolved+KmsEncryptionVerificationJob&statsPeriod=24h). This is a timeout error related to the AWS call to KMS. The `Seahorse::Client::NetworkingError` causes the `KmsEncryptionVerificationJob` to restart. With this change in place, the next run of the job will skip over records that have a verified_decryptable_at date.

## Things to know
1. The .tap method is needed because we need to return the corrupted record(s) from the relation/record block, but still need to execute the code to update the verified_decryptable_at date afterwards. Otherwise, the incorrect return value is returned to `corrupted_records`.   
2. The `verified_decryptable_at` date will be saved once per record and NOT once per encrypted field. This means that if ANY of the encrypted attrs on a record cannot be decrypted, we will mark the entire record as not verified. 

[Related PR that adds the necessary migration and schema changes](https://github.com/department-of-veterans-affairs/vets-api/pull/8570)

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

### CODE REVIEW

**Review by rileyanderson — COMMENTED** [review]
Did you want to remove the migration and the schema change here since they are in your other PR?

**Comment by LindseySaari** [comment]
> just wanted to see if tests pass

Yes definitely. Once I get the migration PR merged in, I'll rebase this branch. I put the migration/schema changes here just to check the tests

**Comment by rileyanderson** [comment]
> > just wanted to see if tests pass
> 
> Yes definitely. Once I get the migration PR merged in, I'll rebase this branch. I put the migration/schema changes here just to check the tests

Guess it would have helped if I read the description 😆

**Review by rileyanderson — DISMISSED** [review]

**Comment by LindseySaari** [comment]
@rileyanderson Alrighty, just rebased. This one is all set for review

**Review by rileyanderson — COMMENTED** [review]
Did you mean to revert your DB changes that you made in your other PR?

**Review by rileyanderson — APPROVED** [review]

**Pull request merged**
