### PR TITLE
6703: change api auth user to loa3

### PR DESCRIPTION
**Pull request by kpethtel**
## Summary

Makes the api auth user loa3 because mobile users must be loa3.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6703

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
Specs. 

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by aherzberg — DISMISSED** [review]
LGTM

**Review by bosawt — CHANGES_REQUESTED** [review]
One small thing, you're gonna want to set the 'authn_context' as well:

` authn_context { LOA::IDME_LOA3_VETS }`

**Comment by bosawt** [comment]
> One small thing, you're gonna want to set the 'authn_context' as well:
> 
> ` authn_context { LOA::IDME_LOA3_VETS }`

but otherwise looks good

**Review by bosawt — APPROVED** [review]
looks gud!

**Pull request merged**
