### PR TITLE
Build new /gids/yellow_ribbon_programs endpoint

### PR DESCRIPTION
**Pull request by kelsonic**
## Description of change
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/5599

This PR creates a proxy endpoint to interface with the new GIDS endpoint needed for the new Yellow Ribbon Program search tool.

## Testing done
Please advise if new tests need to be created, thanks!

#### Unique to this PR
- [ ] Has all the same functionality (and query param support) as the new GIDS endpoint: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5604

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Swagger docs have been updated, if applicable
- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub
- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by kelsonic** [comment]
This PR is not yet ready for review, just sending up a draft PR atm.

**Comment by ncksllvn** [comment]
We should make a follow-up ticket to add this into Swagger, https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/gi_bill_institutions.

**Comment by kelsonic** [comment]
@ncksllvn great idea! Created! https://github.com/department-of-veterans-affairs/va.gov-team/issues/6653

**Comment by kelsonic** [comment]
Not entirely sure why this is failing, doesn't seem to be related:
image

**Comment by johnpaulashenfelter** [comment]
@kelsonic this looks like a legit failure of a spec related to your PR

```
 1) gi client gets yellow ribbon programs search results
     Failure/Error: expect(client_response[:data].first.keys).to contain_exactly(:id, :type, :attributes, :links)

       expected collection contained:  [:attributes, :id, :links, :type]
       actual collection contained:    [:attributes, :id, :type]
       the missing elements were:      [:links]

```

**Pull request merged**
