### PR TITLE
Update staging year to date recipients

### PR DESCRIPTION
**Pull request by hughes-dustin**
## Description of change
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19446

## Testing done
Update unit tests.

## Testing planned
Will reach out to the new recipients after changes are merged into staging and new reports have been generated. 

## Acceptance Criteria (Definition of Done)
- [x] The following emails are included in the distribution for the 22-1995 Daily Fiscal YTD report in staging: 
     - kyle.pietrosanto@va.gov
     - robert.shinners@va.gov
- [x]  The following emails are included in the distribution for the 22-1995 Daily YTD report in staging: 
     - kyle.pietrosanto@va.gov
     - robert.shinners@va.gov
- [x]  The following email is included on all staging distributions from AC 1-2 all of the time: shay.norton-leonard@va.gov

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Swagger docs have been updated, if applicable
- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub
- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by dneel-bah** [comment]
@johnpaulashenfelter My understanding is that the email is in the production distribution list, and this story is to update the staging distribution list.  We will have a follow-up story to update the production lists once the customer has verified the updates in staging.

I have reached out to the customer regarding the gmail email in the production list to determine if it is still valid.  If invalid, we will remove it as part of the production update story.

**Comment by johnpaulashenfelter** [comment]
@dneel-bah thanks.

While things are being updated -- just to be clear, everyone that was *already* on the list here (and later, in production) *STAYS* on the list?

**Comment by dneel-bah** [comment]
@johnpaulashenfelter 
For purposes of the story for this PR that is correct.  We do not update the distribution outside of the requests being made by the customer.  In this instance they have requested for the 3 people to be added.

Once testing has passed, we will have a story to remove the 3 people from the staging distro and add them to the production distro (they do not want to be spammed).

**Comment by johnpaulashenfelter** [comment]
@dneel-bah Could I ask you to review both this list and the production with the customer? I understand they only asked for additions, but I'm also unsure if they know who the full list of recipients is.

Would there be a ticket to take *off* anyone not associated with the project once it wraps up (eg the @bah address?)

**Comment by dneel-bah** [comment]
> @dneel-bah Could I ask you to review both this list and the production with the customer? I understand they only asked for additions, but I'm also unsure if they know who the full list of recipients is.
> 
> Would there be a ticket to take _off_ anyone not associated with the project once it wraps up (eg the @bah address?)

@johnpaulashenfelter I wanted to follow-up on this after receiving response from EDU.  We have a follow-up story to update the production distro's with the correct people.  As part of that we will remove the gmail address and additional va address as specified by the EDU team.

**Pull request merged**
