### PR TITLE
controller flow session model user model integration

### PR DESCRIPTION
**Pull request by saneshark**

### CODE REVIEW

**Comment by saneshark** [comment]
@shauni @robbiethegeek @awong-dev 

This is as yet untested, but I wanted to put it out there to get some eyes on it for now.

**Comment by awong-dev** [comment]
I'm sorta overloaded right now so am going to not be able to look at this. Ping me again if you think you need my input?

**Comment by robbiethegeek** [comment]
I think this looks good would love @shauni to give it a 👍

**Comment by shauni** [comment]
Reviewed and tested locally - looks great!

**Pull request merged**
