### PR TITLE
API-34214 - Add rep search by poa_code

### PR DESCRIPTION
**Pull request by acovrig**
## Summary
- Lookup reps by poa_code when getting multiple by name.

## Related issue(s)
- [API-34214](https://jira.devops.va.gov/browse/API-34214)

## Testing done
- [x] *New code is covered by unit tests*
- If multiple reps with the same first and last name and same middle initial exist, it would fail.
- If multiple reps with the same first and last name exist with no middle name, it would also fail.
- Make a request (get v1 claims is a good one) with multiple reps in the DB with the same first/last/middle names (or same first/last and no middle initial). It should find the rep with the correct poa_code. If multiple reps still come back from that, it should return an error like it used to.

## What areas of the site does it impact?
v1 (claims, 526, itf)

## Acceptance criteria
- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Things to know
This has been fixed in v2 by taking the registration_id, that can't really be done in v1 as it would be a breaking change.

### CODE REVIEW

**Review by FonzMP — APPROVED** [review]
:shipit:

**Review by rockwellwindsor-va — APPROVED** [review]
Ran scenario with multiple reps in DB with same info, looked good to me!

**Comment by FonzMP** [comment]
@department-of-veterans-affairs/lighthouse-pivot @department-of-veterans-affairs/accredited-representation-management  - looks like it's pending approval from your all's end as well. 

FYSA - we had a lookup fail for a PoA due to identical first and last names and no Middle Initial in the DB to specify which individual they were looking for. Adding a PoA code lookup as a third approach to help potentially resolve this issue.

**Review by holdenhinkle — APPROVED** [review]
LGTM

**Pull request merged**
