### PR TITLE
Convert case middleware

### LINKED ISSUE #60: add middleware to convert snakecase/camelcase

### PR DESCRIPTION
**Pull request by lihanli**
closes #60

### CODE REVIEW

**Comment by saneshark** [comment]
@lihanli can you add a note in README and I'll notify the prescriptions and secure messaging F/E devs of this impending change? tagging @ayaleloehr for awareness

**Comment by saneshark** [comment]
Perfect! @ayaleloehr do you want to check with Prescriptions to see what the LOE is for them to support this change? the interim solution could be to set headers on all requests to do dasherize and they could open a separate issue to change to camelCase as time allows.

**Comment by saneshark** [comment]
LGTM, Got the green light from @webinista (prescriptions) and @carlmjohnson (edu claims)

**Comment by carlmjohnson** [comment]
I did give the green light, but I'm benefits claims, not edu claims. :-)

**Pull request merged**
