### PR TITLE
Replace Virtus with Vets::Model on AVS

### PR DESCRIPTION
**Pull request by stevenjcumming**
## Summary

- Virtus is discontinued and needs to be removed. 
- Replace Virtus models with `Vets::Model`
- `Vets::Model` needed a minor update to handle the base case and AVS case
- Another minor update to the spec was required to make the keys symbols

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92443

## Testing done

- [x] manually comparing the previous and new AfterVisitSummary object

## Acceptance criteria

- [x] virtus models are now subclasses of Vets::Model
- [x] model(s) don't use the virtus gem

### CODE REVIEW

**Comment by stevenjcumming** [comment]
@acrollet would you (or someone on your team) mind reviewing this PR when you have a chance?

**Review by RachalCassity — APPROVED** [review]

**Comment by acrollet** [comment]
This is still on my list to review, I've been having issues with socks and unable to view the review instance.

**Comment by acrollet** [comment]
Updating against master for RI rebuild

**Comment by acrollet** [comment]
SOCKs are fixed, now waiting on a RI auth issue.

**Comment by stevenjcumming** [comment]
I switched Vets::Model from a class to a module and the last commit should reflect those changes

**Review by ericboehs — APPROVED** [review]

**Pull request merged**
