### PR TITLE
API-40197-remove-austin-night-report

### PR DESCRIPTION
**Pull request by stiehlrod**
## Summary

- Removes Austin from nightly reports

## Related issue(s)

- [API-40197](https://jira.devops.va.gov/browse/API-40197)

## What areas of the site does it impact?
modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb
modules/claims_api/app/mailers/claims_api/submission_report_mailer.rb
	modified:   modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb
	modified:   modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by FonzMP — DISMISSED** [review]
:shipit:

**Comment by rockwellwindsor-va** [comment]
@stiehlrod  are there two specs that need this removed as well? (didn't see the tests all finish here yet but assume they could fail with this removal?)

`modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb`
`modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb`

**Comment by stiehlrod** [comment]
> @stiehlrod are there two specs that need this removed as well? (didn't see the tests all finish here yet but assume they could fail with this removal?)
> 
> `modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb` `modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb`

@rockwellwindsor-va Good call, I had a filter on my search.

**Review by rockwellwindsor-va — APPROVED** [review]
LGTM!

**Pull request merged**
