### PR TITLE
Remove autoloading

### PR DESCRIPTION
**Pull request by lihanli**
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4917

### CODE REVIEW

**Comment by patrickvinograd** [comment]
I'm on board with the switch to eager loading but I'd like to see this tested reasonably thoroughly in staging - i.e. don't merge it 5 minutes before the prod PR happens :)

**Comment by saneshark** [comment]
I don't really understand why files need to be moved. Why can't you just do something like this in initializer?

```
if Rails.env.development? || Rails.env.testing?
  config.autoload_paths << "#{config.root}/lib"
else
  config.eager_load_paths << "#{config.root}/lib"
end
```

**Comment by lihanli** [comment]
we don't want to eager_load lib/tasks

**Comment by rlbaker** [comment]
Would something like `Dir.glob("#{Rails.root}/lib/*[^workflow]/").each { |dir| config.eager_load_paths << dir }` work? @lihanli @saneshark

**Comment by lihanli** [comment]
we would have to move all base level lib modules into a namespace (because the base lib directory wouldn't be included in eager load), refactor all existing references to those modules, and never use base level modules in the future, seems like more work than just moving the directory to app

**Comment by rlbaker** [comment]
If we remove the trailing slash, we can include all the source files in `lib/` as well. Looks like Rails supports source files in the `eager_load_paths` property: https://github.com/rails/rails/blob/master/railties/lib/rails/engine.rb#L475

```ruby
Dir.glob("#{Rails.root}/lib/*[^tasks]").each { |dir| config.eager_load_paths << dir }
```

**Comment by lihanli** [comment]
adding source files to eager_load_paths doesn't work for me

**Comment by rlbaker** [comment]
Might just be a Rails 5 thing, or I may be misreading the rails source in that spot.

**Comment by lihanli** [comment]
adding individual directories to eager_load_paths is not going to work because rails considers those directories to be base level directories so if you wanted to namespace something `PensionBurial` the directory structure would have to be `lib/pension_burial/pension_burial/file.rb`

what we can do is rename the support files in `lib/tasks/support` to the `.rake` extension, then those files won't get eager_loaded in production and we can preserve the history. or we can move the directory and lose the history.

**Comment by saneshark** [comment]
@lihanli can you provide link or reference to this problem with Rails 5? I'm pretty sure Rails 5 still lets you specify what you want as eager_load and what you want for auto_load. In fact, you could still have the same Rails 4 functionality, just need to manually override a configuration default. In short, Rails 5 isn't really a problem. What is the problem here?

if lib/tasks isn't supposed to be eager loaded, maybe that should be moved to a different folder.

**Comment by lihanli** [comment]
the problem is autoloading is not thread safe, causes random errors that we have already run into in production. you can force rails 5 to use autoloading by changing a config but that's not a good idea.

the reason moving files into `app/lib` is recommended over eagerloading the lib directory is because you don't have to change anything in the config file and you don't want to eager load generators and tasks, since we don't have generators and we want to preserve the commit history i can move the tasks to a different directory, i'll make a new pull request with only the tasks directory moved

**Pull request closed without merging**
