### PR TITLE
Catch correct faraday error class

### PR DESCRIPTION
**Pull request by patrickvinograd**
At some point Faraday refactored and the timeout class became `Faraday::TimeoutError`. This compensates.

Absent this change, the rescue block was not happening, and the error would fall through to the generic ApplicationController rescue block which would raise an InternalServerError. 

With this change, it looks like you'll return a successful status with the refresh status = false in the metadata of the response, which seems less accurate HTTP-wise, but if you've got front-end error handling to compensate I guess is okay. 

I'm open to alternative ways of resolving this, but wanted to raise this since it seems like the intent of the code is not being honored.

### CODE REVIEW

**Comment by patrickvinograd** [comment]
Actually re-review of the logs indicates these timeout cases are resulting in 200s:
```
ESC[32mdsva-vetsgov-prod/srv/vets-api/src/log/vets-api.logESC[0m ESC[36m172.30.35.31ESC[0m I, [2017-08-01T11:45:19.528740 #2073]  INFO -- : [61795598-8cf7-4447-ad0a-b99b2c7fe9ee] [d5fad7ae4c297abb1c03a] Completed 200 OK in 15026ms (Views: 1.6ms | ActiveRecord: 0.5ms)
```
So the rescue in the evss_claims_service must be working...

**Comment by patrickvinograd** [comment]
It is working via the BreakersOutage rescue.

**Comment by saneshark** [comment]
@patrickvinograd this LGTM to address the problem at hand. What's the status of this? Aside: would love to see this client use the errors middleware if possible which should I think correctly handle timeouts as well.

**Comment by jkassemi** [comment]
@patrickvinograd - if I read that correctly then that means that the `Faraday::Error::TimeoutError` is converted to a `Breakers::OutageException`, and therefore the `Faraday::Error::TimeoutError` in the controller is unnecessary?

I'm also having a heck of a time finding out where faraday even throws that `Faraday::TimeoutError` though - the faraday adapter sources seem to indicate that `Faraday::Error::TimeoutError` is appropriate...

**Pull request closed without merging**
