### PR TITLE
Begin switch to LH BI Service for Simple Forms

### PR DESCRIPTION
**Pull request by Thrillberg**
## Summary
This PR is inspired by this spike PR: https://github.com/department-of-veterans-affairs/vets-api/pull/17354 but it adds a feature flag in case things go wrong.

This also cleans up the `s3` class, which I don't believe we ever used.

### CODE REVIEW

**Review by pennja — APPROVED** [review]
Looks good, great work! 👍

**Review by stevenjcumming — APPROVED** [review]

**Comment by wayne-weibel** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR changes <code>510</code> LoC (not counting whitespace/newlines).</p>

<p>In order to ensure each PR receives the proper attention it deserves, those exceeding<br />
<code>500</code> will not be reviewed, nor will they be allowed to merge. Please break this PR up into<br />
smaller ones.</p>

<p>If you have reason to believe that this PR should be granted an exception, please see the<br />
<a href="https://depo-platform-documentation.scrollhelp.site/developer-docs/Submitting-pull-requests-for-approval.655032351.html#Submittingpullrequestsforapproval-FAQ">Submitting pull requests for approval - FAQ</a>.</p>

<details>
  <summary>File Summary</summary>

  #### Files
  - .github/workflows/danger-changelimiter-test.rb (+508/-0)
- Dangerfile (+1/-1)

  ####
  _Note: We exclude files matching the following when considering PR size:_

  ```
  *.csv, *.json, *.tsv, *.txt, *.md, Gemfile.lock, app/swagger, modules/mobile/docs, spec/fixtures/, spec/support/vcr_cassettes/, modules/mobile/spec/support/vcr_cassettes/, db/seeds, modules/vaos/app/docs, modules/meb_api/app/docs, modules/appeals_api/app/swagger/, *.bru
  ```
</details>

<p>Big PRs are difficult to review, often become stale, and cause delays.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by wayne-weibel** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR changes <code>14</code> LoC (not counting whitespace/newlines).</p>

<p>In order to ensure each PR receives the proper attention it deserves, we recommend not exceeding<br />
<code>5</code>. Expect some delays getting reviews.</p>

<details>
  <summary>File Summary</summary>

  #### Files
  - .github/workflows/danger-changelimiter-test.rb (+10/-0)
- Dangerfile (+2/-2)

  ####
  _Note: We exclude files matching the following when considering PR size:_

  ```
  *.csv, *.json, *.tsv, *.txt, *.md, Gemfile.lock, app/swagger, modules/mobile/docs, spec/fixtures/, spec/support/vcr_cassettes/, modules/mobile/spec/support/vcr_cassettes/, db/seeds, modules/vaos/app/docs, modules/meb_api/app/docs, modules/appeals_api/app/swagger/, *.bru
  ```
</details>

<p>Big PRs are difficult to review, often become stale, and cause delays.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by wayne-weibel** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR changes <code>14</code> LoC (not counting whitespace/newlines).</p>

<p>In order to ensure each PR receives the proper attention it deserves, we recommend not exceeding<br />
<code>5</code>. Expect some delays getting reviews.</p>

<details>
  <summary>File Summary</summary>

  #### Files
  - .github/workflows/danger-changelimiter-test.rb (+10/-0)
- Dangerfile (+2/-2)

  ####
  _Note: We exclude files matching the following when considering PR size:_

  ```
  *.csv, *.json, *.tsv, *.txt, *.md, Gemfile.lock, app/swagger, modules/mobile/docs, spec/fixtures/, spec/support/vcr_cassettes/, modules/mobile/spec/support/vcr_cassettes/, db/seeds, modules/vaos/app/docs, modules/meb_api/app/docs, modules/appeals_api/app/swagger/, *.bru
  ```
</details>

<p>Big PRs are difficult to review, often become stale, and cause delays.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
