### PR TITLE
eMIS to VA Profile Transition: Address nil deployment locations

### PR DESCRIPTION
**Pull request by LindseySaari**
## Summary

A Sentry error related to `deployment_locations` being `nil` has been [reported here](http://sentry.vfs.va.gov/organizations/vsp/issues/237910/?environment=production&project=3&query=is%3Aunresolved+prefill%3Avaprofile_military&statsPeriod=1h). We need to update our code to account for cases where `deployment_locations` might be `nil`.

Further context was provided by the 1010 team regarding the implementation of the method in question, as discussed in this [Slack thread](https://dsva.slack.com/archives/C03LT909K1A/p1701881212251729). 

https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/71375
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/71375

### CODE REVIEW

**Comment by tpharrison** [comment]
@lihanli Do you mind reviewing this?  The auth-exp team is listed as a code owner for this, but we shouldn't be.  I'll make updates to the CO file in a separate PR.  Thanks!

**Comment by rmtolmach** [comment]
It's definitely weird that a veteran would have a deployment but no deployment location, but based on that logs that's something we need to cover :/ 

I was able to reproduce the failure in `hca`:
```
rebeccatolmach ~/git/vets-api be rspec spec/lib/hca/military_information_spec.rb 
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 188
[rspec-sidekiq] WARNING! Sidekiq will *NOT* process jobs in this environment. See https://github.com/wspurgin/rspec-sidekiq/wiki/FAQ-&-Troubleshooting
......F.......

Failures:

  1) HCA::MilitaryInformation#sw_asia_combat returns false if there is no deployment location
     Failure/Error: 
               deployment['deployment_locations'].each do |location|
                 location_date_range = location['deployment_location_begin_date']..location['deployment_location_end_date']
       
                 if countries.include?(location['deployment_country_code']) && date_range.overlaps?(location_date_range)
                   return true
                 end

     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./lib/hca/military_information.rb:92:in `block in deployed_to?'
     # ./lib/hca/military_information.rb:91:in `each'
     # ./lib/hca/military_information.rb:91:in `deployed_to?'
     # ./lib/hca/military_information.rb:87:in `sw_asia_combat'
     # ./spec/lib/hca/military_information_spec.rb:25:in `block (4 levels) in <top (required)>'
     # ./spec/lib/hca/military_information_spec.rb:24:in `block (3 levels) in <top (required)>'

Finished in 0.4274 seconds (files took 7.07 seconds to load)
14 examples, 1 failure

Failed examples:

rspec ./spec/lib/hca/military_information_spec.rb:23 # HCA::MilitaryInformation#sw_asia_combat returns false if there is no deployment location
```

We already had a cassette that had a list of `deployments` but no deployment location 🎉 so I used that to write a couple tests @LindseySaari. 

@lihanli FYI, we plan to remove `lib/hca/military_information.rb` after we're completely done with emis! 😄 It's basically copied in `lib/va_profile/prefill/military_information.rb`.

**Comment by hdjustice** [comment]
@rmtolmach - Lihan is out for a couple days.

@JoshingYou1 @jadon1979 - Can you please check this out?  This is in regards to the eMIS deprecation, see the comment from Rebecca above.
Note: We migrated off eMIS in July, but I want to make sure that this doesn't impact what we have going on.

**Review by rjohnson2011 — APPROVED** [review]

**Comment by rmtolmach** [comment]
> @rmtolmach - Lihan is out for a couple days.
> 
> @JoshingYou1 @jadon1979 - Can you please check this out? This is in regards to the eMIS deprecation, see the comment from Rebecca above. Note: We migrated off eMIS in July, but I want to make sure that this doesn't impact what we have going on.

Thanks, @hdjustice! I'm going to merge this with Ryan's approval–we'd like to get it in to prevent further errors. We will be watching [this Sentry issue](http://sentry.vfs.va.gov/organizations/vsp/issues/237910/?environment=production&project=3&query=is%3Aunresolved+prefill%3Avaprofile_military&statsPeriod=1h) to make sure there are no more errors after this is deployed. Just wanted loop yall in since we're changing a file yall own! 🙂

**Pull request merged**
