### PR TITLE
Pension 90364 new add person proxy by icn logic

### PR DESCRIPTION
**Pull request by danlim715**
## Summary

- *This work is behind a feature toggle (flipper): NO*
- Added a new service class that handles fetching MPI profile data for a given ICN, validations for ability to perform proxy add for the retrieved profile, and attempts to initiate the add_person_proxy in the MPI library. This service class is meant to be a standalone tool that is benefit agnostic and assists with generating a participant ID for a given veteran's ICN. This PR also adds a new sidekiq job specific to the context of pension ITF that will attempt this PID creation logic prior to ITF creation for users that have an ICN but are missing a PID.
- Pension benefits team to own this work.

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/90364

## Testing done

- [x] *New code is covered by unit tests*
- begin an authenticated pension form with a user lacking a PID, this will now create one as needed and then file an ITF

## What areas of the site does it impact?

InProgress forms

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)

### CODE REVIEW

**Review by TaiWilkin — APPROVED** [review]
Looks good - I was able to trigger the new job with user vets.gov.user+10@gmail.com

**Review by TaiWilkin — APPROVED** [review]

**Comment by bosawt** [comment]
Why is this existing route not used for this functionality? `app/controllers/v0/mpi_users_controller.rb` I'm not really sure what the purpose of this is when that route can be called already

**Review by bosawt — CHANGES_REQUESTED** [review]
Just gonna mark changes until this question is resolved:

Why is simply the existing functionality with this controller not being invoked instead of this work? `app/controllers/v0/mpi_users_controller.rb`

Also, this MPI call is only meant to be used for certain form submissions, not for every form submission. I believe the ruleset is 'any VBA based claim submission'.

**Comment by danlim715** [comment]
> Just gonna mark changes until this question is resolved:
> 
> Why is simply the existing functionality with this controller not being invoked instead of this work? `app/controllers/v0/mpi_users_controller.rb`
> 
> Also, this MPI call is only meant to be used for certain form submissions, not for every form submission. I believe the ruleset is 'any VBA based claim submission'.

Hello @bosawt. We cannot call the controller directly from our async job because the logic in `v0/mpi_users_controller` only takes a form_id param and relies on `@current_user` to verify user data. But `@current_user` data will not be available if the async job fails and retries at a later time. Hence, we opted to call the MPI Service action directly.

And currently, this logic will only be triggered for auto-created ITF submissions for the pension benefits application (21P-527EZ) and we've got the green light from @joeniquette for this implementation.

**Comment by bosawt** [comment]
> > Just gonna mark changes until this question is resolved:
> > Why is simply the existing functionality with this controller not being invoked instead of this work? `app/controllers/v0/mpi_users_controller.rb`
> > Also, this MPI call is only meant to be used for certain form submissions, not for every form submission. I believe the ruleset is 'any VBA based claim submission'.
> 
> Hello @bosawt. We cannot call the controller directly from our async job because the logic in `v0/mpi_users_controller` only takes a form_id param and relies on the `@current_user` session data to verify user info. But `@current_user` redis data will not be available if the async job fails and retries at a later time. Hence, we opted to call the MPI Service action directly.
> 
> And currently, this logic will only be triggered for auto-created ITF submissions for the pension benefits application (21P-527EZ) and we've got the green light from @joeniquette for this implementation.

Why does the proxy add call need to be async? It should be a fast call, and will either pass or fail, async only unnecessarily complicates it unless I'm missing something

**Comment by wayne-weibel** [comment]
> Why does the proxy add call need to be async? It should be a fast call, and will either pass or fail, async only unnecessarily complicates it unless I'm missing something

The individual form route is the submission, in_progress_forms encompasses all the forms with a save-in-progress.  The form specific route is not called until the end of the form workflow, which may take days or weeks or months.  We are mandated to attempt to establish the earliest possible time for a veteran to receive benefits, ie. the ITF date, which is when an in_progress_form is created.
The MPI controller is not being used because off all the cases where the creation would fail - needing to log and monitor these instances - and gain metrics on the number being requested - all of which is simplified on the backend
MPI proxy add ‘should’ be fast and ‘should’ pass or fail consistently, but that is not guaranteed, and again, needing to log and monitor these instances

**Pull request closed without merging**
