### PR TITLE
Upgrade sentry-raven gem

### PR DESCRIPTION
**Pull request by annaswims**
## Description of change
Upgrading to 2.3.0 the last gem version released before our sever version was released.
Our Sentry server is 8.13.0 released Feb 1, 2017  and versoion 2.3.0 of the sentry-raven gem was released January 04, 2017 .

## Testing planned
will test on staging

## Acceptance Criteria (Definition of Done)
errors continue to be reported in staging.

#### Applies to all PRs

- [x] Appropriate logging
- [x] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [x] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by annaswims** [comment]
Relevant change log from https://github.com/getsentry/raven-ruby/blob/master/changelog.md

We always explicitly set the log level, so the changing default log level will not affect us. 
We don't freeze sensitive data, so the change re: frozen objects won't affect us.
===================================
* CHANGE: Log levels of some messages have been changed. Raven logger is INFO level by default. [@nateberkopec]
* BUGFIX: Exception messages are now limited to 10,000 bytes. [#617, @mattrobenolt]

2.2.0
* ENHANCEMENT: Sentry server errors now return some information about the response headers. [#585, @rafadc]
* BUGFIX/ENHANCEMENT: Frozen objects are no longer sanitized. This prevents some bugs, but you can now also freeze objects if you don't want them to be sanitized by the SanitizeData processor. [#594, @nateberkopec]
* ENHANCEMENT: The ability to use Raven::Instance alone is greatly improved. You can now call #capture_exception directly on an Instance (#595), give it it's own Logger (#599), and set it's own config which will be used when creating Events (#601). Thanks to
* ENHANCEMENT: You may now provide your own LineCache-like class to Raven. This is useful if you have source code which is not available on disk. [#606, @nateberkopec]
* BUGFIX: Raven no longer emits anything to STDOUT if a system command fails [#596, @nateberkopec]
* ENHANCEMENT: Raven now tells you exactly why it will not send an event in the logs [#602, @nateberkopec]

2.1.4
* FIX: Remove contexts key, because it was disabling browser auto-tagging [#587, @nateberkopec]

2.1.3
* Move os context key to server_os [@nateberkopec]

**Comment by saneshark** [comment]
Thats cool actually that we can bypass the Sanitizer by freezing an object. I'm guessing those bugs described there mostly had to do with thread safety though, otherwise I don't really see why freezing the object could help. This could be a handy little work around for the overzearlous sanitizer though.

The only thing we need to be mindful about is that if we do freeze objects at some point, those objects might end up leaking PII since it skips the sanitizer. @jkassemi to @annaswims point we don't really freeze objects. The only place I know where we do this is when a RedisStore object is marked for deletion.

**Comment by jkassemi** [comment]
Sentry is technically within a production security boundary and all state is encrypted at rest. While we should act quickly to clean up any SPI that ends up there, concerns over that shouldn't block testing/deployment as issues can be easily addressed.

**Comment by jkassemi** [comment]
Also, I know it's minor, but really appreciate that included changelog, @annaswims!

**Comment by annaswims** [comment]
@saneshark This is safe to merge.  This brings the ruby client up to date with the current server version, but not all the way up to date. 

Current gem is  sentry-raven v 2.1.2  released Oct 21, 2016.
This PR changes it to v2.3.0 relseased January 04, 2017, which is still older than the current server version 8.13.0 released Feb 1, 2017.

**Comment by annaswims** [comment]
confirmed errors are being reported in stage.

**Pull request merged**
