### PR TITLE
Mobile: Message Counts

### PR DESCRIPTION
**Pull request by Tonksthebear**
## Summary
Update all message index endpoints to include counts of read/unread messages

## Related issue(s)
- [department-of-veterans-affairs/va.gov-team#7214](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7214)

## Testing done
Changed tests to accommodate the new meta schema

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback
Waiting to here if we want to include 0 counts in the meta

### CODE REVIEW

**Review by aherzberg — DISMISSED** [review]
LGTM

**Comment by Tonksthebear** [comment]
Got confirmation 0 counts should be omitted

**Review by kpethtel — APPROVED** [review]
👍

**Review by kpethtel — APPROVED** [review]

**Review by kpethtel — DISMISSED** [review]

**Review by kpethtel — APPROVED** [review]

**Review by ericboehs — APPROVED** [review]

**Review by kpethtel — APPROVED** [review]

**Review by aherzberg — APPROVED** [review]
LGTM

**Review by ericboehs — APPROVED** [review]

**Pull request merged**
