### PR TITLE
Remove Encrypted Jobs Files

### PR DESCRIPTION
**Pull request by tfink419**
## Summary

- Follow up PR for department-of-veterans-affairs/vets-api#15115
  - DO NOT MERGE this ticket until above ticket is in production
- Remove named job files and rename encrypted jobs to original name, remove references to encrypted name

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#67515
- department-of-veterans-affairs/vets-api#15115

## Testing done

- Ran Spec files

## What areas of the site does it impact?
No customer-facing changes as well as no change to logic is expected, this is renaming files and removing excess logic

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  ~~Documentation has been updated (link to documentation)~~
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  ~~Feature/bug has a monitor built into Datadog or Grafana (if applicable)~~
- [x]  ~~If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected~~
- [x]  ~~I added a screenshot of the developed feature~~

### CODE REVIEW

**Review by tblackwe — DISMISSED** [review]

**Comment by tblackwe** [comment]
@tfink419 this ended up with some merge conflicts because of work the Mobile team was doing. When you get back can you clean it up.
Sincere Apologies!

**Review by tblackwe — APPROVED** [review]
renaming files. LGTM

**Review by tblackwe — APPROVED** [review]

**Review by jperk51 — APPROVED** [review]
Mobile changes look good

**Review by aherzberg — APPROVED** [review]
LGTM for mobile change

**Pull request merged**
