### PR TITLE
Hotfix UTC conversion

### PR DESCRIPTION
**Pull request by cferris32**
## Summary
Hotfix for the changes from the related work below. Timezone data is now correctly pulled from `time_zone_id` field, and the converted local time is now stored in a new field `local_start_time` while leaving the UTC time unmodified in the original field. If the conversion could not happen due to lack of timezone data, the new field will contain a warning message `'Unable to convert UTC to local time'`

Since the creation of this hotfix branch, we have decided to move away from using a feature flag for this functionality.

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#56139

## Testing done

- Regression tested changes for UTC conversion and integration specs

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### CODE REVIEW

**Review by ajmagdub — DISMISSED** [review]
LGTM!

**Comment by cferris32** [comment]
> LGTM other than for mobile we updated somethings to match the timezoneId to zoneId change. Since that's being reverted could you update those references too? You can find them in the change log here: https://github.com/department-of-veterans-affairs/vets-api/pull/12632/files

On it

**Comment by Tonksthebear** [comment]
@jperk51 Do you see a reason why we should convert `startTimeUtc` back to UTC? I just changed the fixture so that the single test failure now passes and from what I can see any date comparisons are done between DateTimes which account for timezone differences

**Review by Tonksthebear — DISMISSED** [review]
LGTM

**Review by ajmagdub — APPROVED** [review]
LGTM

**Review by Tonksthebear — APPROVED** [review]
Fixed the failing mobile tests so you should be good to go

LGTM

**Pull request merged**
