### PR TITLE
Added attribute bgjob_errors to form526_job_statuses

### PR DESCRIPTION
**Pull request by cnemeth**
## Description of change

Added attribute `bgjob_errors` to `Form526JobStatus`/

## Original issue(s)

department-of-veterans-affairs/va.gov-team#31489

## Things to know about this PR

- Prerequisite PR #8353 
- This PR is a prerequisite to [PR #8324, Update Form526JobStatus Error Tracking](https://github.com/department-of-veterans-affairs/vets-api/pull/8324)

### CODE REVIEW

**Review by LindseySaari — DISMISSED** [review]

**Comment by LindseySaari** [comment]
Just a reminder that migrations are a manual process, so when you're ready, please just ping in the vfs-platform-support channel

**Comment by cnemeth** [comment]
@LindseySaari The request spec that is in this PR is needed to fix a failure due to added attribute. Is it not supposed to be in this PR even though its absence will cause a spec failure?

**Comment by LindseySaari** [comment]
> @LindseySaari The request spec that is in this PR is needed to fix a failure due to added attribute. Is it not supposed to be in this PR even though its absence will cause a spec failure?

Hi, only /db changes in this PR :) You can address the spec updates in a separate PR

**Comment by cnemeth** [comment]
@LindseySaari  How are we supposed to merge this PR when that one request spec failure is preventing this PR from merging?

**Review by LindseySaari — APPROVED** [review]

**Pull request merged**
