### PR TITLE
Remove old feature flags

### PR DESCRIPTION
**Pull request by wullaski**
## Summary

- Removes `check_in_experience_pre_check_in_action_link_top_placement` and `check_in_experience_travel_logic`

## Related issue(s)

- (https://github.com/department-of-veterans-affairs/va.gov-team/issues/84396)[https://github.com/department-of-veterans-affairs/va.gov-team/issues/84396]

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by LindseySaari** [comment]
Can review when tests are passing. Are you aware of the extra step here ([3a to delete the feature from the DB upon removing from features.yml)](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)

If you have Argo terminal access, you should be able to do this in lower envs, but will need to create a separate support request for a support engineer to remove these after the production deploy.

**Comment by LindseySaari** [comment]
Are you aware of the extra step here ([3a to delete the feature from the DB upon removing from features.yml)](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)

If you have Argo terminal access, you should be able to do this in lower envs, but will need to create a separate support request for a support engineer to remove these after the production deploy.

**Comment by LindseySaari** [comment]
@wullaski Please respond to my comment and then we can move forward with the approval.

**Comment by wullaski** [comment]
@LindseySaari I was not that's new since the last time I've done this. I talked with the team and someone from CIE can do the lower environments and I'll put in the support ticket once this is closed. Thanks!

**Comment by LindseySaari** [comment]
> @LindseySaari I was not that's new since the last time I've done this. I talked with the team and @kanchanasuriya from CIE can do the lower environments and I'll put in the support ticket once this is closed. Thanks!

Sounds great! Thanks

**Review by LindseySaari — APPROVED** [review]

**Pull request merged**
