### PR TITLE
Evss test script

### PR DESCRIPTION
**Pull request by omgitsbillryan**
I've sunk a fair amount of time into the rails console testing EVSS users.  I made this convenience script so I can quickly test users.  Might be helpful for front-end devs too.

The main bonus is that it contains human readable error messaging.

### CODE REVIEW

**Comment by omgitsbillryan** [comment]
@kreek rake task works.  As for specifying a user - EVSS only seems to care about `ssn` so I don't think setting the first name, last name, or anything else matters.

I did not realize that there's a `:connectivity` rake namespace already.  This could fit there, in which case, it needs to be cleaned up a bit.

**Comment by omgitsbillryan** [comment]
@kreek I took a closer look at the `:connectivity` rake namespace, and I don't think this script applies.  I filed an issue for that separately here:
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3496

The script I wrote is more: "I want to easily see if test users exist in EVSS", whereas the rake task is more "I want to see if I can make a connection".

**Comment by kreek** [comment]
It can definitely be it's own thing, I was thinking it could live in tasks where there's similar checks i.e. code not associated to the day to day functionality of the site. That way there's a common way to kick those scripts off, `rake task`. Another option is for it to live in the vets.gov-team repo.

**Comment by jkassemi** [comment]
Agreed I don't think this applies to the connectivity task, adding some notes to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3496.

**Comment by ayaleloehr** [comment]
Pinging @omgitsbillryan on the status here?

**Comment by omgitsbillryan** [comment]
I'm embarrassed that I have the oldest outstanding PR.  Closing because:
1. This is old and probably won't work anymore.
2. Probably had no real place in our `master` branch since it's a hack script

**Pull request closed without merging**
