### PR TITLE
Pass GA clientId along in querystring to ID.me

### PR DESCRIPTION
**Pull request by narin**
## Description of change
In order to enable cross-domain tracking on Google Analytics, we must also append the clientId when redirecting to ID.me.  Added the clientId in `url_service` and moved the appending of the `signup` param into the URL service as well.

I didn't see a unit test present for the `signup` param, so was not sure how to test for the `clientId` param.  If we feel a unit test for this is necessary I could use some help in that area.

## Testing done
Tested locally along with front end changes (`13866-cross-domain-ga` branch) that clientId is appended when present.

## Acceptance Criteria (Definition of Done)
- [ ] Backend provides `clientId` if provided in the redirect url that is sent to the front end

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Swagger docs have been updated, if applicable
- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub
- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by saneshark** [comment]
It's a little unclear to me why this is necessary. Why not just keep track of the clientID in localstorage? https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id

**Comment by annaswims** [comment]
@saneshark Like we talked about in standup, the point is to pass the Google Analytics id to id.me so that we can have a unified view of a user's login experience across our tracking and id.me's . 

What @saneshark did in https://github.com/department-of-veterans-affairs/vets-api/pull/2869 will be in conflict with with this pr.

**Comment by saneshark** [comment]
@annaswims I remember now -- totally forgot about the ID.me component. 

Narin, do you anticipate that this is something we might need to do elsewhere? In which case maybe it would be better to use "headers" for this type of thing. Actually, scratch that, it might end up breaking CORS for any of the ones that require authentication. I think what you're trying to do is fine. 

My PR will introduce conflicts, but if its merged first you can use what I did there as an example of how to write specs. It introduces a helper that you can use for sessions_controller and url_service specs. I'll tag you on the PR for review/awareness.

**Comment by saneshark** [comment]
There is a unit test for signup, but it mostly lives in sessions_controller_spec. But I think we will likely use the helper I created for both url_service and sessions_controller_spec similar to this PR does. https://github.com/department-of-veterans-affairs/vets-api/pull/2869

**Pull request closed without merging**
