### PR TITLE
API-526-v2-change-address-pdf-gen

### PR DESCRIPTION
**Pull request by stiehlrod**
## Summary

Maps the following properties to the 526 PDF Generator (Column C, 526EZ PDF Generator Mapping on [Schema Planning Doc](https://docs.google.com/spreadsheets/d/1eW8dWUKXyGuMEpOtKK0ZCcPd4j9oIqEW6BHs18K_NPc/edit#gid=0)):
- changeOfAddress.dates.beginningDate
- changeOfAddress.dates.endingDate
- changeOfAddress.typeOfAddressChange
- changeOfAddress.numberAndStreet
- changeOfAddress.apartmentOrUnitNumber
- changeOfAddress.city
- changeOfAddress.country
- changeOfAddress.zipFirstFive
- changeOfAddress.zipLastFour
- changeOfAddress.state

## Related issue(s)
- [API-26192](https://vajira.max.gov/browse/API-26192)

## Testing done

- rspec

## What areas of the site does it impact?
	modified:   modules/claims_api/app/controllers/claims_api/v2/veterans/disability_compensation_controller.rb
	modified:   modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
	modified:   modules/claims_api/spec/fixtures/v2/veterans/disability_compensation/form_526_json_api.json

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by FonzMP** [comment]
I would think the same as https://github.com/department-of-veterans-affairs/vets-api/pull/12600#issuecomment-1542876423

since we have zip here as well, we could just pass the two needed values to the method and return the newly constructed value

**Review by mchristiansonVA — DISMISSED** [review]
Looks good to me.

**Review by mchristiansonVA — APPROVED** [review]
Looks good.

**Review by FonzMP — APPROVED** [review]
:shipit:

**Pull request merged**
