### PR TITLE
[Bugfix] For user attributes, first look at the identity provider, then MVI

### PR DESCRIPTION
**Pull request by annaswims**
## Description of change
We were troubleshooting an disability claim with a veteran and we were unable to retrieve a veteran's rated disability from evss because we were sending a nil value to evss for gender. The veteran had a gender in MVI, but gender was nil from the identity provider (id.me).  

https://github.com/department-of-veterans-affairs/vets-api/pull/1666 changed the order of presedence for the data. 

MHV gives us a limited subset of the attributes that the other identity providers so we were using `mhv_icn.present?` as a way to determine if the user logged in with MHV (and therefore we'd need to look up all the attributes in MVI). But now, there's no reason not to use the identity provider's data first, and MVI's data second (note: we only do MVI lookups for LOA3 users).
## Original issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/8908

### CODE REVIEW

**Comment by annaswims** [comment]
we should probably do the same for middle name, but I don't think it matters nearly as much.  when I fall back to the middle name in MVI 30+ test fail because many of our identity mocks don't have middle names and our factory has a faker middle name

**Comment by annaswims** [comment]
@patrickvinograd I don't think this affects you, but I figured I'll tag you just in case.

**Comment by annaswims** [comment]
If you'd rather, I could just make the change for gender, but it made sense to me to make the change for all attributes.

**Comment by kfrz** [comment]
LGTM. FWIW I certainly don't mind cleaning up related code in simple changesets.

**Pull request merged**
