### PR TITLE
EVSS: Get CA certs, client certs, client keys from env if possible

### PR DESCRIPTION
**Pull request by carlmjohnson**

### CODE REVIEW

**Comment by carlmjohnson** [comment]
I don't understand the Travis failure I have now. It looks like rake db is failing? Can that be right?

**Comment by austin-martinez** [comment]
I ran into this yesterday, it's actually simplecov
`File (/home/travis/build/department-of-veterans-affairs/vets-api/lib/evss/base_service.rb) is only (86.84%) covered. This is below the expected minimum coverage per file of (90.00%).`

**Comment by carlmjohnson** [comment]
Oh, I think I'm just misinterpreting it. The real failure is

> file (/home/travis/build/department-of-veterans-affairs/vets-api/lib/evss/base_service.rb) is only (86.84%) covered. This is below the expected minimum coverage per file of (90.00%).

I'm not sure how to test this code without certs really being active.

**Comment by carlmjohnson** [comment]
Add nocov for now until we learn a good way to test certs.

**Comment by austin-martinez** [comment]
is there anything you can add to README.md/application.yml.sample? are there certs we want to circulate for connecting to dev env for local development?

**Comment by carlmjohnson** [comment]
Once everyone has VA net access, we can change to using http://vaebnapp7.aac.va.gov:8001 for testing. To use certs, we'd need to give out our private cert to all devs, which seems like a bad move, even if it is just a private cert for dev.

**Pull request merged**
