### PR TITLE
VBA data format updates

### PR DESCRIPTION
**Pull request by patrickvinograd**
VBA updated their data to add some fields and change the names of others in the backing GIS service. Adjusting accordingly.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
LGTM

**Comment by ayaleloehr** [comment]
@plusjeff or @robbiethegeek: VBA updated their data schema last minute on us. Need to get this into vets-api for the facility locator launch. Please merge.

**Comment by patrickvinograd** [comment]
We just realized they changed the VHA schema slightly as well, hang on and let me include that in this PR, should have it in a few minutes

**Comment by NatalieEMoore** [comment]
Who can merge this PR?

**Comment by robbiethegeek** [comment]
LGTM

**Pull request merged**
