### PR TITLE
Mobile: Add meta data that counts the number of prescriptions with various statuses

### PR DESCRIPTION
**Pull request by Tonksthebear**
## Summary
Add meta data that counts the number of prescriptions with various statuses

## Related issue(s)
- [department-of-veterans-affairs/va.gov-team#7212](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7212)

## Testing done
Added a test for the metadata

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
None

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by kpethtel — COMMENTED** [review]
This looks good, but I think it would be wise to determine whether we want to include zero counts. I'm sure FE can work with whatever we give them, but it might be better to consistently provide the same values in the meta.

**Comment by Tonksthebear** [comment]
@kpethtel no you are correct, this would not show 0 counts. I had asked front end if they want that but I need to poke them again. Thanks for catching that

**Comment by Tonksthebear** [comment]
Just got confirmation I should leave this the way it is, so it should be good to go if you don't have any other concerns

**Review by kpethtel — APPROVED** [review]
👍

**Pull request merged**
