### PR TITLE
Incorporate VHA user satisifaction data

### PR DESCRIPTION
**Pull request by patrickvinograd**
Incorporates VHA user satisfaction data that was just incorporated into our backing GIS service. 
https://github.com/department-of-veterans-affairs/kudos-team/issues/219

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@mphprogrammer can you give this a review? I know you don't have context but just from a Rails perspective would be helpful

**Comment by mphprogrammer** [comment]
@patrickvinograd This is a nit, given our deadlines... You'll probably want to dry up the from_gis_attr in the vha, vba, and nca facility adapters. But other than that, LGTM. Feel free to merge, if time is of the essence and dry later.

**Comment by patrickvinograd** [comment]
@mphprogrammer For sure, but I'd rather do it after 11/11.

**Comment by plusjeff** [comment]
LGTM

**Comment by bshyong** [comment]
LGTM

**Pull request merged**
