### PR TITLE
Prune edu applications that were processed > 1 month ago

### PR DESCRIPTION
**Pull request by markolson**
We don't want to hold onto this information forever once it's sent over, but we do need to keep it for a while in case it needs to be re-processed. After a reasonable amount of time, we should prune it though.

### CODE REVIEW

**Comment by carlmjohnson** [comment]
Can we generalize this to all processed things older than N months?

**Comment by markolson** [comment]
@carlmjohnson Do you mean to make it an ENV or config variable, or to make it possible to apply it to other sorts of records?

**Comment by carlmjohnson** [comment]
I just wonder if we shouldn't just be cleaning up all old tasks after a certain amount of time. Is there a reason we'd want to keep an old task once the "useful for debugging" window time is up?

**Comment by markolson** [comment]
(After chatting, we figured out we were talking about 2 different things)

**Comment by leannammiller** [comment]
@markolson - what's the status of this and who should be the assignee?

**Pull request merged**
