### PR TITLE
Vet360 telephone text permissions

### PR DESCRIPTION
**Pull request by annaswims**
## Description of change
In order for the Bylight team to complete their notifications (text message) project they will need to update the value of text_message_perm_ind in Vets 360.

in addition we are updating the relevant swagger docs to include previously implemented attributes
## Testing done
updated specs

## Testing planned
verify on staging

#### Applies to all PRs

- [x] Appropriate logging
- [x] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [x] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by annaswims** [comment]
I did some testing in their swagger docs.  I started testing at https://int.vet360.va.gov:7005/contact-information-hub/swagger-ui.html#/TelephoneBio-v1 but that environment seemed to have errors related to an MVI connection so I switched to https://qa.vet360.va.gov:7005/contact-information-hub/swagger-ui.html#/TelephoneBio-v1.  qa.vet360.va.gov is the server that our staging environment connects to.   

We'll need to ensure a value is sent for `textMessagePermInd` each put/post or the value will be falsy on vets360.

**Comment by annaswims** [comment]
I did some more testing in vets360 qa swagger environment and it looks like sending a nil textMessagePermInd value has the same behavior as not setting it at all (it's false-y)

**Comment by elwoodva** [comment]
@annaswims Does this need to be updated with master branch?

**Comment by annaswims** [comment]
@elwoodva  there's no harm in updating it now, but I generally don't bother until it's gone through review.  It'll have to be updated again if anybody else merges.

**Pull request merged**
