### PR TITLE
delete old-style unused generator

### PR DESCRIPTION
**Pull request by erluti**
## Description of change
This generator hasn't been used and we plan to introduce a new generator.  Making the way for the new work.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#8461

## next steps
* implement new generators

### CODE REVIEW

**Review by LindseySaari — APPROVED** [review]
💯

**Comment by annaswims** [comment]
@saneshark / @kreek Did you use the generator on your covid_vaccine module?

**Comment by kreek** [comment]
> @saneshark / @kreek Did you use the generator on your covid_vaccine module?

@annaswims I wasn't involved in the covid_vaccine module, but I did use it when creating the mobile module (although there's been some manual tweaks since then)

**Comment by erluti** [comment]
We'll hold off on merging this until we've got the new one up.  We'll consider renaming this one

**Comment by erluti** [comment]
new generator maintains some of this work

**Pull request closed without merging**
