### PR TITLE
update base_path for GIBS service config

### PR DESCRIPTION
**Pull request by AdamKing0126**
## Summary
I am a member of the VA-IIR team, and we are the owners of this component.

See [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1718033925620709)

The `base_path` attribute of the `EducationBenefits::Configuration` object was too generic and it matched the `base_path` of the Forms API.  When the `EducationBenefits` service had a downtime event (this service is flaky, it happens somewhat frequently), the Breakers service blocked access to the Forms API, shutting out thousands of users.

This PR modifies the `base_path` attribute to be the fully qualified URI for the Lighthouse endpoint.  That way, the matcher logic in the Breakers service will not confuse it with any other services.

## Related issue(s)

[GitHub Issue](https://github.com/department-of-veterans-affairs/va-iir/issues/770)

## Testing done

Code is covered by unit tests.  I tested in local development:
- log in as a test user
- navigate to `/education/gi-bill/post-9-11/ch-33-benefit/status`
    - in chrome dev tools, see that the network request is behaving as it should
    - in running docker container, place a debugger, inspect the response that comes back from Lighthouse
- Existing functionality is maintained.

## What areas of the site does it impact?

Post-9/11 GI Bill Statement of Benefits at `/education/gi-bill/post-9-11/ch-33-benefit/status/`

## Acceptance criteria

Current tests are passing with no issues.  Existing functionality is maintained.  `base_path` attribute is now a unique, full URI (as opposed to the base url value it held before).  We should see no conflict with the Breakers functionality in the future. 

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by acrollet — CHANGES_REQUESTED** [review]
I think for personal preference I would keep the paths as constants, which would also keep the approach consistent with e.g. [direct deposit](https://github.com/department-of-veterans-affairs/vets-api/blob/dd9da376ef72c5db10a23b73651a81e7c1c6d74a/lib/lighthouse/direct_deposit/configuration.rb#L94), but overall this looks good to me and I believe will fix the issue. thanks!

**Comment by AdamKing0126** [comment]
> I think for personal preference I would keep the paths as constants, which would also keep the approach consistent with e.g. [direct deposit](https://github.com/department-of-veterans-affairs/vets-api/blob/dd9da376ef72c5db10a23b73651a81e7c1c6d74a/lib/lighthouse/direct_deposit/configuration.rb#L94), but overall this looks good to me and I believe will fix the issue. thanks!

Cool thanks, will fix.

**Review by acrollet — APPROVED** [review]
Thank you!

**Review by ryan-mcneil — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
