### PR TITLE
Retryable/Idempotent SubmitDependentPdfJob

### PR DESCRIPTION
**Pull request by tfink419**
## Summary
- Utilized Sidekiq retry capabilities to auto retry job
- Ensure files are only uploaded to VBMS once utilizing completed_at timestamp on PersistentAttachments and a basic array logging form names for the base forms.
- Completely rewrite `submit_dependents_pdf_job_spec.rb` and `dependency_claim_spec.rb`

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/65144
- https://github.com/department-of-veterans-affairs/vets-api/pull/13907

## Testing done
- Create a claim via `/view-change-dependents/add-remove-form-21-686c/`
- Check in `/sidekiq` admin console that claim will retry if there is an error (locally it will fail always)

## Screenshots
Screenshot 2023-09-19 at 17 02 31

## What areas of the site does it impact?
None are functionally impacted, this should only assist in background jobs being handled better after errors

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature

## Next Steps
Merge https://github.com/department-of-veterans-affairs/vets-api/pull/13907

### CODE REVIEW

**Review by tblackwe — APPROVED** [review]
LGTM!

**Review by tblackwe — APPROVED** [review]
Thanks! LGTM

**Review by tblackwe — APPROVED** [review]
ty for fixing the linting.

**Review by ryan-mcneil — APPROVED** [review]
👌

**Pull request merged**
