### PR TITLE
[SIMPLE_FORMS] feat: form remediation solution streamlining, test coverage, and documentation - PART 8

### PR DESCRIPTION
**Pull request by pennja**
## Summary

This solution is designed to remediate form submissions which have failed submission and are over two weeks old. It is composed of several Ruby on Rails service objects which interact with each other.

The primary use-case for this solution is for form remediation. This process consists of the following:

1. Accept a form submission identifier.
1. Generate an archive payload consisting of the original form submission data as well as remediation specific documentation:
    1. Hydrate the original form submission
    1. Hydrate any original attachments that were a part of this submission
    1. Generate a JSON file with the original metadata from the submission
    1. Generate a manifest file to be used in the remediation process
1. Upload the generated archive as a .zip file onto the configured S3 bucket
1. Optionally return a presigned URL for accessing this file

This solution also provides a means for storing and retrieving a single .pdf copy of the originally submitted form.

The following image depicts how this solution is architected:

Error Remediation Architecture Diagram_2024-10-07_14-14-25

- This work updates the form remediation solution to be configurable and usable by all other va.gov teams.
- This is part 8 of a larger PR which was too large and needed broken up. It removes all code which was replaced.

## Related issue(s)

- [Form Submission Remediation - Genericize S3 bucket archiving solution for external team usage](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1954)

## Testing done

- [x] New logic is covered by unit tests

## Requested Feedback

Any

### CODE REVIEW

**Review by Thrillberg — APPROVED** [review]
🔥 Burn it down! 🔥

**Review by stevenjcumming — APPROVED** [review]

**Comment by rmtolmach** [comment]
Danger is failing so this won't merge automatically. I've disabled auto-merge. @pennja since this PR is a couple weeks old, I'm going to update your branch with `master`.

**Comment by rmtolmach** [comment]
@pennja let me know when you're ready to merge this and I'll merge it for you :)

**Comment by pennja** [comment]
> @pennja let me know when you're ready to merge this and I'll merge it for you :)

@rmtolmach I'm ready when you are!

**Pull request merged**
