### PR TITLE
Set CC/Telehealth appointment to uncancellable

### PR DESCRIPTION
**Pull request by JunTaoLuo**
## Summary

- This change updates all CC and Telehealth appointments to uncancellable, like currently done for CnP and covid appointments
- This affects vaos APIs

## Related issue(s)

- [ZenHub Ticket](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/zh/326)

## Testing done

- [x] *New code is covered by unit tests*
- Verified that CC and Telehealth appointments are set to uncancellable.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
@cferris32 Did we ever find out whether we should treat "phone" appointments as telehealth?

**Comment by cferris32** [comment]
> @cferris32 Did we ever find out whether we should treat "phone" appointments as telehealth?

I believe we determined that they are different, so this should be the appropriate coverage for now

**Review by cferris32 — DISMISSED** [review]
LGTM

**Review by ryan-mcneil — DISMISSED** [review]
👍

**Review by cferris32 — APPROVED** [review]

**Pull request merged**
