### PR TITLE
Hca emis

### PR DESCRIPTION
**Pull request by lihanli**
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4230

### CODE REVIEW

**Comment by lihanli** [comment]
prefill happens when someone loads the first page of a form, frontend makes a call to `InProgressFormsController#show` and it will try to return a prefilled form. not sure how long the calls will take, we could initially release it only prefilling eMIS for accounts we have control of to test the speed, then we can consider backgrounding things.

**Comment by ayaleloehr** [comment]
Let's also make sure @J-Quag has eyes on this (well not the code itself but an understanding of what fields are getting prefilled where), just to make sure everyone is on the same page before it goes live!

**Comment by aub** [comment]
@J-Quag does unicorns have a plan in place for deploying this work if we want to test it on a limited set of users before going fully live? This is probably fine, but the idea of us making a handful of outbound API calls to a VA service while responding to a GET request makes me pretty nervous. If we did a limited release and added some timing capture to the code then we could get some data and make an informed choice before pushing it to everyone. One option there would be to do the prefill for some small percentage of users when they launch the form. I'll let you and @rtluu take it from here.

**Comment by aub** [comment]
Before he left, @lihanli and I talked about changing this to limit the users who it could apply to (initially to nobody) and adding some reporting on the time it took to make the eMIS requests. It looks like the former got done but not the latter, so that's what's remaining to be done here. I think once that's in we can go ahead and merge this since it's not going to apply to anyone at present.

@J-Quag and @rtluu I believe you should have a plan for how to roll this out some users who we've identified to make sure it's working properly and to get some metrics, once the timing code is in place and this is merged. In order to do that, we'll just need to add the EDIPI numbers for those users to the code temporarily.

**Comment by aub** [comment]
I talked with @saneshark about the timing aspects of this, and he pointed out that we already collect timing for entire controller actions. Since the eMIS calls are made within the controller action, we could track the performance of calls to our system that generate prefilled forms over time and report on that. Since this is entirely disabled for all users at present, I believe we are ready to merge it once specs pass.

**Pull request merged**
