### PR TITLE
Appeals status beta enablement

### PR DESCRIPTION
**Pull request by patrickvinograd**
Proposal for enabling appeals status beta.

Should consider adding a `can_access_appeals` method to the User class if there are additional conditions for accessing appeals status (i.e. similar to how evss claims requires ssn and edipi). I'm not sure of the business logic there.

### CODE REVIEW

**Comment by patrickvinograd** [comment]
I added an explicit conditional check for can_access_appeals so that that business logic is reflected in the code.

**Comment by patrickvinograd** [comment]
@bshyong Do you know where the other appeals status backend code is available right now? Is it in master or in a branch?

**Comment by bshyong** [comment]
@patrickvinograd I was working off `appealsII` but I couldn't find it yesterday. I think it was merged into kudos-launch or master at some point because I'm using kudos-launch locally to develop against

**Comment by patrickvinograd** [comment]
Ok, I will merge this to kudos-launch as well.

**Pull request merged**
