### PR TITLE
vic submission job reschedule job instead of sleeping

### PR DESCRIPTION
**Pull request by lihanli**
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8912
i kept one sleep in there so we don't send too many s3 api calls

### CODE REVIEW

**Comment by lihanli** [comment]
@patrickvinograd hey did you want to review this? i made the change we were talking about

**Comment by patrickvinograd** [comment]
Looking now

**Comment by patrickvinograd** [comment]
I think this is better than holding the worker thread, but I was thinking more along the lines of using Sidekiq's `perform_in` method to actually schedule the job for a later time, potentially even doing some kind of exponential backoff. That may not be warranted though. 

Thinking back to how this ties into the controller and UX - the submission job is asynchronous. So why is a 10 sec timeout important...does the frontend query the status of the submission and that's why we need to fail after a relatively short interval? 

In practice if we do develop a processing backlog, as things stand right now both the image processing jobs and the submit jobs are all on the same queue, so rescheduling the job will push it back to the end of the line and be unlikely to be serviced before the timeout interval. Queues are hard...

I think I'm okay with this as implemented but if you want to take a quick look at the sidekiq `perform_in` to see if it would make for a cleaner implementation, that's fine too.

**Comment by lihanli** [comment]
@patrickvinograd the frontend queries the status of the submission before the confirmation page, we did it this way because we don't have email notifications yet, so we can't wait too long on this job. i looked into `perform_in` earlier but according to [this](https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs) our version of sidekiq only checks for new jobs every 15 seconds so unless we want to change that to 1 second and make the load higher `perform_in` will probably reschedule the job too late.

if we have a processing backlog then the initial submit job won't even be run until after the image processing jobs are run, so the reschedule won't be needed.

**Comment by patrickvinograd** [comment]
Ok, in that case 👍

**Pull request merged**
