### PR TITLE
Update all references to FastJsonapi

### PR DESCRIPTION
**Pull request by yakschuss**
Currently, vets-api uses a gem called [fast_jsonapi](https://github.com/Netflix/fast_jsonapi). This gem is no longer being maintained as of 2018.

The inheritor to this project is a gem called [jsonapi-serializer](https://github.com/jsonapi-serializer/jsonapi-serializer)

The steps followed in this PR are outlined [here](https://github.com/jsonapi-serializer/jsonapi-serializer#migrating-from-netflixfast_jsonapi)

I could not find any reference to us using caching for our serializers, so no cache_options were updated.

Additionally, `VAOS#OperationOutcomeSerializer` has a `serialized_json` method that is build "with the FastJsonapi API". I wasn't sure if that should be refactored as well.

Please let me know what you think!

### CODE REVIEW

**Review by kreek — APPROVED** [review]
@yakschuss thanks for updating this! 👏🥳 it was on my todo list for the mobile endpoints, LGTM 🚀

**Comment by LindseySaari** [comment]
Does jsonapi-serializer have camel casing support? There's [currently a PR open](https://github.com/department-of-veterans-affairs/vets-api/pull/5811) that utilizes `set_key_transform :camel_lower`, which removes the dependency upon Olive Branch (a rack middleware) to transform snakecase keys to camel. I also made a comment on the PR I linked, maybe you both can discuss details 👍 I know we would like to eventually remove the dependency on Olive Branch from vets-api

**Comment by yakschuss** [comment]
> Does jsonapi-serializer have camel casing support? There's [currently a PR open](https://github.com/department-of-veterans-affairs/vets-api/pull/5811) that utilizes `set_key_transform :camel_lower`, which removes the dependency upon Olive Branch (a rack middleware) to transform snakecase keys to camel. I also made a comment on the PR I linked, maybe you both can discuss details 👍 I know we would like to eventually remove the dependency on Olive Branch from vets-api. I'm definitely in favor of these changes though, especially since fastjson is no longer maintained

It does! See [here](https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/README.md#key-transforms)

My understanding is that jsonapi-serializer is a fork of fast_jsonapi. Unfortunately, with the current jenkins test failures, it would indicate there are subtle differences that I need to explore in order to get this PR to pass through. 

As far as moving away from Olive Branch, this PR won't set us back.

**Comment by LindseySaari** [comment]
> > Does jsonapi-serializer have camel casing support? There's [currently a PR open](https://github.com/department-of-veterans-affairs/vets-api/pull/5811) that utilizes `set_key_transform :camel_lower`, which removes the dependency upon Olive Branch (a rack middleware) to transform snakecase keys to camel. I also made a comment on the PR I linked, maybe you both can discuss details 👍 I know we would like to eventually remove the dependency on Olive Branch from vets-api. I'm definitely in favor of these changes though, especially since fastjson is no longer maintained
> 
> It does! See [here](https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/README.md#key-transforms)
> 
> My understanding is that jsonapi-serializer is a fork of fast_jsonapi. Unfortunately, with the current jenkins test failures, it would indicate there are subtle differences that I need to explore in order to get this PR to pass through.
> 
> As far as moving away from Olive Branch, this PR won't set us back.

Great! Thanks for the info! Happy that you're taking this on 😃

**Review by ericboehs — APPROVED** [review]

**Review by SlakrHakr — APPROVED** [review]

**Pull request closed without merging**
