### PR TITLE
Add Overcommit

### PR DESCRIPTION
**Pull request by markolson**
Overcommit will run checks using git hooks against any staged code and commit messages before allowing the code to be committed or pushed. This example .overcommit.yml file follows what I've tended to use on past projects.

It's opt-in by running the `overcommit --install --sign` command, and can always be disabled or overridden if needed. Any changes made to the `.overcommit.yml` file or any plugins require `overcommit --sign` to be run again.

For an example of how it works, make one of the yaml configuration files invalid and try to commit it.

🚲 🏠

### CODE REVIEW

**Comment by jkassemi** [comment]
I'll speak to CI integration and not to the update to developer workflow. There's some functionality overlap with rubocop (newline detection), but we can throw this into the Jenkinsfile (or as part of the `ci` rake task).

**Comment by markolson** [comment]
I'm not entirely sure about the benefit of adding this to Jenkins, especially given the need to sign the `.overcommit` file whenever it changes. We'd have to run `overcommit -r`, which scans the entire repo instead of the just staged commits and could catch a lot more than is strictly necessary for the PR/branch itself.

**Comment by aub** [comment]
@markolson is it even possible to make it non-optional? I think it looks good but might change the language in the README to something that makes it seem more imperative, or at least gives a reason why one should install it.

**Comment by markolson** [comment]
Can do. I'll also change `bin/setup` as part of this to do a lot of what the README suggests, including enabling `overcommit`.

**Comment by aub** [comment]
@markolson that sounds perfect!

**Comment by markolson** [comment]
@aub I've added a (very likely overly complex) setup script for people using OS X which enables overcommit as part of the setup process.

**Comment by markolson** [comment]
@aub Updated the README. I also did a run-through where I deleted my homebrew, rubies, postgres, and redis and the script got me setup and running.

**Comment by aub** [comment]
!!! Awesome, let's do this.

**Pull request merged**
