### PR TITLE
remove deprecated 'branch' option

### PR DESCRIPTION
**Pull request by rmtolmach**
## Summary

This updates an action in the k8s branch to remove a deprecated option. It was removed here: https://github.com/EndBug/add-and-commit/commit/6fdb34ed01d242c909eeb7e31bf1c4d37db43a54 and we get warnings about it ([here](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/8649115753/job/23715334322), for example. Note: it's not making anything fail)
```
Warning: Unexpected input(s) 'branch', valid inputs are ['add', 'author_name', 'author_email', 'commit', 'committer_name', 'committer_email', 'cwd', 'default_author', 'fetch', 'message', 'new_branch', 'pathspec_error_handling', 'pull', 'push', 'remove', 'tag', 'tag_push', 'github_token']
```
Trying `new_branch`. Not having a branch option was pushing this to _all_ active branches, which we don't need. 

https://dsva.slack.com/archives/C0460N83Y9G/p1713967398724749

## What areas of the site does it impact?
k8s branch github action that pushes tag to manifest repo. 

## Testing
I'll watch CI after merge.

### CODE REVIEW

**Comment by RachalCassity** [comment]
@rmtolmach This commits the image tags to the manifest repo's main branch. The main branch should not be removed.

**Comment by rmtolmach** [comment]
@RachalCassity I believe it commits to the default branch (`main`) by default. The `branch` option is deprecated.

**Comment by RachalCassity** [comment]
The default branch would be k8s. Let me look into this more.

**Comment by rmtolmach** [comment]
But it's pushing into the manifest repo. 

This is definitely a low-priority item, it's just something I saw while on support. So if it feels too risky, we can just close it.

**Comment by RachalCassity** [comment]
The new_branch allows customizing the branch name. In this workflow, the default branch would be k8s. We are sending this to another repo and the k8s branch does not exist. We can add main as the new_branch
`new_branch: main`

**Comment by rmtolmach** [comment]
I want to reiterate that nothing is broken here. This PR would just remove the warning:
image

I don't know if we do need to add `new_branch`. From the [README](https://github.com/EndBug/add-and-commit/blob/main/README.md):
> If you want the action to commit in a new branch, you can use the `new_branch` input.
Please note that if the branch exists, the action will still try push to it, but it's possible that the push will be rejected by the remote as non-straightforward.

`main` isn't a new branch, though.

> By default the action runs the following command: `git push origin ${new_branch input} --set-upstream`.

So currently what it's running is `git push origin --set-upstream` and that seems to be working 🤷

**Review by RachalCassity — APPROVED** [review]

**Pull request merged**
