### PR TITLE
remove feature flag, all single issue CfI go to VRO

### PR DESCRIPTION
**Pull request by lukey-luke**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- Previously, this API call to Contention Classification service in VRO was behind a feature flag
- this feature flag has been removed to reduce technical debt and improve readability of future PR's

## Related issue(s)
- https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/260

## Testing done

- `bundle exec rspec spec/jobs/evss/disability_compensation_form/submit_form526_all_claim_spec.rb`

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by lukey-luke** [comment]
> Hi @lukey-luke, I noticed Ci isn't passing on this branch. I'm part of backend-review-group and I wanted to mention that one of the issues, Code Checks/Linting and Security, will be resolved once you update your branch with master.
Updated to latest version of master!

> 
> Also, to clarify, it sounds like the feature flag was already removed, but this PR just removes one remaining reference to it, is that correct?

Specifically, I am trying to keep all single contention CfI claims routed to VRO. I will then either reuse the existing feature flag or add a new one in order to route single contention NEW claims to VRO. Do you have a recommendation on which route to take? @gia-lexa

**Review by tyler-spangler6 — APPROVED** [review]
Approved

**Comment by lukey-luke** [comment]
[This logger  statement ](https://github.com/department-of-veterans-affairs/vets-api/blob/task-remove-existing-cc-ff/app/models/concerns/form526_claim_fast_tracking_concern.rb#L96) is causing the issues. I will submit a new PR to fix this in an effort to avoid reconciling divergent branches

**Comment by lukey-luke** [comment]
new pr here: https://github.com/department-of-veterans-affairs/vets-api/pull/13938

**Pull request closed without merging**
