### PR TITLE
bradl3yC - debt letters - Remove v2 feature flip

### PR DESCRIPTION
**Pull request by bradl3yC**
## Description of change
Remove the feature flip for V2.  The MVP will not be released and V2 is now the release version.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

### CODE REVIEW

**Review by camerontesterman — APPROVED** [review]

**Comment by erluti** [comment]
is this also being removed from frontend?

**Comment by bradl3yC** [comment]
Yes

**Comment by erluti** [comment]
Is there a Frontend PR that goes with this?

**Comment by bradl3yC** [comment]
Yes it’s https://github.com/department-of-veterans-affairs/vets-website/pull/14434

**Review by erluti — APPROVED** [review]
LGTM!  thanks for linking the partner PR

**Pull request merged**
