### PR TITLE
MHV-60102 SM: OH integration: requiresOHTriageGroup for alltriageteams API

### PR DESCRIPTION
**Pull request by oleksii-morgun**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- MHV SM API added requiresOHTriageGroup to alltriageteams API. This flag needs to be implemented on VA.gov backend and front-end. 

**GIVEN** A user is on `/my-health/secure-messages`
**WHEN** An application calls for alltriageteams API
**THEN** requiresOHTriageGroup flag is not included in API query and response does not include OH pools

**GIVEN** A user is on `/my-health/secure-messages-pilot`
**WHEN** An application calls for alltriageteams API
**THEN** requiresOHTriageGroup flag is included in API query and response does include OH pools

## Related issue(s)

- https://github.com/department-of-veterans-affairs/vets-website/pull/31616
- https://jira.devops.va.gov/browse/MHV-60102
- image

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by oleksii-morgun** [comment]
@KolbyVA  test

**Comment by oleksii-morgun** [comment]
> @KolbyVA test

another test

**Comment by oleksii-morgun** [comment]
@KolbyVA test

**Review by mmoyer-va — DISMISSED** [review]
Looks good to me.

**Review by rjohnson2011 — DISMISSED** [review]

**Comment by oleksii-morgun** [comment]
there were some spec requests changes pushed meanwhile causing merge conflicts, had to push another commit to resolve. @rjohnson2011 @mmoyer-va would you please re-approve? Thanks

**Review by mmoyer-va — APPROVED** [review]

**Review by rjohnson2011 — APPROVED** [review]

**Pull request merged**
