### PR TITLE
API-34017 update /generatePDF route docs

### PR DESCRIPTION
**Pull request by rockwellwindsor-va**
## Summary
* Updates route
	* Adjusts relevant tests
* Updates documentation in dev and prod

## Related issue(s)
[API-34017](https://jira.devops.va.gov/browse/API-34017)
Screenshot 2024-02-13 at 10 30 46 AM

## Testing done
- [x] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
     * The old endpoint just changed so instead of accessing `/services/claims/v2/veterans/veteran-icn/526/generatePDF/` you now need `/services/claims/v2/veterans/:veteran-icn/526/generatePDF/minimum-requirements`  
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
     * Hitting the old endpoint should error out and say the route does not exists.  Then hit the new endpoint and it should return PDF as expected
    
* When you request a token you need to make sure it has the correct scope on it, the scope value should be what is below
```
--scope=system/526-pdf.override
```
* Sample 526 to send to endpoint
````
{
  "data":{
    "type":"form/526",
      "attributes":{
        "claimDate": "2021-01-30",
        "claimProcessType":"STANDARD_CLAIM_PROCESS",
        "veteranIdentification": {
          "mailingAddress": {
            "addressLine1":"1234 Couch Street",
            "city":"Portland",
            "state":"OR",
            "country":"USA",
            "zipFirstFive":"12345"
          },
          "currentVaEmployee": false
        },
        "disabilities":[
          {
            "name":"vision loss",
            "serviceRelevance":"Heavy equipment operator in service",
            "approximateDate":"2017-07",
            "disabilityActionType":"NEW"
          }
        ],
        "serviceInformation":{
        "servicePeriods":[
          {
            "serviceBranch":"Air Force",
            "serviceComponent":"Active",
            "activeDutyBeginDate":"2015-11-14",
            "activeDutyEndDate":"2018-11-30"
          }
        ]
      },
      "claimantCertification":true
    }
  }
}
````

## Screenshots
Screenshot 2024-02-12 at 2 41 37 PM

## What areas of the site does it impact?
	modified:   modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
	modified:   modules/claims_api/config/routes.rb
	modified:   modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
	modified:   modules/claims_api/spec/requests/v2/veterans/rswag_disability_compensation_request_spec.rb

## Acceptance criteria
- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by mchristiansonVA — DISMISSED** [review]
Tested locally with new scope added to CCG token request, confirmed incorrect scope results in 401 unauthorized, and the correct scope was successful. Also confirmed the old route is inaccessible, and results in a 404 with message "There are no routes matching your request". Documentation updates look good also.

**Review by rileyanderson — DISMISSED** [review]
`OCTO-identity` doesn't actually own any of this code. Approving to unblock

**Comment by FonzMP** [comment]
> `OCTO-identity` doesn't actually own any of this code. Approving to unblock

Agreed. @department-of-veterans-affairs/backend-review-group - we're suggesting the changes to the CODEOWNERS file as all files associated with the token validation (both lib and specs) are Lighthouse elements focused around teams Dash, Pivot! and Banana Peels. For now, we'll act as the owners with the potential addition of Banana Peels in the future.

**Comment by rockwellwindsor-va** [comment]
@department-of-veterans-affairs/backend-review-group  Now seeing the merge conflict from the update from [this](https://github.com/department-of-veterans-affairs/vets-api/pull/15515) PR.  Please advise on who the proper owners of this should be so I can make sure to resolve the merge conflict correctly.  Thanks!

**Comment by FonzMP** [comment]
@department-of-veterans-affairs/lighthouse-banana-peels to be added as co(de)-owners of token_validation @rockwellwindsor-va

**Review by FonzMP — APPROVED** [review]
:shipit:

**Review by ericboehs — APPROVED** [review]

**Pull request merged**
