### PR TITLE
12423 remove all statsd from initializers

### PR DESCRIPTION
**Pull request by bosawt**
## Summary

- This PR removes unnecessary StatsD reset counters from all initializers. This should help anyone seeing metrics flipping back and forth between `count` and `rate` (making metrics appear to be performing unexpectedly)

## Related issue(s)
- department-of-veterans-affairs/vets-api#12423

## Testing done

- I started a Rails server and performed various actions to confirm that things worked fine and that StatsD were still reporting as expected

## What areas of the site does it impact?
Metric

## Acceptance criteria

- [ ]  Confirm that your own StatsD metrics still log as expected in `log/statsd.log

### CODE REVIEW

**Review by kpethtel — COMMENTED** [review]
I don't know much about statsd, but it looks like you're saying we're misusing the increment method. This looks like it should include some work on each team's part to maintain the metrics you're removing. Do we need any followup actions?

**Review by rmtolmach — APPROVED** [review]
Looks good. Follow-up with @kpethtel required.

**Comment by rmtolmach** [comment]
oh wait... I swear all the checks were passing a minute ago. But now they're not. Can you look into those @bosawt?

**Comment by bosawt** [comment]
> I don't know much about statsd, but it looks like you're saying we're misusing the increment method. This looks like it should include some work on each team's part to maintain the metrics you're removing. Do we need any followup actions?

I wouldn't go so far as to say we were 'misusing' it, just that there appears to have been a historic reason we were initializing these to 0, but as far as I can tell, that historic reason is no longer true.

Also, doing an increment reset in the initializers was at worst a no-op until the recent EKS switch, it was causing a ton of metric issues for us. And it's possible we could change how EKS reports metrics to fix it, but for now what was happening was:
- EKS instance would increment metric X whenever route on EKS was run, for whatever reason, Datadog would classify this metric as a `rate` type metric
- Any time BRD instance was deployed, it would 'reset' metric X with that 'increment 0' in the initializer, and for whatever reason, Datadog would classify the metric as `count` type metric
- The difference in `rate` versus `count` type metrics was taking a metric that was like 'X was incremented 100 times', and making it something really messed up like 'X was incremented 15.43 times'

**Comment by bosawt** [comment]
@rmtolmach Finally made it so specs are no longer breaking

**Review by kpethtel — APPROVED** [review]
Thanks for cleaning this up. I'm going to file a ticket for my team to review our use of statsd and evaluate whether we need to re-add any of the removed metrics (but without issues).

**Review by rmtolmach — APPROVED** [review]

**Pull request merged**
