### PR TITLE
Validate betamocks services config

### PR DESCRIPTION
**Pull request by kreek**
Goal of this is to catch betamocks services config errors/typos, like the one I made 👋 , originally was going to be a spec, but I don't think it applies to how the application runs in production. This will raise an error in dev and test envs if the `config/betamocks/services_config.yml` file fails to generate with interpolated vars from `config/settings.yml`

### CODE REVIEW

**Comment by omgitsbillryan** [comment]
I don't like that this would block someone who only wants to use some feature completely unrelated to mock data.  Now they are blocked needlessly (their feature would continue to work w/o mock data).

**Comment by omgitsbillryan** [comment]
> originally was going to be a spec 

I think I'd prefer to be a spec so as to prevent anyone from ever committing an invalid `services_config.yml` into `master. 

> but I don't think it applies to how the application runs in production

I'm not sure I fully understand what you mean by ^^

**Comment by kreek** [comment]
In a non-obvious way it does stop someone committing an invalid `services_config.yml` because specs can't pass if an initializer throws an error and the linter will reject your face 😄 

My initial concern about it being in a spec is that this is deep down a problem with betamocks, not vets-api itself (especially in production where we don't mock). IMO specs should not test dependencies, e.g. we don't test that ActiveRecord works. Which may be the answer?... That betamocks should validate it's own config and raise a more helpful error than the `NoMethodError` which is thrown when a services config var is nil.

**Comment by omgitsbillryan** [comment]
> In a non-obvious way it does stop someone committing an invalid services_config.yml because specs can't pass if an initializer throws an error and the linter will reject your face smile

A fair point :wink: 

> My initial concern about it being in a spec is that this is deep down a problem with betamocks, not vets-api itself

I thought the `NoMethodError on Nil Class` was because we tried to evauluate `Settings.doesnt_exist.something` - wouldn't this cause a `NoMethodError` no matter where we were sending such a value since `Settings.doesnt_exist` resolves to `nil`?

**Pull request merged**
