### PR TITLE
upgrade puma to 3.12

### PR DESCRIPTION
**Pull request by tskinn**
## Description of change
Upgrades puma server to version 3.12
There are two major changes with puma 3.0
- Ruby pre-2.0 is no longer supported. We'll do our best to not add features that break those rubies but will no longer be testing with them.
- Don't log requests by default.

This is required in order to use puma-plugin-statsd which is need to resolve https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/14065 (get more insight into server threads)

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by saneshark** [comment]
We will definitely want to test this on both vets.gov and va.gov after a production deploy and likely want to suspend off-cycle production deploys while we're testing. I'd also be curious to learn about other minor/major releases since we have not upgraded this gem in a really long time. Aside form the changes from the jump to 3.0, was there anything else of note in the minor releases?

**Comment by annaswims** [comment]
I've read through the change log and "Don't log requests by default - https://github.com/puma/puma/commit/03ed48ca903879f3b9a649f5df1cf9d6577ef3d2 was the only thing that jumped out at me as significant change in behavior, but easy to change our config, if necessary. 

Another commit that I don't fully understand the impact of is https://github.com/puma/puma/commit/8b12efab100cc5092e91a2099b3361c239184894

There were a lot of changes that were about using SSL & puma without ngixn, but all of our ssl config is with nginx, right?

**Comment by annaswims** [comment]
As of 3.12.0 ruby 2.2+ is required (still fine)

**Comment by annaswims** [comment]
@tskinn deployed to http://dev.va.gov and I was able to log in and make a handful of requests.  It seems to be good.  If there were any problems I'd expect them to be big (like puma not starting) rather than small, based upon what I read from the change log.

**Comment by annaswims** [comment]
🥂 Stage looks good too.

**Pull request merged**
