### PR TITLE
Validate edu benefits form field

### LINKED ISSUE #26: Validate Education Form Submissions against JSON Schema

### PR DESCRIPTION
**Pull request by lihanli**
closes #26

### CODE REVIEW

**Comment by saneshark** [comment]
@lihanli how did you get so many commits in this PR with only 2 files modified? :)

**Comment by lihanli** [comment]
dunno, it gave me a bunch of duplicate commits after hitting update branch

**Comment by saneshark** [comment]
I know you're not really touching the controller here, but in the controller you might want to do something with those validation errors using this: https://github.com/department-of-veterans-affairs/va-api-common/blob/master/lib/va/api/common/exceptions/validation_errors.rb

wrapping the resource in that raised exception will automatically catch it in application_controller and render the JSON errors object according to spec.

**Comment by markolson** [comment]
LGTM - Feel free to merge once tests pass.

**Pull request merged**
