### PR TITLE
[schema] Add field into VA Forms table

### PR DESCRIPTION
**Pull request by ncksllvn**
Per the danger bot I broke out the `schema.rb` changes from PR https://github.com/department-of-veterans-affairs/vets-api/pull/4719 into this PR.

## Description of change

Adds a field into the VA Forms table.

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/12027

## Things to know about this PR

It's a DB migration

### CODE REVIEW

**Comment by annaswims** [comment]
where is the migration file?  You shouldn't be making changes to schema.rb by hand.

**Comment by f1337** [comment]
> this shouldn't be merged without a migration file

ack, i totally missed that. good catch @annaswims !

**Comment by annaswims** [comment]
I think @charleystran is theoretically correct, but practically speaking we don't actually put our migrations in the modules.

**Comment by annaswims** [comment]
@f1337 Have you been making changes to Danger bot?

````
[2020-08-17T15:18:48.226Z] fatal: Couldn't find remote ref refs/heads/danger_base

[2020-08-17T15:18:48.480Z] fatal: Couldn't find remote ref refs/heads/danger_head

[2020-08-17T15:18:51.728Z] bundler: failed to load command: danger (/usr/local/bundle/bin/danger)

[2020-08-17T15:18:51.728Z] RuntimeError: Cannot find a merge base between danger_base and danger_head. If you are using shallow clone/fetch, try increasing the --depth

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/gems/danger-8.0.4/lib/danger/scm_source/git_repo.rb:138:in `find_merge_base'

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/gems/danger-8.0.4/lib/danger/scm_source/git_repo.rb:22:in `diff_for_folder'

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/gems/danger-8.0.4/lib/danger/danger_core/dangerfile.rb:270:in `setup_for_running'

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/gems/danger-8.0.4/lib/danger/danger_core/dangerfile.rb:280:in `run'

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/gems/danger-8.0.4/lib/danger/danger_core/executor.rb:29:in `run'

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/gems/danger-8.0.4/lib/danger/commands/runner.rb:73:in `run'

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/gems/danger-8.0.4/bin/danger:5:in `<top (required)>'

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/bin/danger:29:in `load'

[2020-08-17T15:18:51.728Z]   /usr/local/bundle/bin/danger:29:in `<top (required)>'

[2020-08-17T15:18:51.728Z] make: *** [danger] Error 
````

**Comment by ncksllvn** [comment]
@annaswims my branch may have just been too out of sync with master

**Pull request merged**
