### PR TITLE
Make this an api only app

### PR DESCRIPTION
**Pull request by saneshark**
these changes will make this an api only app, no more cookies.

### CODE REVIEW

**Comment by saneshark** [comment]
@shauni @robbiethegeek the cookie stuff is interfering with me, I'm changing the app to be api only and removing some of the rack middleware and unused gems.

@ayaleloehr if you have a moment can you look this over since you made similar changes to prescriptions?

**Comment by shauni** [comment]
I am all for this change, but was scared to bite the bullet because it seemed like it was going to take a while to untangle ... so thank you for taking it on and good luck :)

That said, taking cookies out completely right now without your redis session changes will break the ID.me demo & the build ... I agree, the stateless, token-only approach is the right way to go, but we'll be in a weird spot until we have a demo client.

**Comment by saneshark** [comment]
@shauni that's true maybe I will add the cookie stuff back in and test to make sure that this PR can stand on its own two legs. Then just remove cookies in my other PR.

**Comment by shauni** [comment]
Ok, I guess I lied about the build breaking, but that means our tests aren't very good (which we knew already)

**Comment by saneshark** [comment]
I went ahead and added the 2 files for session cookie and cookie serialization, and temporarily set application.rb and application_controller to utilize all of actiondispatch. I marked these files with TODO for easy removal in separate PR.

**Comment by saneshark** [comment]
Ahh, i need to add back the cross site forgery check again since we're using cookies again. That check is no longer required when move off of cookies.

**Comment by ayaleloehr** [comment]
Looks like @shauni gave this the conceptual OK and I'm giving this a LGTM saying this matches what I did on the prescriptions-api side to remove all the unnecessary asset serving sections as well as many unused gems from roadrunner-rails. Other than adding rails-api, this PR exclusively removes things and add TODOs so it feels safe to merge. (if anyone prefer me not to merge on this repo in the future, please let me know!  not sure on the proper etiquette here)

**Comment by saneshark** [comment]
Thanks! we can always revert if it comes to that. I made sure to mostly just comment stuff out, so adding things back in shouldn't be too difficult should we require them.

**Comment by robbiethegeek** [comment]
This is great thanks @saneshark for doing this!

**Pull request merged**
