### PR TITLE
BE | Ask VA API:  Update Translator and deprecate Categories, Topics, Subtopics, and Optionset

### PR DESCRIPTION
**Pull request by Khoa-V-Nguyen**
## Summary

Refactor Translator Class and Update Dependencies Across Codebase

This PR introduces a series of refactors aimed at improving code readability, maintainability, and overall performance, with a focus on the Translator class and associated dependencies across the InquiryPayload, SubmitterProfile, VeteranProfile, and testing setup.

Key Changes:

1. Translator Class Refactor
 • Enhanced readability and modularity by extracting mappings to a MAPPINGS constant within to_snake_case, simplifying future updates.
 • Improved error handling in fetch_optionset, providing detailed context on retrieval failures.
 • Updated call method to handle missing keys in optionset data, ensuring robust error management.
 • Refactored to_snake_case to efficiently handle special-case transformations and remove unnecessary prefixes.
2. Updates to InquiryPayload, SubmitterProfile, and VeteranProfile
 • Adapted these classes to align with the refactored Translator structure and methods.
 • Adjusted method calls and key handling to ensure compatibility with the new Translator class, maintaining functionality across dependent classes.
3. StaticDataController and BaseRetriever Cleanup
 • Removed deprecated Categories, Topics, Subtopics, and Optionset references from StaticDataController and BaseRetriever.
 • Updated logic to support the current data structure and tested for backward compatibility, improving codebase maintainability by removing obsolete dependencies.
4. Improved Specs for Cached Optionset Data
 • Updated specs to use JSON data directly from get_optionset_mock_data.json for clarity.
 • Replaced optionset_cached_data with a cached_data variable that directly parses data from the JSON file, simplifying the test setup and ensuring consistency with mock data.

These changes collectively enhance the clarity, reliability, and maintainability of the codebase, particularly around translation logic, data structure updates, and test data setup.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/ask-va/issues/1463

## Testing done

- [x] *New code is covered by unit tests*
- I implemented the /contents endpoint in earlier PRs to replace the existing categories, topics, and subtopics endpoints. Since the optionset classes were not in use, I have also deprecated those.
The Frontend team has fully transitioned to using /contents, and my team has verified that everything is functioning as expected with this new structure.
With this confirmation, I have approval to proceed with deprecating the old endpoints.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected

### CODE REVIEW

**Comment by Khoa-V-Nguyen** [comment]
> 1 Error
> 🚫	This PR changes `788` LoC (not counting whitespace/newlines).
> In order to ensure each PR receives the proper attention it deserves, those exceeding `500` will not be reviewed, nor will they be allowed to merge. Please break this PR up into smaller ones.
> 
> If you have reason to believe that this PR should be granted an exception, please see the [Submitting pull requests for approval - FAQ](https://depo-platform-documentation.scrollhelp.site/developer-docs/Submitting-pull-requests-for-approval.655032351.html#Submittingpullrequestsforapproval-FAQ).
> 
> File Summary
> Big PRs are difficult to review, often become stale, and cause delays.
> 
> Generated by 🚫 [Danger](https://danger.systems/)

This is due to depracating Categories, Topics, Subtopics, and Optionset

**Review by hemeshvpatel — APPROVED** [review]
Lgtm

**Comment by Khoa-V-Nguyen** [comment]
> 1 Error
> 🚫	This PR changes `969` LoC (not counting whitespace/newlines).
> In order to ensure each PR receives the proper attention it deserves, those exceeding `500` will not be reviewed, nor will they be allowed to merge. Please break this PR up into smaller ones.
> 
> If you have reason to believe that this PR should be granted an exception, please see the [Submitting pull requests for approval - FAQ](https://depo-platform-documentation.scrollhelp.site/developer-docs/Submitting-pull-requests-for-approval.655032351.html#Submittingpullrequestsforapproval-FAQ).
> 
> File Summary
> Big PRs are difficult to review, often become stale, and cause delays.
> 
> Generated by 🚫 [Danger](https://danger.systems/)

This is due to deprecating Categories, Topics, Subtopics, and Optionset

**Review by hemeshvpatel — APPROVED** [review]
lgtm

**Review by rmtolmach — APPROVED** [review]

**Pull request merged**
