### PR TITLE
Suppresses expected RecordNotFound reporting in Sentry for ConnectedApplications controller

### PR DESCRIPTION
**Pull request by patrickvinograd**
## Summary

Adds the "IgnoreNotFound" mixin to the Connected Applications Controller. This suppresses reporting of RecordNotFound responses in Sentry, in an attempt to reduce the noise in that tool so true issues can be more easily observed. These are expected responses for users who do not have any connected applications and are not in Okta. 

## Related issue(s)
http://sentry.vfs.va.gov/organizations/vsp/issues/71505/?environment=production&project=3&query=is%3Aunresolved+RecordNotFound&statsPeriod=14d

## Testing done
None, but this mixin is used successfully in other controllers where RecordNotFound is expected and not worth reporting to Sentry. 

## Screenshots
None.

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

Looking for concurrence/merge by the team that owns the VA.gov Profile application.

### CODE REVIEW

**Review by tpharrison — DISMISSED** [review]
LGTM!

**Review by tpharrison — APPROVED** [review]
Thank you for making this update.  My team will be reviewing and updating the CODEOWNERS file this sprint.

**Comment by patrickvinograd** [comment]
@tpharrison I took a stab at updating codowners - assigned everything under app/controllers/v0/profile to your team. But now I see a merge conflict. If you want to just take over this PR and merge at your leisure, I'm comfortable with that.

**Comment by tpharrison** [comment]
@patrickvinograd I'm fine with that.

**Pull request merged**
