### PR TITLE
[facility locator] updating show method and provider model

### PR DESCRIPTION
**Pull request by SimonSchama**
## Description of change
Alters the code around fetching details for community care providers based on breaking changes made to the ProviderServices model in PPMS. This fixes the details page for community care providers and has the side effect of eliminating one additional call to ppms for retreiving location information for a provider.

## Testing done
Tested API in review instance environment to ensure that errors on the affected endpoint were resolved and data was coming though.

## Testing planned
Will test in staging after PR is merged and in production after code is deployed.

#### Unique to this PR
- [x] 'show' endpoint for ccp_controller no longer returns 500 errors.

#### Applies to all PRs

- [x] Appropriate logging
- [x] Swagger docs have been updated, if applicable
- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by rtluu** [comment]
@department-of-veterans-affairs/backend-review-group can someone from the group give this a review? Thanks!

**Comment by SimonSchama** [comment]
Unfortunately I don't have an issue to link for this, I discovered it myself after a call with ppms yesterday and immediately started working with them to get it resolved.

**Comment by kfrz** [comment]
Is there a spec/mock in place to ensure that the appropriate expected responses are returned?

**Comment by SimonSchama** [comment]
There are specs for the relevant ccp_controller that invokes this call and a spec in the ppms_client for this specific call. I could update the spec/VCR cassette for that second spec since the data/the way we're using it has changed.

**Pull request merged**
