### PR TITLE
Add spring rspec

### PR DESCRIPTION
**Pull request by lihanli**

### CODE REVIEW

**Comment by saneshark** [comment]
LGTM other than the aforementioned caveat

**Comment by saneshark** [comment]
https://github.com/rails/spring/issues/113

**Comment by saneshark** [comment]
possibly consider adding this work around to rails_helper.rb with a comment as to why it is needed. Please also test to make sure that this is in fact an issue.

```
config.seed = srand % 0xFFFF unless ARGV.any? { |arg| arg =~ /seed/ }
```

**Comment by saneshark** [comment]
Alternately, why not just have the guardfile run `bin/rake` ? that way you're testing everything that travis tests, including rubocop and other linters. I'm not entirely sure we need these other gems.

**Comment by lihanli** [comment]
@saneshark guard runs rubocop on just a single file when it is changed but it runs rspec on all files on every change because a single file change could affect other tests. if we just have bin/rake then it will run everything on all files on every change which will be slower

**Comment by saneshark** [comment]
Yea, fair point, I've had all kinds of problems with guard in the past, particularly with Celluloid dependency that it has so I generally try to stay away from it if I can help it, but I'm +1 for this as long as we can just remove it if there is some broken dependency issue in the future that can't be easily resolved.

**Comment by lihanli** [comment]
sounds good, i haven't used it much before but it's been helpful since i forget to run linters sometimes

**Comment by saneshark** [comment]
hmmm, i'm not sure why that test would suddenly fail, could you try running it locally with the seed that travis used and seeing if the test is fragile for some reason? I deliberately tried to give it a huge range so that it would not be fragile.

**Comment by lihanli** [comment]
fixed now

**Comment by saneshark** [comment]
LGTM

**Pull request merged**
