### PR TITLE
23925 QR pdf updates

### PR DESCRIPTION
**Pull request by dillo**
## Description of change

- Display timezone next to appointment date and time
- Display time in the pacific timezone for our test pilot
- Implementing style updates for the design team

## Original issue(s)
department-of-veterans-affairs/va.gov-team#23925

## Things to know about this PR

- [x] Feature flag.

- [x] RSpec tests written and passing

### CODE REVIEW

**Review by mdewey — APPROVED** [review]
LGTM

**Review by cbtkc — COMMENTED** [review]
Are all of these fonts needed? Are the italic fonts being used?

**Comment by dillo** [comment]
> Are all of these fonts needed? Are the italic fonts being used?

@cbtkc Yes, the fonts came as a package and the design team will be using those in the future within health_quest.

**Review by mdewey — APPROVED** [review]
LGTM

**Pull request merged**
