### PR TITLE
quickfix nil check on appointment requested periods

### PR DESCRIPTION
**Pull request by cferris32**
## Summary

- fix to address bug noticed in processing appointment requested periods, using safe navigation and nil checking

### CODE REVIEW

**Review by JunTaoLuo — COMMENTED** [review]
Nice catch. Let's also add a unit test for the scenario.

**Review by JunTaoLuo — APPROVED** [review]
LGTM!

**Comment by cferris32** [comment]
looks like we still need an approval from @department-of-veterans-affairs/backend-review-group

**Review by rjohnson2011 — APPROVED** [review]

**Comment by cferris32** [comment]
need one more approval from @department-of-veterans-affairs/backend-review-group at your convenience, tysm

**Review by rjohnson2011 — APPROVED** [review]

**Pull request merged**
