### PR TITLE
Mobile: Update demographics policy and update all associated controllers and …

### PR DESCRIPTION
**Pull request by Tonksthebear**
…service to use policy

## Summary
We have confirmation on who should be able to update gender identity and preferred name. The policy is now updated to reflect that

## Related issue(s)
- [department-of-veterans-affairs/va.gov-team#5776](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5776)

## Testing done
Updated all tests to ensure they still pass

## What areas of the site does it impact?
Preferred name and gender updating

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by Tonksthebear** [comment]
I changed a couple of things outside of our module on behalf of @tpharrison for the mobile team members wondering why there are changes outside of mobile

**Comment by Tonksthebear** [comment]
I had to change one swagger test @tpharrison let me know if I should have fixed it another way

**Review by jperk51 — APPROVED** [review]

**Review by kpethtel — APPROVED** [review]
Love to see this cross team collaboration. Using the demographics policy as the source of truth is a nice improvement. I'm not exactly sure why this allowed us to simplify the spec setup, but I'm happy to see that too. Nice improvements.
🚀

**Review by ryan-mcneil — APPROVED** [review]
Appreciate all the reviews!

**Comment by jperk51** [comment]
@Theresa-Gainsburg

**Pull request merged**
