### PR TITLE
update checkboxes to be x's

### PR DESCRIPTION
**Pull request by evansmith**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

-YES va_burial_v2
- Changed the formatting of the PDF to check boxes as X instead of a square.
- Altered the properties within adobe acrobat
- VA Benefits and Claims

## Related issue(s)

[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80695)

## Testing done

- [ ] *New code is covered by unit tests*
- Prior, checkboxes were filled in by squares or dots.
-Fill out a claim and verify the generated PDF has X's in the boxes. Alternatively, pull a blank copy of the pdf from the repo and confirm manually.

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
Burials V2

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by tblackwe — APPROVED** [review]
Downloaded the file and validated manually.

**Review by rmtolmach — APPROVED** [review]
Is this your team's form? If so, you could add it to CODEOWNERS, because right now CODEOWNERS is falling back on this line:
```CODEOWNERS
lib/pdf_fill @department-of-veterans-affairs/vsa-debt-resolution @department-of-veterans-affairs/backend-review-group @department-of-veterans-affairs/vfs-10-10 @department-of-veterans-affairs/vfs-1095-b
```
Tag me if you end up changing CODEOWNERS and I'll re-review.

**Comment by tblackwe** [comment]
Lib/pdf_fill is not owned by our team. It is core functionality leveraged by several different teams.

**Comment by tblackwe** [comment]
I asked Evan to merge as is, we are auditing all our forms for ownership and will get them updated in a separate pr

**Pull request merged**
