### PR TITLE
Fixing bad documentation for valid_pdf

### PR DESCRIPTION
**Pull request by bastosmichael**
## Description of change
Documentation error is showing the valid_pdf as being an integer instead of it's stated boolean in the example. They also needed us to remove the forms_details_url for now until they are ready for production.

## Original issue(s)
https://vajira.max.gov/browse/API-2585
https://vajira.max.gov/browse/API-2654

### CODE REVIEW

**Comment by ryanlink** [comment]
Michael Bastos(NONFED) it's not just the documentation according to the example response payload he sent for `form_name VA10192`:

`"valid_pdf": 3,`

**Review by ryanlink — CHANGES_REQUESTED** [review]
@bastosmichael  it's not just the documentation according to the example response payload he sent for `form_name VA10192`:

`"valid_pdf": 3,`

**Comment by templeman15** [comment]
Looks good to me other than Ryans comment. CI is also failing due to the security check.

**Review by templeman15 — APPROVED** [review]
👍

**Review by ncksllvn — APPROVED** [review]
LGTM. Good thinking doing the override in the serializer

**Pull request merged**
