### PR TITLE
Enable Zeitwerk

### PR DESCRIPTION
**Pull request by ericboehs**
Remove use of `config.autoloader = :classic`.

These changes must go with enabling zeitwerk:
Add underscore to va forms workers. -- Resolves https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10641.

Have autoloader ignore erb files for education forms. -- Resolves https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15891

### CODE REVIEW

**Comment by erluti** [comment]
This is as breezy as I had hoped! LGTM

**Comment by ericboehs** [comment]
@erluti Guess I'll need a real review for merge.

**Review by thilton-oddball — APPROVED** [review]
LGTM

**Comment by erluti** [comment]
Did you find any specs for these?  Let's hold off on this merge because I tried to do this in a parallel place `app/models/saved_claim/education_benefits/` and it's specs are failing.  I think this changed is blocked by the VA inflection

**Comment by erluti** [comment]
If this comes together well, it will resolve https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10183

**Comment by erluti** [comment]
Running into cascading zeitwerk issues, so after merging latest master I've decided to make my tweaks here to see what will get us across the line for enabling zeitwerk https://github.com/department-of-veterans-affairs/vets-api/pull/5225

**Pull request merged**
