### PR TITLE
[CST] Override 'PMR Pending' tracked items to all have the status 'NEED_FROM_OTHERS'

### PR DESCRIPTION
**Pull request by iandonovan**
## Summary

- This work is behind a feature toggle (flipper): **NO**
- TrackedItems within Claims with the `displayName` of `"PMR Pending"` will now all have their `status` fields reported as `NEEDED_FROM_OTHERS` to the web and mobile clients.
- There is a request out to BGS to recategorize these Items even further upstream, but that could take months. This is a unified workaround to consolidate code in an area where both the web and mobile clients retrieve it.
- Benefits Management 2

## Related issue(s)

- [Original request](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9671)
- [Backend investigation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95618)
- [Ticket for backend implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96081)

## Testing done

- [ ] *New code is covered by unit tests*
- PMR Pending tracked items were incorrectly reported as `NEEDED_FROM_YOU` even though the veteran does not have an action to take.
- PMR Pending tracked items will be in a new section on the website and mobile app.

## What areas of the site does it impact?
Mobile and web client, the veteran's view of their actionable items.

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

This is my first issue, so I am interested in feedback around

1. Code style
2. How I should work with this sort of ticket going forward. I used `claims_api/.../swagger.json` as my source for what the response will actually look like, but if that's inaccurate, this code will not work. How can I make sure I definitely, for certain, know what the json schema I am modifying looks like?

### CODE REVIEW

**Review by dysbo — DISMISSED** [review]
looks great, clean and tests are passing and a ruby novice like me can tell what is happening 😄

**Comment by rmtolmach** [comment]
@iandonovan Can you add or update any testing in spec/lib/lighthouse/benefits_claims/service_spec.rb?

Can you also update [this line in the CODEOWNERS file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/CODEOWNERS#L930) to fix the typo? it needs an `s` after `benefit`. I was wondering why backend-review-group was the only codeowner!! 😄

**Comment by iandonovan** [comment]
> @iandonovan Can you add or update any testing in spec/lib/lighthouse/benefits_claims/service_spec.rb?
> 
> Can you also update [this line in the CODEOWNERS file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/CODEOWNERS#L930) to fix the typo? it needs an `s` after `benefit`. I was wondering why backend-review-group was the only codeowner!! 😄

Sure thing!

Should I do the same to the line beneath it (931), since that has the same typo? benefit_claims --> benefits_claims.

**Comment by rmtolmach** [comment]
> > @iandonovan Can you add or update any testing in spec/lib/lighthouse/benefits_claims/service_spec.rb?
> > Can you also update [this line in the CODEOWNERS file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/CODEOWNERS#L930) to fix the typo? it needs an `s` after `benefit`. I was wondering why backend-review-group was the only codeowner!! 😄
> 
> Sure thing!
> 
> Should I do the same to the line beneath it (931), since that has the same typo? benefit_claims --> benefits_claims.

Yes, please! good catch

**Comment by iandonovan** [comment]
> > > @iandonovan Can you add or update any testing in spec/lib/lighthouse/benefits_claims/service_spec.rb?
> > > Can you also update [this line in the CODEOWNERS file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/CODEOWNERS#L930) to fix the typo? it needs an `s` after `benefit`. I was wondering why backend-review-group was the only codeowner!! 😄
> > 
> > 
> > Sure thing!
> > Should I do the same to the line beneath it (931), since that has the same typo? benefit_claims --> benefits_claims.
> 
> Yes, please! good catch

All set, thank you! Good morning as well.

**Review by dysbo — APPROVED** [review]

**Review by rmtolmach — APPROVED** [review]

**Pull request merged**
