### PR TITLE
Updates sidekiq worker file to log warnings to console when retry limit is exhausted

### PR DESCRIPTION
**Pull request by asmithgovcio**
## Summary

- *This work is behind a feature toggle (flipper): NO*
- *This sets a sidekiq worker to retry up to 14 times before it dies*
- *Currently seeing errors in datadog monitors for this sidekiq worker hitting its retry limit, there is no useful logging in place to figure out why they are failing only that there is a failure. This fix should hopefully increase logging visibility to make finding out what the main cause is for the failures. 
-*debt-devs (debt-api team [vets-api project])*

## Related issue(s)
 
Screenshot 2024-02-13 at 4 58 51 PM

## Testing done

- [X] *New code is covered by unit tests*

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X]  No error nor warning in the console.
- [X]  Events are being sent to the appropriate logging solution
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by ericboehs** [comment]
I'm trying to understand the request better. The job was already retrying 25 times by default. This looks to be lowering the retry count.

I believe the original ask concerns what happens when it stops retrying. The job just dies and does nothing and the data is lost forever unless it can be recovered from logs.

I believe what you need to do is add [a hook for sidekiq_retries_exhausted](https://github.com/sidekiq/sidekiq/wiki/Error-Handling#configuration).

**Comment by asmithgovcio** [comment]
Thank you @ericboehs I think you're right, I added a check for the workers to log when they've exhausted their retry limit and removed the retry limit of 14 that I created previously. With these improvements I should be able to find the cause of the failures

**Review by kjsuarez — APPROVED** [review]
lgtm

**Comment by asmithgovcio** [comment]
Not responsible for this section of the application, punting to someone who is responsible

**Pull request closed without merging**
