### PR TITLE
Remove my_va_lighthouse_claims feature flag

### PR DESCRIPTION
**Pull request by DanielMiller-agile6**
## Summary

- removes `my_va_lighthouse_claims` feature flag from config/features.yml
- this feature flag is no longer used by MyVA now that evss -> lighthouse migration is complete
- MyVA Auth Exp Team

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/59817
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/61808

Note: the related [vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25974) to remove usage of this flag should be merged and deployed first.

## Testing done

- verified removal of feature flag locally
- specs pass locally

## What areas of the site does it impact?
This feature flag was used by MyVA while migrating from evss to lighthouse, so that MyVA code could use one service or the other in case we needed to switch.  Once the related vets-website PR is merged, this flag will no longer be used by vets-website.

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

This is my first vets-api PR, so let me know if there's anything else you need from me :)

Also, I saw the "removing feature toggle" docs from the platform website (https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles) and don't have access to ArgoCD yet.  I will need someone to help with the manual removal of these flags from the DB when ready.  How do I go about creating a support request for that?

### CODE REVIEW

**Review by allisonlu — APPROVED** [review]

**Review by rmtolmach — APPROVED** [review]
@DanielMiller-agile6, there is a bug in our job that deletes flippers after they're removed from features.yml, so they're not actually removed. It will need to be deleted manually (step 3 [in these docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)) from each env in ArgoCD terminal **AFTER your changes have been deployed to each env.** Do you have the ArgoCD permissions to do that or do you need me to?

**Comment by tpharrison** [comment]
@DanielMiller-agile6 @rmtolmach I am going to be removing another feature flag tomorrow so I can remove this as well.  Thanks.

**Comment by DanielMiller-agile6** [comment]
I don't have access to ArgoCD, so I will need some help with that.  Thanks for the assistance Tom & Rebecca!  We may need to wait to merge [this vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25974) first, before merging this one though, since that code removes the remaining feature flag usage in MyVA, so not sure if this will be ready by tomorrow.

**Comment by tpharrison** [comment]
@DanielMiller-agile6 I'll wait to hear from you before removing it.

**Comment by DanielMiller-agile6** [comment]
@tpharrison will do.  thanks Tom!

**Comment by DanielMiller-agile6** [comment]
@tpharrison this PR is merged now that FE changes have been deployed, so let me know if you still have time to remove these from the DB this week. otherwise i can make a support request :)

**Comment by tpharrison** [comment]
@DanielMiller-agile6 I can remove them tomorrow.  I'll let you know when they're gone.

**Comment by tpharrison** [comment]
@DanielMiller-agile6 I removed the feature flag from dev and staging, but it doesn't look like this made it to prod yet.  Want me to hold off on removing it from prod?

**Comment by DanielMiller-agile6** [comment]
Thanks Tom! Yea, we can hold off until it gets to prod.  Not urgent, since the FE code is no longer using the flag 👍

**Comment by tpharrison** [comment]
@DanielMiller-agile6 Ok to remove this from prod?

**Comment by DanielMiller-agile6** [comment]
support request to remove this flag from prod is complete 👍

**Pull request merged**
