### PR TITLE
Forms API: parse out characters that break json

### PR DESCRIPTION
**Pull request by gmrabian**
We had a production issue where users entered newlines or tabs in a text area and it broke a JSON.parse in the backend. this code removes all possible offending characters.

## Summary

- Remove offending JSON characters

## Testing done

- Tested locally with newlines and tabs (the ones we've seen so far) and it worked

## What areas of the site does it impact?
Forms (only 26-4555 so far)

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by rmtolmach** [comment]
@gmrabian Is this something you could test on your review instance? http://647fca2770cd2190f712c271614ca249.review.vetsgov-internal/

**Comment by gmrabian** [comment]
@rmtolmach yes thank you!
I filled out the form in the deployed instance, with bad characters in the payload as such:
`..."remarks":"stuffhere; \tand also this; \tand here"...`
and it submitted successfully!

**Comment by jeremy6d** [comment]
I wonder if we could capture this validation of proper functionality in a unit test? That way if anybody wondered why the behavior changed there would be some documentation of this.

**Comment by rmtolmach** [comment]
Awesome! Glad it's working in the review instance @gmrabian! Like Jeremy mentioned, can you add a unit test for this?

**Comment by gmrabian** [comment]
that's a good point. i added some tab and newline characters to our sample payload so we can verify it works as expected within our flow.
payload:
`..."remarks": "Lengthy remarks here \nabout what is needed\tand such"...`

resulting text in document:
Screenshot 2023-04-14 at 9 58 43 AM

**Review by rmtolmach — APPROVED** [review]
LGTM!

**Pull request merged**
