### PR TITLE
Add auth configuration for staging API

### PR DESCRIPTION
**Pull request by acrollet**
## Summary

- Adds auth config for the AVS API

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#62215

## Testing done

The API currently runs against mocks and [only the dev environment will be affected at this time](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2253), testing will happen there.

## What areas of the site does it impact?
- AVS module and under development app

### CODE REVIEW

**Comment by acrollet** [comment]
Thanks @gia-lexa , it looks like the CODEOWNERS info was removed in https://github.com/department-of-veterans-affairs/vets-api/commit/56ffb7706072ed51a60b00f39eabfa4dc5af0b08 - I'll add it back in this PR but cc'ing @RachalCassity in case it was intentional or there's anything else we should know 🙂

**Comment by acrollet** [comment]
@gia-lexa tests are looking good now 🙂

**Review by mdewey — APPROVED** [review]
LGTM!

**Comment by acrollet** [comment]
@gia-lexa could I get a re-review when you're able? Thanks! 🙂

**Pull request merged**
