### PR TITLE
19897 add mobile appointments cache flag (VCR cassettes only)

### PR DESCRIPTION
**Pull request by kreek**
## Description of change
Splitting up PR https://github.com/department-of-veterans-affairs/vets-api/pull/5948 this one is just the VCR cassettes.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#19897

### CODE REVIEW

**Review by jperk51 — APPROVED** [review]
LGTM

**Comment by kreek** [comment]
@thilton-oddball I noticed there's exceptions for large files with these paths
```*.csv, *.json, *.tsv, *.txt, Gemfile.lock, app/swagger, modules/mobile/docs, spec/fixtures/, spec/support/vcr_cassettes/``` 

could we get our mobile modules spec supports files/dirs added to that list? 
`modules/mobile/spec/support/{fixtures, schemas, vcr_cassettes}`

**Comment by ericboehs** [comment]
If you need to get this through, I can disable the danger check when you're ready to merge.

**Review by ericboehs — APPROVED** [review]

**Comment by kreek** [comment]
thanks @ericboehs this is ready to go now if you could push it through that would be appreciated 😄

**Pull request merged**
