### PR TITLE
MHV-49867 Filter out inactive FHIR records

### PR DESCRIPTION
**Pull request by mmoyer-va**
## Summary

- Due to recent changes to the MHV MR FHIR APIs, we now need to specifically request only active records.
- Quick change to session's redis key, making it ICN instead of MHV Correlation ID, per Patrick's comment here: https://github.com/department-of-veterans-affairs/vets-api/pull/13969#issuecomment-1741335318
- Updated CODEOWNERS to better reflect medical records file ownership

### [MHV-49867](https://jira.devops.va.gov/browse/MHV-49867) - Filter FHIR records to select only "active" records ###

> Because of the way we are now handling "entered-in-error" records, we will need to make sure we only display active records in the frontend.
> 
> This can be done by filtering when making the FHIR call.
> 
> Append "clinical-status=active"

## Testing done

- Updated the relevant VCR cassettes to reflect the new API calls
- Verified manually that passing the new parameter returns the right results to the user interface

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
MHV Medical Records

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by Wyzardsleeves — APPROVED** [review]
Approved!

**Review by mattwrightva — APPROVED** [review]
Ok!

**Comment by rmtolmach** [comment]
@mmoyer-va Please fix failing tests.

**Comment by mmoyer-va** [comment]
> @mmoyer-va Please fix failing tests.

@rmtolmach Sorry about that! I thought I had updated all the relevant tests but I missed a batch.

**Pull request merged**
