### PR TITLE
 Use New Status Field to Maintain InProgressForm Data for Dependents Application

### PR DESCRIPTION
**Pull request by tfink419**
## Summary

- In case of failure, InProgressForm is no longer deleted and now a status field is updated and the forms are not shown if the field is set
- Code is split into 3 PR's
  - department-of-veterans-affairs/vets-api/pull/15873
  - department-of-veterans-affairs/vets-api/pull/16094
  - department-of-veterans-affairs/vets-api/pull/16097

## Related issue(s)
department-of-veterans-affairs/va.gov-team/issues/77171

## Testing done
- [ ] *New code is covered by unit tests*
- In progress form would be deleted immediately, now it is saved until submission succeeds or fails the final time
- Submit a dependents change application and check if the form still appears immediately after submission, and that it will reappear after the status is changed back (normally after failures)

## Screenshots
Pending Submission:
Screenshot 2024-03-15 at 15 38 16

Processing Submission:
Screenshot 2024-03-15 at 15 38 35

## What areas of the site does it impact?
Dependents application submission

## Acceptance criteria

- [x] ~ I fixed|updated|added unit tests and integration tests for each feature (if applicable). ~
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  ~Documentation has been updated (link to documentation)~
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  ~If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected~
- [x]  ~I added a screenshot of the developed feature~

### CODE REVIEW

**Review by tblackwe — APPROVED** [review]

**Review by micahaspyr — DISMISSED** [review]
👍

**Review by bramleyjl — APPROVED** [review]

**Comment by RachalCassity** [comment]
@tfink419 Can you confirm the CODEOWNERS file is correct for all of these files? Should the @department-of-veterans-affairs/benefits-dependents-management be added to these other files in CODEOWNERS?

**Review by tblackwe — DISMISSED** [review]

**Comment by RachalCassity** [comment]
@tfink419 Is this PR still relevant?

**Comment by tfink419** [comment]
> @tfink419 Is this PR still relevant?

@RachalCassity
Yes this PR needs to be approved and merged

**Comment by RachalCassity** [comment]
I noticed that the in_progress_form shows `has_many :form_submissions, dependent: :nullify`. Would it be appropriate to add     `add_foreign_key :form_submissions, :in_progress_forms, column: :in_progress_form_id, on_delete: :nullify`.

I also noticed this in SavedClaim and UserAccount. These should be in the schema as well.

**Comment by tfink419** [comment]
> > I noticed that the in_progress_form shows `has_many :form_submissions, dependent: :nullify`. Would it be appropriate to add `add_foreign_key :form_submissions, :in_progress_forms, column: :in_progress_form_id, on_delete: :nullify`.
> > I also noticed this in SavedClaim and UserAccount. These should be in the schema as well.
> 
> @RachalCassity I do see the foreign key constraints in the schema already. I can add them to the model files

@RachalCassity I'm not sure anything should be done, form submission has those 3 other models as optional which aligns with nullifying the id.

**Comment by RachalCassity** [comment]
@tfink419 Thank you for your patience. In the past, I have seen errors with InProgressForms which is why I'm digging through the models and controllers. Here's one sentry issue, [here](http://sentry.vfs.va.gov/organizations/vsp/issues/16624/?environment=production&project=3&query=is%3Aunresolved+form&statsPeriod=14d). I noticed during the update, a InProgressForm is initialized here:
```
    def update
      form = InProgressForm.form_for_user(form_id, @current_user) ||
             InProgressForm.new(form_id:, user_uuid: @current_user.uuid)
```

Would it make sense to use find_or_initialize_by?
```
    def update
      form = InProgressForm.form_for_user(form_id, @current_user) ||
             InProgressForm.find_or_intialize_by(form_id:, user_uuid: @current_user.uuid)
```
I also noticed in the model, the user.account is being used. 
```
  def self.form_for_user(form_id, user)
    user_uuid_form = InProgressForm.find_by(form_id:, user_uuid: user.uuid)
    user_account_form = InProgressForm.find_by(form_id:, user_account: user.user_account) if user.user_account
    user_uuid_form || user_account_form
  end
```
 I'm wondering if the user_account is taking precedence even though the InProgressForm that is being updated has the uuid instead of the user account.

**Review by RachalCassity — APPROVED** [review]

**Comment by tfink419** [comment]
@RachalCassity I'll look into it for a new ticket but for now this PR is overdue to be merged so I will proceed with that

**Review by tblackwe — APPROVED** [review]

**Pull request merged**
