### PR TITLE
use redis for rackattack backend

### PR DESCRIPTION
**Pull request by wyattwalter**
Default RackAttack uses Rails.cache.store, which is not used by anything else in vets-api and is defaulting to local filesystem. Changing to Redis store so throttling is done via site-wide metrics rather than node-specific.

Part of https://github.com/department-of-veterans-affairs/vets.gov-team/issues/7063

### CODE REVIEW

**Comment by saneshark** [comment]
@wyattwalter is there any risk of redis namespace collisions? What is the key name that gets created by RackAttack and is there any risk that it could collide with how we serialize various classes in Redis?

**Comment by wyattwalter** [comment]
The key used is `rack::attack:<time period>:<throttle name>:<ip>`. So for me locally using the Docker container it gets set as `rack::attack:421004:feedback/ip:172.18.0.1`. It's defined here: https://github.com/kickstarter/rack-attack/blob/master/lib/rack/attack/cache.rb#L41

I'm happy to setup a separate namespace in Redis if that's desired as well.

**Comment by saneshark** [comment]
LGTM

**Comment by wyattwalter** [comment]
Double-checked this by deploying to dev and watching traffic over the wire. Rack::Attack does not do any Redis operations on any requests except to the ones we explicitly defined in the Rack::Attack config. Agreed that our monitoring is inadequate there, will open a ticket on that.

**Pull request merged**
