### PR TITLE
Chore: Add dogstatsd line

### PR DESCRIPTION
**Pull request by oseasmoran73**
## Description

Two part PR
[Part 1](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1257/files)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/49511

### CODE REVIEW

**Review by RachalCassity — DISMISSED** [review]

**Review by RachalCassity — APPROVED** [review]

**Comment by jerekshoe** [comment]
@oseasmoran73 I'm having issues running vets-api locally because I don't have sidekiq-pro installed. I think it's related to this PR, commenting out this line fixes it:
```ruby
Sidekiq::Pro.dogstatsd = -> { Datadog::Statsd.new('localhost', 8125, namespace: 'sidekiq') }
```

**Comment by oseasmoran73** [comment]
@jerekshoe Looking into this

**Comment by RachalCassity** [comment]
@jerekshoe Pull from master and you should be good to go. :)

**Comment by jerekshoe** [comment]
@oseasmoran73 @RachalCassity pulled master just now and all is well. Thanks to you both!

**Pull request merged**
