### PR TITLE
Status page: Creates Vets-API external service statuses endpoint

### PR DESCRIPTION
**Pull request by hpjaj**
## Description of change
**User Story:** As a FE I want an endpoint that I can hit to get the current status of our external services so that I can know the current state of our services.

## Testing done

Automated spec coverage

## Testing planned

Testing in staging

#### Unique to this PR

- [x] Creates a new `GET /v0/backend_statuses` endpoint to fetch current external service statuses
- [x] Swagger docs and specs
- [x] Spec coverage
- [x] Extends `:raise_error` middleware to recognize more custom exception keys

#### Applies to all PRs

- [x] Appropriate logging
- [x] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [x] Provide which alerts would indicate a problem with this functionality (if applicable)

#### New `/v0/backend_statuses` endpoint swagger docs

image

#### New `/v0/backend_statuses` endpoint swagger response model details

image

### CODE REVIEW

**Comment by jholton** [comment]
Should this functionality be combined with the `BackendStatusesController` functionality?
It looks like that was created because we needed an endpoint to check when GIBS was down via regular scheduled downtime, but it also just returns an "up" status for other services without checking anything (e.g. PagerDuty API).  Also it's named `BackendStatusesController` instead of something like `GibsStatusController` implying it was anticipated it would be used for other services.

[Here's the original `BackendStatuses` PR](https://github.com/department-of-veterans-affairs/vets-api/pull/1769).  Couldn't find a connected issue.

**Comment by hpjaj** [comment]
@jholton

> Should this functionality be combined with the BackendStatusesController functionality?

We went through [an RFC process](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16830) to determine the functionality and implementation of this feature. This endpoint is the culmination of the chosen implementation.  So we would not want to alter the functionality of the implementation.

> I'm concerned that we will have two controllers/endpoints that appear to serve the same purpose otherwise.

I am fine moving this into a `backend_statuses#index` action. I agree that it does make sense for these "status" related things to live in the same controller.  

My only (minor) reservation is that the `index` and `show` actions would be similar in their purpose, yet different in their implementation and data sourcing. So in a sense conveying that they are more aligned than they are.

That said, I'm fine either way.  @kreek , shall we migrate this over to the `backend_statuses#index` action?

**Comment by kreek** [comment]
@hpjaj I could see it going there, one thing to watch out for is that the GIBS messaging is very specific to being business hours. If you were to implement `backend_statuses/{service}` and combined `pager duty + gibs data = gibs status` that gibs being down would show the "we're not in business hours" message when we were.

**Comment by hpjaj** [comment]
I'll migrate this to the `backend_statuses#index` action.

**Pull request merged**
