### PR TITLE
79218 - Patient eligibility using VPG

### PR DESCRIPTION
**Pull request by devin-mccurdy**
## Summary

- This work is behind a feature toggle (flipper): YES - `va_online_scheduling_enable_OH_eligibility`
- Patient eligibility requests are made through a new endpoint within va-mobile. Previously this used /vaos/v1 , but now will go to /vpg/v1 in order to provide the ability to support Oracle Health and Vista locations. The data structures are identical so no code changes are needed to handle a response from the vpg endpoint differently than the vaoos endpoint.

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79218

## Testing done

- [x] *New code is covered by unit tests*
- Frontend changes will be required to fully support appointment scheduling for Oracle Health facilities (currently only Vista facilities are supported)

## What areas of the site does it impact?
These changes impact patient eligibility requests in the vaos and mobile apps.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

The mobile app uses multithreading in `FacilityEligibilityController` when calling the vaos module's `PatientsService`, which prevents the Flipper flag state from being overridden in tests. I updated the tests to use the VPG endpoints as if the flag is on, but do I need to worry about this causing build issues in the future? If so, I could update this to use VCR cassette files based on the test runtime flag value.

### CODE REVIEW

**Review by drewconnelly — APPROVED** [review]
Approved.

**Review by stevenjcumming — APPROVED** [review]

**Review by cferris32 — APPROVED** [review]
LGTM for the VAOS module

**Review by ericboehs — APPROVED** [review]

**Comment by devin-mccurdy** [comment]
@jperk51 could I get a review from someone on the mobile team? Thanks!

**Review by aherzberg — APPROVED** [review]
Looks good! With flippered features like this we try to copy the old one and add `legacy` to it's name, just to make sure if we do have to turn off the flippers, it'll still work but in this case we should be fine without since facility eligibility is not currently used in the app so it is much lower risk.

**Pull request merged**
