### PR TITLE
PBP 94672 Pension and Burial ZSF manual remediation script

### PR DESCRIPTION
**Pull request by wayne-weibel**
## Summary

create manual remediation script to package a pension/burial claim for upload to sharepoint

## Related issue(s)

[PBP | Add manual remediation script for pension and burial](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94762)
[Sidekiq Exhaustion - StructuredData::ProcessDataJob](https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/255)
[Pension | re upload remediation pdf for failure from 10/3](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94763)
[Burial | manual remediation of failed StructuredData::ProcessDataJob](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94764)

## Testing done

script run local performed for an older pension claim
script run on staging for pension and burial claim

## What areas of the site does it impact?

none - applies to ZSF remediation for pension and burial

## Acceptance criteria

- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by balexandr — DISMISSED** [review]

**Review by TaiWilkin — DISMISSED** [review]

**Review by stevenjcumming — COMMENTED** [review]
Forgive me for asking a stupid question, but how do the `docs/modules/_template_` files fit into this?

**Comment by wayne-weibel** [comment]
> Forgive me for asking a stupid question, but how do the `docs/modules/_template_` files fit into this?

There is an intent to create other modules in the future and this leaves a template to be used (for other teams as well)

**Comment by stevenjcumming** [comment]
> There is an intent to create other modules in the future and this leaves a template to be used (for other teams as well)

Makes sense, thanks for indulging my stupid question. 

I have one more question, but it's less stupid. Could those files be moved to the [module generator](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/generators)? That way the generated/template code is all in one place?

**Comment by wayne-weibel** [comment]
> > There is an intent to create other modules in the future and this leaves a template to be used (for other teams as well)
> 
> Makes sense, thanks for indulging my stupid question.
> 
> I have one more question, but it's less stupid. Could those files be moved to the [module generator](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/generators)? That way the generated/template code is all in one place?

:facepalm: Well, now if I had know that was there, would have updated the generator directly, but that can be another ticket, will remove this PR

**Comment by stevenjcumming** [comment]
> 🤦 Well, now if I had know that was there, would have updated the generator directly, but that can be another ticket, will remove from this PR

No worries. Sometimes I feel like this code needs it's own search engine lol

I'll approve this, you don't need to ask a teammate to re-review

**Review by stevenjcumming — APPROVED** [review]

**Pull request merged**
