### PR TITLE
updating native.md instructions for certs

### PR DESCRIPTION
**Pull request by saneshark**
Certificate path should be consistent with what is default in settings.yml

### CODE REVIEW

**Comment by jkassemi** [comment]
Is there a reason to not go the other way around? Would maintain compatibility with the current docker configuration instructions.

**Comment by saneshark** [comment]
I think the problem then would be that everyone would need to make the modification locally.

**Comment by saneshark** [comment]
@rianfowler I'm tagging you in on this since you recently ran into this issue too.

**Comment by saneshark** [comment]
Closing, as certs were relocated.

**Pull request closed without merging**
