### PR TITLE
Update mock_mvi_responses.yml.example

### PR DESCRIPTION
**Pull request by ayaleloehr**
Edits users that Rx and SM team is using.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@saneshark is this the format you'll need them in?

**Comment by saneshark** [comment]
@ayaleloehr can you format the mhv_id to be similar to how MVI provides it?

"mhv_correlation_id^blahblah^blahblah"

Shouldn't those be referencing whatever is in the environment variable so that we have a canonical place to make changes or does that make things confusing?

**Comment by saneshark** [comment]
Also, we have different MHV user id for secure messaging vs prescriptions so I think the description above is a little misleading.

**Comment by ayaleloehr** [comment]
@saneshark this better?

This MHV ID has both an SM and Rx account, so should work for at least testing the APIs at first until we have stage1a access set up.

**Pull request merged**
