### PR TITLE
78498 [1010-CG] Update caregivers application for new format and data collection - Update vets-json-schema

### PR DESCRIPTION
**Pull request by coope93**
## Summary

- *This work is behind a feature toggle (flipper): NO*
-  Update `vets-json-schema` to support new 1010-CG schema changes

## Related issue(s)

- https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/81588

## Testing done

- [x] *New code is covered by unit tests*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*Form 1010-CG

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback
none

### CODE REVIEW

**Comment by LindseySaari** [comment]
Is this for testing purposes? Could you please mark as so?

**Comment by coope93** [comment]
> Is this for testing purposes? Could you please mark as so?

You caught us in the middle of the changes. We had to merge in our vets-json-schema branch first to get the commit SHA. This change is planned to go out in conjunction with vets-website changes [here](https://github.com/department-of-veterans-affairs/vets-website/pull/30357).

**Review by LindseySaari — DISMISSED** [review]

**Comment by coope93** [comment]
@LindseySaari Can we get another check on this one? We had to update some specs.

**Review by Mitch-A6 — APPROVED** [review]
LGTM out of necessity

**Review by JoshingYou1 — APPROVED** [review]
LGTM! Great work team!

**Review by stevenjcumming — APPROVED** [review]

**Pull request merged**
