### PR TITLE
MHV-50917 Split JWT/FHIR session files

### PR DESCRIPTION
**Pull request by mmoyer-va**
## Summary

Split the module MHVJwtSessionClient into two, separating all the FHIR-related code into MhvFhirSessionClient.

### [MHV-50917](https://jira.devops.va.gov/browse/MHV-50917) - Separate the FHIR/JWT session helper into two modules ###

> Currently we have one module to create a session that includes setup for both JWT and FHIR elements of the session.
> 
> Ideally these concerns should be separated into two modules. This has several benefits:
> 
> - It will support future MHV work that relies on a JWT-based session but may have nothing to do with FHIR.
> - It reduces the complexity of each module, making them easier to understand.
> - It reduces file size, keeping everything well below a project-mandated limit of 100 lines per module.

## Testing done

- No new functionality here, only separation of concerns
- Split the existing spec tests into two files

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
MHV Medical Records

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by mattwrightva — DISMISSED** [review]
Looks good!

**Review by ryan-mcneil — APPROVED** [review]
👍

**Comment by mmoyer-va** [comment]
> 👍

@ryan-mcneil My apologies -- can you re-approve? I accidentally pushed a commit to this branch and then had to revert it.

**Review by ryan-mcneil — APPROVED** [review]
👌

**Pull request merged**
