### PR TITLE
Fix sso cookie not getting deleted

### PR DESCRIPTION
**Pull request by saneshark**
## Description of change
gets rid of the `sessions/logout`, handles everything in `sessions/slo/new`
1 less redirect, and we can destroy everything in a get request so no worry about Set-Cookie not working.

## Testing done
Just specs, need to verify on staging. For both va and vets

## Testing planned
Verify on staging before shipping to production.

#### Unique to this PR

- [ ] _Replace this line with individual tasks unique to your PR_

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Swagger docs have been updated, if applicable
- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub
- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by annaswims** [comment]
I see the same Issue in staging. I was looking at the response headers for `/sessions/slo/new`  The response headers have Set-Cookie `vagov_session_staging=GT45NEysW.....; domain=.va.gov; path=/; secure; HttpOnly`

**Comment by saneshark** [comment]
well the code hasn't been deployed yet.

**Comment by U-DON** [comment]
No issues on Staging for me. Cookie gets persisted on login and cleared on logout.

**Comment by saneshark** [comment]
@U-DON did you verify va and vets? what about api_session cookie? thats working too right?

**Comment by annaswims** [comment]
ok, now checking master locally, sso cookie looks good.  Still setting api_session on /sessions/slo/new though.  🤷‍♀️ 
web_sniffer

**Pull request merged**
