### PR TITLE
Remove Comments from LoC Danger check

### PR DESCRIPTION
**Pull request by wayne-weibel**
## Summary

adjust danger line of code check to (properly) ignore empty lines and commented lines

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/86369

## Testing done

run locally: `bundle exec danger --base=master --head=HEAD local`
this PR is itself also the test - files that would trigger warning and error for LoC before are included

https://danger.systems/guides/troubleshooting
https://github.com/danger/danger/issues/382

## What areas of the site does it impact?

All PRs

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by mjknight50** [comment]
I haven't had much luck with testing this.  Here is what I did:
Using the existing Dangerfile, not the new one:
`bundle exec danger pr https://github.com/department-of-veterans-affairs/vets-api/pull/17395;`

This results in:
 `lines_of_code | 800`

Then I locally changed the Dangerfile to use the new one and re-ran:
`bundle exec danger pr https://github.com/department-of-veterans-affairs/vets-api/pull/17395;`

Results in the same number of lines_of_code

I've tried  `git reset --hard origin/master` thinking it might be caching?

**Review by mjknight50 — APPROVED** [review]
Hard to test, but looks good.

**Comment by stevenjcumming** [comment]
@wayne-weibel thank you for doing this. I just want to make sure you plan to remove those two test files at some point

**Review by stevenjcumming — APPROVED** [review]

**Comment by mjknight50** [comment]
@stevenjcumming @rmtolmach  This is ready for review

**Pull request merged**
