### PR TITLE
VAAFI headers: Build the JSON magic header

### PR DESCRIPTION
**Pull request by carlmjohnson**
EVSS isn't working for me right now. I thought it might have something to do with us not including this header, so I added it in. That doesn't seem to actually be the issue, but we may as well merge this in.

### CODE REVIEW

**Comment by austin-martinez** [comment]
Do we know any more details about the JSON in the header? My preference would be to not include it if it isn't necessary (why were requests without it successful?). As a side note while we are working with the headers, we should make sure VCR is matching on full requests with the headers and not just the URL

**Comment by carlmjohnson** [comment]
When I asked them about why the header is necessary and seems to be ignored on CI, Jon Shrader said:

>The JSON header is required on our end in many operations, I would highly recommend you send that.  The IAM explanation of this JSON header has gone back and forth over the years, and the current stance from them is that it isn't required from their end and we shouldn't rely on it.  But our code does rely on it, aligning with the explanation from years ago we should rely on that header first and foremost.  These operations in our CI may not exhibit any odd behavior if you omit it, but that is for various reasons I don't want to bore you with.  Your safest best is to send that header, even though the values are duplicated.  And trust me I share your frustration with them being duplicated...I've had many a conversation with IAM engineers over the years about their duplicating that data and not "scrubbing" the data as a data provider to us, forcing us to deal with 2+ names, 2+ emails, etc.  That is why I tried to narrow down the minimum fields in that JSON that I believe we need so you don't need to construct a huge object graph.  If we get a release in the future where we have time to enhance these services for easier external consumption, I'd love the opportunity to tune our usage of these IAM headers and clean it up...perfect example of things that aren't tuned perfectly for external consumption.
>
>If you want me to research further to see if you could actually omit the JSON header for these operations I could, but that will be more research and my gut feeling is I'd still determine you are going to need to pass it.  Passing it is the safest way to invoke these services as-is.  

So, I think we will need it eventually. May as well start including it.

**Comment by carlmjohnson** [comment]
Branch has a rubocop violation. I will fix it.

**Comment by robbiethegeek** [comment]
LGTM 👍

**Pull request merged**
