### PR TITLE
4842: remove unused maintenance window

### PR DESCRIPTION
**Pull request by kpethtel**
## Summary

After some investigation, I've found that none of the auth maintenance windows are used by the mobile app. I've created a ticket for the front end team to remove them on their side. This removes the one on our side.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/4842
https://app.zenhub.com/workspaces/va-mobile-frontend-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5008

## What areas of the site does it impact?

Remove unused maintenance window option.

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by aherzberg — COMMENTED** [review]
Should this be removed from `modules/mobile/spec/models/service_graph_spec.rb` and `modules/mobile/docs/schemas/MaintenanceWindows.yml` as well?

**Comment by kpethtel** [comment]
> Should this be removed from `modules/mobile/spec/models/service_graph_spec.rb` and `modules/mobile/docs/schemas/MaintenanceWindows.yml` as well?

Yes, I should remove it from the yaml file. But IMO it had nothing to do with that spec file. The spec file is just test data that alastair copied over from real values. I've looked at the commit that adds both this controller and that spec file and the two lists weren't even equal when he added them. For example, that spec file also contains `auth_dslogon` and `auth_mhv` which were never in the controller but do exist in the mobile app. I found this very confusing, but I assume we decided it isn't necessary during the dev process and he just decided to remove them from the controller but didn't bother with the specs because it's just arbitrary test data.

**Comment by kpethtel** [comment]
> Should this be removed from `modules/mobile/spec/models/service_graph_spec.rb` and `modules/mobile/docs/schemas/MaintenanceWindows.yml` as well?

Added the doc change. Thanks for catching that.

**Review by aherzberg — APPROVED** [review]
LGTM

**Pull request merged**
