### PR TITLE
[Lighthouse Doc Upload Migration] Fix 526 Document Upload provider ID logging

### PR DESCRIPTION
**Pull request by NB28VT**
## Summary

- *This work is behind a feature toggle (flipper): YES/NO*

Yes, these providers are being iteratively added to different document upload jobs; currently this is only being used in the [UploadBDDInstructions ](https://github.com/department-of-veterans-affairs/vets-api/blob/95604-disability-benefits-nb-fix-document-upload-api-provider-submission-logging/app/sidekiq/evss/disability_compensation_form/upload_bdd_instructions.rb#L0-L1) job

- *(Summarize the changes that have been made to the platform)*

When submission activity is logged to the Rails logger, there is a precedent for a `submission_id` key to mean a Form526Submission's primary key ID; when initially implemented, these API providers for Form 526 document upload were logging the submission's VBA submitted claim ID under this key.

Corrects this to log both the submitted claim id and the Form526Submission record ID with the traditional `submission_id` key.

## Related issue(s)

- This is part of a handful of [follow on items](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95604) from the `UploadBDDInstructions` release

## Testing done

- [X] *New code is covered by unit tests*

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [X]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation) N/A
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [X]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected N/A
- [ ]  I added a screenshot of the developed feature N/A

### CODE REVIEW

**Review by kylesoskin — APPROVED** [review]

**Comment by NB28VT** [comment]
I'm not sure what is going on with CI here I think there is a failing test in master

**Review by freeheeling — APPROVED** [review]

**Comment by rmtolmach** [comment]
> I'm not sure what is going on with CI here I think there is a failing test in master

yes, you were seeing a test bug (fixed in https://github.com/department-of-veterans-affairs/vets-api/pull/19228). So I'll update your branch.

**Comment by NB28VT** [comment]
@rmtolmach looks like I had to update the branch again sorry, should be good to go now thanks!

**Comment by rmtolmach** [comment]
> @rmtolmach looks like I had to update the branch again sorry, should be good to go now thanks!

The next failure was the `Error: The action 'Run Specs' has timed out after 20 minutes.` message that we're fighting with 😒 we haven't quite pinned down why this is happening. But it's not related to your PR :)

**Review by rmtolmach — APPROVED** [review]

**Pull request merged**
