### PR TITLE
DBEX: implement Metadata Validator for backup submissions

### PR DESCRIPTION
**Pull request by freeheeling**
## Summary

Backup submission processing of form 526 has experienced failures triggered as a result of Benefits Intake API regex validations, including the presence of special characters (e.g., an apostrophe) in a Veteran's first and/or last names.

This PR adds a call to the [metadata validation library](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/simple_forms_api_submission/metadata_validator.rb). The validation cleans the passed metadata, aligning it with [Benefits Intake metadata requirements](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75323#:~:text=https%3A//developer.va.gov/explore/api/benefits%2Dintake/docs%3Fversion%3Dcurrent).

According to the Benefits Intake `DocumentUploadMetadata` schema, "Only upper/lower case letters, hyphens(-), spaces and forward-slash(/)" are allowed characters for first and last names.

Also included in the PR is a hardcoding of the `forceOfframp` value as 'true', to avoid any future reversions. This Flipper was previously enabled and then later disabled, resulting in backup submissions not being appropriately routed. The corresponding Flipper, used only here, is removed from [config/features.yml](config/features.yml).

## Related issue(s)

- Zenhub ticket [#75323](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75323) – Implement Metadata Validator for Backup Submissions
- Zenhub ticket [#75240](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75240) – Default forceOfframp to true & delete corresponding Flipper

## Testing done

No adjustment required or impact to [spec/lib/sidekiq/form526_backup_submission_process/processor_spec.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/lib/sidekiq/form526_backup_submission_process/processor_spec.rb) as a result of the update. The `get_meta_data` method is private and the library it's leveraging has its own spec.

## What areas of the site does it impact?

Form 526 backup submission process

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by tblackwe — COMMENTED** [review]
Is there a test to update?

and we have a ticket to default `forceOfframp` to be true. do you want to do that at the same time?

**Comment by freeheeling** [comment]
> Is there a test to update?

What are your thoughts, @tblackwe, on whether a test is needed if the `get_meta_data` method is private and the library it's leveraging has its own spec?

> and we have a ticket to default `forceOfframp` to be true. do you want to do that at the same time?
 
I initially considered combining both tickets given both modify the same method, but I later thought it better to document each update in separate PRs. What do you think?

**Review by tblackwe — APPROVED** [review]

**Comment by tblackwe** [comment]
once this is merged in we need to manually delete the flipper

`Flipper.remove(:form526_backup_submission_force_offramp)`

**Comment by tblackwe** [comment]
> > Is there a test to update?
> 
> What are your thoughts, @tblackwe, on whether a test is needed if the `get_meta_data` method is private and the library it's leveraging has its own spec?
> 
> > and we have a ticket to default `forceOfframp` to be true. do you want to do that at the same time?
> 
> I initially considered combining both tickets given both modify the same method, but I later thought it better to document each update in separate PRs. What do you think?
> 
> **Edit:** I went ahead and wrapped the `forceOfframp` change into this PR, and am updating the description to reflect that change.

Thanks for capturing the flipper change
This code is already being tested, and the metadata validator has its own tests. I'm good without adding more overhead.

**Review by ericboehs — APPROVED** [review]

**Pull request merged**
