### PR TITLE
MHV-39259 Adding MHV FHIR-ized API calls

### PR DESCRIPTION
**Pull request by mmoyer-va**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

Added the preliminary pieces to implement MHV Medical Records FHIR APIs. The MHV APIs are still being actively developed, so the vets-api code is likely to be changed quite a bit in the future.
Added a new lib/medical_records client and configuration (very preliminary, but enough to allow further development)

## Related issue(s)
https://vajira.max.gov/browse/MHV-39259 - MR to VA.gov: Build MR APIs in VA.gov

## Testing done
Added rspec tests for both the client API calls as well as the new vets-api controller. These tests are somewhat preliminary as the underlying MHV API framework is still being developed and, as such, our own code is likely to undergo substantial rework. We will update the tests to keep pace with further upstream development.

Here is the ticket for that work:
https://vajira.max.gov/browse/MHV-44716 - MR to VA.gov: Add testing and OpenAPI docs for MR controllers

## Screenshots
None

## What areas of the site does it impact?
This is brand new code and should only impact the MHV Medical Records migration work currently under development.

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by mattwrightva — APPROVED** [review]
Excellent work!

**Comment by ryan-mcneil** [comment]
@mmoyer-va Hi Mike, as this is establishing a new set of endpoints, can we also get some tests covering what we have so far? We don't want to go too far down that road and hurt our coverage. Thank you! Looking good!

**Comment by mmoyer-va** [comment]
@ryan-mcneil I added some basic tests as you suggested. We'll continue to update them as we add more functionality. Thanks!

**Review by ryan-mcneil — APPROVED** [review]
Beautiful, thank you! 🚀

**Pull request merged**
