### PR TITLE
added logging for type_of_care in appointment_requests_controller

### PR DESCRIPTION
**Pull request by grossb1**
## Description of change

Updated appointment request controller to log type_of_care_id

## Original issue(s)
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13760

## Things to know about this PR

Respective unit tests were updated to reflect this change

### CODE REVIEW

**Comment by saneshark** [comment]
We still want the ID too, but we also want the type_of_care_id. It looks like you removed ID.

**Comment by grossb1** [comment]
Where did I remove Id?

**Review by kfrz — COMMENTED** [review]
Just a gut-check: there's no correlated information in the logs that might allow someone to associate a given patient with type of care requested? Just want to be extra sure we're not logging more than we need to in that regard. 

cc @f1337

**Comment by saneshark** [comment]
> Just a gut-check: there's no correlated information in the logs that might allow someone to associate a given patient with type of care requested? Just want to be extra sure we're not logging more than we need to in that regard.
> 
> cc @f1337

I think users account ID or UUID is always part of the logs, their remote IP address is also part of the logs. None of the details we're logging are any more specific to a user than those. That being said, all the reports that I pull deliberately exclude these additional attributes from the CSV files I generate.

**Review by saneshark — APPROVED** [review]
LGTM

**Pull request merged**
