### PR TITLE
[AVS] Main PR

### PR DESCRIPTION
**Pull request by acrollet**
This is a container PR for the following PRs that will together provide the complete After Visit Summary API module:

* #13489 
* #13493 
* #13497
* #13498
* #13502
* #13510 

The PRs were split out to ease review and avoid danger warnings. (Although it appears that comparisons are done against the master branch, so it is triggering on the later PRs)

## Summary

Adds After Visit Summary (AVS) module. This module provides the following two endpoints:

* Return the (frontend) path for the AVS for the given (VistA) station number and Appointment Ien, if one exists
* Return the data for the AVS with the given ID

All data is currently mocked, as the backend API is not yet available. Configuration will be updated in a follow-on once the API is available and the fwdproxy setup is in place.

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#63287

## Testing done

- Extensive local testing with the [vets-website avs-view branch](https://github.com/department-of-veterans-affairs/vets-website/tree/feature/avs-view).
- specs created for controller, serializer and API docs

## Screenshots

image

## What areas of the site does it impact?

No existing areas of the site are impacted. The only existing code that is impacted is the touchpoints created by the vets-api module generator.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature

## Requested Feedback

This is my first vets-api module so I'm interested in any and all feedback, especially relating to best practices and where I may not be writing idiomatic code. 🙂

### CODE REVIEW

**Review by mdewey — APPROVED** [review]
I checked out the child PRs and they look good.

**Review by ryan-mcneil — APPROVED** [review]
👍

**Review by ryan-mcneil — APPROVED** [review]
👍 let's not do that again 🤣

**Comment by acrollet** [comment]
> 👍 let's not do that again 🤣

haha sorry and many many thanks!

**Review by ryan-mcneil — APPROVED** [review]
👍

**Pull request merged**
