### PR TITLE
884 tracking other prescriptions - In Progress

### PR DESCRIPTION
**Pull request by mphprogrammer**
Adding schema correction for other prescriptions

### CODE REVIEW

**Comment by mphprogrammer** [comment]
@saneshark Would like to see case where prescription tracking has no other_prescriptions.

**Comment by saneshark** [comment]
As to your question about cases where there is no other prescriptions, I think we should be able find one in the curl scripts no? If not you can write up a spec and run vcr again for something that doesn't have --- it's a good idea to do that I agree to ensure the scheme is valid for that case.

**Comment by ayaleloehr** [comment]
@mphprogrammer Because I'm excited about this and want to help keep it unblocked, here is an example with both other prescriptions and without them:

```
{
  "prescriptionName": "CARBAMAZEPINE (TEGRETOL) 200MG TAB",
  "prescriptionNumber": "2719552",
  "facilityName": "DAYT29",
  "rxInfoPhoneNumber": "(555)772-0956",
  "ndcNumber": "00078042034",
  "lastUpdatedtime": "Wed, 29 Mar 2017 04:30:15 EDT",
  "trackingInfo": [
    {
      "shippedDate": "Fri, 24 Mar 2017 00:00:00 EDT",
      "deliveryService": "UPS",
      "trackingNumber": "111787647693",
      "otherPrescriptionListIncluded": [
        {
          "prescriptionName": "TERAZOSIN HCL 10MG CAP",
          "prescriptionNumber": "2719554",
          "ndcNumber": "07985440050",
          "stationNumber": "989"
        },
        {
          "prescriptionName": "IBERSARTAN 300MG TAB",
          "prescriptionNumber": "2719557",
          "ndcNumber": "07985440050",
          "stationNumber": "989"
        }
      ]
    },
    {
      "shippedDate": "Wed, 07 Sep 2016 00:00:00 EDT",
      "deliveryService": "USPS",
      "trackingNumber": "657068347564",
      "otherPrescriptionListIncluded": [
        
      ]
    },
    {
      "shippedDate": "Wed, 06 Jul 2016 00:00:00 EDT",
      "deliveryService": "USPS",
      "trackingNumber": "345787647659",
      "otherPrescriptionListIncluded": [
        {
          "prescriptionName": "PAROXETINE HCL 30MG TAB",
          "prescriptionNumber": "2719551",
          "ndcNumber": "00781168131",
          "stationNumber": "989"
        }
      ]
    },
    {
      "shippedDate": "Sun, 26 Jun 2016 00:00:00 EDT",
      "deliveryService": "USPS",
      "trackingNumber": "345787647654",
      "otherPrescriptionListIncluded": [
        
      ]
    }
  ]
}
```


Retrieved through the commands
```
curl -H "appToken:3Olp2DAjWDaI8B4vV4cHzHRJTYZO+XfMWEiVSGzFDYg" -H "mhvCorrelationId:12210827" -v https://essapi-sysb.myhealth.va.gov/mhv-api/patient/v1/session
```
Then take the Token from that output and copy it into:
```
curl -H "Accept: application/json" -H "Token: [INSERT_TOKEN_HERE]" -v https://essapi-sysb.myhealth.va.gov/mhv-api/patient/v1/prescription/rxtracking/13650542
```

**Comment by mphprogrammer** [comment]
@ayaleloehr Thanks

**Pull request merged**
