### PR TITLE
API-40384 directory controller displayName update

### PR DESCRIPTION
**Pull request by dmekala-va**
## Summary

- This PR makes a change to the directory controller to avoid duplicate displayNames showing up on the apps you can use page.
-  Team Pivot!

## Related issue(s)

- https://jira.devops.va.gov/browse/API-40384

## Testing done

- Unit tests working

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X]  No error nor warning in the console.
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by mwise-va — APPROVED** [review]

**Review by mwise-va — DISMISSED** [review]

**Review by TylerGuerrero-va — DISMISSED** [review]

**Review by crolarlibertyva — DISMISSED** [review]

**Comment by rmtolmach** [comment]
> Unit tests working

Where's the spec file? What is testing this code?

**Comment by dmekala-va** [comment]
> > Unit tests working
> 
> Where's the spec file? What is testing this code?

The spec files for this endpoint are here. They have not changed since main functionality has not changed. It is just removing duplicates.

https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/lib/okta/directory_service_spec.rb
https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/apps_api/spec/requests/apps_api/v0/directory_spec.rb

**Comment by rmtolmach** [comment]
> > > Unit tests working
> > 
> > 
> > Where's the spec file? What is testing this code?
> 
> The spec files for this endpoint are here. They have not changed since main functionality has not changed. It is just removing duplicates.
> 
> https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/lib/okta/directory_service_spec.rb https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/apps_api/spec/requests/apps_api/v0/directory_spec.rb

Can you write a test that includes duplicates to make sure they're being removed?

**Review by crolarlibertyva — DISMISSED** [review]

**Review by rmtolmach — APPROVED** [review]
Test looks good! 👍

**Review by mwise-va — APPROVED** [review]

**Review by crolarlibertyva — APPROVED** [review]

**Pull request merged**
