### PR TITLE
Adding Rake task to create test sessions

### PR DESCRIPTION
**Pull request by knkski**
Run with

    bundle exec rake redis:create_sessions[10]

Useful for doing automated testing, such as load testing, and avoids talking to id.me completely.

### CODE REVIEW

**Comment by knkski** [comment]
@kreek: Can you take a look at the fake data here and see if it all makes sense for testing? In addition, is there some way of generating valid test MHV IDs?

**Comment by omgitsbillryan** [comment]
Very clever, LGTM

**Comment by kreek** [comment]
@knkski do you want a set of MHV IDs that exist in an environment or are you looking for the format of a valid MHV ID? e.g. 12345678^PI^200MH^USVHA^A

**Comment by knkski** [comment]
@kreek: I'd like to be able to use this to generate a user that can access api endpoints such as `/v0/prescriptions` while running tests.

**Comment by kreek** [comment]
@knkski these differ per environment, and in mvi dev none of the users we were given have mhv ids, prescriptions team is your best bet if you need specific ids

**Comment by kreek** [comment]
once you have what you need the PR looks LGTM though 👍

**Pull request merged**
