### PR TITLE
VACMS-19255 Remove Find Forms feature flipper

### PR DESCRIPTION
**Pull request by randimays**
## Summary
Ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19255

We removed the code that uses this flipper, so we can now remove the flipper too.

### CODE REVIEW

**Comment by rmtolmach** [comment]
@randimays I converted to a draft. Mark as ready to review when it's ready! 🙂

**Comment by randimays** [comment]
@rmtolmach This is ready for your review please

**Review by chriskim2311 — APPROVED** [review]
LGTM

**Review by rmtolmach — APPROVED** [review]
👍 Once this is deployed, you'll need to follow step 3 of [this section of this guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles) to completely remove this toggle. You'll need to do it in the terminal of each ArgoCD environment. If you or no one on your team has access to those terminals, let me know and I can do it for you. Remember, don't delete them in Argo until the code has been deployed.

**Pull request merged**
