### PR TITLE
Makefile command to rebuild docker image

### PR DESCRIPTION
**Pull request by rlbaker**
When gems are updated in the `Gemfile` or `Gemfile.lock`, it can sometimes break the bundler checks when launching a container because the `vets_api` docker image installs gems when the image is built, rather than mounting them into a container when it is run.

This PR adds a `make rebuild` command to rebuild the `vets-api` image, resolving the bundler issues (and additional volume mounting bugs that crop up)

### CODE REVIEW

**Comment by mloberg** [comment]
What about doing this every time? If nothing has changed, the time it takes Docker to build the image is almost nothing. Then you know that every time you do `up` it will work.

**Comment by rlbaker** [comment]
I definitely am amenable to that change. We can just append `--build` to the `docker-compose up` command. My only concern was an image being rebuilt unintentionally while working on things like migrations, but I wasn't sure how much of an effect that would have.

**Comment by mloberg** [comment]
I haven't worked with migrations. How would adding `--build` to docker-compose up affect things like migrations?

**Comment by rlbaker** [comment]
@mloberg My example was a pretty poor one so I think we can disregard it, and the more I think through it though, I don't really have any realistic scenarios where it would be problematic. It was more based on a concern of making a rebuild explicitly called by the user, rather than implicitly. 

Considering the general use case though (and the issue that this was meant to resolve), it may match peoples expectations more to always reflect the current repo state (by rebuilding), rather than to have an image that reflects some previous state of the repository.

**Comment by wyattwalter** [comment]
Been playing around with this locally as I've been struggling with a few issues around the way that the Makefile is managing things. The biggest drawback to passing `--build` all the time is that untags the latest image and creates a new one, so you end up with a huge list of untagged images. Doing the build as a separate command like this I think is useful with current config, so +1 from me.

**Comment by rlbaker** [comment]
@wyattwalter I also ran into some issues based on the fact that the `up` command has a dependency on the `db` command which launches a preliminary vets-api container before the `--build` flag is hit in the `up` command (which would be susceptible to the same bundler issue we've been having). I'll merge this for now and we can maybe circle back around to adjusting the build workflow in the future.

**Pull request merged**
