### PR TITLE
API-41894 Fix schema to ref BRD for separationLocationCode

### PR DESCRIPTION
**Pull request by mchristiansonVA**
## Summary

- *This work is behind a feature toggle (flipper): NO*
- Updates v1 526 schema to reference BRD as the source of location codes for submissions.
- Adds generated swagger for v1.

## Related issue(s)

[API-41894](https://jira.devops.va.gov/browse/API-41894)

## Testing done

- [ ] *New code is covered by unit tests*
- Submit an integer separationLocationCode for a service period with activeDutyEndDate in future and confirm the resulting 422 detail message includes: "Code must match the values returned by the /intake-sites endpoint on the [Benefits reference Data API](https://developer.va.gov/explore/benefits/docs/benefits_reference_data?version=current)."
- View swagger doc locally to confirm the v1 /forms/526 schema includes the above message for separationLocationCode. 

## Screenshots
Screenshot 2024-11-12 at 10 56 42 AM
Screenshot 2024-11-12 at 10 56 23 AM

## What areas of the site does it impact?
v1 526.json schema
v1 swagger documentation

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by tycol7 — COMMENTED** [review]
Schema looks good, but the swagger looks out of sync (something I've also been noticing when generating v1 docs). Not sure what the long term fix is, but in the meantime, I've been manually editing the v1 swagger to only include the relevant changes. Do we want to do that here, or are we are ok merging the large diff?

**Review by FonzMP — APPROVED** [review]
:shipit: 

this can merge before https://github.com/department-of-veterans-affairs/vets-api/pull/19377 since we're already calling BRD, granted we're not actually validating correctly, so it doesn't work, but the changes here are truthful.

**Comment by FonzMP** [comment]
> Schema looks good, but the swagger looks out of sync (something I've also been noticing when generating v1 docs). Not sure what the long term fix is, but in the meantime, I've been manually editing the v1 swagger to only include the relevant changes. Do we want to do that here, or are we are ok merging the large diff?

Good callout @tycol7 . I should have opened that v1 swagger file. A bit overwhelming that it's reflecting that many changes, whether it's just ordering or what, it's probably concerning enough it'd be better if we just manually updated the description for that specific section.

**Review by rockwellwindsor-va — COMMENTED** [review]
I am still getting this

```
{
    "errors": [
        {
            "title": "Invalid field value",
            "detail": "\"1111111111\" is not a valid value for \"separationLocationCode\"",
            "code": "103",
            "status": "400"
        }
    ]
}
```

My servicePeriods looked like this for my v1 submission so let me know if I am missing anything
```
                "serviceInformation": {
                     "servicePeriods": [{
                                "serviceBranch": "Army",
                                "activeDutyBeginDate": "2015-09-14",
                                "activeDutyEndDate": "2026-09-17",
                                "separationLocationCode": "1111111111"
                           }
                     ]
                },
```

**Review by rockwellwindsor-va — APPROVED** [review]
LGTM!

**Pull request merged**
