### PR TITLE
Add mvi status to  saml_callback errors

### PR DESCRIPTION
**Pull request by annaswims**
## Description of change
Log mvi status as part of extra context for login errors

## Testing done
specs

### CODE REVIEW

**Comment by BBarone1** [comment]
commenting here that we may not want to go through with this PR.

Currently, 004 a login error page that shows "Records not found" when a user fails to login because they are not found in MVI. This should only ever happen is the user is an MHV premium account, thus, the only rationale for why this user is unable to log in should be that MVI is down.

I propose we change the purpose of 004 to be "MVI is down" and update the messaging, as opposed to creating a new backend code 006 which would serve the same purpose

**Comment by BBarone1** [comment]
We talked about this at standup - we decided messaging for 004 should switch to this and 006 should be implemented as a backend code for us to use temporarily as a logging experiment and see how many users are being effected by MVI breakers outage

**Comment by BBarone1** [comment]
Anna to confirm - can you make sure 006 errors (breakers outage) happen in concert and only for logging purposes, and don't take the user to a separate page before pushing this PR?

**Comment by annaswims** [comment]
It's possible `latest_outage` could be nil.  I modeled it after the code here
https://github.com/department-of-veterans-affairs/breakers/blob/c782fef6d4924d783ab74e5b18b1c619f321179e/lib/breakers/uptime_middleware.rb#L24

**Pull request merged**
