### PR TITLE
5490 transform form

### PR DESCRIPTION
**Pull request by lihanli**
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2658

### CODE REVIEW

**Comment by markolson** [comment]
Can you actually make a new test document for `currentSameAsPrevious` so that we have both the true and false cases covered?

**Comment by lihanli** [comment]
@markolson ok i added a spec

**Comment by ayaleloehr** [comment]
pinging @markolson and @lihanli to see what should happen with this?

**Comment by lihanli** [comment]
i'm waiting on a review

**Pull request merged**
