### PR TITLE
WiP: Move loa.current out of User and into Model

### PR DESCRIPTION
**Pull request by omgitsbillryan**
Related Issue:
https://github.com/department-of-veterans-affairs/platform-team/issues/170

Abstractly, it makes more sense the the `loa.level` to be in `Session` instead of `User` - especially since `User` is cahced for 24 hours and `Session` only 1 hour.

This PR does the following
- Remove `loa.current` from the `User` model
- Add `level` to the `Session` model
- Add a `GET /v0/sessions` route that will return the level of the session

### CODE REVIEW

**Comment by kreek** [comment]
LGTM - in the future we might be able to make the user more polymorphic to remove conditional validation etc. but for splitting out LOA to the session this looks good 👍 :shipit: 🚀

**Comment by saneshark** [comment]
Could delegate loa3 method on user to session to keep backward compatibility.

**Comment by saneshark** [comment]
@carlmjohnson If this is a breaking change, I would also suggest adding some specs for evss as that is something that should have been picked up by CI I think as broken spec.

**Comment by omgitsbillryan** [comment]
@saneshark there are actually 157 broken specs 😀.  Before spending the time to fix them, I started this WiP PR to get feedback to make sure I wasn't being too crazy with this change.  

This basically all hinders on the fact that, in Redis, `session` expires in 1 hour, but `user` expires in 24.  If they both expired at the same time this change would not be necessary.

**Comment by saneshark** [comment]
In that case it makes more sense to me make user be 1 hour TTL and move MVI into a 24 hour TTL. The 24 hour was just to satisfy MVI because they don't want us querying that often.

**Comment by omgitsbillryan** [comment]
Since the commit by @kreek for mvi cache'ing.  I'm redo'ing this feature with the comments received here.  Another PR will be coming soon.

**Pull request closed without merging**
