### PR TITLE
User Model Serialization

### PR DESCRIPTION
**Pull request by omgitsbillryan**
User serialization [as defined in our design](https://github.com/department-of-veterans-affairs/vets-api/blob/profile-endpoint-design/docs/api/profile.md)

This serialization occurs with a GET request to `/v0/profile`

### CODE REVIEW

**Comment by aub** [comment]
LGTM as well

**Comment by kreek** [comment]
LGTM 🚀

**Comment by austin-martinez** [comment]
Can we also add a request spec that tests the final output against a schema? That is what we've been doing for most of our API endpoints in the other products

**Comment by omgitsbillryan** [comment]
@austin-martinez sure.  Can you point me to where we do this already so I have a good example to follow?

**Comment by austin-martinez** [comment]
@omgitsbillryan some example request specs can be found in `spec/request` and schemas in `spec/support/schemas`

**Comment by robbiethegeek** [comment]
Once the test lands and they pass let's get this in! Good job @omgitsbillryan

**Comment by omgitsbillryan** [comment]
@austin-martinez I created a json schema for `profile` and added the respective rspec.  Having done so, I wonder it my `user_serializer_spec.rb` is redundant to the profile schema spec.  

It also made me wonder if our `/serializers` need to be versioned the same way our controllers are... but that conversation is probably outside the scope of this PR.

**Comment by austin-martinez** [comment]
@omgitsbillryan It does look like the serializer spec is now redundant and can be removed or tweaked a bit to only test that the `va_profile` is being set correctly. The schemas are a bit loose right now in that they allow `null` for the values in the `va_profile`, so another approach may be to have two schemas, one for the LOA1 user and another for the LOA3 user. Once the services array is constructed, you may want to have that spec in the serializer as the schema will only validate that correct values are being sent (but not the logic that determines which values).

**Comment by robbiethegeek** [comment]
Seems like the services array should be a separate issue since this is about updating the profile endpoint to match our current defined profile structure.  We good to merge this is?

**Comment by omgitsbillryan** [comment]
@austin-martinez I like your idea for two schemas since the attributes are different for each.  I logged an issue for it #284

**Pull request merged**
