### PR TITLE
Vebt 605 - Fix datadog error within School Certifying Officials email

### PR DESCRIPTION
**Pull request by alexchan-va**
## Summary

- *This work is behind a feature toggle (flipper): YES/NO* No
- *(Summarize the changes that have been made to the platform)* Fix datadog error within School Certifying Officials email
- *(If bug, how to reproduce)* Check datadog to see if errors go away
- *(What is the solution, why is this the solution?)* To not use Redis with the Sidekiq job
- *(Which team do you work for, does your team own the maintenance of this component?)* VEBT
- *(If introducing a flipper, what is the success criteria being targeted?)* N/A

## Related issue(s)

- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira* https://jira.devops.va.gov/browse/VEBT-605
- *Link to previous change of the code/bug (if applicable)* N/A

## Testing done

- [ x] *New code is covered by unit tests* Yes
- *Describe what the old behavior was prior to the change* There were datadog errors saying the sidekiq job was exhausted
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing* Submit 10203, confirm SCO email is sent
- *If this work is behind a flipper:* N/A

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)* SCO Email

## Acceptance criteria

- [x ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x ]  No error nor warning in the console.
- [x ]  Events are being sent to the appropriate logging solution
- [x ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x ]  Feature/bug has a monitor built into Datadog (if applicable)

### CODE REVIEW

**Comment by rmtolmach** [comment]
@alexchan-va what's the Datadog error? Can you link to some DD logs?

**Comment by alexchan-va** [comment]
@rmtolmach 
datadog

Here is a picture of the slack message that refers to the Datadog error.

**Comment by GcioGregg** [comment]
@rmtolmach Thanks for your comment/questions.  The solution that Alex did for this PR was based on a meeting that Noah Stern and I had with Steve Albers to discuss this error and it's solution.  We're thinking it makes sense to deploy this solution and see if the errors go away.  Perhaps we can look at additional handlers in a separate PR?  Thanks.

**Review by rmtolmach — APPROVED** [review]

**Comment by rmtolmach** [comment]
> @rmtolmach Thanks for your comment/questions. The solution that Alex did for this PR was based on a meeting that Noah Stern and I had with Steve Albers to discuss this error and it's solution. We're thinking it makes sense to deploy this solution and see if the errors go away. Perhaps we can look at additional handlers in a separate PR? Thanks.

Sounds good 👍

**Pull request merged**
