### PR TITLE
Adds trace service tags for public websites API controllers

### PR DESCRIPTION
**Pull request by patrickvinograd**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

Adds the newly-created `Traceable` concern to public-websites-related API controllers, and tags their services so error traces will be associated correctly in Datadog. 

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/66141

## Testing done

- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *Describe the tests completed and the results*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
Error traces in Datadog for these controllers will now be searchable by service name.

### CODE REVIEW

**Review by ryan-mcneil — APPROVED** [review]
👌

**Comment by patrickvinograd** [comment]
This should get merged after https://github.com/department-of-veterans-affairs/vets-api/pull/14299 which includes some adjustments to the Traceable concern

**Comment by patrickvinograd** [comment]
@ryan-mcneil Could I get another ✅ after the force push?

**Comment by dsasser** [comment]
FYI @patrickvinograd Public Websites also owns the Income limits API https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/income_limits/app/controllers/income_limits

**Comment by patrickvinograd** [comment]
Thanks @dsasser I added that one to this PR.

**Review by ericboehs — APPROVED** [review]

**Pull request merged**
