### PR TITLE
Replace Root AMS serializers with JSONAPI serializers - Part 11

### PR DESCRIPTION
**Pull request by stevenjcumming**
## Summary

Switched the following to JSONAPI::Serializer:

- PersistentAttachmentSerializer
- PersonalInformationSerializer
- Post911GIBillStatusSerializer

**_`REMOVED`_** the following serializers: 
- PhoneNumberSerializer - didn't appear to be used anywhere

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87047

## Testing done

- [x]  No tests added or updated
	
## Acceptance criteria

- [x] Each serializer uses jsonapi-serializer 
- [x] Each serializer has 100% coverage

### CODE REVIEW

**Comment by rmtolmach** [comment]
@stevenjcumming there is a merge conflict.

**Comment by stevenjcumming** [comment]
@AdamKing0126 & @adamwhitlock1 would you both mind reviewing this PR?

**Review by AdamKing0126 — APPROVED** [review]
This is great.  I wasn't even aware that we were using two different serializer classes.  Thanks for the cleanup!

**Review by rmtolmach — APPROVED** [review]
LGTM, but not sure if you still wanted @adamwhitlock1's review

**Pull request merged**
