### PR TITLE
[30408] adds logingov to account_login_stats table

### PR DESCRIPTION
**Pull request by bramleyjl**
## Description of change

Updates `account_login_stats` table to be able to track Login.gov logins

Companion PR: https://github.com/department-of-veterans-affairs/vets-api/pull/8366

## Original issue(s)
department-of-veterans-affairs/va.gov-team#30408

## Things to know about this PR

No functionality removed, logins and unit specs pass.

### CODE REVIEW

**Review by jscanish — COMMENTED** [review]
This looks fine. Bear in mind that for the whole process to actually work `SAML::User::AUTHN_CONTEXTS` will need to include `logingov`. Is the plan is to just put this column in place now and adjust that hash later?

**Comment by bramleyjl** [comment]
> This looks fine. Bear in mind that for the whole process to actually work `SAML::User::AUTHN_CONTEXTS` will need to include `logingov`. Is the plan is to just put this column in place now and adjust that hash later?

Yes, this is just the schema update separated out from the Login.gov IAL1 implementation, which includes the update to that constant: https://github.com/department-of-veterans-affairs/vets-api/pull/8366

**Review by jscanish — DISMISSED** [review]

**Review by LindseySaari — COMMENTED** [review]
Is there a migration that goes with this schema update?

**Comment by bramleyjl** [comment]
> Is there a migration that goes with this schema update?

There is! Somehow got left out of my git commit command.

**Pull request merged**
