### PR TITLE
[API-39351] Add `find_poas` to `local_bgs` service

### PR DESCRIPTION
**Pull request by tycol7**
## Summary

* Add findPOAs call to local BGS service
* Add `StandardDataWebService` to BGS client definitions
* Add test and VCR cassette
* Account for arrays in BGS result parsing

## Related issue(s)

[API-39351](https://jira.devops.va.gov/browse/API-39351)

## Testing done

- [x] *New code is covered by unit tests*
- Verified manually in console

## Screenshots

N/A

## What areas of the site does it impact?

Local BGS service

## Acceptance criteria

- [x]  I added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

N/A

### CODE REVIEW

**Review by mchristiansonVA — COMMENTED** [review]
Ran standard_data_web_service_spec.rb locally and getting a "Bad Gateway" error. Looks like this test leverages a VCR cassette, so just want to make sure this is expected?

```
 1) ClaimsApi::StandardDataWebService#find_poas responds as expected
     Failure/Error: result = subject.find_poas

     Common::Exceptions::BadGateway:
       Bad Gateway
     # ./modules/claims_api/lib/bgs_service/local_bgs.rb:325:in `rescue in make_request'
     # ./modules/claims_api/lib/bgs_service/local_bgs.rb:309:in `make_request'
     # ./modules/claims_api/lib/bgs_service/standard_data_web_service.rb:10:in `find_poas'
     # ./modules/claims_api/spec/lib/claims_api/standard_data_web_service_spec.rb:12:in `block (4 levels) in <top (required)>'
     # ./modules/claims_api/spec/lib/claims_api/standard_data_web_service_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Net::OpenTimeout:
     #   Failed to open TCP connection to internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com:4447 (execution expired)
     #   ./modules/claims_api/lib/bgs_service/local_bgs.rb:319:in `block in make_request'

Finished in 2 minutes 0.5 seconds (files took 17.57 seconds to load)
1 example, 1 failure
```

**Comment by tycol7** [comment]
> Ran standard_data_web_service_spec.rb locally and getting a "Bad Gateway" error. Looks like this test leverages a VCR cassette, so just want to make sure this is expected?

Unexpected! Moved the cassette into its own directory and failed to update the spec. Should be good [now](https://github.com/department-of-veterans-affairs/vets-api/pull/18301/commits/82b47cebdb689603867d32af424958594bc427cb).

**Comment by tycol7** [comment]
Note to reviewer: should be the same as the [previously approved](https://github.com/department-of-veterans-affairs/vets-api/pull/18195#pullrequestreview-2280490169) #[18195](https://github.com/department-of-veterans-affairs/vets-api/pull/18195/files/18d4156befa0c69ac2b89da55d6fe43a75a02e69) before the bad merge.

**Review by mchristiansonVA — APPROVED** [review]
Pulled down latest updates and re-ran specs locally; test in question that failed with bad gateway is now passing. Looks good to me!

**Pull request merged**
