### PR TITLE
rubocop todos

### PR DESCRIPTION
**Pull request by SlakrHakr**
## Description of change
Trying to resolve previously marked todo items within rubocop

## Things to know about this PR
There is a lot here but the vast majority of these changes were auto-corrected by rubocop and then just reviewed by me.

### CODE REVIEW

**Review by batemapf — APPROVED** [review]

**Review by jimiray — DISMISSED** [review]
HOORAY for string interpolation and getting rid of "dig", this was something I wondered about for a while.

**Comment by kreek** [comment]
Could this be broken up by product, or maybe by cop? Seems fairly innocuous but it touches basically the entire API.

**Comment by SlakrHakr** [comment]
> Could this be broken up by product, or maybe by cop? Seems fairly innocuous but it touches basically the entire API.

I actually planned on doing it in smaller chunks but after doing just a few of them i was already over the 500 loc limit so i figured id just do a few more. I can try to break them up if people don't feel comfortable with this large pr though.

**Review by stephenBarrs — DISMISSED** [review]

**Comment by SlakrHakr** [comment]
closing this for now as its proving too big and spread across the codebase to get enough people to sign off before something else is pushed to master that breaks a rubocop rule.

will probably open up smaller prs for this stuff in the future

**Pull request closed without merging**
