### PR TITLE
[70023] Allow user_attributes claim for service account access tokens

### PR DESCRIPTION
**Pull request by dickdavis**
## Summary

This PR allows service accounts to pass a `user_attributes` claim in the assertion used to request a service account access token which will then be included in the generated access token. Some endpoints that use service account authentication (such as the in-progress MAP STS endpoint) require additional attributes about a user to perform a given action; this PR provides a mechanism for service accounts to provide that information and for the endpoints to retrieve it from the service account access token.

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#70023

## Testing done

- Open the Rails console and generate an assertion.
```ruby
private_key = OpenSSL::PKey::RSA.new(
  File.read('spec/fixtures/sign_in/sample_service_account.pem')
)

payload = {
  'iss' => 'http://localhost:3001',
  'sub' => 'vets.gov.user+0@gmail.com',
  'aud' => 'http://127.0.0.1:3000/v0/sign_in/token',
  'iat' => Time.now.to_i,
  'exp' => 10.days.from_now.to_i,
  'scopes' => ['http://localhost:3000/v0/map_services/chatbot/token'],
  'service_account_id' => '88a6d94a3182fd63279ea5565f26bcb4',
  'jti' => SecureRandom.hex,
  'user_attributes' => { 'icn' => 'foobar' }
}

JWT.encode(payload, private_key, 'RS256')
```
- Using the Sign in Service postman collection, obtain a service account token.
  - Paste the generated assertion as the value for the `signed_service_account_assertion` collection variable.
  - Send the `token` request (located in the `Service Account Auth` collection.)
- Verify the endpoint responds with a valid service account token.
- Put a breakpoint in the `SignIn::ServiceAccountAccessTokenJwtDecoder` service, line 36 should work fine.
- Send the request to any service account authenticated endpoint with the token.
- Inspect the decoded access token and verify the user attributes claim is present and has the expected value.

## Screenshots
Not relevant.

## What areas of the site does it impact?
This impacts any area using service account authentication.

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by bosawt — CHANGES_REQUESTED** [review]
This looks like a good start, but can we add a set of explicit `user_attribute` keys that we will accept, which are stored in the service account config? (Basically the same implementation as the `client_config` `access_token_attributes` stuff)

**Review by bramleyjl — COMMENTED** [review]
Tested and it looks good
```ruby
[1] pry(#<SignIn::ServiceAccountAccessTokenJwtDecoder>)> decoded_jwt
=> {"iss"=>"va.gov sign in",
 "aud"=>"http://localhost:3001",
 "jti"=>"fd95f694-85ce-4260-8ae7-9d84adfa7326",
 "sub"=>"vets.gov.user+0@gmail.com",
 "exp"=>1700406177,
 "iat"=>1700405877,
 "version"=>"V0",
 "scopes"=>["http://localhost:3000/v0/map_services/chatbot/token"],
 "service_account_id"=>"88a6d94a3182fd63279ea5565f26bcb4",
 "user_attributes"=>{"foo"=>"bar"}}
 ```
 
 I agree with Trevor about adding key validations, there's no reason not to limit claims to whatever is relevant to the ServiceAccount in question.

**Review by kpethtel — DISMISSED** [review]
Good AFAIK

**Review by bosawt — APPROVED** [review]
Confirmed that a service account `/token` request that included an ICN assertion was rejected when service account did not have ICN as an allowable value, and accepted when service account did have ICN as an allowable value

**Pull request merged**
