### PR TITLE
34057 Removing checkin v0 controller code

### PR DESCRIPTION
**Pull request by kanchanasuriya**
## Description of change

As first step of deprecating v0 endpoint, removing controller code, specs and api docs for check_in/v0.  Planning to open multiple PRs for removing services code, models and removing chip_api endpoint from settings.yml/test.yml

## Original issue(s)
department-of-veterans-affairs/va.gov-team#34057

## Things to know about this PR

- [X] rspec
- [X] rubocop

### CODE REVIEW

**Comment by thilton-oddball** [comment]
There was a CVE issue that was preventing the Linting and Security check from passing. It is fixed now, so you will need to pull master in and merge with your branch, then checks should pass and PR can get approved.

**Comment by kanchanasuriya** [comment]
> There was a CVE issue that was preventing the Linting and Security check from passing. It is fixed now, so you will need to pull master in and merge with your branch, then checks should pass and PR can get approved.

**Comment by kanchanasuriya** [comment]
> There was a CVE issue that was preventing the Linting and Security check from passing. It is fixed now, so you will need to pull master in and merge with your branch, then checks should pass and PR can get approved.

Thank you, all checks cleared now.

**Review by thilton-oddball — APPROVED** [review]

**Review by randomsync — APPROVED** [review]
lgtm

**Pull request merged**
