### PR TITLE
'API-25271-tracked-items-uploaded-always-false

### PR DESCRIPTION
**Pull request by stiehlrod**
## Summary

- As reported by VA.gov's CST team, the /claim/{id} endpoint is always returning 'trackedItem.uploaded' as false.
- Solution: Replaces 'rcvd_dt' with 'received_dt'
- Team Dash

## Related issue(s)
- [API-25271](https://vajira.max.gov/browse/API-25271)

## Testing done

- rspec
- Postman: `{{uri}}/services/claims/v2/veterans/1012830905V768518/claims/600382810`

## Screenshot
Screenshot 2023-03-29 at 12 43 18 PM

## What areas of the site does it impact?
modules/claims_api/app/controllers/claims_api/v2/veterans/claims_controller.rb

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Comment by FonzMP** [comment]
These are all still showing false per the ICN and Claim in the ticket
```
(byebug) a = map_bgs_tracked_items(bgs_claim)
(byebug) a.map{ |a| a[:uploaded] }
[false, false, false, false, false, false, false, false, false, false]
```

Also, let's get away from `! .nil?` and use `.present?`

**Comment by FonzMP** [comment]
also, does this require a doc update?

**Review by FonzMP — APPROVED** [review]
:shipit:

**Review by FonzMP — DISMISSED** [review]
:shipit: :shipit:

**Review by FonzMP — DISMISSED** [review]
:shipit:

**Review by acovrig — APPROVED** [review]

**Pull request merged**
