### PR TITLE
Fix MHVLogoutService

### PR DESCRIPTION
**Pull request by saneshark**
Fixes: http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/293/

The logic for logout service was wrong, this simplifies and fixes, makes more readable.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
Logic feels right and simpler to me. LGTM. would love to get one more set of eyes since this caused an issue the first time.

**Comment by saneshark** [comment]
@ayaleloehr I think the issue was that the "unless" logic was really cryptic. I changed the logic to read better for one. What was happening was that the logout facility which gets triggered by all logouts (regardless of having mhv_correlation_id) in sessions_controller had incorrect logic. It would have tried calling the service when no mhv_correlation_id exists or user does not have proper LOA3 level.

**Comment by saneshark** [comment]
There are specs for testing this, but the specs kind of missed the boat too because they assumed a user with mhv_correlation_id, there are no specs for testing when that is not the case. I could add some if we want.

**Comment by kreek** [comment]
LGTM 🚀

**Pull request merged**
