### PR TITLE
Add Regional Office for CH31 Pilot

### PR DESCRIPTION
**Pull request by kathleencrawford**
`PM Note: can we pause hold on this for a few?  Just learned the date for this is changing.`

## Description of change

We have a new partner integration with Veteran Readiness and Employment (VR&E) for Chapter 31 submissions.  The VR&E team is rolling out their pilot in phases to different regional offices.  ~~This PR is a minor update to add the San Diego regional office to receive Chapter 31 submissions.~~  It also updates the "default" email address to the Pittsburgh regional office.
## Original issue(s)
~~department-of-veterans-affairs/va.gov-team#24539~~
department-of-veterans-affairs/va.gov-team#24668
## Things to know about this PR

Super tiny PR so no new logging or settings have been added.

- [x] Local testing
- [x] Staging testing planned
- [x] Partner integration testing planned

### CODE REVIEW

**Comment by jason-gcio** [comment]
Let's pause this for a second - stakeholders just made it known that their pilot is frozen at the moment.  More info coming later today.

**Review by thilton-oddball — APPROVED** [review]
Looks good!

**Comment by kathleencrawford** [comment]
Note: I removed the addition of the San Diego office, but we still need the change for the default email address to be deployed.  The addition of the San Diego office will be updated in a future PR.

**Comment by kathleencrawford** [comment]
@thilton-oddball so sorry to bother you - may i please get a second review on this when you get a chance?  i had to remove a line of code due to a change requested by the VR&E team but didn't make any other changes.

**Review by thilton-oddball — APPROVED** [review]
LGTM

**Pull request merged**
