### PR TITLE
Map missing vet360 error codes 305 & 307

### PR DESCRIPTION
**Pull request by emersonthis**
Closes [11070](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11070)

### CODE REVIEW

**Comment by emersonthis** [comment]
@bshyong @ncksllvn @Samara-Strauss 
In keeping with the convention, the error title and message are basically what we get directly from Vet360. But here's a bit of explanation in case you guys want to communicate these in a more user-friendly way:

305: Delivery Point Not Confirmed
I believe this one happens if the address is valid, but doesn't correspond to a single deliverable point. Like an entire apartment building. Or perhaps a corn field with no houses on it?

307: Additional Input
I think this one would more accurately be titled Too Much Input or perhaps Repeated Input. The request in the logs that triggered this:
```
{
addressLine1: 3808 Martin Luther King Jr Blvd, 
addressLine2: 3808 Martin Luther King Junior Blvd, 
addressPou: CORRESPONDENCE, 
addressType: DOMESTIC, 
city: FILTERED, 
countryName: United States, 
id: 121, 
stateCode: CA, 
zipCode: FILTERED
}
```
^ As you can see, the user typed the address in twice

**Comment by Samara-Strauss** [comment]
Can we use the error state outlined in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11032#issuecomment-398747359?

**Comment by emersonthis** [comment]
@Samara-Strauss I think that makes sense for 305 but not 307

**Comment by Samara-Strauss** [comment]
@emersonthis can you explain 307 a bit more? From what I'm reading above, it sounds like this may result from a user entering repeated information in the address form (like the street address in the example above). Is there more that could trigger this error?

**Comment by emersonthis** [comment]
@Samara-Strauss Honestly I don't know. The description in [the docs](https://github.com/department-of-veterans-affairs/mdm-cuf-person/blob/development/mdm-cuf-person-server/src/inttest/resources/mdm/cuf/person/testData/error_codes.csv) isn't very helpful: 
> Additional Input found please review

I can ask for you in the vet360 channel but if we really want to gain confidence we'll probably need @steve-gov to find someone with definitive knowledge on this.

**Comment by Samara-Strauss** [comment]
@emersonthis got it. In that case, I would still say the generic address error we have can be used for this use case since we don't have enough insight into this error to provide more helpful guidance. If we can get that insight, then we can consider whether a more specific error message might be helpful.

**Comment by emersonthis** [comment]
Sounds reasonable to me. My only concern is that (based on the limited information we have) 307 appears to be the result of a user mistake. For example, the instance found in the logs was a nonsense address, likely due to a copy/paste mistake or something. Meanwhile the error state linked above seems to imply we "found" the address in some way. But at least at the end it says to re-enter the address, which is ultimately what probably needs to happen in these cases.

**Comment by Samara-Strauss** [comment]
Yeah, I see what you mean @emersonthis, but I also agree that since we prompt people to try again, this can be helpful for people who do make a mistake. They'll likely take a look over the form at that point and realize their error, correct it, and be able to submit successfully.

**Pull request merged**
