### PR TITLE
Update Direct Deposit email text

### PR DESCRIPTION
**Pull request by jholton**
## Description of change
Updates the text contained in the Direct Deposit email

## Testing done
specs

## Testing planned
manual generation of email

#### Unique to this PR

- [x] Update text in Direct Deposit email

#### Applies to all PRs

- [ ] ~~Appropriate logging~~
- [ ] ~~Swagger docs have been updated, if applicable~~
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] ~~Provide which alerts would indicate a problem with this functionality (if applicable)~~

### CODE REVIEW

**Comment by Samara-Strauss** [comment]
Hello! How can I be most helpful in reviewing this request?

**Comment by erikphansen** [comment]
@Samara-Strauss make sure the phone number isn't for Purina or something :)

**Comment by Samara-Strauss** [comment]
@erikphansen actually, that's a good point

@jholton can you share the text for the email? I want to make sure the number is correct. Also, if we still have the "and select 5" copy, that little bit needs to be taken out.

**Comment by jholton** [comment]
> @jholton can you share the text for the email? I want to make sure the number is correct. Also, if we still have the "and select 5" copy, that little bit needs to be taken out.

Yup, that's exactly what [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/3252/files) is for:
```
Call 800-827-1000 (TTY: 800-829-4833). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. We can help you take the steps you need to protect your bank account information and prevent fraud.
```

**Comment by Samara-Strauss** [comment]
> Yup, that's exactly what this PR is for

Ugh, sorry. I have pre-vacation brain.

Everything looks good.

**Pull request merged**
