### PR TITLE
Remove PCIU Controllers

### PR DESCRIPTION
**Pull request by tpharrison**
## Summary
Coverband shows no requests being sent to these controllers:
- V0::Profile::EmailsController
- V0::Profile::PrimaryPhoneController
- V0::Profile::AlternatePhonesController

These files are no longer in use and need to be removed.

## Tickets
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76173
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76212

## Tasks
Remove the following:

- [x] Routes
  - [x] `resource :email, only: %i[show create]`
  - [x] `resource :primary_phone, only: %i[show create]`
  - [x] `resource :alternate_phone, only: %i[show create]`
- [x] Controllers
  - [x] `app/controllers/v0/profile/emails_controller.rb`
  - [x] `app/controllers/v0/profile/primary_phones_controller.rb`
  - [x] `app/controllers/v0/profile/alternate_phones_controller.rb`
- [x] Controller Specs
  - [x] `spec/requests/email_request_spec.rb`
  - [x] `spec/requests/primary_phone_request_spec.rb`
  - [x] `spec/requests/alternate_phone_request_spec.rb`
- [x] Swagger Specs
  - [x] Remove references from `spec/requests/swagger_spec.rb`
  - [x] Remove references from `app/swagger/swagger/requests/profile.rb`
  - [x] Remove references from `.rubocop_todo.yml`
- [x] Codeowners Updates
  - [x] Remove `spec/requests/email_request_spec.rb`
  - [x] Remove `spec/requests/primary_phone_request_spec.rb`
  - [x] Remove `spec/requests/alternate_phone_request_spec.rb`

### CODE REVIEW

**Comment by tpharrison** [comment]
Hey @RachalCassity!  Let me know if I missed anything.  Thanks!

**Comment by LindseySaari** [comment]
> Hey @RachalCassity! Let me know if I missed anything. Thanks!

Hey @tpharrison! @RachalCassity Is out this week. I've forwarded this PR to our team channel. Thanks!

**Review by LindseySaari — APPROVED** [review]
🥳

**Comment by LindseySaari** [comment]
@tpharrison When you are ready, I can merge this in for you since it needs a danger override. Please just ping me when you're ready. Thanks!

**Comment by tpharrison** [comment]
Thanks @LindseySaari - merge away!

**Pull request merged**
