### PR TITLE
[DBEX] create Lighthouse526DocumentUpload migration

### PR DESCRIPTION
**Pull request by freeheeling**
## Summary

**Objective:** Implements a system for periodically polling the Lighthouse [uploads/status](https://dev-developer.va.gov/explore/api/benefits-documents/docs?version=current) endpoint to confirm the status of supplemental documents submitted to Lighthouse as part of a Form 526 Submission. The purpose of this system is to surface successes and failures that happen in the Form 526 process after being forwarded to Lighthouse for processing.

- Create `Lighthouse526DocumentUpload` database migration
  - model that represents a document uploaded to Lighthouse
  - Veteran Upload document types have an associated `FormAttachment` record, where an S3 pointer for the document is stored
  - will store the `requestId` returned by Lighthouse, as `lighthouse_document_request_id`
- Subsequent PRs will implement model validations and methods, as well as interaction with the Lighthouse Benefits Document API client
- *This work is behind a feature toggle (flipper): ~YES~/**NO***
- Responsible team: Disability Benefits Experience Team 2 (dBeX Carbs 🥖)

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87617
- https://github.com/department-of-veterans-affairs/vets-api/pull/15964
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75804

## Testing done

- Database migration; nothing to test

## What areas of the site does it impact?

- non-user facing, asynchronous job tracking the status of uploaded documents submitted in conjunction with Form 526EZ 

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

### CODE REVIEW

**Review by tblackwe — DISMISSED** [review]

**Comment by stevenjcumming** [comment]
@freeheeling a bad test was introduced into master. Could you update your branch to resolve the failing code check?

**Comment by freeheeling** [comment]
> @freeheeling a bad test was introduced into master. Could you update your branch to resolve the failing code check?

@stevenjcumming Merged master branch in. All checks now passing. Please review. Thank you!

**Review by stevenjcumming — CHANGES_REQUESTED** [review]
Please add a new line to the end of your migration file

**Comment by freeheeling** [comment]
> Please add a new line to the end of your migration file

Addressed in https://github.com/department-of-veterans-affairs/vets-api/pull/17405/commits/a64e9bb1f62901a6810eb17db22f945a289372a9

**Review by NB28VT — APPROVED** [review]
This looks good to me assuming you're good with the schema I came up with, I felt it may have been a little over-engineered but more data is better than less data and we can always drop columns that don't make sense

**Pull request merged**
