### PR TITLE
[10688] Adding auto-uplevel capability for id.me and login.gov authen…

### PR DESCRIPTION
**Pull request by bosawt**
…tications for sign in service

## Description of change
This PR adds the capability to auto-uplevel an id.me or login.gov account for a sign in service authentication if the requested authentication level was `min` (highest available authorization), the user has previously authenticated at the `IAL2` equivalent level, and the `Settings.sign_in.auto_uplevel` flag is set for the relevant environment. This will prevent double-authentications for id.me and login.gov assuming a user has previously authenticated with VA.gov for these credentials

## Original issue(s)
department-of-veterans-affairs/vets-api#10688

## Things to know about this PR
- Authenticate on Sign in Service with login.gov or id.me with an account that has authenticated before with VA.gov
- Open network inspector, and confirm only a single VA `sign_in/authorize` to `sign_in/callback` is made (without this PR, there would have previously been two `sign_in/authorize` to `sign_in/callback` loops)

### CODE REVIEW

**Review by LindseySaari — COMMENTED** [review]
Do you have a corresponding devops PR for the new `auto_uplevel: true` setting? You will also need to update the configmap for each environment in the k8s manifest repo as well.

**Comment by bosawt** [comment]
> Do you have a corresponding devops PR for the new `auto_uplevel: true` setting? You will also need to update the configmap for each environment in the k8s manifest repo as well.

Yup, it's merged here: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/861
https://github.com/department-of-veterans-affairs/devops/pull/11941

**Review by bramleyjl — APPROVED** [review]
Screen Shot 2022-09-15 at 10 53 12 AM
Confirmed a previously logged-in IAL2 user with only one trip with SiS.

**Review by LindseySaari — APPROVED** [review]
👍

**Pull request merged**
