### PR TITLE
add postgres

### LINKED ISSUE #33: add activerecord back and choose a database

### PR DESCRIPTION
**Pull request by lihanli**
closes #33

### CODE REVIEW

**Comment by robbiethegeek** [comment]
We have a meeting scheduled today about persistence and the platform. I think the implementation is going to be postgres but let's leave this unmerged til @kreek merges or comments and changes this based on the functional requirements.

**Comment by kreek** [comment]
LGTM

**Comment by robbiethegeek** [comment]
👍  :)

**Comment by shauni** [comment]
🚀 

Is there a corresponding devops plan for adding postgres?

**Pull request merged**
