### PR TITLE
Use Fuubar formatter in rspec

### PR DESCRIPTION
**Pull request by kfrz**
## Description of change
This PR changes `.rspec` default formatter to use `Fuubar` as it's much more friendly to the developer than the `--format progress` that is shipped w/ rspec. It shows ETA of spec completion, shows failures with output as they happen and is a bit shinier overall.

68747470733a2f2f6b6f6d70616e65652d7075626c69632d6173736574732e73332e616d617a6f6e6177732e636f6d2f726561646d65732f6675756261722d6578616d706c65732e676966
[Source](https://github.com/thekompanee/fuubar)

This will not impact CI as Jenkins runs the JUnit formatter. 
Works w/ Guard, too:

[asciicast](https://asciinema.org/a/PQ6K89hGTrcYmBSYlJEms4r5I)

## Testing done
Tested locally

## Testing planned
Jenkins build

#### Unique to this PR
- [x] `fuubar` added to development/test group
- [x] `.rspec` default updated
- [x] `Guardfile` updated

#### Applies to all PRs

- [x] Appropriate logging
- [x] Swagger docs have been updated, if applicable
- [x] Provide link to originating GitHub issue, or connected to it via ZenHub
- [x] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [x] Provide which alerts would indicate a problem with this functionality (if applicable)

### CODE REVIEW

**Comment by kfrz** [comment]
> Wondering if it might make sense to keep `.rspec` really lean and move Fuubar into a configuration file to make it clearer that we're doing something with another tool. Also opens the door to things like this:
> 
> ```
> RSpec.configure do |config|
>   config.fuubar_output_pending_results = false
> end
> ```

I'm indifferent, I think it's leaner to keep it in the `.rspec` file, which could be overridden in a user's local environment easily, also until we need to update a config setting it'd just be another file.

**Comment by annaswims** [comment]
Any idea where this output comes from?  looks to be something about pdf parsing maybe.
````
[info ] ...Reading header...==================== 45 =====================================>                                                                                                |  ETA: 00:02:18
[info ] ...Parsing revision 1...
[info ] ...Parsing xref table...
[info ] ...Parsing trailer...
[info ] ...Propagating types...
[info ] ...Reading header...==================== 45 =====================================>                                                                                                |  ETA: 00:02:18
[info ] ...Parsing revision 1...
[info ] ...Parsing xref table...
[info ] ...Parsing trailer...
[info ] ...Propagating types...
[info ] ...Reading header...
[info ] ...Parsing revision 1...
[info ] ...Parsing xref table...
[info ] ...Parsing trailer...
[info ] ...Propagating types...
[info ] ...Reading header...===================== 46 ======================================>                                                                                              |  ETA: 00:02:16
[info ] ...Parsing revision 1...
[info ] ...Parsing xref table...
[warn ] Unable to parse xref table! Xrefs might be stored into an XRef stream.
[info ] ...Parsing trailer...
[info ] ...Parsing revision 2...
[info ] ...Parsing xref table...
[warn ] Unable to parse xref table! Xrefs might be stored into an XRef stream.
[info ] ...Parsing trailer...
[warn ] Found a XRefStream for this revision at 16 0 R
[warn ] This file has been linearized.
[info ] ...Propagating types...
[warn ] This document contains encrypted data!
[info ] ...Reading header...===================== 46 ======================================>                                                                                              |  ETA: 00:02:15
[info ] ...Parsing revision 1...
[info ] ...Parsing xref table...
[info ] ...Parsing trailer...
[info ] ...Propagating types...
[info ] ...Reading header...===================== 46 ======================================>                                                                                              |  ETA: 00:02:15
[info ] ...Parsing revision 1...
````

**Comment by kfrz** [comment]
@annaswims I have no idea in particular, I believe it's related to the `origami` gem and not related to this PR. We could discuss at backend sync if there's value in supressing `stdout` like this in test suite

cc: @camerontesterman introduced this gem - have you seen similar output in your builds?

**Comment by annaswims** [comment]
I've discovered a pretty big downside to this formatter.  It interferes with the command line if you put `binding.pry` in a test. 
Screen Shot 2019-10-08 at 11 57 16 AM

**Pull request merged**
