### PR TITLE
Mark.viterna/api 5193 sunset v0 benefits intake

### PR DESCRIPTION
**Pull request by mviterna**
## Description of change

Benefits Intake team is sunsetting v0. There are no active users since last year, and we have done communications to end users > 90 days. Removing the endpoint, cleaning up swagger, and leaving on internal v0 route for AWS

## Original issue(s)
https://vajira.max.gov/browse/API-5193

## Things to know about this PR

Tested locally and in Docker against s3 dev. Checked doc status from pending->uploaded->received. Ensured swagger 0.0.1 is gone in portal

### CODE REVIEW

**Review by gpbowman-git — COMMENTED** [review]
is the v0 security_scheme_swagger.rb still needed?

**Comment by mviterna** [comment]
> is the v0 security_scheme_swagger.rb still needed?

Nope. Gone now

**Review by thilton-oddball — APPROVED** [review]
Looks good!

**Comment by saneshark** [comment]
Please remember to check in Gemfile.lock changes.

**Pull request merged**
