### PR TITLE
Hca login form changes

### PR DESCRIPTION
**Pull request by lihanli**
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/942

### CODE REVIEW

**Comment by markolson** [comment]
@lihanli I'm thinking we may need to revert this and put it on hold until the testing of the initial port is done.

**Comment by lihanli** [comment]
ok

**Comment by lihanli** [comment]
the new form is only sent when someone is logged in

**Comment by markolson** [comment]
Yep, but I think we need a charter for this work to go live, and that'll be separate from the initial port going live.

**Pull request merged**
